### ISSUE TITLE
dynamic map stack order changing on pan and zoom

### ISSUE THREAD

**Issue by cgalvarino** [Esri/esri-leaflet#1000]
* Version of Leaflet (`L.version`):

1.0.3

* Version of esri Leaflet (`L.esri.VERSION`):

2.0.8

I have a fistful of dynamic layers inside of one `L.layerGroup`.  This `L.layerGroup` is defined as an array of items that look something like this:
```
[
  L.esri.dynamicMapLayer({
    url: 'my.rest.service/foo/bar'
    layers: [1,2,3,...],
    f: 'image',
    format: 'png32',
    opacity: 0.6,
    attribution: 'NWS',
    position: 'back'
  }),
  L.esri.dynamicMapLayer({
    url: 'my.rest.service/foo/bar'
    layers: [20,21,22,...],
    f: 'image',
    format: 'png32',
    opacity: 0.6,
    attribution: 'NWS',
    position: 'back'
  }),
  ...
]
```

I have tried changing `position: 'back'` to `position: 'front'` and even adding a `zIndex`, but I always get inconsistent results.

If you visit here, http://mwp.secoora.org/?quality=Off&units=English&duration=3%20days&maps=x-sst,x-nws_hti,x-noaa_radar,nws_wwa,x-storm_tracks,x-nws_wwa_boundaries&legend=Off&forecast=Point&hti=&sst=&region=MWP&bbox=-99.49218750000001,25.93828707492375,-90.362548828125,31.690781806136822&iframe=null, and allow the map to populate itself.  You will probably notice that even if you nudge the map a little, the layers rerender in a different order.

I do have a map listener on moveend, but it doesn't have anything to do w/ the render.

Any ideas?  Does it matter in the order each request was returned?

Initial view.
![image](https://user-images.githubusercontent.com/180985/29738086-6ca11bf8-89e8-11e7-99b6-5e959ab38ee7.png)

Nudge the map a bit.
![image](https://user-images.githubusercontent.com/180985/29738098-a144c4e0-89e8-11e7-82b8-da0930f1d475.png)

Incidentally, the "nudge the map a bit" is what I want.  It keeps the more important hazards on top.

**Comment by jgravois** [comment]
to get more explicit control you should be using [map panes](http://leafletjs.com/reference-1.2.0.html#map-pane), introduced in Leaflet 1.x

http://esri.github.io/esri-leaflet/examples/layer-ordering.html

**Comment by cgalvarino** [comment]
Map panes are a GAME CHANGER.  Thank you so much.

**Comment by jgravois** [comment]
issue 💯 0!!!

:tada::tada::tada:
