### ISSUE TITLE
Create returnM method for setting param on Query task

### ISSUE THREAD

**Issue by jfolds** [Esri/esri-leaflet#1001]
L.esri.Query does not have a returnM method. It currently exists in the Find task, but is missing from Query.

**Comment by jgravois** [comment]
you up for contributing it as a new feature? i'd be happy to review a PR.

https://github.com/Esri/esri-leaflet/blob/58f05b33ca0b510c366e5cd1a6b4031accfee683/src/Tasks/Query.js#L11-L21

**Comment by jfolds** [comment]
Sure, I'll try and submit a PR soon.

**Comment by jgravois** [comment]
thank you @jfolds! in the meantime, folks can also use this 'weird trick'

```js
var query = L.esri.query({
    url:'https://services.arcgis.com/.../stops/FeatureServer/0'
});

query.within(bounds);

query.params.returnM = true;

query.run(function(error, featureCollection, response){
    console.log('Found ' + featureCollection.features.length + ' features');
});
```
