### ISSUE TITLE
ESRI Leaflet + Types + Angular 4

### ISSUE THREAD

**Issue by tgmendes** [Esri/esri-leaflet#1003]
Hello,

I'm trying to get esri-leaflet and leaflet to work with typescript typings. I have installed the types into my package.json, and successfully imported them (with no errors) in vscode.

However, when running the application and defining a basemap layer, I get the error: 
`ERROR TypeError: Cannot read property 'basemapLayer' of undefined`
I found out that the application does not bind esri to the leaflet module (L.esri is undefined).

Am I doing something wrong?

* Browser and version:

Chrome 59

* Version of Leaflet (`L.version`):

1.2.0

* Version of esri Leaflet (`L.esri.VERSION`):

2.2.1

Steps to reproduce the error:

1. Add leaflet, esri-leaflet, @types/leaflet, @types/esri-leaflet to package.json
2. Import the files within my application:
`import * as L from 'leaflet'`
`import 'esri-leaflet'`
3. Try to use esri-leaflet as basemap:
`basemap = L.esri.basemapLayer('oceans')`

I then get the error described above: 
`ERROR TypeError: Cannot read property 'basemapLayer' of undefined`

I have searched throughout the issues, and found a similar issue, but I had no success in solving it.

I'm not using the  [CDN](http://www.jsdelivr.com/projects/leaflet.esri), I'm loading/bundling the library using:

[webpack](https://webpack.github.io/)

Thanks for the help!
Regards,
Tiago

**Comment by blahmonkey** [comment]
Hi,

Had same issue with vuejs but solution should work for you (I'm using ES6 not typescript, but I dont see a big issue for you)

```
  import L from 'leaflet'
  import esri from 'esri-leaflet'
  
  this.darkStyleEsri = esri.basemapLayer('DarkGray')
```

Try that :-)

**Comment by tgmendes** [comment]
Hey,

Thanks for the reply!

However, this does not work for me, I get an immediate error saying that esri-leaflet has no default export. 

This is also what I would expect, since the goal of esri-leaflet typings is to extend leaflet and add an esri object to the main L object. Looking at the typings definition, esri-leaflet does not export anything (it simply extends the L object).

Anyway, thanks again!

**Comment by blahmonkey** [comment]
Hi,

I'm using esri-leaflet v2.1.1 -- in my case, when I import esri from esri-leaflet, looking at console.log(esri), I can see that its basically picking up on the exports from src/EsriLeaflet.js 

`VERSION: "2.1.1", Support: {…}, options: {…}, Util: {…}, get: ƒ, …}
`

Perhaps in your case typescript or some thing else is blocking that.

(While the intent of esri-leaflet is to bind to the main L object, that didnt work for me so I settled for this workaround)

**Comment by jgravois** [comment]
sounds _very_ similar to #994

**Comment by tgmendes** [comment]
@jgravois it is, and I looked at it carefully, but the solution does not work for me.
When trying to declare 
When I try to do:
```
declare module 'esri-leaflet' {
     export = L.esri;
  }
```

I get an error saying that Exports and export assignments are not permitted in module augmentations.

Could it be due to typescript versions? I'm using 2.5.2, it says in index.d.ts it's using version 2.3.

**Comment by HarelM** [comment]
I managed to make it work: Angular 4 + leaflet + typescript:
`import "esri-leaflet";`
At the beginning of the file.
Since it's only one line of code I decided not to use the typings and used this line of code instead:
`let esriLayer = (L as any).esri.basemapLayer('Imagery');`
but @jgravois 's deceleration will work as well.
I have the following `tsconfig.json` settings:
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./wwwroot/out-tsc",
    "baseUrl": "sources",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2016",
      "dom"
    ]
  }
}
```
and `tsconfig.app.json`:
```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "module": "es2016",
    "baseUrl": "",
    "types": [
      "google.visualization",
      "leaflet.gridlayer.googlemutant"
    ]
  },
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ]
}
```
hope this helps.

**Comment by HarelM** [comment]
Sorry, my mistake, the following is what's working for me:
`import * as esri from "esri-leaflet";`
and use it:
`let esriLayer = esri.basemapLayer('Imagery');`
No issues with typings.

**Comment by tgmendes** [comment]
@HarelM 
Thanks a lot! This worked for me.

1. Removed ESRI typings from package.json and node_modules
2. Used the import you mentioned: `import * as esri from 'esri-leaflet';
3. Used esri directly (i.e. not as an extension of Leaflet). 
4. Still could use leaflet typings without a problem.

However, I still consider this to be a workaround, since it's still not possible to use esri-leaflet's typings.

**Comment by jgravois** [comment]
> I still consider this to be a workaround

@tgmendes what specifically needs to be fixed?

**Comment by TroySchmidt** [comment]
It would be nice if the package included TypeScript types directly so that direct import would be typed out for TypeScript natively without needing any @types package.  Especially when it is centered around it being import and available as part of L., but this doesn't seem to work with TypeScript at all.

**Comment by calegarifabio** [comment]
const esri = require('esri-leaflet'); works for me!
