### ISSUE TITLE
Loading custom styled basemap

### ISSUE THREAD

**Issue by blahmonkey** [Esri/esri-leaflet#1004]
* Browser and version:

Chrome 60.0.3112.101 

* Version of Leaflet (`L.version`): 

1.2.0

* Version of esri Leaflet (`L.esri.VERSION`):

2.1.1, master

I have created a custom style in arcgis online (downloaded root.json, edited, updated) for the topographical basemap. This custom style is a 'tile layer' that I would like to use as an alternate base map layer in my vuejs app using esri-leaflet

In the item view in argis online, the URL shows as http://basemaps.arcgis.com/arcgis/rest/services/World_Basemap/VectorTileServer

But I'm unable to use this URL in my app - I played around a bit, and tried things like the below, with and without the item id, with and without the token (token is the test token from dev account, valid today)

```
esri.tiledMapLayer({
  url: 'http://basemaps.arcgis.com/arcgis/rest/services/World_Basemap/VectorTileServer?id=<long-item-id>',
  token: '<edited out>' 
})
```

None of these yield any results when I invoke addTo(map) -- no tiles get drawn. If I replace with a basemapLayer('streets') it works just fine. Network inspector shows some JSON responses, but no image responses.

Am I using the right URL format? Any help would be appreciated

**Comment by jgravois** [comment]
loading `VectorTileLayer` services requires a separate plugin.

https://github.com/esri/esri-leaflet-vector

**Comment by blahmonkey** [comment]
Thank you! Working with it.
