### ISSUE TITLE
Loading 4326 TitleLayer failed, using proj4leaflet to convert CRS

### ISSUE THREAD

**Issue by es3154** [Esri/esri-leaflet#1005]
* Browser and version:

firefox

* Version of Leaflet (`L.version`):

1.2.0

* Version of esri Leaflet (`L.esri.VERSION`):

2.1.1

* Version of proj4leaflet (`L.esri.VERSION`):
1.0.1
Steps to reproduce the error:

var crs = new L.Proj.CRS('EPSG:4326', '+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs', {
        origin: [-400.0, 400.0],
        resolutions: [
            0.00951784402332112,
            0.00475892201166056,
            0.0035691915087454206,
            0.00237946100583028,
            0.0017845957543727103,
            0.00118973050291514,
            5.9486525145757e-4,
            2.97432625728785e-4,
            1.5228550437313792e-4,
            7.614275218656896e-5,
            3.807137609328448e-5,
            1.903568804664224e-5,
            9.51784402332112e-6,
            4.75892201166056e-6,
            2.37946100583028e-6,
        ]
    });

    var map = L.map('map', {
        crs: crs
    }).setView([114.37638000000015, 36.063049999999976], 7);

    L.esri.tiledMapLayer({
        url: 'http://10.87.61.14:6080/arcgis/rest/services/Nbasemap/MapServer',
        maxZoom: 12,
        minZoom: 1,
    }).addTo(map);

What happens is [X].

  Request the title in 404
For example http://10.87.61.14:6080/arcgis/rest/services/Nbasemap/MapServer/tile/7/3749/5729

**Comment by jgravois** [comment]
> origin: [-400.0, 400.0],

given that X is restricted to +-180 and Y is restricted to +-90, that origin seems problematic.

please see if you can reproduce the error with [this public `wkid:4326`](https://services.arcgisonline.com/arcgis/rest/services/ESRI_Imagery_World_2D/MapServer) tiled map service and provide a fiddle/jsbin/codepen.

**Comment by es3154** [comment]
I modified it in this example [http://esri.github.io/esri-leaflet/examples/non-mercator-projection.html](url)  _it can load, but the map seems to be off_
`var crs = new L.Proj.CRS('EPSG:4326', '+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs', {
        origin: [-180.0, 90.0],
        resolutions: [
            0.3515625,
            0.17578125,
            0.087890625,
            0.0439453125,
            0.02197265625,
            0.010986328125,
            0.0054931640625,
            0.00274658203125,
            0.001373291015625,
            6.866455078125E-4,
            3.4332275390625E-4,
            1.71661376953125E-4,
            8.58306884765629E-5,
            4.29153442382814E-5,
            2.14576721191407E-5,
            1.07288360595703E-5
        ]
    });
    var map = L.map('map', {
        crs: crs
    }).setView([114.37638000000015, 36.063049999999976], 7);

    L.esri.tiledMapLayer({
        url: 'https://services.arcgisonline.com/arcgis/rest/services/ESRI_Imagery_World_2D/MapServer',
        maxZoom: 15,
        minZoom: 0,
    }).addTo(map);

    var cities = L.esri.featureLayer({
        url: 'https://sampleserver6.arcgisonline.com/arcgis/rest/services/WorldTimeZones/MapServer/0',
        where: 'POP_RANK < 5',
        pointToLayer (geojson, latlng) {
            return L.shapeMarkers.diamondMarker(latlng, 5, {
                color: '#0099FF',
                weight: 2
            })
        }
    }).addTo(map);`

**Comment by es3154** [comment]
The tileSize property of the tiledMapLayer is set to 512
`var map = L.map('map', {
        crs: crs
    }).setView([-56.093004, -15.615], 1);

    L.esri.tiledMapLayer({
        url: 'https://services.arcgisonline.com/arcgis/rest/services/ESRI_Imagery_World_2D/MapServer',
        tileSize:512,
        maxZoom: 15,
        minZoom: 0,
    }).addTo(map);`

**Comment by jgravois** [comment]
> The tileSize property of the tiledMapLayer is set to 512

are you saying that setting the appropriate constructor option resolved your problem?

**Comment by es3154** [comment]
But our own map service Origin is [400,-400],tileSize is 256, or failed to load, I don't know why, I am now trying to publish a map service test of Origin is [-180.0, 90.0]
thank you

**Comment by es3154** [comment]
It's my problem, the latitude and longitude of the setView method is backwards, so origin can be defined by the definition of the map service, it doesn't have to be [-180,90].
