### ISSUE TITLE
default layers passed to identify()

### ISSUE THREAD

**Issue by cgalvarino** [Esri/esri-leaflet#1006]
* Version of Leaflet (`L.version`):

1.0.3

* Version of esri Leaflet (`L.esri.VERSION`):

2.0.8

Hello, team esri-leaflet.  A quick comment about `dynamicMapLayer.identify()`.  Until I watched the queries go across the wire, I didn't realize that the identify wasn't checking its own `dynamicMapLayer.options.layers` when making a query.  Instead it passes along `all`.  I'm curious why that is.

Doing a `.layers('all:' dynamicMapLayer.options.layers.join(','))` works just fine, but I falsely assumed that would have been the default.

No complaints!  I'm thankful for such a great product.

**Comment by jgravois** [comment]
greetings @cgalvarino! its a good question!

whether you spawn `identify()` from `dynamicMapLayer` or instantiate a standalone [`IdentifyFeatures`](http://esri.github.io/esri-leaflet/api-reference/tasks/identify-features.html) task, it is a blank slate.

https://github.com/Esri/esri-leaflet/blob/4c615ccbee9fa3d2927c27f0edd1ed1850e75bb2/src/Services/MapService.js#L8-L10

that said, there _is_ an option for identifying that inherits `dynamicMapLayer` constructor options you've set to augment layer visibility (including definition expressions) : [`bindPopup()`](http://esri.github.io/esri-leaflet/examples/customizing-popups.html)

as you can see in the code below, internally we use more or less the same technique you describe to incorporate constructor options for layer visibility and also pass through any definition expressions that have been set.
https://github.com/Esri/esri-leaflet/blob/4c615ccbee9fa3d2927c27f0edd1ed1850e75bb2/src/Layers/DynamicMapLayer.js#L90-L108

i hope this information is helpful. if you have any other questions i'd be happy to chat more.

**Comment by jgravois** [comment]
i'm going to assume my previous reply resolved your query, but i'm happy to keep chatting if anyone has other questions.

**Comment by cgalvarino** [comment]
Roger that, @jgravois.  Thanks again for a great product.
