### ISSUE TITLE
Issue using esri-leaflet with an Angular CLI application

### ISSUE THREAD

**Issue by wznuk** [Esri/esri-leaflet#1007]
# ERROR TypeError: Cannot read property 'basemapLayer' of undefined
I have built a very basic application using the Angular CLI. When I build and run the application using `ng serve -o` everything builds successfully. However, when I view the application in Chrome the map portion does not load. Further inspecting the page I see this error in the console.

`ERROR TypeError: Cannot read property 'basemapLayer' of undefined`

## Setup
* Angular 4
* Chrome 61
* leaflet 1.2.0
* esri-leaflet 2.1.1
* types/leaflet for 1.2
* types/leaflet for 2.1.

## Steps to reproduce the error:

These steps assume that you already have [angular CLI](https://cli.angular.io/) installed.

#### Steps 1-6 & 10 are done in terminal/cmd prompt window
1. Create a new application `ng new esriLeafletApp`
2. Navigate to the new application `cd esriLeafletApp`
3. `npm install --save leaflet`
4. `npm install --save esri-leaflet`
5. `npm install --save @types/esri-leaflet`
6. `npm install --save @types/leaflet`
7. Update the contents of the *app.component.ts* file
```
import { Component, OnInit } from '@angular/core';

import * as L from 'leaflet';
import 'esri-leaflet';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})

export class AppComponent implements OnInit {
  title = 'app';

  constructor() { }

  ngOnInit () {
    const map = L.map('map').setView([51.505, -0.09], 13);
    L.esri.basemapLayer('Streets').addTo(map);
  }
}
```
8. Update the contents of the *app.component.html* file
```
<div style="text-align:center">
  <h1>
    Welcome to {{title}}!
  </h1>
</div>
<div id="map"></div>
```
9. Update the contents of the *app.component.css* file
```
#map {
    height: 500px;
    width: 100%;
}
```
10. Build and run the application `ng serve -o`
11. View the application in Chrome
12. Inspect the code and view the error in the inspector console

## Please Help
Does anyone know why `esri` is `undefined` in the code block ` L.esri.basemapLayer('Streets').addTo(map);` ?

**Comment by jgravois** [comment]
please see https://github.com/Esri/esri-leaflet/issues/1003

**Comment by wznuk** [comment]
Thanks @jgravois!

That provided a work around to my issue. It seems the issue lies with the typings file for esri-leaflet, instead of with esri-leaflet itself. I have opened an [issue](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/19872) on the DefinitelyTyped github.

## The workaround:

- Removed ESRI typings from package.json and node_modules
- Used the import you mentioned: `import * as esri from 'esri-leaflet';
- Used esri directly (i.e. not as an extension of Leaflet).
- Still could use leaflet typings without a problem.

```
import { Component, OnInit } from '@angular/core';

import * as L from 'leaflet';
import * as esri from 'esri-leaflet';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})

export class AppComponent implements OnInit {
  title = 'app';

  constructor() { }

  ngOnInit () {
    const map = L.map('map', {
      maxZoom: 18,
      minZoom: 0
    }).setView([51.505, -0.09], 15);

    const esriLayer = esri.basemapLayer('Imagery');
    map.addLayer(esriLayer);
  }
}
```

Thank you @HarelM & @tgmendes

**Comment by strajuser** [comment]
Dublicating another workaround for this issue from [here](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/19872#issuecomment-343059183).

Now the workaround is to use previous versions of @types/esri-leaflet, for example. v2.1.0:

1. npm install --save @2.1.0
2. npm install --save @1.0.69 (I don't understand why, but without specific version by default npm installs typings for leaflet 0.7)

@jgravois this issue seems to appears because default way to import leaflet plugins is (and for most other leaflet-plugins this way is working):
`
import * as L from 'leaflet'; 

import 'esri-leaflet';
`

But it's not working for esri-leaflet. Does it have some difference from [leaflet.wms](https://github.com/heigeo/leaflet.wms) for example?

As @wznuk noticed, importing 'esri-leaflet' this way makes L.esri undefined...

**Comment by jgravois** [comment]
> Does it have some difference from leaflet.wms for example?

yes. leaflet.wms is a UMD module. esri-leaflet is written in ES6 and transpiled.

as suggested previously you should be doing this:

```ts
import * as esri from "esri-leaflet";
```
