### ISSUE TITLE
esri-leaflet fails to attach itself to the global instance of L

### ISSUE THREAD

**Issue by PavelGolodoniuc** [Esri/esri-leaflet#1013]
Environment:

- "`@angular/cli`": "1.4.7",
- "`@angular/compiler-cli`": "^4.4.5",
- "`typescript`": "~2.3.0"

and:

- "`leaflet`": "^1.2.0",
- "`esri-leaflet`": "^2.1.1",
- "`@types/leaflet`": "^1.2.0",
- "`@types/esri-leaflet`": "^2.1.1"

**Steps to reproduce the error:**

In an Angular component loading both libraries using the following imports:

```
import * as L from "leaflet";
import "esri-leaflet";
```

This exposes leaflet via L but fails to attach esri-leaflet to the same instance of L, i.e. I can see the esri-leaflet-debug.js script being loaded into the browser, but its exports are getting lost.

leaflet.js fixed what appears to be a similar issues via adding the following:

```
// Always export us to window global (see #2364, https://github.com/Leaflet/Leaflet/issues/2364)
window.L = exports;
```

**RESOLUTION:**
Following the same approach if I add the following to the esri-leaflet-debug.js it fixes the issue.

```
L$1.esri = exports;
```

**Comment by jgravois** [comment]
please see #1003, #1009
