### ISSUE TITLE
Cannot click layers with a lower z-index than Canvas.

### ISSUE THREAD

**Issue by hoisingtonp** [Esri/esri-leaflet#1020]
* Browser and version:

Firefox 52.3.0

* Version of Leaflet (`L.version`):

1.0.3

* Version of esri Leaflet (`L.esri.VERSION`):

Undefined

Steps to reproduce the error:

1. Create a map pane at a z-index higher than that of the overlayPane (will require CSS).
2. Create a canvas, use it to render some circleMarkers and add them to the newly-created pane.
3. Create a polygon with "{ interactive: true}" and an on-click event, add it to the map (not the newly-created pane).

What happens is the polygon does not receive click events.

I was expecting the polygon to be able to receive click events. When I remove the canvas, polygons receive click events just fine.

Is this a limitation of using a canvas to render geometry?

NOTE: I want the the canvas to display *over* the overlayPane (where the polygon is, by default, added), so that it receives click events first.

* Optional: I'm *not* using the [CDN](http://www.jsdelivr.com/projects/leaflet.esri), I'm loading/bundling the library using:

[RequireJS](http://requirejs.org/)

**Comment by gavinr** [comment]
@hoisingtonp It seems like this issue has to do with only Leaflet core items ([Canvas](http://leafletjs.com/reference-1.2.0.html#canvas), [polygon](http://leafletjs.com/reference-1.2.0.html#polygon), etc). If so, you probably want to log this issue over in the [Leaflet Issues area](https://github.com/Leaflet/Leaflet/issues), as they will be able to better address your issues. If not, can you please clarify for me - what parts of Esri Leaflet are you using?  Thanks!

**Comment by hoisingtonp** [comment]
Sorry, Gavin--I couldn't close the issue on my own, but I should've at least commented. I realized a few minutes after posting that this was the wrong place to post my issue, and I created an issue over at the main Leaflet issues area. Thanks for following up! But yeah, this can be closed.

**Comment by jgravois** [comment]
thanks for confirming. I always thought the OP _could_ close their own issue.

**Comment by gavinr** [comment]
Related issue in the Leaflet repo (for future searchers): https://github.com/Leaflet/Leaflet/issues/5886#issuecomment-340272396
