### ISSUE TITLE
How to query features from a esri vector tile service.

### ISSUE THREAD

**Issue by phprad** [Esri/esri-leaflet#1023]
How can we get all the features from vector service layer when using query()?
I was able to do the same with mapboxgl. using the source https://basemaps.arcgis.com/v1/arcgis/rest/services/World_Basemap/VectorTileServer/tile/{z}/{y}/{x}.pbf

I want to be able to do the same using leaflet.

**Sample**

```
var service = L.esri.featureLayerService({
        url: 'https://basemaps.arcgis.com/v1/arcgis/rest/services/World_Basemap/VectorTileServer/tile/{z}/{y}/{x}.pbf'
    });

      service.query().run(function(error, featureCollection, response){
          console.log(featureCollection);
      });
```

**Comment by jgravois** [comment]
if you really want to get the features in a single tile you could use something like [`@mapbox/vt2geojson`](https://github.com/mapbox/vt2geojson)

we don't currently expose a technique to query all the raw source behind vector tilesets directly.

https://community.esri.com/ideas/12828-vector-tile-layers-queryinglegends
