### ISSUE TITLE
SSL warning when using tiles

### ISSUE THREAD

**Issue by HarelM** [Esri/esri-leaflet#1032]
* Browser and version:

ie: Chrome 62, and all other I guess.

* Version of Leaflet (`L.version`):
1.2.0

* Version of esri Leaflet (`L.esri.VERSION`):
Using direct tiles

Steps to reproduce the error:
The following warning is presented:

1. surf to https://israelhiking.osm.org.il/#!/?s=4A1SY88XNQ
2. open F12 tools
3. it uses the following address:
https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}.png

What happens is [X].
The SSL certificate used to load resources from https://services.arcgisonline.com will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.
I was expecting [Y].
No warnings

I know this is not 100% related to the code here, but I'm not sure where else to open this issue.

**Comment by andygup** [comment]
Thanks for the heads up about the SSL warning from `*.arcgisonline.com`. We are working on getting that resolved and it should be taken care of before the end of the year. 

cc @jgravois

**Comment by jgravois** [comment]
thanks @HarelM for the report and @andygup for confirming that we're actively working on a fix!
