### ISSUE TITLE
intermittent test failures on Travis

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet#1038]
we are _still_ experiencing intermittent errors when running the test suite on [Travis](https://travis-ci.org/Esri/esri-leaflet).

i've had _some_ success in the past playing with the order individual tests are executed, but i'd love to actually put the problem to bed once and for all.

https://github.com/Esri/esri-leaflet/blob/a95cdce0b47bafc8716aeb08bfd78895a3c7f5c0/karma.conf.js#L14-L22

do you have any ideas @Biboba?

**Comment by Biboba** [comment]
I do experienced it locally as well.
I am under the impression that some tests are failing depending on asynchronous timing.

I noticed that for example, 'it will load a new image when the map moves'  test of DynamicMapLayerSpec is falling quite often. 

https://github.com/Esri/esri-leaflet/blob/a95cdce0b47bafc8716aeb08bfd78895a3c7f5c0/spec/Layers/DynamicMapLayerSpec.js#L106-L122

In this one, there are nested layer load event, and by debugging it seems that when failing, it exits the test and fails before having "reach" the 'done' callback. 

<img width="485" alt="capture d ecran 2018-01-04 a 19 09 20" src="https://user-images.githubusercontent.com/11556423/34578273-9c8d0198-f184-11e7-8801-700073804abd.png">

**Comment by jgravois** [comment]
> I am under the impression that some tests are failing depending on asynchronous timing.

what would be the best improvement we could make?

**Comment by jgravois** [comment]
the tweaks in 043d19e912ca41c513096185cfd09828fe640eb6 seem to generate _slightly_ more predictable behavior, but we'll need to rethink how we set up and tear down the map in the DynamicMapLayer and ImageMapLayer tests in order to get to the **root** of the problem.

**Comment by patrickarlt** [comment]
In general almost every travis build (except gh-release branch which should fail) has passed in the last few years so I'm going to close this https://travis-ci.org/Esri/esri-leaflet/builds.

**Comment by jgravois** [comment]
I'm okay with closing this issue, but just as a heads up, besides test failures I've also seen a substantial number of runs where the test suite exited with a `0` after only executing a handful of the tests.
