### ISSUE TITLE
TiledMapLayer doesn't use options.proxy to retrieve tiles

### ISSUE THREAD

**Issue by spoilsportmotors** [Esri/esri-leaflet#1052]
* Browser and version: All browsers
* Version of Leaflet (`L.version`): 1.0.3
* Version of esri Leaflet (`L.esri.VERSION`): 2.0.8 onwards

Steps to reproduce the error:
1. Configure a proxy ([ESRI Resource Proxy](https://github.com/Esri/resource-proxy)) for consuming a basemap - a tile layer from ArcGIS Online is fine
2. Add the basemap with a proxy in the options to a map

What happens is: you can see the request for metadata go through the proxy, and return successfully, but requests for tiles go directly to the underlying tile layer URL, ignoring the proxy. In the case where no authentication is required, the map appears to function as expected, but in cases where the proxy is actually performing a more critical role, no tiles appear in the map. 

* Optional: I'm *not* using the [CDN](http://www.jsdelivr.com/projects/leaflet.esri), I'm loading/bundling the library using [webpack](https://webpack.github.io/)

I think that the fix is nigh-trivial; PR incoming.

**Comment by jgravois** [comment]
thanks for the detailed bug report and fix @spoilsportmotors!
