### ISSUE TITLE
Editing multiple features at once

### ISSUE THREAD

**Issue by mladenp** [Esri/esri-leaflet#1055]
It looks like methods for editing multiple features doesn't exist in this library.
I can only find addFeature/updateFeature methods but they accept only one feature.
Currently i am calling ArcGIS updateFeatures manually, without esri-leaflet lib, by sending requests via form-data.
And i am sending features data like so: 
`[{"attributes":{"OBJECTID":2406107,"PROGRESS_STATUS":"Assigned"}}]`

So my question is: is there any way to edit multiple features at once and can i send just data i want to update, like i am already doing in my form-data request?

**Comment by jgravois** [comment]
i added a method to bulk `deleteFeatures()` in #510. a pull request for something similar to `updateFeatures()` would be welcome.

**Comment by Biboba** [comment]
Hi,

Would see an `addFeatures: function (feature, callback, context)` function, taking as input a feature GeoJSON FeatureCollection or an array of features or should support both ?

**Comment by jgravois** [comment]
sorry, i thought i already replied here @Biboba. support for FeatureCollections would be sufficient.

**Comment by jgravois** [comment]
resolved (way back in April) in #1083
