### ISSUE TITLE
How To Detect Invalid Token Error

### ISSUE THREAD

**Issue by bdk0172** [Esri/esri-leaflet#1058]
We are generating a token and then putting it into localStorage until it expires and we generate a new one.  We've had some users report that they have a token that doesn't expire for 2 days and then a server admin will reboot the ArcGIS server and invalidate all of the tokens.  The user attempts to retrieve tiles with the token from localStorage which to the browser hasn't expired yet and there is no error returned back.  When we add the layer to the map, we are including a callback to on load and on tileerror.  It comes back to the load callback and not tileerror and there is nothing in the dev tools console stating any kind of error.  I see in your code you are checking for 498 and 499, but when I step through it doesn't hit that part of the code.  Any ideas?

**Comment by tvblomberg** [comment]
Use authenticationrequired event to detect this. Here is a reference:
https://esri.github.io/esri-leaflet/examples/arcgis-server-auth.html
