### ISSUE TITLE
Can I update symbology of a dynamicMapLayer?

### ISSUE THREAD

**Issue by ahalota** [Esri/esri-leaflet#1059]
Hi,

I'm trying to edit the symbology for a polygon that is being shown as part of a dynamicMapLayer. The services is a MapService with a photomosaic db, and footprint and boundary polygon layers. 

Is there any way to use esri-leaflet to change the symbology for the boundary layer interactively? (I want to set a thicker line width and possibly color change one mouseover so that my users know what they are looking at)

**Comment by ahalota** [comment]
Ah, I see now it can act as a FeatureLayer if I just reference that specific layer by its suburl ( ./...Mapserver/1)

Non-issue then. I'll leave this here in case any other curious person checks in.

**Comment by jgravois** [comment]
:+1: see also https://github.com/Esri/esri-leaflet/issues/566
