### ISSUE TITLE
dynamicMapLayer.bindPopup() causes function call for EVERY dynamic map layer on the map

### ISSUE THREAD

**Issue by ahalota** [Esri/esri-leaflet#1061]
* Version of Leaflet (`L.version`):
1.3.1
* Version of esri Leaflet (`L.esri.VERSION`):
2.1.2

Steps to reproduce the error:

Similar to the sample: http://esri.github.io/esri-leaflet/examples/customizing-popups.html
Create a few dynamic map layers (in different locations) and bind a pop up to each one. If you include a console log when the function is run you will notice it is run once for each layer on the map.

var count = 0;
for (i in myLayers){
    myLayers.bindPopup(function(error,fc){
       count++;
       console.log(count);
     return 'This is my popup!';
}}

Maybe it's not a huge deal, but it is unexpected behavior...

**Comment by jgravois** [comment]
> you will notice it is run once for each layer on the map.

when you bind a popup to more than one `dynamicMapLayer` we _need_ to send an identify request to each one in order to determine whether the map click location intersects any features in each of the corresponding services.

> it does not seem like it checks whether the clicked layer was the same one or not

the same as what?

**Comment by jgravois** [comment]
closing, but happy to chat more if you have additional questions.
