### ISSUE TITLE
What is the (efficiency) difference of creating several dynamicMapLayers from one service, versus updating layers array?

### ISSUE THREAD

**Issue by ahalota** [Esri/esri-leaflet#1062]
I'm trying to decide between two methods. I have 10 layers in my MapService, which the user can add or remove via checkbox. I'd like to minimize calls to the server.

Should I:
a) create 10 dynamicMapLayers, each with the options `layers: [layerNum]` , and map.add/remove, or;
b) one dynamicMapLayer, with option `layers: [0,1,2,3,4,5,6,7,9]`, and update layers 

I'm doing some tests on my own for this but if anyone knows for sure one is better than the other would be interested. Thanks.

**Comment by jgravois** [comment]
option b) would make a single request to the service initially, option a) will make 10.

later, when a checkbox is ticked to remove a layer, option b) will make another single request to the service. option a) will not.

**Comment by Biboba** [comment]
Option b) is clearly better to minimize calls to the server.
I would just add that I only see 2 advantages with option a) : 
- You would be able to play with the order the layers are displayed. With option b) you cannot, layers will be ordered the way it is exposed on the REST API.
- You will be able to on the transparency of each layer individually : with option b) it will be applied to all the layers

**Comment by jgravois** [comment]
@Biboba is right.

the [dynamic layers capability](https://enterprise.arcgis.com/en/server/latest/publish-services/linux/about-dynamic-layers.htm) of map services was designed to expose more fine grained control over individual layer symbology, draw order and transparency.

**Comment by ahalota** [comment]
Thanks for the input. I'll make the switch in my code and go for option b) to speed up the initial loading process.

**Comment by ahalota** [comment]
I ended up going for option a). Option b) was too slow on the redraw so the check/uncheck changes weren't happening as fast as I wanted.
