### ISSUE TITLE
esri-leaflet throws error when bundled with Rollup

### ISSUE THREAD

**Issue by rbrtmrtn** [Esri/esri-leaflet#1063]
* Browser and version:

n/a

* Version of Leaflet (`L.version`):

1.3.1

* Version of esri Leaflet (`L.esri.VERSION`):

2.1.3

Steps to reproduce the error:

1. `yarn add esri-leaflet`
2. Write some code to `import { tiledMapLayer } from 'esri-leaflet'`
2. `rollup`

What happens is [X].

I get an error:

    [!] Error: 'geojsonToArcGIS' is not exported by ..\mapboard\node_modules\@esri\arcgis-to-geojson-utils\dist\arcgis-to-geojson.js

I was expecting [Y].

No error.

(if possible, create a [jsbin](http://jsbin.com/dagilag/edit?html,output) that demonstrates the problem)

* Optional: I'm *not* using the [CDN](http://www.jsdelivr.com/projects/leaflet.esri), I'm loading/bundling the library using:

Rollup

**Comment by jgravois** [comment]
hi @rbrtmrtn! what version of rollup are you using?

can you do me a solid and try adding the line below to `@esri/arcgis-to-geojson-utils/package.json`?

```js
"module": "index.js"
```

**Comment by rbrtmrtn** [comment]
Hey @jgravois ! So I added that line and it worked :smile:  I also found that using `rollup-plugin-node-resolve` with a config option of `jsnext: true` gets around it as well.

**Comment by jgravois** [comment]
fix released as [`v2.1.4`](https://github.com/Esri/esri-leaflet/releases/tag/v2.1.4)
