### ISSUE TITLE
can you toggle through more than one popup?

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet#1068]
when several features are stacked on top of one another?

(_good_ question from user at DevSummit)

**Comment by pepperlk** [comment]
This would be nice.. We had to create from scratch in the base popup ..

**Comment by jgravois** [comment]
can you share any of that code?

**Comment by pepperlk** [comment]
@jgravois possibly.. need to check with a few people..

**Comment by pmacMaps** [comment]
@pepperlk, any updates as to whether you can share the code?

**Comment by pepperlk** [comment]
@pmacMaps Unfortunately no we cannot share.. but maybe we can look at doing a pr from original work in the future.. thanks

**Comment by patrickarlt** [comment]
@pmacMaps @pepperlk If one of you could PR a sample for this that would be great and probably give people enough guidance to close this issue. A pretty decent example might be:

1. Listen to the [feature layer events](https://esri.github.io/esri-leaflet/api-reference/layers/feature-layer.html#events) and add features to a client side index like [rbush](https://github.com/mourner/rbush)
1. Bind a popup to the layer
1. Listen for `popupopen` on the layer
1. When you get a `popupopen` event query the index for nearby features and then customize the popup UI accordingly.

**Comment by jgravois** [comment]
happy to see a new demo land, but closing.
