### ISSUE TITLE
No callback for useCors=false and Server Error

### ISSUE THREAD

**Issue by strajuser** [Esri/esri-leaflet#1069]
There is no callback for request with useCors=false and any server error.
As example, any not-found-url:
http://jsbin.com/nesomeyiju/edit?html,console,output

Can be simply fixed by addind script.onerror handler in src/Requests.js, e.g:
script.onerror = function(error) { callback.call(context, error); }

**Comment by jgravois** [comment]
thx for taking the time to point this out @strajuser! a pull request would be sincerely appreciated. if that's not feasible, i will patch myself in time.

**Comment by strajuser** [comment]
#1070 =)

**Comment by jgravois** [comment]
wow. its been that kind of week. thanks again!
