### ISSUE TITLE
Question: adding custom L.esri.BasemapLayer

### ISSUE THREAD

**Issue by advancedits** [Esri/esri-leaflet#1071]
Is it possible to add https://tileservice.charts.noaa.gov as a L.esri.BasemapLayer  or is it only the ones listed here: https://esri.github.io/esri-leaflet/api-reference/layers/basemap-layer.html

**Comment by jgravois** [comment]
`tiledMapLayer` allows you to pass in any service url you want.

`basemapLayer` is more or less a wrapper around the class above that (only) allows you to supply a string from the predefined list.

**Comment by advancedits** [comment]
I was thinking that might be the case. We have our basemap layer selector on the top left icon here https://www.nwfsc.noaa.gov/data

and I wanted to add https://tileservice.charts.noaa.gov however it doesn't seem like I can get this tileMapLayer to be an option within the base map selector correct?

**Comment by jgravois** [comment]
> it doesn't seem like I can get this tileMapLayer to be an option within the base map selector correct?

that's not true. you can pass any layer type you want to [`L.Controls.Layers`](http://leafletjs.com/reference-1.3.0.html#control-layers).

Our example [here](http://esri.github.io/esri-leaflet/examples/layers-control.html) passes two `basemapLayer`s, but you could just as easily swap in a `tiledMapLayer`

**Comment by advancedits** [comment]
Ok so I tried two different ways, I have updated https://www.nwfsc.noaa.gov/data (check it out incognito)

Using imageMapLayer the nautical map shows up but super slow. Using TileLayer, nothing shows up. What am I doing wrong on the tile layer side that nothing is being shown. In Dev console, I do see pngs being returned.

```
     var rnc_image = L.esri.imageMapLayer({
            url: "https://seamlessrnc.nauticalcharts.noaa.gov/arcgis/rest/services/RNC/NOAA_RNC/ImageServer",
            attribution: 'NOAA Office of Coast Survey',
            position: "back"
        });

     var rnc_image2 = L.tileLayer('https://tileservice.charts.noaa.gov/tiles/50000_1/${z}/${x}/${y}.png');



   var map = L.map('map', { zoomControl: false , layers: oceans}).setView([39.351, -116.48], 5);

	var baseMaps = {
			  "Imagery" : imagery,
			  "Shaded Relief" : shadedrelief,
			  "Oceans" : oceans,
			  "Topographic" : topographic,
			  "National Geographic": nationalGeographic,
			  "Nautical Charts ImageMapLayer": rnc_image,
			  "Nautical Charts TileLayer": rnc_image2
	};

```

**Comment by jgravois** [comment]
if you snoop the web traffic you'll see that the mistake in your [syntax](http://leafletjs.com/reference-1.3.0.html#tilelayer) is appending `$` signs in the tile requests being sent out.

```
https://tileservice.charts.noaa.gov/tiles/50000_1/$1/$0/$1.png
```

**Comment by advancedits** [comment]
perfect that was it :)
