### ISSUE TITLE
Esri Map Layers Not Clearing Properly

### ISSUE THREAD

**Issue by developingcountries** [Esri/esri-leaflet#1072]
I've created a web map that uses ArcGIS FeatureServer layers at https://americanredcross.github.io/cancross/ontario-regions-map.  The ArcGIS feature layers are hosted off ArcGIS feature server, e.g. https://services1.arcgis.com/PcevIObMOTNlnhqj/arcgis/rest/services/Algoma_District/FeatureServer/0 and https://services1.arcgis.com/PcevIObMOTNlnhqj/arcgis/rest/services/Geography_North/FeatureServer/0.  Web map is using leaflet.js and  esri-leaflet-rc6.js. 
When I add more than one of these ArcGIS feature server layers and then try to clear these layers, they do not clear properly.   

My Chrome is browser version 63.0.3239.132 (Official Build) (64-bit), but I also encounter this problem on other browsers such as Internet explorer etc.

My function for clearing the layers is:

```    function clearAllLayers() {
        map.eachLayer(function (layer) {
            map.removeLayer(layer);
        });
        displayedServiceLayers.length = 0; 
        L.esri.basemapLayer('Streets').addTo(map);
        map.setView([47, -81], 5);
    }
```

The map is initialized with     

```var map = L.map('map').setView([ 47, -81], 5);
    L.esri.basemapLayer('Streets').addTo(map);
```

and each drop-down map layer is added with:
```
            var region = L.esri.featureLayer(serviceLayer, {
                simplifyFactor: 1,
                style: function (feature) {
                    return { color: 'red', weight: 1 };
                }
            }).addTo(map);
```

But the clearAllLayers() function does not remove all the layers at once, but it needs to be called more than once by clicking the Clear Map Layers button. 

For example, on the web map, if you choose Geography Zones > North, and then also choose GAC > Dryden, you'll see two ArcGIS feature server layers super-imposed upon each other. But then you'll need to hit the "Clear Map Layers" button a few times (i.e. call clearAllLayers() function a few times) before these layers are cleared.  clearAllLayers() should only be called once and it should clear all the layers.

![esri-leaflet-wontclear](https://user-images.githubusercontent.com/5304587/37562278-ade0a1e0-2a21-11e8-9c99-08871157fb50.jpg)

Is there a better way than map.removeLayer to clear all the layers, or perhaps another solution needed?  Thanks.

**Comment by jgravois** [comment]
i just took a look at your site and the layers all disappear when i click <kbd>Clear Map Layers</kbd> once. does that mean you solved your own problem?

**Comment by developingcountries** [comment]
Hi there, my problem still has not been solved. 

To reproduce the issue, try adding a few map layers. For example, add a layer from the "Geography Zones", and then a layer from "GAC", and a third layer from "Regions" drop down menu.  Then you'll find that you need to click "Clear Map Layers" a couple of times in order to clear the map layers.   All the layers do not clear off the map from one click of "Clear Map Layers" button. 

I had this issue on different browsers running in Windows 7, including Chrome and Internet Explorer browsers. Thanks.

**Comment by jgravois** [comment]
> To reproduce the issue, try adding a few map layers.

That's what i did when i tested a couple weeks ago.

When i launch the app and select a geography zone _now_ it fails to display the new layer altogether.

* running the app over `http` i see that volunteers.csv and fleet.csv fail to load.
* over `https`, the flat files load but the `http` service url induces a mixed content error.

**Comment by developingcountries** [comment]
Thanks for pointing that out. There was a mismatch as some were http and some were https resources.  I've updated all the js libraries and ArcGIS feature server layers to only use https. 

I'm adding ESRI feature server layers (Geography Zones, GAC, and Regions) with .addTo(map)

```
    function addMapLayer(serviceLayer, selectedValue, popupInfo){
        if($.inArray(serviceLayer, displayedServiceLayers) == -1 && selectedValue.indexOf('Geography')==0) {
            var geography = L.esri.featureLayer(serviceLayer, {
                //Speeds up performance of map layers
                simplifyFactor: 1,
                style: function (feature) {
                    return { color: 'yellow', weight: 3 };
                }
            }).addTo(map);
            geographyInfo = popupInfo;
            geography.bindPopup(function(features) {
                return geographyInfo; 
            });
            geography.query().bounds(function (error, latlngbounds) {map.fitBounds(latlngbounds);});
            //Keeps track of which region map layers have already been displayed.
            displayedServiceLayers.push(serviceLayer)
        }else if($.inArray(serviceLayer, displayedServiceLayers) == -1 && selectedValue.indexOf('Region')==0) {
            var region = L.esri.featureLayer(serviceLayer, {
                simplifyFactor: 1,
                style: function (feature) {
                    return { color: 'red', weight: 1 };
                }
            }).addTo(map);
            regionInfo = popupInfo;
            region.bindPopup(function(features){
                return regionInfo;
            });
            region.query().bounds(function (error, latlngbounds) {map.fitBounds(latlngbounds);});
            displayedServiceLayers.push(serviceLayer);
        } else if($.inArray(serviceLayer, displayedServiceLayers) == -1 && selectedValue.indexOf('GAC')==0) {
            var GAC = L.esri.featureLayer(serviceLayer, {
                simplifyFactor: 1,
                style: function (feature) {
                    return { color: 'blue', weight: 2 };
                }
            }).addTo(map);
            GACInfo = popupInfo;
            GAC.bindPopup(function(features){
                return GACInfo; 
            });
            GAC.query().bounds(function (error, latlngbounds) {map.fitBounds(latlngbounds);});
            displayedServiceLayers.push(serviceLayer);
        }        
    }
```

and the Remove function is using map.removeLayer() function, but I need to call this function multiple times to clear multiple layers. One call to this function should clear all the layers.
```
    function clearAllLayers() {
        map.eachLayer(function (layer) {
            map.removeLayer(layer);
        });
        displayedServiceLayers.length = 0; 
        L.esri.basemapLayer('Streets').addTo(map);
        map.setView([47, -81], 5);
    }

```
Is there a better way to clear the map layers? Thanks.

**Comment by jgravois** [comment]
> Is there a better way to clear the map layers?

Your current approach seems valid to me. I took a few minutes to update your app to the most recent release of Leaflet/Esri Leaflet and it seems to resolve the problem.

http://jsbin.com/neqaqoz/edit?html,output

```js
// new syntax
featureLayer({
  url: `${your service url}
  otherOptions
});
```

**Comment by developingcountries** [comment]
Thanks so much for your help, and for your suggestions. I updated my app to the newest Leaflet and Esri-Leaflet and the map layers are clearing now.  

Could you delete your jsbin? Even though it only has sample data, I would prefer not having the code out there on the web. Thanks.
