### ISSUE TITLE
Layer order control with zIndex issues

### ISSUE THREAD

**Issue by advancedits** [Esri/esri-leaflet#1073]
Sorry here's another question :) Let me know if I should file questions somewhere else.

So I add esri arcGIS layers using mostly tiledMapLayer so
```js
node.data.layer = L.esri.tiledMapLayer({
  url: node.data.url,
  pane: 'custom',
  useCors: false,
  zIndex:1
});

map.addLayer(node.data.layer);
```

I am also using the https://github.com/ljagis/leaflet-measure tool and setting { captureZIndex: 10000 }

```js
var measureControl = new L.Control.Measure({position: 'topleft', captureZIndex: 10000 });
measureControl.addTo(map);
```

My issue is that the measurement tool shows behind the arcGIS layers instead of being on top even though the zIndex is higher

Check it out here https://www.nwfsc.noaa.gov/data/

Any thoughts on the use of zIndex here? AddLayer seems to disregard the zIndex option in tiledMapLayer

**Comment by jgravois** [comment]
i'd suggest using [map panes](http://leafletjs.com/reference-1.3.0.html#map-pane) instead.

http://esri.github.io/esri-leaflet/examples/layer-ordering.html

**Comment by advancedits** [comment]
For the arcGIS layers we are using "pane: 'custom'" but for the Measure control, do I create another pane? I see that it says "Panes are added to the map in order" so if the user uses the measurement tool first then checks the arcGIS layer, wouldn't the arcGIS layer get added on top of the measurement?

**Comment by jgravois** [comment]
that plugin doesn't yet pass through custom panes when it adds its own [`L.layerGroup()`](https://github.com/ljagis/leaflet-measure/blob/ba0aa5b3d0ce466a7b006f2c188ba0b7bb2b3f12/src/leaflet-measure.js#L58) to the map internally. this means that the sketched features always end up in the `overlay` pane.

you should send them a PR to introduce that as a new constructor option.

**Comment by advancedits** [comment]
Posted on their github https://github.com/ljagis/leaflet-measure/issues/103
closing here
