### ISSUE TITLE
Error :"Cannot set property 'innerHTML' of null" when attribution is missing

### ISSUE THREAD

**Issue by octavm** [Esri/esri-leaflet#1077]
I'm using Chrome 65.0.3325.181 (Official Build) (64-bit), leaflet-1.3.1, esri-leaflet-2.1.4 master, 

Steps to reproduce the error:

1. Set the attribution option of TileLayer to 'null' for any Esri BasempLayer
2. Drag the map a few times, zoom in, out. After a few moves, it will freeze.
3. See F12 for errors:
`Uncaught TypeError: Cannot set property 'innerHTML' of null
    at M (Util.js:342)
    at Util.js:313
    at Object.window._EsriLeafletCallbacks.(anonymous function) [as c0] (https://unpkg.com/esri-leaflet@2.1.3/dist/esri-leaflet.js:4:2566)
    at World_Street_Map?callback=window._EsriLeafletCallbacks.c0&f=json:1`

Here is a CodePen that demonstrates the problem: ([CodePen](https://codepen.io/anon/pen/wmpQPo))

This means that whenever the attribution is null or missing completely, BasemapLayer don't work anymore.
Also I've seen problems with the "*Labels" basemaps, that have attribution=''. When Debugging the code the same error happens.

**Comment by jgravois** [comment]
> Set the attribution option of TileLayer to `null` for any Esri BasempLayer

Why would anyone do this?

**Comment by octavm** [comment]
For the simple case when a user doesn't want to have an attribution label at all. 
Wouldn't you prefer to have a reliable code that doesn't crash on unexpected values?

**Comment by Biboba** [comment]
Hi,

I think what @jgravois means is that ESRI basemaps layers are subject to copyrights and it is mandatory to display attribution. You are basically violating a copyrights by doing so. So 'Why would anyone do this?' 
You should consider attribution property as read-only !

**Comment by octavm** [comment]
Ok, I can understand from the copyright perspective that attribution should always be present. But still from a programming point of view, it doesn't seem very nice for the program to crash just like that. Even the [Leaflet](http://leafletjs.com/reference-1.3.0.html#tilelayer-attribution) documentation states that the default value for attribution is null (valid value).

At the very least it should be handled gracefully, notifying the user that attribution is mandatory for ESRI Basemaps.

Also, please see my comment from pull #1076 . Currently, all the baselayers ending with "*Lables" are crashing because their attribution is "" (empty string).

**Comment by jgravois** [comment]
the _correct_ way to ignore our [terms](https://github.com/Esri/esri-leaflet#terms) would be to omit the attribution control entirely.

```js
var map = L.map("map", {
  attributionControl: false
}).setView([37.75, -122.23], 10);

L.esri.basemapLayer("OceansLabels").addTo(map);
```
http://jsbin.com/dajehuz/edit?html,output

> Even the Leaflet documentation states that the default value for attribution is `null`.

That may be, but its not the default for `L.esri.basemapLayer`.
