### ISSUE TITLE
While loading two dynamicMapLayers after layer zindex value cannot be set

### ISSUE THREAD

**Issue by zhuxiangjian** [Esri/esri-leaflet#1080]
* Browser and version:

ie: Chrome 51, IE11

* Version of Leaflet (`L.version`):

0.7.7, 1.0.0?

* Version of esri Leaflet (`L.esri.VERSION`):

hello,when i use DynamicMapLayer to loading two layers  ,because of layers z-index ,when layer loading ,sometimes a covered b,and sometimes b covered a  ,can you give DynamicMapLayer  an attribute to set zindex

**Comment by jgravois** [comment]
in Leaflet 1.x you shouldn't use z-index to control layer order, you should use [map panes](http://esri.github.io/esri-leaflet/examples/layer-ordering.html)

**Comment by jgravois** [comment]
`zIndex` is now supported as a constuctor option to help refine draw order within a pane.

#1084
