### ISSUE TITLE
Using esri-leaflet with traffic map service

### ISSUE THREAD

**Issue by Techn1x** [Esri/esri-leaflet#1082]
Hi everyone,

I've just started using ESRI map layers, and they are great! I wanted to add a traffic layer however, I can't seem to get it to work. My understanding is I need to use a TiledMapLayer with a custom URL (rather than BasemapLayer)

I have generated a Traffic Layer proxy URL (and ensured that the referrer list is correct - not getting 403 forbidden errors)
`https://utility.arcgis.com/usrsvcs/appservices/XXXXXXXXX/rest/services/World/Traffic/MapServer`

I have tried the following;
```javascript
this.L.esri.tiledMapLayer({url: 'https://utility.arcgis.com/usrsvcs/appservices/XXXXXXXXX/rest/services/World/Traffic/MapServer'})
```

Looking at the network traffic, leaflet then tries to get tiles from the following URL (adds /tile/z/y/x)
`https://utility.arcgis.com/usrsvcs/appservices/XXXXXXXXX/rest/services/World/Traffic/MapServer/tile/6/35/53`

But this URL returns 404 for all tiles.......

Am I using this service correctly? Should I be using a different esri-leaflet layer? Do I need to add some additional URL parameters? I can't seem to find any correct URL examples for this service..

Thanks!

**Comment by jgravois** [comment]
since traffic changes by the minute, you'll need to use [`dynamicMapLayer`](http://esri.github.io/esri-leaflet/api-reference/layers/dynamic-map-layer.html)

live example (you'll skip authenticating)
http://esri.github.io/esri-leaflet/examples/premium-content.html

**Comment by Techn1x** [comment]
Thankyou! Works perfectly
