### ISSUE TITLE
Fix the flicker when zooming projected dynamic layer

### ISSUE THREAD

**Issue by appleshowc** [Esri/esri-leaflet#1085]
* Browser and version: Chrome 64

* Version of Leaflet (`L.version`): 1.3.1

* Version of esri Leaflet (`L.esri.VERSION`): `master`

When zooming L.esri.dynamicMapLayer, it will disappear for a few milliseconds because of the offset position of the scaled layer was not correctly calculated.

I found some issuses about this 
* [Offset in custom projection with ImageOverlay](https://github.com/Leaflet/Leaflet/issues/2592)
* [Add ImageOverlay that accepts bounds as projected coordinates](https://github.com/kartena/Proj4Leaflet/pull/68)

It is better to use L.Proj.ImageOverlay than L.ImageOverlay when creating RasterLayer's image.

Here are the changes I've made:

### esri-leaflet v2.1.4 RasterLayer
```javascript
// to fix dynamiclayer offset (tips: require proj4leaflet before esri-leaflet)
var Overlay = leaflet.Proj ? leaflet.Proj.ImageOverlay : leaflet.ImageOverlay.extend({...});
```

### proj4leaflet v1.0.1
```javascript
L.Proj.ImageOverlay = L.ImageOverlay.extend({
  //!!! remove initialize
  onAdd: function (map) {
      var ne = map.options.crs.project(this._bounds._northEast),
          sw = map.options.crs.project(this._bounds._southWest);
      this._projectedBounds = L.bounds(L.point(sw.x, ne.y), L.point(ne.x, sw.y));
      L.ImageOverlay.prototype.onAdd.call(this, map);
  },
  ...
});
```

**Comment by jgravois** [comment]
it sounds as if your proposed patch makes it possible to inherit from proj4leaflet only when it is present but requires that proj4leaflet itself be patched with the `onAdd()` logic you've shared in order for everything to work appropriately. is that correct?

if so, i'd be happy to make changes here, but it probably makes more sense to open a pull request upstream before we take any action.

**Comment by gruffwy** [comment]
works well !!! thanks !!!

**Comment by jwasilgeo** [comment]
> it probably makes more sense to open a pull request upstream before we take any action.

https://github.com/Esri/esri-leaflet/issues/1085#issuecomment-410057418

Agreed and closing the issue for now. Thanks all.
