### ISSUE TITLE
How do I not use the debug version?

### ISSUE THREAD

**Issue by timwis** [Esri/esri-leaflet#1087]
Hiya folks! I'm using [webpack-bundle-analyzer](https://www.npmjs.com/package/webpack-bundle-analyzer) to inspect my bundle's dependencies and noticed that `esri-leaflet-debug.js` is one of the largest. I tried running `webpack` with `NODE_ENV=production` to see if there was a flag that made a difference, but it's still there. Any idea how to not use the debug version? (I assume the non-debug version is smaller).

<img width="1404" alt="screen shot 2018-04-09 at 6 38 45 pm" src="https://user-images.githubusercontent.com/761444/38526730-712058d4-3c25-11e8-9b9f-20fdc5065d82.png">

I'm importing it this way:

```javascript
import { tiledMapLayer as EsriTileLayer } from 'esri-leaflet'
```

**Comment by timwis** [comment]
Hey John! Thanks for the quick response. That makes sense, and it's cool to see this library shipping both versions. It looks like the issue was that by default, [webpack gives precedence to the `browser` property](https://webpack.js.org/configuration/resolve/#resolve-mainfields), _then_ `module`, then `main`. By changing the order of this in my webpack config, I was able to resolve the issue.

![screen shot 2018-04-10 at 5 56 59 am](https://user-images.githubusercontent.com/761444/38550267-022d687c-3c84-11e8-961f-408635d5112a.png)

Up next is that pesky `leaflet-src.js`! Thanks for the suggestion on that -- I'll give it a shot. Cheers.

**Comment by timwis** [comment]
FYI it looks like leaflet ships an ESM version, but it doesn't actually come through when you `npm install leaflet`. I've [posted an issue here](https://github.com/Leaflet/Leaflet/issues/6131) if you're interested.

**Comment by jgravois** [comment]
even though at `v1.3.1` leaflet didn't yet ship a _flat_ ES6 bundle, their unbuilt code has been ES6 modules for awhile.

so just try adding `"module": "src/Leaflet.js"`.

**Comment by timwis** [comment]
To a fork of leaflet? Or an alias of sorts in my webpack config?

**Comment by jgravois** [comment]
i meant setting a new value in `/node_modules/leaflet/package.json` in your local project for webpack to pick up on.

**Comment by dadamssg** [comment]
@timwis hey can you show exactly what you did in your webpack config to handle this? Something like this? 

```
module.exports = {
  //...
  resolve: {
    mainFields: ['module', 'main', 'browser']
  }
}
```

This breaks my app. :/

**Comment by timwis** [comment]
Sure, I think if you clicked the commits linked above it should show you the exact changes I used. To be honest it was a few months ago and I don't remember. It may be worth cloning my Repository and using that bundle inspect tool to see if the leaflet dependency is actually smaller (use the v2 branch not master). Can't remember if I figured it out, but the reference commits suggest I may have.
