### ISSUE TITLE
Imagery + Imagery Labels work separately.  How to join/mix this in Leaflet Control Layers to make them "become" a single layer 

### ISSUE THREAD

**Issue by albabrobia** [Esri/esri-leaflet#1089]
Hello, 
in my leaflet map, I want to use ESRI Imagery base map with Imagery labels. 

I only got it by using Esri Leaflet "Switching basemaps", but I wish to use Leaflet Control Layers, and 
I don't know how.

The question is: Is it possible to make "imagery + imagerylabels" appear in the leaflet control layers as a "single layer"/ be managed as a "single layer"?

THANKS

**Comment by albabrobia** [comment]
solved:

var esriSatellite = L.esri.basemapLayer('Imagery');
var esriSatelliteLabels = L.esri.basemapLayer('ImageryLabels');
var esriImageryLabels = L.featureGroup([esriSatellite, esriSatelliteLabels]);

**Comment by jgravois** [comment]
glad to hear it. you can also find an example here:
http://esri.github.io/esri-leaflet/examples/layers-control.html
