### ISSUE TITLE
dynamicLayers option for L.esri.dynamicMapLayer -- Object or Array?

### ISSUE THREAD

**Issue by plaxdan** [Esri/esri-leaflet#1091]
The documentation for `L.esri.dynamicMapLayer(<Object> options)` ([here](http://esri.github.io/esri-leaflet/api-reference/layers/dynamic-map-layer.html)) states that the type of the `dynamicLayers` option should be an `Object` but [the examples](https://developers.arcgis.com/rest/services-reference/export-map.htm#GUID-D77B8AC3-4BF2-40FD-80A8-A9596AE6D965) from the Export Map documentation show the `dynamicLayers` querystring parameter as an Array. 

Which should it be?

**Comment by jgravois** [comment]
The service definitely expects an Array.

live demo: http://jsbin.com/fitowil/edit?html,output

tracking for our doc bug: https://github.com/Esri/esri-leaflet-doc/issues/180
