### ISSUE TITLE
XMLHttpRequest calls fail when server requires credentials

### ISSUE THREAD

**Issue by mcalmus** [Esri/esri-leaflet#1093]
* Browser and version:

all

* Version of Leaflet (`L.version`):

all

* Version of esri Leaflet (`L.esri.VERSION`):

Reproduced in 2.0.8, 2.1.4

We have a layers server that requires/uses client authentication. We had to patch esri-leaflet to add the following:

var s=jnewXMLHttpRequest;
Added ====> s.withCredentials = true;
return s.onError=....

**Comment by jgravois** [comment]
see #881
