### ISSUE TITLE
Map doesn't load on window size expansion

### ISSUE THREAD

**Issue by advancedits** [Esri/esri-leaflet#1095]
* Browser and version:

Chrome
Version 66.0.3359.139 (Official Build) (64-bit)

* Version of Leaflet (`L.version`):

Leaflet 1.3.1

* Version of esri Leaflet (`L.esri.VERSION`):

https://unpkg.com/leaflet@1.3.1/dist/leaflet.js

Steps to reproduce the error:

1. Make browser size small

2. go to 
https://www.nwfsc.noaa.gov/data/map

2. then maximize window and see gray bars around the map. 

What happens is when the window maximizes

I was expecting the map to reload or expand onto the areas that were not previously loaded due to the window size.

**Comment by Mak-NOAA** [comment]
Please close issue, I filed a ticket with Leaflet
https://github.com/Leaflet/Leaflet/issues/6156

**Comment by advancedits** [comment]
https://github.com/Leaflet/Leaflet/issues/6156
