### ISSUE TITLE
esri-leaflet 2.0.8 is no longer available on unpkg

### ISSUE THREAD

**Issue by rbrtmrtn** [Esri/esri-leaflet#1096]
* Browser and version:

n/a

* Version of Leaflet (`L.version`):

n/a

* Version of esri Leaflet (`L.esri.VERSION`):

2.0.8

Steps to reproduce the error:

1. Go to https://unpkg.com/esri-leaflet@2.0.8

What happens is:

It throws a `404` with the message: `Cannot find module "dist/esri-leaflet-debug.js" in package esri-leaflet@2.0.8`

I was expecting: A `200` :smile: 

---

I have an app that was loading in esri-leaflet 2.0.8 via unpkg in production. It's been running for over a year now and just stopped working this morning. It looks like the browser version of the library (`esri-leaflet-debug.js`) is no longer available. I'm guessing this issue goes back to it not being available on npm. Were there any changes lately that might have deleted it? Just wanted to give a heads up!

Thanks

**Comment by rbrtmrtn** [comment]
Oddly, this URL works: https://unpkg.com/esri-leaflet@2.0.8/dist/esri-leaflet-debug.js

But unpkg can't make the hop from https://unpkg.com/esri-leaflet@2.0.8

Not seeing this behavior with any other version... very strange 🤔

**Comment by jgravois** [comment]
tracking in https://github.com/unpkg/unpkg/issues/110

**Comment by rbrtmrtn** [comment]
Awesome, thanks @jgravois! I'll keep an eye on the unpkg issue.

**Comment by rbrtmrtn** [comment]
@jgravois Sounds like unpkg is making progress on solving the intermittent errors. Thanks again for digging into this and I'll go ahead and close out the issue here!
