### ISSUE TITLE
Some way of Adding Legends to The WebMap leaflet

### ISSUE THREAD

**Issue by thefreakingmind12** [Esri/esri-leaflet#1097]
I have created the Leaflet Map but is there is someway of adding Legends to it. I have to add it anyhow to represt my Data. So Please Help me regarding it.

**Comment by pmacMaps** [comment]
There's a [repo](https://github.com/w8r/esri-leaflet-legend)for doing this.  It appears to have limited support for feature layers at this point.

You could also create icons/images representing the data and just create unordered lists for a legend.

**Comment by thefreakingmind12** [comment]
I am actually using esri webmap and plotting it on Leaflet. Is there is some quick way doing this. And how can i put icon on esri webmap plotted on leaflet.

**Comment by pmacMaps** [comment]
Are you looking to put an ArcGIS Online web map into Leaflet? If so, there's a [plugin](https://github.com/ynunokawa/L.esri.WebMap) to do that.

**Comment by thefreakingmind12** [comment]
I Have implemented arcgis online webmap into leaflet and got coloured layers but the problem is legends are not appearing for showing the values of those colors.
