### ISSUE TITLE
 "Cannot find module "dist/esri-leaflet-debug.js" in package esri-leaflet@2.1.1"

### ISSUE THREAD

**Issue by DonaldPeat** [Esri/esri-leaflet#1102]
* Browser and version:

    Chrome 65.0

* Version of Leaflet (`L.version`):

    1.2.0

* Version of esri Leaflet (`L.esri.VERSION`):

    2.1.1

What happens: Map doesn't load.  
  Console error : "Cannot find module "dist/esri-leaflet-debug.js" in package esri-leaflet@2.1.1"

I was expecting: Map to load.
   Updating to version 2.1.4 resolved the error.  (versions 2.1.0, 2.1.2, 2.1.3, 2.1.4 all work)

**Comment by jgravois** [comment]
I can't reproduce the behavior you describe but if you're reporting a problem with the unpkg.com CDN, temporary errors we're  reported a few weeks ago in #1096

https://unpkg.com/esri-leaflet@2.1.1/dist/esri-leaflet-debug.js

**Comment by DonaldPeat** [comment]
Yes, it seems to be an issue with unpkg and at the moment just with version 2.1.1. Upgrading the version resolved the issue. You may want to open an issue with unpkg.
