### ISSUE TITLE
Entities of all types appear the same color

### ISSUE THREAD

**Issue by valleyofdawn** [Esri/esri-leaflet#1103]
* Browser and version:
Chrome  67.0.3396.99 

* Version of Leaflet (`L.version`):
 1.3

* Version of esri Leaflet (`L.esri.VERSION`):
 Latest from npm.

Steps to reproduce the error:
My colleague installed the default setting of esri-leaflet in our site.
Added this feature-server as an overlay:
https://services2.arcgis.com/9xNzs4HrnCQY9yx4/ArcGIS/rest/services/tama_8/FeatureServer/0
This layer contains several "types" and in ArcGIS viewer each one has a different color.

What happens is:
All the types appear in the same color.
See here:
https://israelhiking.osm.org.il/share/EzljwnZ9i8

I was expecting each type to appear in a different color as in here:
http://www.arcgis.com/home/webmap/viewer.html?useExisting=1&layers=cf927291f74643cd8ad6230d8a64c770

I went through the documentation here:
https://esri.github.io/esri-leaflet/api-reference/layers/feature-layer.html
and didn't find any reference to this issue.

Any ideas?

**Comment by pmacMaps** [comment]
To retain the symbology of a service when adding it using the **L.esri.FeatureLayer** constructor, you also need to use the [Esri Leaflet Renderers](https://github.com/Esri/esri-leaflet-renderers) plugin.  Load this plugin after the base Esri Leaflet plugin.

From the Renderers page:
> The sole purpose of this plugin is to allow L.esri.FeatureLayer to automatically take on renderers defined in ArcGIS Feature Services. Esri Leaflet Renderers works in conjunction with Esri Leaflet, but it does not add any additional methods or properties to the class that it extends.

**Comment by valleyofdawn** [comment]
Thanks,
We'll try that.

**Comment by jgravois** [comment]
it'd be a good idea to add a note to the `FeatureLayer` API reference page about this.

it's a common point of confusion.

**Comment by jgravois** [comment]
resolved via https://github.com/Esri/esri-leaflet-doc/pull/183

thx @pmacMaps!
