### ISSUE TITLE
its difficult to understand which urls correspond with each esri leaflet layer

### ISSUE THREAD

**Issue by HarelM** [Esri/esri-leaflet#1104]
* Browser and version: 
Chrome 6x

* Version of Leaflet (`L.version`):
1.3.0

* Version of esri Leaflet (`L.esri.VERSION`):
2.1.4

Steps to reproduce the error:
Can be seen in the jsbin below. Using leaflet 1.1 there's no error but still no layer is visible.

1. Use leaflet 1.3.0
2. Try adding the following layer as dynamicMapLayer https://ags.moin.gov.il/arcgis/rest/services/PlanningPublic/tama35_hanchayot_svivatiot/MapServer/14

What happens is [X].
Layer is not showing
I was expecting [Y].
Layer should be seen

http://jsbin.com/kesuqakifa/edit?html,output

I'm probably missing something in my code, but how do I know which layer factory to use if I'm given an address? whether to use fature layer or dynmaic map layer?

The following is the code I'm using, but I'm sure it's no good...:
https://github.com/IsraelHikingMap/Site/blob/master/IsraelHiking.Web/sources/application/services/map-layers.factory.ts
Is there a chance to get a factory from this library that will know which layer to use according to the address?

**Comment by jgravois** [comment]
You can't pass a url that ends in a number to `DynamicMapLayer`

http://jsbin.com/nuzazuh/edit?html,output

see http://esri.github.io/esri-leaflet/tutorials/introduction-to-layer-types.html & https://github.com/Esri/esri-leaflet/issues/403

**Comment by HarelM** [comment]
Ok, Thanks a lot for the info! This is truly confusing...
A factory that gets an address and returns the right layer would solve most noobies questions, IMHO.
Also, I would recommend adding the above page to the API documentation some how, I always go to API page to find out what I can't or can do with a library:
http://esri.github.io/esri-leaflet/api-reference/

**Comment by jgravois** [comment]
i agree that this is an ideal opportunity to improve the developer experience.

i'll leave this issue open in hopes that someone can contribute a tweak to the API reference to link out to the relevant tutorial, an improvement to the lib itself to make the process of choosing the correct object less opaque (or both :smile:).

a factory that uses the capabilities in the metadata response for a given url or even just trapping the error and logging a warning in the console to point devs in the right direction would be _super_ helpful.
