### ISSUE TITLE
ArcGIS map is not displayed

### ISSUE THREAD

**Issue by dmitrygen** [Esri/esri-leaflet#1105]
* Browser and version:

Chrome (any version)

* Version of Leaflet (`L.version`):

"1.3.1"

* Version of esri Leaflet (`L.esri.VERSION`):

"2.1.4"

Steps to reproduce the error:

Use the library with the following url:
http://gis.72to.ru/arcgis/rest/services/Building_and_transport/Building_and_transportation/MapServer

What happens is [X].
Map is not displayed

I was expecting [Y].
Map is displayed

http://jsbin.com/cuviyedebi/edit?html,output

**Comment by jgravois** [comment]
your tiled map service isn't using the same standardized Levels of Detail as Google/Bing/OSM/ArcGIS Online. the coordinate reference system is the same, but not the scale levels or resolution.

you have two options:

1. republish the tiles
2. define the custom LODs explicitly in your app using proj4leaflet ([live example](http://esri.github.io/esri-leaflet/examples/non-mercator-projection.html))

**Comment by dmitrygen** [comment]
@jgravois Thank you very much. Is there any specification on "standardized Levels of Detail", so that i could correctly configure ArcGIS tiles cache?

**Comment by pmacMaps** [comment]
@dmitrygen, I have a [CodePen ](https://codepen.io/pmckinney/pen/ambpgj)using our organization's standard projection and tiling scheme, which also does not match the Google/Bing/OSM/ArcGIS Online.

If you go to [epsg](http://epsg.io/3857),  you can get the code snippet to construct your CRS with the proj4leaflet plugin.  The "origins" and "resolutions" information can be found at the REST endpoint under Levels of Detail (resolution for each tile level) and the Origin property after "Compression Quality".  Good luck!

**Comment by jgravois** [comment]
> Is there any specification on "standardized Levels of Detail", so that i could correctly configure ArcGIS tiles cache?

https://services.arcgisonline.com/arcgis/rest/services/World_Street_Map/MapServer?f=pjson

**Comment by dmitrygen** [comment]
Thank you, guys!
