### ISSUE TITLE
esri-leaflet fails when calling fitbounds

### ISSUE THREAD

**Issue by HarelM** [Esri/esri-leaflet#1106]
* Browser and version: Chrome latest

* Version of Leaflet (`L.version`): 1.3.0

* Version of esri Leaflet (`L.esri.VERSION`): 2.1.4

Steps to reproduce the error:
It's hard to say, since I couldn't create a minimal reproduction, but it has to do with `fitbounds` method called when the zoom level is already set to the same zoom.

What happens is [X].
I get an ugly error message
I was expecting [Y].
No error message should appear

Here is the error message:
```
TypeError: Cannot read property 'min' of undefined
    at NewClass._isValidCell (esri-leaflet-debug.js:3028)
    at NewClass._addCells (esri-leaflet-debug.js:2997)
    at NewClass._update (esri-leaflet-debug.js:2980)
    at NewClass.fire (leaflet-src.js:593)
    at NewClass.panBy (leaflet-src.js:3276)
    at NewClass._tryAnimatedPan (leaflet-src.js:4500)
    at NewClass.setView (leaflet-src.js:3154)
    at NewClass.fitBounds (leaflet-src.js:3253)
    at DataContainerService.push../sources/application/services/data-container.service.ts.DataContainerService.setData (data-container.service.ts:45)
    at DataContainerService.<anonymous> (data-container.service.ts:97)
```

Here's a screenshot of the debug I tried, but I'm clueless to what should be the right values, maybe you guys can look at it and let me know if you need more info, I have no problem reproducing it.
![image](https://user-images.githubusercontent.com/3269297/42184491-68294748-7e4e-11e8-8ac5-24e95c112399.png)

I can probably also upload a beta site with the source maps if you'd like to debug it yourself.
The layers are extremely valuable to my users but I can't have my site crashing on a third party plug-in...

**Comment by jgravois** [comment]
that logic is buried in [`leaflet-virtual-grid`](https://github.com/patrickarlt/leaflet-virtual-grid/blob/master/src/virtual-grid.js#L294-L302).

my best guess is that `map.getPixelWorldBounds();` is returning `null` in your own app intermittently. so perhaps a more defensive check (returning `false` immediately if cellNumBounds is undefined?) would be appropriate.

**Comment by HarelM** [comment]
Thanks for the extremely fast response!
I can check what this function returns just before I call fitbounds to see if I get `null` too, never the less, it seems like `_getCellNumBounds` can return `null` according to the code you linked to, so I think `_isValidCell` should check for `null` as well.
Any chance to get a pre-release version with this fix? I'm using webpack so I kinda need an updated npm package if possible...
Thanks again!

**Comment by HarelM** [comment]
Might be that the at the time that get `getPixelWorldBounds()` is called to initialize the class member the value is `null`. When I call it just before calling `fitBounds` it returns a valid value:
```Bounds {min: Point, max: Point}max: Point {x: 65536, y: 65536}min: Point {x: 3.637978807091713e-12, y: 3.637978807091713e-12}__proto__: Object```
Let me know if there's anything I can do to help.

**Comment by jgravois** [comment]
can you dig into the raw source of `leaflet-vector-grid` locally and add the check i described prior to compiling with webpack?

i'm wary of patching and releasing something without confirming manually that the change does indeed lead to acceptable behavior.

**Comment by HarelM** [comment]
I can confirm the following code seems to solve the issue:
```js
_isValidCell: function (coords) {
    var crs = this._map.options.crs;

    if (!crs.infinite) {
      // don't load cell if it's out of bounds and not wrapped
      var cellNumBounds = this._cellNumBounds;
      if (!cellNumBounds) { // you can probably check for null or undefined.
           return false;
      }
      if (
        (!crs.wrapLng && (coords.x < cellNumBounds.min.x || coords.x > cellNumBounds.max.x)) ||
        (!crs.wrapLat && (coords.y < cellNumBounds.min.y || coords.y > cellNumBounds.max.y))
      ) {
        return false;
      }
    }
```

**Comment by jgravois** [comment]
glad to hear it.

a pull request to `leaflet-virtual-grid` would be _sincerely_ appreciated, otherwise i'll get to it myself as soon as i am able.

**Comment by HarelM** [comment]
I'll see what I can do, I'm facing another issue now with setStyle... :-/ seems like this library doesn't like me... I'll open another issue if I can reproduce...

**Comment by jgravois** [comment]
released as leaflet-virtual-grid [`v1.0.7`](https://unpkg.com/leaflet-virtual-grid@1.0.7/dist/virtual-grid.js). thanks for your help trapping the error.

**Comment by HarelM** [comment]
Thanks a lot for a super quick fix, keep up the good work!

**Comment by HarelM** [comment]
I'm not sure I understand how to use this package, I'm currently only referencing `esri-leaflet`...

**Comment by jgravois** [comment]
i'll cut a release of esri-leaflet (that bundles the latest release of `leaflet-virtual-grid`) in the next couple days.

**Comment by Braedennz** [comment]
This issue still persists, is there a solution for this error?

**Comment by vladimirbuskin** [comment]
If somebody still needs it.
I've fixed it this way for myself outside without pull request, i can make a pull request though if needed.

This is content of fixEsriLeaflet.js
just create the file and import it after your "esri-leaflet" import.

```JS
import * as esri from "esri-leaflet";

// FIX FeatureGrid._isValidCell
var _isValidCellOriginal = esri.FeatureManager.prototype._isValidCell;
esri.FeatureManager.prototype._isValidCell = function (coords) {
  if (this._globalCellRange == null) {
    return false;
  }
  return _isValidCellOriginal.call(this, coords);
}
```

**Comment by gavinr** [comment]
@vladimirbuskin thanks for the code. Are you able to provide an example use case that causes the error? Creating a new issue with that as well as a PR would be appreciated! Thanks!
