### ISSUE TITLE
errors with 2.2.0 and webpack because node_modules/esri-leaflet/src/Layers is missing

### ISSUE THREAD

**Issue by ajrothwell** [Esri/esri-leaflet#1109]
* Browser and version:
any

* Version of Leaflet (`L.version`):
1.3.1

* Version of esri Leaflet (`L.esri.VERSION`):
2.2.1 `master`?

Steps to reproduce the error:
add esri-leaflet to package.json and build with webpack

What happens is [X].
I can't build the project any more.  The errors say it is because "node_modules/esri-leaflet/src/Layers" can't be found.  If you go to https://unpkg.com/esri-leaflet@2.2.0/src/, you can see there is no Layers folder anymore.

I was expecting [Y].
The project to build as it has been building for months.  It still works if I force it to build with esri-leaflet 2.1.4

* Optional: I'm *not* using the [CDN](http://www.jsdelivr.com/projects/leaflet.esri), I'm loading/bundling the library using:
webpack

**Comment by jgravois** [comment]
ugh. this is is a bug i introduced in https://github.com/Esri/esri-leaflet/commit/cae13d321b315097d36efb0594ff0be19fc294bf

```
"src/**/*.js"
```

thanks for reporting. i'll patch and release shortly.

**Comment by ajrothwell** [comment]
Cool, glad I could be of help

**Comment by jgravois** [comment]
i've released [`v2.2.1`](https://github.com/Esri/esri-leaflet/releases/tag/v2.2.1) with the fix. sorry for the inconvenience.
