### ISSUE TITLE
Return "measure" values in identify - request for better task configuration

### ISSUE THREAD

**Issue by rustygreen** [Esri/esri-leaflet#1112]
When using the "DymamicMapLayer" I have a need to return measure values with the geometry (returnM=true when doing an identify). I imagine other people may want to return "z values" as well. There are many possible configurations (which we obviously don't want to hard-code). Can better task/parameter configuration be built into the library?

The default parameters for all tasks should be able to be extended by the consumer. For example:

```javascript
L.esri.dynamicMapLayer({
      url: serviceUrl,
      identifyParams: { returnM:true }, // Let users override default Identify params.
      queryParams: {...}
      etc...
    })
```

These options could be easily passed in here:
https://github.com/Esri/esri-leaflet/blob/master/src/Layers/DynamicMapLayer.js#L75

Or at a global level:
```javascript
L.esri.options({
      identifyParams: { returnM:true }
    })
```

**Comment by jgravois** [comment]
the extensibility you're asking for is already available via DynamicMapLayer's [`popup`](http://esri.github.io/esri-leaflet/api-reference/layers/dynamic-map-layer.html#options) constructor option (ref: https://github.com/Esri/esri-leaflet/issues/633).

one catch is that IdentifyTask currently doesn't have a `returnM` utility method. a PR for that would be welcome, but you can also already include the parameter manually (relevant: https://github.com/Esri/esri-leaflet/issues/1001).

```js
const url = "http://sampleserver6.arcgisonline.com/arcgis/rest/services/Census/MapServer"

var customBehavior = L.esri.identifyFeatures({ url })
  .layers("all:3")
customBehavior.params.returnM = true

var dynamicLayer = L.esri.dynamicMapLayer({
  url,
  // identifyFeatures
  popup: customBehavior
}).addTo(map)

dynamicLayer.bindPopup(/* ... */)

```
![identify returnM](https://user-images.githubusercontent.com/3011734/42828251-223fa3a8-899d-11e8-9c6c-a07e4a04c781.png)

**Comment by rustygreen** [comment]
Very good. Thanks, @jgravois!
