### ISSUE TITLE
How can I show the default icon from arcGIS service ????

### ISSUE THREAD

**Issue by emazzu** [Esri/esri-leaflet#1117]
* Browser and version:

ie: Chrome Version 67.0.3396.99 (Official Build) (64-bit)

* Version of Leaflet (`L.version`):
https://unpkg.com/leaflet@1.3.3/dist/leaflet.js

* Version of esri Leaflet (`L.esri.VERSION`):

https://unpkg.com/esri-leaflet@2.2.1/dist/esri-leaflet.js

Steps to reproduce the error:

What happens is [X].

I call to this service, it works very good, but doen't show me, the service icons  ????
http://nahwgis01/ArcGIS/rest/services/SINOPECGIS/AH_InstalacionesPozos_GSJ/MapServer/35

How can I show the default icon from arcGIS service ????

(if possible, create a [jsbin](http://jsbin.com/dagilag/edit?html,output) that demonstrates the problem)

* Optional: I'm *not* using the [CDN](http://www.jsdelivr.com/projects/leaflet.esri), I'm loading/bundling the library using:

[webpack](https://webpack.github.io/), [browserify](http://browserify.org/), [RequireJS](http://requirejs.org/)?

**Comment by jgravois** [comment]
please see https://github.com/Esri/esri-leaflet/issues/1074
