### ISSUE TITLE
Not proxying "exportImage" calls when using the "ImageMapLayer"

### ISSUE THREAD

**Issue by dangowans** [Esri/esri-leaflet#1120]
I'm successfully using the "proxy" option to load feature layers from my restrictive intranet.  It appears that the "proxy" option should work the same on image map layers, but I'm seeing the "exportImage" requests not going through the proxy.

Firefox 61
Leaflet 1.3.3
ESRI Leaflet 2.2.2

**Comment by jgravois** [comment]
proposed fix in #1121. thx @dangowans!

**Comment by jgravois** [comment]
released as [`v2.2.3`](https://github.com/Esri/esri-leaflet/releases/tag/v2.2.3). thanks for the fix :tada:
