### ISSUE TITLE
L.esri.imageMapLayer documentation example points to a broken resource

### ISSUE THREAD

**Issue by cgalvarino** [Esri/esri-leaflet#1128]
* Browser and version:

Chrome 69

* Version of Leaflet (`L.version`):

1.3.4

* Version of esri Leaflet (`L.esri.VERSION`):

2.2.3

Steps to reproduce the error:

Running the Simple Image Layer sample, https://esri.github.io/esri-leaflet/api-reference/layers/image-map-layer.html#simple-image-layer, does not render since it runs into CORS errors.

I know this is not an esri-leaflet bug, but perhaps the documentation should point to an error-free resource.

![image](https://user-images.githubusercontent.com/180985/47386668-362e8380-d6db-11e8-99d0-c33b3460d8e9.png)

**Comment by jgravois** [comment]
good catch. a PR to [esri-leaflet-doc](https://github.com/Esri/esri-leaflet-doc/blob/master/src/pages/api-reference/layers/image-map-layer.md#simple-image-layer) with the update below would be _most_ welcome.

```js
L.esri.imageMapLayer({
  url: url,
  opacity : 0.25,
  // only necessary for old versions of ArcGIS Server
  useCors: false
}).addTo(map);
```

**Comment by cgalvarino** [comment]
Closing by way of https://github.com/Esri/esri-leaflet-doc/pull/200.

**Comment by cgalvarino** [comment]
Thx, @jgravois !
