### ISSUE TITLE
esri-leaflet in vue，[Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'dynamicMapLayer' of undefined"

### ISSUE THREAD

**Issue by defineconst** [Esri/esri-leaflet#1136]
1、npm install esri-leaflet --save
2、require("esri-leaflet");
3、add layer to map,
      var envLayer = L.esri.dynamicMapLayer({
        url: url,
        opacity: opacity
      });
      envLayer.addTo(this.map);
4、but
[Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'dynamicMapLayer' of undefined"

found in

how to use it in vue ？

thank you very much！

**Comment by jgravois** [comment]
see #994, #1003

**Comment by defineconst** [comment]
var L = require('leaflet');
var esri = require('esri-leaflet');

esri.basemapLayer('Topographic').addTo(map);

3q!


> see #994, #1003

var L = require('leaflet');
var esri = require('esri-leaflet');

esri.basemapLayer('Topographic').addTo(map);

3q!

**Comment by jgravois** [comment]
this isn't the best place to get assistance mashing up multiple leaflet plugins using your JS framework of choice.

if you think you've encountered an esri leaflet bug, please open a new issue and include a reproducible test case with only the bare minimum code to demonstrate the error.

https://github.com/Esri/esri-leaflet#issues
