### ISSUE TITLE
Can't load feature layer in Edge 42.17134.1.0

### ISSUE THREAD

**Issue by kxwang** [Esri/esri-leaflet#1137]
* Browser and version:

Edge 42.17134.1.0

Works on Chrome, FireFox, IE 11.

* Version of Leaflet (`L.version`):

1.4.0

* Version of esri Leaflet (`L.esri.VERSION`):

2.2.3

Steps to reproduce the error:

L.esri.featureLayer({
  url: 'https://www.portlandmaps.com/arcgis/rest/services/Public/Utilities_Water/MapServer/6/'
}).addTo(map);

What happens is no layer is loaded.

I was expecting the polygon layer to be loaded.

* Optional: I'm *not* using the CDN. I'm loading both leaflet and esri-leaflet from my local copy.

**Comment by jgravois** [comment]
![screenshot 2019-01-28 16 50 47](https://user-images.githubusercontent.com/3011734/51876266-df10fe00-231c-11e9-8753-8cbcdf17793d.png)

you'll have to tell esri-leaflet that the ArcGIS Server doesn't support [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS).

```js
L.esri.featureLayer({
  url: "https://portlandmaps.com/arcgis/rest/services/Public/Utilities_Water/MapServer/6",
  useCors: false,
}).addTo(map);
```
http://esri.github.io/esri-leaflet/api-reference/layers/feature-layer.html#options
