### ISSUE TITLE
how to change the map city name to chinese

### ISSUE THREAD

**Issue by kt7456** [Esri/esri-leaflet#1139]
* Browser and version:

ie: Chrome 51, IE11

* Version of Leaflet (`L.version`):

0.7.7, 1.0.0?

* Version of esri Leaflet (`L.esri.VERSION`):

1.0.4, 2.0.3, `master`?

Steps to reproduce the error:

1. first do this
2. then do this

What happens is [X].

I was expecting [Y].

(if possible, create a [jsbin](http://jsbin.com/dagilag/edit?html,output) that demonstrates the problem)

* Optional: I'm *not* using the [CDN](http://www.jsdelivr.com/projects/leaflet.esri), I'm loading/bundling the library using:

[webpack](https://webpack.github.io/), [browserify](http://browserify.org/), [RequireJS](http://requirejs.org/)?

**Comment by pmacMaps** [comment]
There are vector basemaps that support local language (see https://www.arcgis.com/home/group.html?id=30de8da907d240a0bccd5ad3ff25ef4a#overview).

They haven't been incorporated into the esri leaflet vector (https://github.com/Esri/esri-leaflet-vector) plugin yet. But a simple PR could add them in.

**Comment by jgravois** [comment]
@pmacMaps is right.

demo app: https://jsbin.com/qugoyos/edit?html,output

**Comment by kt7456** [comment]
thanks ,but i want the GrayLabels to support the chinese .

**Comment by pmacMaps** [comment]
@kt7456, use the code sample above, but put in "3ffec1551cd14606a286622c634b0bb4" as the value to get Light Gray Canvas local language.

**Comment by jgravois** [comment]
the problem with the gray local language vector labels is that you can only draw one vector tileset at a time and the labels are separate from the rest of the basemap.

**Comment by pmacMaps** [comment]
I did a quick check, and it looks like it may be possible to use the vector labels layer, and a standard "raster" basemap together.
