### ISSUE TITLE
unable to render vector tile layers published privately to ArcGIS Online

### ISSUE THREAD

**Issue by gduvall** [Esri/esri-leaflet#1140]
* Browser and version: Chome 71.0.3578.98
* Version of Leaflet 1.4.0
* Version of esri Leaflet 2.2.3

Steps to reproduce the error:

1. Generated access token for web application
2. Published vector tile layer to ArcGIS Online via ArcGIS Pro and made available to organization and group
3. Attempted to access the vector tile layer in esri-leaflet with ```L.esri.tiledMapLayer()``` passing in URL and token

What happens is 404 errors and the token is only appended to the URL via query parameter ```token```.

I was expecting for the tile layer to render. Using an IdentityManager in Esri JavaScript API, I can get the Tile Layers to render, so I thought it would be possible in esri-leaflet as well. We are looking at esri-leaflet as an option for older browser support.

* Optional: I'm *not* using the [CDN](http://www.jsdelivr.com/projects/leaflet.esri), I'm loading/bundling the library using: ```yarn add esri-leaflet```

**Comment by jgravois** [comment]
> We are looking at esri-leaflet as an option for older browser support

leaflet _or_ JSAPI, drawing vector tiles requires a modern browser that supports WebGL.

> Attempted to access the vector tile layer in esri-leaflet with `L.esri.tiledMapLayer()`

[`tiledMapLayer`](http://esri.github.io/esri-leaflet/api-reference/layers/tiled-map-layer.html) rather is used to display _raster_ tiles published to ArcGIS Online or Enterprise.

`esri-leaflet-vector` is another plugin that extends this library, but i have no idea how it'd do with secure services and its not recommended for production apps anyway.

https://github.com/esri/esri-leaflet-vector#disclaimer

**Comment by gduvall** [comment]
Thanks @jgravois for your response. 

I also cannot get a raster tile layer with an access token to work. Does esri-leaflet support ArcGIS Online resources that need authentication with access tokens?

**Comment by jgravois** [comment]
> Does esri-leaflet support ArcGIS Online resources that need authentication with access tokens?

absolutely.

http://esri.github.io/esri-leaflet/examples/premium-content.html

**Comment by gduvall** [comment]
I have generated an access token as seen here: https://developers.arcgis.com/labs/rest/get-an-access-token/

The workflow provided in your example above does not work when I provide the access token. Are there more steps that I need to provide? 

Also, L.esri.service is not available in your types file, as well as a type for authenticating for event "authenticationrequired".

**Comment by jgravois** [comment]
i don't maintain the types for this JavaScript library, but they _definitely_ include `L.esri.Service`.

(groannnn :wink:)

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f94196eafeb06fbe05ff3f22c514b5a9f89f374a/types/esri-leaflet/index.d.ts#L625-L644

**Comment by gduvall** [comment]
Ah ok. Well, I guess the L.esri.service() method is missing. (Lowercase versus capital class name)

Any advice for the first question? 
> I have generated an access token as seen here: https://developers.arcgis.com/labs/rest/get-an-access-token/

> The workflow provided in your example above does not work when I provide the access token. Are there more steps that I need to provide?

**Comment by jgravois** [comment]
> Any advice for the first question?

yes. try hardcoding user credentials for your prototype instead of app credentials.

> Tokens obtained by applications can only read public content and services.

https://developers.arcgis.com/documentation/core-concepts/security-and-authentication/limitations-of-application-authentication/

**Comment by jgravois** [comment]
did you ever sort yourself out @gduvall?

**Comment by gduvall** [comment]
Yes, thanks @jgravois 

This article helped with publishing settings: https://community.esri.com/thread/87142

Now, trying again to add vector tile layers using other plugins. Having trouble with labels, but I do not believe that is in the scope of this repo 😉 thanks again.
