### ISSUE TITLE
dynamicMapLayer click event  propagation 

### ISSUE THREAD

**Issue by hlj184** [Esri/esri-leaflet#1141]
* Browser and version:

Chrome 72.0.3626.119

* Version of Leaflet (`L.version`):

1.4.0

* Version of esri Leaflet (`L.esri.VERSION`):

2.2.3

When more than two dynamicMaplayer overap，then click the top one，the popup content actually is from the bottom layer. I think it's due to mouse click event propagation.
I respect to you can confirm this issue,thank you!

**Comment by jgravois** [comment]
i can't reproduce the behavior you describe.

https://jsbin.com/bijobom/edit?html,output

can you provide more information to clarify exactly what you mean?

**Comment by hlj184** [comment]
i edit your code as below:
***********************************************
    const one = L.esri.dynamicMapLayer({
      url:'https://sampleserver6.arcgisonline.com/arcgis/rest/services/Census/MapServer',
      pane: 'one'
    }).addTo(map);
	
	one.bindPopup(() => {
      return 'bottom layer'
    })

    const two = L.esri.dynamicMapLayer({
      url:'https://sampleserver6.arcgisonline.com/arcgis/rest/services/WorldTimeZones/MapServer',
      pane: 'two'
    }).addTo(map);
  
    two.bindPopup(() => {
      return 'top layer'
    })
*********************************************************************
then i have two questions:
1、when mouse click the US inland  as chicago nearby,it seems normal, while click Polynesia islands,which locat in the west of  the US,it's unnormal；
2、when i click the blank area,where the layers are not cover,the popup alsow open.

thank your reply very much.

**Comment by jgravois** [comment]
its up to you to inspect the results that are passed back and `return false` if you don't want to display a popup.

live example: https://esri.github.io/esri-leaflet/examples/customizing-popups.html
