### ISSUE TITLE
append license text from projects we reproduce code from

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet#1144]
right now we 🎩tip projects we pilfered code from in the README, but we should 
_really_ include them in our LICENSE file.

```md
------------------------------------------------------------------------------

Contains code from arcgis-level-fixer

The MIT License (MIT)

Copyright (c) 2014 Geographic Information Services, Inc.

Permission is hereby granted, free of charge...

------------------------------------------------------------------------------

Contains code from leaflet-ags

...
```
* https://github.com/gisinc/arcgis-level-fixer/blob/master/LICENSE
* https://github.com/sanborn/leaflet-ags/blob/master/LICENSE

**Comment by pmacMaps** [comment]
This is something I could probably do. I just need a little guidance.  What all information from these other lib's license text goes into this repo's license?

And is it just the two listed in the [Credit Section](https://github.com/Esri/esri-leaflet#credit) of the README? Or other projects as well?

**Comment by jgravois** [comment]
thank you @pmacMaps!

What all information from these other lib's license text goes into this repo's license?

all of it!

check out this (good) example from the JSAPI: https://github.com/Esri/arcgis-js-api/blob/master/copyright.txt

> is it just the two listed in the Credit Section of the README? 

yup!
