### ISSUE TITLE
Missing event before export request in dynamicMapLayer

### ISSUE THREAD

**Issue by ogix** [Esri/esri-leaflet#1146]
Now when using dynamicMapLayer, 'loading' event fires only after export request which sometimes takes quite long. So it is not possible to show a loader before export request happens.
It would be very useful to fire 'loading' event (or introduce another event) before export request.

**Comment by jgravois** [comment]
this event was added in https://github.com/Esri/esri-leaflet/pull/148

> 'loading' event fires only _after_ export request

i agree that it'd be more helpful if 'loading' fired immediately _before_ `/export` is called. would you be willing to contribute a pull request of your own?

**Comment by ogix** [comment]
I made a PR. Please have a look.
