### ISSUE TITLE
How to securely authenticate with Arcgis Server using username && password 

### ISSUE THREAD

**Issue by Djohn12** [Esri/esri-leaflet#1150]
* Version of Leaflet (`L.version`):

1.4.0

* Version of esri Leaflet (`L.esri.VERSION`):

2.2.3

Hi,
I'm using [this tutorial from the doc](https://esri.github.io/esri-leaflet/examples/arcgis-server-auth.html) to authenticate to an ArcGIS server and then retrieve a DynamicMapLayer.
The tutorial shows how to authenticate by hardcoding the credentials in the application.

I'm using one of my company's account and I'd like to secure it so no user of the web application can get them and use them without our knowledge nor our consent for another purpose.
We still want to login to this service using our own account though and not force users to create a personnal ArcGIS account.

Does esri-leaflet offer a way to authenticate to an ArGIS service on the server side of the application ?
This would avoid lots of complications trying to hide the credentials on the client-side...

Thank you

**Comment by jgravois** [comment]
> Does esri-leaflet offer a way to authenticate to an ArcGIS service on the server side of the application?

nope. there is nothing built in to esri-leaflet to help with something like that.

**Comment by Djohn12** [comment]
Ok.
Is there a way I could protect the credentials used to authenticate so we could still allow our users to access the data through the web app but without letting them access those credentials ?

I can't imagine I'm the first one looking for such a feature. This would be very useful for securely showing stuff to non-ArcGIS people.

**Comment by pmacMaps** [comment]
@Djohn12, have you checked out the [tutorial](https://esri.github.io/esri-leaflet/tutorials/working-with-authenticated-services-server.html) on using a form to add a secured service to a map?

You could use the users/roles capabilities of ArcGIS Server to create username/password that enables access to the map service.  The users could submit a form to authenticate and then add the service to the map.

**Comment by jgravois** [comment]
@pmacMaps from the sound of it @Djohn12 wants to display secure services _without_ asking users to login. 

@Djohn12 if i've got that right, you most certainly are _not_ the first person to have asked such a question. INAL, but it sounds like a violation of the [Esri Master Agreement](https://www.esri.com/en-us/legal/terms/full-master-agreement):

> 2.5 Named User Licenses

> a. Named Users
> 1. Named User login credentials are for designated users only and may not be shared with other individuals.
> 2. Customer may reassign a Named User License to another user if the former user no longer requires access to the Software or Online Services.

> b. Value-Added Applications

> 2. Customer may not embed a Named User Credential into Value-Added Applications. Value-Added Applications that enable access to Customer's private data or content must require individual users to log in to the application(s) with their unique Named User login credentials.

this does _not_ mean that folks must sign in each and every time they view private content in your own application. Whether you use a built-in identity store or a SAML provider, there are techniques you can use to persist a user's login.

**Comment by Djohn12** [comment]
About the Esri Master Agreement : I got in touch with the person in charge at my company. The MapService we use from Esri is public (the concerned data originally comes from the NOAA) so we can share it without infringing any terms of use if we give it for free.

About securing the credentials inside the web app : I think we will instead get the data directly from [this api](https://hub.arcgis.com/datasets/GEMA-SOC::current-wind-conditions/geoservice?geometry=-188.534%2C19.307%2C90.607%2C62.753) which is free of use and doesn't require any token or authentication process.

Thanks for your help
