### ISSUE TITLE
TypeError: Cannot read property 'basemapLayer' of undefined

### ISSUE THREAD

**Issue by marnenivishal** [Esri/esri-leaflet#1151]
Team,

I'm having an issue with the esri-leaflet please find the error below 

TypeError: Cannot read property 'basemapLayer' of undefined
    at t.value (http://dmoain.com/index.js?MTU1ODA0NjU1NTg1MA==:1:1458715)
    at t.value (http://dmoain.com/index.js?MTU1ODA0NjU1NTg1MA==:1:1458348)
    at Ma (http://dmoain.com/index.js?MTU1ODA0NjU1NTg1MA==:1:643944)
    at ya (http://dmoain.com/index.js?MTU1ODA0NjU1NTg1MA==:1:639768)
    at _a (http://dmoain.com/index.js?MTU1ODA0NjU1NTg1MA==:1:639113)
    at fa (http://dmoain.com/index.js?MTU1ODA0NjU1NTg1MA==:1:638142)
    at ia (http://dmoain.com/index.js?MTU1ODA0NjU1NTg1MA==:1:637201)
    at Object.enqueueSetState (http://dmoain.com/index.js?MTU1ODA0NjU1NTg1MA==:1:667519)
    at t.i.setState (http://dmoain.com/index.js?MTU1ODA0NjU1NTg1MA==:1:572733)
    at t.value (http://dmoain.com/index.js?MTU1ODA0NjU1NTg1MA==:1:1118128)

**Comment by jgravois** [comment]
`L.esri` is undefined. you should check out these:

https://github.com/Esri/esri-leaflet/issues/994
https://github.com/Esri/esri-leaflet/issues/1003
https://github.com/Esri/esri-leaflet/issues/1136

**Comment by marnenivishal** [comment]
> `L.esri` is undefined. you should check out these:
> 
> #994
> #1003
> #1136

I have used named export like the below

import React, { Component } from 'react';
import PropTypes from 'prop-types';
import Leaflet from './leaflet/leaflet.js';
import * as esri from 'esri-leaflet';

**Comment by jgravois** [comment]
are you calling `esri.basemapLayer()`?

if so, a reproducible test case with only enough code to demonstrate the error would be _really_ helpful.

**Comment by marnenivishal** [comment]
> are you calling `esri.basemapLayer()`?
> 
> if so, a reproducible test case with only enough code to demonstrate the error would be _really_ helpful.

`import React, { Component } from 'react';
import PropTypes from 'prop-types';
import Leaflet from './leaflet/leaflet.js';
import EsriLeaflet from 'esri-leaflet';

import './leaflet/leaflet.css';

export default class BaseMapLayer extends Component {
    componentDidMount() {
        this._updateLayer()
    }
    
    componentDidUpdate(prevProps) {
        if(prevProps.type !== this.props.type) {
            if(this.state.basemapLayer) {
                this.state.basemapLayer.removeFrom(this.context.map)
                this._updateLayer()
            }
        }
    }

    componentWillUnmount() {
        if (this.state.basemapLayer) {
            this.state.basemapLayer.removeFrom(this.context.map);
        }
    }

    _updateLayer() {
        const basemapLayer = EsriLeaflet.basemapLayer(this.props.type).addTo(this.context.map);
        this.setState({ basemapLayer })
    }

    render() {
        return null;
    }
};

BaseMapLayer.contextTypes = {
    map: PropTypes.object
};

BaseMapLayer.propTypes = {
    type: PropTypes.string
};

BaseMapLayer.defaultProps = {
    type: 'Streets'
};
`

this is how exactly we are doing

**Comment by jgravois** [comment]
I'm not inclined to take time to stand up a simple react application of my own and attempt to integrate your code to try and reproduce the problem you're reporting. 

since this isn't a bug report, I'd suggest you try StackOverflow. you're not likely to get more help here unless you take the time to provide a ready to run demo of your own.

**Comment by marnenivishal** [comment]
the problem is I haven't updated anything it was working fine suddenly this issue came up is there any issues with named export in the version which I'm using

**Comment by marnenivishal** [comment]
Hey, I found the solution it's because of named import statement when i changed it to require it seems to be working fine which is weird. It was working fine with named imports till date from the last 2 years. There is some issue `import React, { Component } from 'react';
import PropTypes from 'prop-types';
//import EsriLeaflet from 'esri-leaflet';

import './leaflet/leaflet.css';
const EsriLeaflet = require('esri-leaflet');
const Leaflet = require('./leaflet/leaflet.js');

export default class BaseMapLayer extends Component {
    componentDidMount() {
        this._updateLayer()
    }
    
    componentDidUpdate(prevProps) {
        if(prevProps.type !== this.props.type) {
            if(this.state.basemapLayer) {
                this.state.basemapLayer.removeFrom(this.context.map)
                this._updateLayer()
            }
        }
    }

    componentWillUnmount() {
        if (this.state.basemapLayer) {
            this.state.basemapLayer.removeFrom(this.context.map);
        }
    }

    _updateLayer() {
        const basemapLayer = EsriLeaflet.basemapLayer(this.props.type).addTo(this.context.map);
        this.setState({ basemapLayer })
    }

    render() {
        return null;
    }
};

BaseMapLayer.contextTypes = {
    map: PropTypes.object
};

BaseMapLayer.propTypes = {
    type: PropTypes.string
};

BaseMapLayer.defaultProps = {
    type: 'Streets'
};
`

**Comment by jgravois** [comment]
> There is some issue

there most certainly is, but i couldn't tell you exactly what. the article [here](https://stackoverflow.com/questions/38500397/i-cant-get-esri-leaflet-to-work-with-reactjs-basemaplayer-of-undefined) indicates that it was sufficient to `require` `1.0.0-rc.1` and `import` esri-leaflet.

now that Leaflet itself is written with ES Modules, i'd expect either to work (as long as webpack and babel are properly configured).
