### ISSUE TITLE
fitbounds returns null

### ISSUE THREAD

**Issue by mapsgeek** [Esri/esri-leaflet#1155]
* Browser and version:
Version 75.0.3770.100 (Official Build) (64-bit)

* Version of Leaflet (`L.version`):
1.5
* Version of esri Leaflet (`L.esri.VERSION`):
2.2.4

Steps to reproduce the error:

1. as in example here in the docs
https://esri.github.io/esri-leaflet/examples/zooming-to-all-features-1.html

2. i use koopjs to serve a featureServer from geojson data, the endpoints works just fine as you expect it to be on ArcGIS online
example here:
http://mapsgeek.maps.arcgis.com/home/webmap/viewer.html?webmap=da1d36c8661d476fbd68718d74788168

but on esri-leaflet, the layer renders but there is a problem with the fitbounds function returns null for the `latlngbounds`
after some digging we found that in the docs example leaflet makes a request for querying features ending with `?f=geojson`
however with our endpoint leaflet always makes the request with
ending with `?f=json`, however if you manually hit the query route with `?f=geojson` our endpoint will respond just fine

but the library will always just make the request in the `?f=json` format which i believe is what causing the issue for the library to not be able to get bounds.

here's a reproducing example, please copy to you local file system as the server will give mixed content error when trying to server the layer.

https://jsbin.com/sohojutini/edit?html,output

**Comment by gavinr** [comment]
Hi! I think as a workaround you can add `isModern` property to your `featureLayer` and it [should use the geojson param](https://github.com/Esri/esri-leaflet/blob/master/src/Tasks/Query.js#L129).

```
var trees = L.esri.featureLayer({
  url: 'https://koopserver.herokuapp.com/file-geojson/rest/services/country/FeatureServer/0',
  isModern: true
}).addTo(map);
```

**Comment by mapsgeek** [comment]
thank you, yes i wasn't aware of that option and it actually do make fetch with geojson endpoint, but the guys at koopjs identified the cause of the issue which is the lack of `returnExtentOnly` support, the geojson part was our first suspect.
