### ISSUE TITLE
Time filtering for FeatureLayer does not persist when zooming or panning map

### ISSUE THREAD

**Issue by pjbiogit** [Esri/esri-leaflet#1156]
* Browser and version: Chrome Version 75.0.3770.100

* Version of Leaflet (`L.version`): 1.3.4

* Version of esri Leaflet (`L.esri.VERSION`): 2.0.8

Description:

I am creating a time-based layerGroup with several feature layers from https://wildfire.cr.usgs.gov/arcgis/rest/services/geomac_dyn/MapServer. Whenever the date range is updated by the user I want to only show features within that time range based on datetime properties of the features themselves. Upon adding the layer and changing date ranges the features loaded properly, but when zooming or panning on the map, all features in a given feature layer would then be added to the map. The images below show what the view looked like before and after zooming. 
I found in my testing that the `createLayers` function did not check to see if the feature was within the set time range. By slightly altering the code to match the if statement later in the same function I was able to get the layers to function as I wanted. 

![wildfireLayerPreZoom](https://user-images.githubusercontent.com/52584128/60812192-f1f6ec80-a15e-11e9-90b4-9e6dd176427e.PNG)
![wildfireLayerPostZoom](https://user-images.githubusercontent.com/52584128/60812227-03d88f80-a15f-11e9-903f-261f4282ed48.PNG)

![image](https://user-images.githubusercontent.com/52584128/60827594-90df1100-a17e-11e9-87b9-65d135241797.png)

**Comment by pjbiogit** [comment]
I hadn't realized before, but I also added the same code into the if statement of the `addLayers` function of the Feature Management Methods to get the featureLayers to function properly. Basically just adding a check for the time range before any feature is added to the map.

**Comment by jgravois** [comment]
do you think you could open a pull request with your suggested fix?

**Comment by gavinr** [comment]
addressed in #1157
