### ISSUE TITLE
CORB issue with tiled layers from ArcGIS Online

### ISSUE THREAD

**Issue by ajrothwell** [Esri/esri-leaflet#1161]
* Browser and version:

Chrome 75, FireFox 68

* Version of Leaflet (`L.version`):

1.5.1

* Version of esri Leaflet (`L.esri.VERSION`):

2.2.4

Steps to reproduce the error:

1. create an L.esri.tiledMapLayer and for the url parameter, pass a tiled map layer using http - ex: http://tiles.arcgis.com/tiles/fLeGjb7u4uXqeF9q/arcgis/rest/services/CityImagery_2016_3in/MapServer 

What happens is:
The console shows the message:
Cross-Origin Read Blocking (CORB) blocked cross-origin response http://tiles.arcgis.com/tiles/fLeGjb7u4uXqeF9q/arcgis/rest/services/CityImagery_2016_3in/MapServer/tile/12/1551/1193 with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.

The map does not show up.

I was expecting:
The map to work, as it did just the other day

* Optional: I'm *not* using the [CDN](http://www.jsdelivr.com/projects/leaflet.esri), I'm loading/bundling the library using:

[webpack](https://webpack.github.io/) and Vue

I can't tell if it has something to do with this: https://www.chromestatus.com/feature/5629709824032768

**Comment by gavinr** [comment]
@ajrothwell does it work for you if you use the CDN version?

**Comment by ajrothwell** [comment]
@gavinr I just copied the basic EsriLeaflet example file and put in our imagery and it only works when you put in the service as https

<html>
<head>
  <meta charset=utf-8 />
  <title>Esri Leaflet Quickstart</title>
  <meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />

    
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.5.1/dist/leaflet.css"
    integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
    crossorigin=""/>
    <script src="https://unpkg.com/leaflet@1.5.1/dist/leaflet.js"
    integrity="sha512-GffPMF3RvMeYyc1LWMHtK8EbPv0iNZ8/oTtHPx9/cc2ILxQ+u905qIwdpULaqDkyBKgOaB57QTMg7ztg8Jm2Og=="
    crossorigin=""></script>


    
    <script src="https://unpkg.com/esri-leaflet@2.2.4/dist/esri-leaflet.js"
    integrity="sha512-tyPum7h2h36X52O2gz+Pe8z/3l+Y9S1yEUscbVs5r5aEY5dFmP1WWRY/WLLElnFHa+k1JBQZSCDGwEAnm2IxAQ=="
    crossorigin=""></script>


  <style>
    body { margin:0; padding:0; }
    #map { position: absolute; top:0; bottom:0; right:0; left:0; }
  </style>
</head>
<body>

<div id="map"></div>

<script>
  var map = L.map("map").setView([39.953338, -75.163471], 16);

  L.esri.basemapLayer("Topographic").addTo(map);
  L.esri.tiledMapLayer({ url: 'https://tiles.arcgis.com/tiles/fLeGjb7u4uXqeF9q/arcgis/rest/services/CityImagery_2016_3in/MapServer' }).addTo(map);

</script>

</body>
</html>

I just talked to someone here at the City of Philadelphia, and found out that ESRI ArcGIS Online only lets you use https for accessing services now.  Not sure why our http site that was accessing this kind of imagery through http was working until today, but it is working again when I just tell the http site to get the service from https, so there's nothing down here now.  Maybe it really is not supposed to work the way it was working and this is better.

**Comment by gavinr** [comment]
So this was fixed when you switched to HTTPS? Sounds good. I'll close this issue then. Thanks!
