### ISSUE TITLE
esri-leaflet throws error when bundled with Rollup 

### ISSUE THREAD

**Issue by LancerSung** [Esri/esri-leaflet#1165]
- Browser and version:
n/a

- Version of Leaflet (L.version):
1.5.1

- Version of esri Leaflet (L.esri.VERSION):
2.3.0

- Version of Rollup:
1.21.2

- Steps to reproduce the error:

  1. yarn add esri-leaflet
  2. Write some code to import { tiledMapLayer } from 'esri-leaflet'
  3. rollup
- What happens is [X].
I get an error:
```
[!] (plugin buble) SyntaxError: Unexpected token (2:8)
node_modules/esri-leaflet/package.json (2:8)
1 : {
2 :   "name": "esri-leaflet",
            ^
SyntaxError: Unexpected token (2:8)
    at Object.pp$4.raise (/node_modules/acorn/dist/acorn.js:2825:15) was expecting [Y].
```

**Comment by gavinr** [comment]
Hi, have you tried the fixes mentioned in https://github.com/Esri/esri-leaflet/issues/1063?

**Comment by LancerSung** [comment]
> Hi, have you tried the fixes mentioned in #1063?

yes,but it make no sense and i have the different error

**Comment by gavinr** [comment]
I am trying to follow your replication steps, I do not get the error:

1. Create new directory
1. `npm install --global rollup` (this installs `v1.21.4`)
2. `npm init -y`
3. `npm install esri-leaflet`
4. create `main.js` with contents:
```
import { tiledMapLayer } from 'esri-leaflet';
```
5. `rollup main.js --format iife --name "myBundle" --file bundle.js`

Outputs:
```
main.js → bundle.js...
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
esri-leaflet (imported by main.js)
(!) Unused external imports
tiledMapLayer imported from external module 'esri-leaflet' but never used
(!) Missing global variable name
Use output.globals to specify browser global variable names corresponding to external modules
esri-leaflet (guessing 'esriLeaflet')
created bundle.js in 33ms
```

**Comment by jgravois** [comment]
sounds like the error is coming from `rollup-plugin-buble`.
@LancerSung you'll need to provide a little more information if you'd like assistance.

**Comment by LancerSung** [comment]
> sounds like the error is coming from `rollup-plugin-buble`.
> @LancerSung you'll need to provide a little more information if you'd like assistance.
Thank you for your prompt reply. i have a rollup config file 

```javascript
import node from 'rollup-plugin-node-resolve';
import cjs from 'rollup-plugin-commonjs';
import buble from 'rollup-plugin-buble';
import replace from 'rollup-plugin-replace';
import cleanup from 'rollup-plugin-cleanup';
export default [
  {
    input: 'src/index.js',
    output: [
      {
        format: 'cjs',
        file: 'dist/eye-map.cjs.js'
      }
    ],
    plugins: [
      replace({ 'process.env.NODE_ENV': 'production' }),
      node({
        jsnext: true,
        extensions: ['.js', '.json']
      }),
      cjs(),
      cleanup(),
      buble({
        objectAssign: true
      })
    ]
  },
  {
    input: 'src/index.js',
    output: {
      format: 'umd',
      name: 'EyeMap',
      file: 'dist/eye-map.min.js'
    },
    plugins: [
      replace({ 'process.env.NODE_ENV': 'production' }),
      node({
        extensions: ['.js', '.json']
      }),
      cjs(),
      cleanup(),
      buble({
        objectAssign: true
      })
    ]
  }
];

```

and my code use `esri-leaflet` :
```javascript
// map.js
import { map } from 'leaflet';
import { basemapLayer, featureLayer } from 'esri-leaflet';
const div = document.createElement('div');
document.body.appendChild(div);
const leafletMap = map(div).setView([37.837, -122.479], 8);

basemapLayer(Streets).addTo(leafletMap);
featureLayer({
  url:
    'https://sampleserver6.arcgisonline.com/arcgis/rest/services/Earthquakes_Since1970/MapServer/0'
}).addTo(map);
```
```javascript
// index.js
export { default as Map } from './map.js';
```
when i excute
```javascript
rollup -c --environment NODE_ENV:production
```
i got the error

**Comment by jgravois** [comment]
Esri-leaflet isn't a CommonJS library. it's written in ES6.

you may have other problems, but at a minimum, you need to tell `rollup-plugin-commonjs` about that (or omit the plugin entirely if you aren't actually trying to bundle any CJS dependencies).

```js
plugins: [
  cjs({ exclude: [ 'node_modules/esri-leaflet/**' ] }),
]
```

**Comment by LancerSung** [comment]
@jgravois OK !Thank you
