### ISSUE TITLE
Merge ArcGIS feature layer and display as one layer on client side

### ISSUE THREAD

**Issue by fnick851** [Esri/esri-leaflet#1169]
* Browser and version:

All supported browsers

* Version of Leaflet (`L.version`):

N/A

* Version of esri Leaflet (`L.esri.VERSION`):

N/A
Steps to reproduce the error:

N/A

What happens is [X].

N/A

I was expecting [Y].

I've read through the doc and couldn't find this... 
So does the library support merging several ArcGIS feature layer and display as one single layer on **client-side** on the fly?  
e.g. (a URL for a ArcGIS feature layer service would be) https://services6.arcgis.com/awdfawfwafawrawe/arcgis/rest/services/[project_name]/FeatureServer/1
So I can have several of these based on what the user toggles. (User could toggle to activate two layers or more) And I want to merge all the layers user selected, and display only one merged layer on the client side.

Or, what are the alternatives (don't have to be client-side) to achieve this - "merging several feature layer and display as one layer on the fly"?

Thanks.

**Comment by jwasilgeo** [comment]
Some alternative ideas:

1. Try to use the [Leaflet `L.LayerGroup`](https://leafletjs.com/reference-1.5.0.html#layergroup) to group your [`L.esri.FeatureLayer`](https://esri.github.io/esri-leaflet/api-reference/layers/feature-layer.html) instances.  Does this solve your use case?
2. If you have access to ArcGIS Enterprise MapServer layers instead (with "...MapServer/" at the end of the URL), you could use the [`L.esri.DynamicMapLayer`](https://esri.github.io/esri-leaflet/api-reference/layers/dynamic-map-layer.html) and set its `layers` property.

**Comment by fnick851** [comment]
@jwasilgeo  Thanks for the response. `L.LayerGroup` or `L.FeatureGroup` do not really merge the layers right? 

So when I do:
`
var layer2 = L.esri
    .featureLayer({
        url:        "https://services6.arcgis.com/dasda/arcgis/rest/services/dadsadas/FeatureServer/0"
    })
    .on("click", function(e) {
        console.log(e)
    })
    .addTo(map)

var layer1 = L.esri
    .featureLayer({
        url:         "https://services6.arcgis.com/adadasdasda/arcgis/rest/services/dadssadasd/FeatureServer/5"
    })
    .on("click", function(e) {
        console.log(e)
    })
    .addTo(map)
`

It is exactly the same as: 
`
var layer2 = L.esri
    .featureLayer({
        url:         "https://services6.arcgis.com/Wwv1InPxRQv6NCzu/arcgis/rest/services/WIOA_Participants_in_remedial_training/FeatureServer/0"
    })


var layer1 = L.esri
    .featureLayer({
        url:         "https://services6.arcgis.com/Wwv1InPxRQv6NCzu/arcgis/rest/services/ECMC_social_factors/FeatureServer/5"
    })
    

L.featureGroup([layer1, layer2])
    .on("click", function(e) {
        console.log(e)
    })
    .addTo(map)
`

The console.log is only printing out data for layer1, meaning the layer is still one on top on the other, and the click event is only fired on layer1 which was added later.

But I want one merged layer, so when I click, the data should contain all from both layers.

**Comment by jgravois** [comment]
@jwasilgeo is right. you can use `L.esri.DynamicMapLayer` both to display and query features in more than one layer.

see https://esri.github.io/esri-leaflet/examples/identifying-features.html

**Comment by jwasilgeo** [comment]
@fnick851, as @jgravois has also pointed out and as you've also described in more detail, we have some caveats but also several potential options to consider.  Can you please create a live, editable code sample so we can try out some things collaboratively?

It is true that there isn't a concept of client-side "merging" of `L.esri.FeatureLayer`s with the requirements you have expressed.  As I understand it, ```L.LayerGroup``` or ```L.FeatureGroup``` combine them to be _managed_ together.  But even if the `L.esri.DynamicMapLayer` option is unavailable to you (e.g. if your FeatureLayers come from different services), we should be able to wire up a `click` listener with a query(ies) to get all the info you want at that click location.

**Comment by fnick851** [comment]
@jwasilgeo Thanks for the helps!
Here is a live demo that you can edit: https://codesandbox.io/s/bold-thunder-ez83r?fontsize=14

What I need (I've also added in the code comments):
1. The `e` capture merged or all data from all layers.
2. The map color coding represent the merged data, not just the layer on top. (Thus I am thinking merging all layers into one.)

**Comment by jwasilgeo** [comment]
1. After line 60 in your example I added this as a quick example of how to manually query each featurelayer on click.  You could drop the `L.featureGroup` (unless it helps with overall visibility or popup management) and instead wire up the click against the map as is shown in @jgravois's example that relies on the dynamicmaplayer (but that's all contained in the same mapservice URL).

    ```js
    .on("click", function (e) {
      console.log(e); // NEED THE 'e' capture all data properties from all layers (merged) // line 60
      layer1.query()
        .intersects(e.latlng)
        .run(function (error, featureCollection) {
          console.log("layer1 query results:", featureCollection);
        });

      layer2.query()
        .intersects(e.latlng)
        .run(function (error, featureCollection) {
          console.log("layer2 query results:", featureCollection);
        });
    })
    ```

    These could be made sequential by nesting the next layer's query logic in the previous query's `run` callback.  Or these could potentially be made concurrent by wrapping them each in Promises and a `Promise.all()` on click.  It is worth trying out one of these improvements since you want to aggregate your feature's attributes that are at the click location.

2.  Assuming I follow what you are hoping to do, the symbology topic makes me wonder about finding other potential cartographic solutions to merging data from inherently different geographies contained in different layers, as well as how to deal with challenges associated with topics like [MAUP](https://en.wikipedia.org/wiki/Modifiable_areal_unit_problem).

    But, for the sake of JS, you could access a feature at a clicked location in the `run` callback to change its style if you have all the disparate info you need aggregated at this point in time.

    ```js
    // featureCollection is just geojson available in the query run callback
    // you can look up the feature from the id back in the featurelayer
    layer2.getFeature(featureCollection.features[0].id).setStyle({
      fillOpacity: 0.5,
      fillColor: "hotpink"
    });
    ```

    Otherwise, to modify symbology overall, without relying on a click, one thing I can think of at the moment is to access features from each layer and perform your own geometry intersection tests to decide if you are going to do something with intersecting features' symbols.

**Comment by fnick851** [comment]
@jwasilgeo  Thanks for the detailed answer! I think I have clearer direction now. I'm closing the issue for now.

**Comment by jwasilgeo** [comment]
@fnick851, you're welcome! If you come up with something interesting you can share later we'd be curious to see it.

Another thing that crossed my mind is that if you are using SVGs with Leaflet (meaning `false` for [this `map` property](https://leafletjs.com/reference-1.5.0.html#map-prefercanvas)) you may be able to try out SVG filters to [blend](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feBlend) overlapping layers.

**Comment by fnick851** [comment]
Hi @jwasilgeo 
So this is the actual map I am working on to modify: http://public-air-national-map-ecmc.s3-website-us-east-1.amazonaws.com/
If you toggle on two layers, you can see the latter layer will cover up the previous one.
I want to merge the two layers into a single one, regardless of the meaning of the aggregated number (the MAUP issue). 
In reality there could be any number of layers that the user toggles on, so it needs to merge on-the-fly, not beforehand.

Does this still seem possible (any approach, either client side or not)
Thanks.
