### ISSUE TITLE
Basemap renders tiles unevenly and scattered.

### ISSUE THREAD

**Issue by blakemorgan** [Esri/esri-leaflet#1171]
* Browser and version:

Chrome 77

* Version of Leaflet (`L.version`):

1.5.1

* Version of esri Leaflet (`L.esri.VERSION`):

2.3.1

Steps to reproduce the error:

1) Include the libraries.
2) Include the following code:

```javascript
      const map = L.map('byuMap').setView([37.75, -122.23], 10)
      esri.basemapLayer('Topographic').addTo(map)
```

What happens is that the basemap displays oddly:

![Screenshot from 2019-10-14 13-25-50](https://user-images.githubusercontent.com/9389424/66777613-9dae8780-ee86-11e9-8650-6f56077605a1.png)

I was expecting all the tiles to render properly.

I'm *not* using the [CDN](http://www.jsdelivr.com/projects/leaflet.esri), I'm loading/bundling the library using:

[webpack](https://webpack.github.io/), vue, and nuxt.

**Comment by jwasilgeo** [comment]
What are your JS and CSS versions of your Leaflet-related dependencies? We see this sometimes when they aren’t the same.

**Comment by jwasilgeo** [comment]
@blakemorgan let's close this for now. But if you find you are still having issues after verifying that the Leaflet CSS and JS versions are aligned, then feel free to provide the info and reopen.

**Comment by KingUgochukwu** [comment]
> What are your JS and CSS versions of your Leaflet-related dependencies? We see this sometimes when they aren’t the same.

@jwasilgeo Hello there , I am having this exact issue on my simple angular hello world type of map. I am a noob in angular and I am not sure how to see the leaflet css and jss version to ensure they are the same. How find this? Any ideas on how to solve this? 

`{
  "name": "map-test",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~12.1.0",
    "@angular/common": "~12.1.0",
    "@angular/compiler": "~12.1.0",
    "@angular/core": "~12.1.0",
    "@angular/forms": "~12.1.0",
    "@angular/platform-browser": "~12.1.0",
    "@angular/platform-browser-dynamic": "~12.1.0",
    "@angular/router": "~12.1.0",
    "@types/esri-leaflet": "^2.1.9",
    "@types/leaflet": "^1.7.4",
    "angular-esri-map": "^2.0.5",
    "esri-leaflet": "^3.0.2",
    "leaflet": "^1.7.1",
    "rxjs": "~6.6.0",
    "tslib": "^2.2.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~12.1.4",
    "@angular/cli": "~12.1.4",
    "@angular/compiler-cli": "~12.1.0",
    "@types/jasmine": "~3.8.0",
    "@types/node": "^12.11.1",
    "jasmine-core": "~3.8.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "typescript": "~4.3.2"
  }
}
`

**Comment by jwasilgeo** [comment]
Can you verify you’re importing the Leaflet CSS stylesheet in your Angular app? Missing it may cause this behavior.

**Comment by KingUgochukwu** [comment]
Thanks for taking the time to respond to me. I was wrongly importing the
css stylesheet as you pointed out. I have sorted this out. Thanks a lot
