### ISSUE TITLE
use new GitHub 'pinned issues' feature

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet#1172]
https://help.github.com/en/github/managing-your-work-on-github/pinning-an-issue-to-your-repository

GitHub launched a nifty new feature to make up to three 'gotcha' issues sticky. anything with the <kbd>FAQ</kbd> label would be a good candidate to pin.

https://github.com/esri/esri-leaflet/issues?q=is%3Aissue+label%3AFAQ+is%3Aclosed

**Comment by jgravois** [comment]
I still recommend y'all consider this, no need to keep an issue open though.

**Comment by gavinr** [comment]
bam, thanks for the reminder:
![image](https://user-images.githubusercontent.com/209355/71054072-7c993a00-2148-11ea-92db-40175cca100e.png)
