### ISSUE TITLE
Feature Layer queries are ignorning Extent

### ISSUE THREAD

**Issue by EduardoCopat** [Esri/esri-leaflet#1175]
* Browser and version: 78.0.3904.108 (Official Build) (64-bit)
* Version of Leaflet (`L.version`): 1.5.1+build.2e3e0ffb
* Version of esri Leaflet (`L.esri.VERSION`): "2.3.2"

Steps to reproduce the error:

- Query a feature outside of Extent

What happens is: a query is sent to the server anyway.
I was expecting: the query not be sent.

You can check this using the [feature layer documentation sample](https://esri.github.io/esri-leaflet/examples/querying-feature-layers-1.html). 
This is querying a [feature server](https://services5.arcgis.com/7nsPwEMP38bSkCjy/arcgis/rest/services/TEST_PYTHON_ZONING/FeatureServer/0?f=json) which has the following `extent`:

```
"extent": {
  "xmin": 6359577.620000005,
  "ymin": 1713083.900000006,
  "xmax": 6514573.680000007,
  "ymax": 1945515.3199999928,
  "spatialReference": {
    "wkid": 102645,
    "latestWkid": 2229
  }
},
```

If you move the map outside this boundaries, requests are still being sent:

![image](https://user-images.githubusercontent.com/2248490/70106929-e6760600-16a9-11ea-9541-109f25f910bc.png)

They return `"features": []`.

I would expect it to behave similar to Min and Max Zoom (see #926 ). If it's not in the correct zoom level, it does not query.

**Comment by jgravois** [comment]
I'm not sure what to tell you. the library doesn't do any clientside math to try and avoid firing requests that are entirely outside the extent advertised for a feature service.

it's certainly _possible_, but doing so would induce significant overhead in situations where the service is reprojected to web mercator on the fly.

**Comment by gavinr** [comment]
Thanks for bringing this up @EduardoCopat. Right now, this is expected behavior of how the library will work. If you'd like to create a PR to improve on it we're always open to it!
