### ISSUE TITLE
ERR_ABORT 404 Issue when querying

### ISSUE THREAD

**Issue by lrpatterson** [Esri/esri-leaflet#1176]
* Browser and version:

78.0.3904.108

* Version of Leaflet (`L.version`):

1.6.0

* Version of esri Leaflet (`L.esri.VERSION`):

2.3.2

Steps to reproduce the error:
I am currently working on a function to allow users to click on the map and return data about that feature.  I tried using identify but it is terribly slow.  So I pivoted to use an intersect by capturing e.latLng.  I am intermittently getting the ERR_ABORT 404 (I have included the image below and the offending url here: https://gisservices2.cabarruscounty.us/arcgis/rest/directories/arcgisoutput/DataExplorerDatasets_MapServer/_ags_map9e56558d44fd40adb1c92da2a5379552.png)

I was expecting for a map click to return data from the server about the property.

I'm *not* using the [CDN](http://www.jsdelivr.com/projects/leaflet.esri), I'm loading/bundling the library using: NPM

Here is the code:
```js
const parcelData = 'https://gisservices2.cabarruscounty.us/arcgis/rest/services/GISWebsites/MapServer/11'
 var parcelDataQuery = L.esri.query({
    url: parcelData,
    useCors:false
  });
  // GET PROPERTY DATA ON MAP CLICK
  map.on(`click`, function (e) {

    location = e.latlng
    results.clearLayers();
    results.addLayer(L.marker(e.latlng))
    parcelDataQuery.intersects(location)
    .run(function (error, featureCollection, response, ids) {
      if (error) {
        return;
      } else if (featureCollection.features.length > 0){
        // features = featureCollection.features[0].properties
        pin = featureCollection.features[0].properties['PIN14']
        addresses.query({useCors:false}).where("PIN14=" + "'" + pin + "'").run(function (error, featureCollection) {
          try {
            features = featureCollection.features[0].properties
            bindDataDrawer('body', features, map, location)

          } catch (error) {
            console.warn(error);
            console.log("No property at site selected. Please try again.")
            
          }
          
        })
      }
      
    });
```

**Comment by jwasilgeo** [comment]
What is the URL for `addresses` which is the 2nd/subsequent query that I see in your code?

Can you also provide example network requests for the 2 different query REST calls, too, from your network dev tools?  Something with this structure with more params: `https://gisservices2.cabarruscounty.us/arcgis/rest/services/GISWebsites/MapServer/11/query? ...`

(I wonder if this has more to do with the server rather than Leaflet or Esri-Leaflet.)

**Comment by lrpatterson** [comment]
Here is the `addresses`.

`
const addressData = 'https://gisservices2.cabarruscounty.us/arcgis/rest/services/DataExplorerDatasets/MapServer/0'

const addresses = L.esri.featureLayer({
    url: addressData, 
    useCors: false,   
    renderer: L.svg(),
    pointToLayer: function (geojson, latlng) {
      return L.circleMarker(latlng);
    },
    style: {
      "color": "#ff7800",
      "radius": 2,
      // "weight": 1,
      // "opacity": 0.65
    },
    minZoom: 18
  })`

**Comment by lrpatterson** [comment]
It looks like the `addresses` are the ones bombing out.

**Comment by lrpatterson** [comment]
Here is what I am getting from the network tab.

`General

Request URL: https://gisservices2.cabarruscounty.us/arcgis/rest/services/GISWebsites/MapServer/11/query?returnGeometry=true&where=1%3D1&outSR=4326&outFields=*&inSr=4326&geometry=%7B%22x%22%3A-80.571589398302%2C%22y%22%3A35.38958727253337%2C%22spatialReference%22%3A%7B%22wkid%22%3A4326%7D%7D&geometryType=esriGeometryPoint&spatialRel=esriSpatialRelIntersects&callback=window._EsriLeafletCallbacks.c163&f=json
Request Method: GET
Status Code: 404 Not Found
Remote Address: 192.168.0.91:443
Referrer Policy: no-referrer-when-downgrade

Response Header

Cache-Control: private
Content-Length: 1339
Content-Type: text/html;charset=ISO-8859-1
Date: Thu, 05 Dec 2019 17:41:32 GMT
Expires: Wed, 31 Dec 1969 19:00:00 EST
Server: Microsoft-IIS/7.5
Server: Apache-Coyote/1.1
X-AspNet-Version: 2.0.50727
X-Powered-By: ASP.NET

Request Headers

Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,ja;q=0.8
Connection: keep-alive
Cookie: JSESSIONID=AB1B0064CF48FD00D02E6B1CC8586CA3
DNT: 1
Host: gisservices2.cabarruscounty.us
Referer: https://ccswebtest.cabarruscounty.us/leaflet-cabcoGIS/dev/build/
Sec-Fetch-Mode: no-cors
Sec-Fetch-Site: same-site
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36

String Query Parameter

returnGeometry: true
where: 1=1
outSR: 4326
outFields: *
inSr: 4326
geometry: {"x":-80.571589398302,"y":35.38958727253337,"spatialReference":{"wkid":4326}}
geometryType: esriGeometryPoint
spatialRel: esriSpatialRelIntersects
callback: window._EsriLeafletCallbacks.c163
f: json
`

**Comment by lrpatterson** [comment]
@jwasilgeo  I also tried to log these call in ArcGIS server but there was nothing logged.

**Comment by jwasilgeo** [comment]
@lrpatterson I was going to suggest that, too, and see if you can pinpoint server logs (verbose setting) that show up when there is an erroneous response.

I am still thinking this is a server-side issue that doesn't have to do with esri-leaflet's query that gets sent to the server.  Unless there is a specific combination of query parameters that are being created and sent by esri-leaflet's code to this layer's REST query endpoint and consistently failing, I am afraid there's not much we can do here to debug under the esri-leaflet umbrella.

We will close this issue for now, but please feel free to reopen if you think upon further investigation that there's something here to do with esri-leaflet source code.  Thanks.
