### ISSUE TITLE
Basemap switcher not loading featureLayer

### ISSUE THREAD

**Issue by lrpatterson** [Esri/esri-leaflet#1177]
* Browser and version:
Chrome 78

* Version of Leaflet (`L.version`):
1.6.0

* Version of esri Leaflet (`L.esri.VERSION`):
2.3.2

Steps to reproduce the error:

I am working on a layer switcher.  When I add the following basemap and overlay layers via this snippet:

var overlay = {
  "tester": L.esri.featureLayer({
    url: 'https://gisservices2.cabarruscounty.us/arcgis/rest/services/opendata/MapServer/1',
    useCors: false,})
}

var base = {
  "base": L.esri.imageMapLayer({url:'https://location.cabarruscounty.us/arcgisservices/rest/services/Imagery/Aerial1938/ImageServer', useCors: false,}) 
}

L.control.layers(base, overlay).addTo(map)`

Only the base variable is added (see image).  Is there something wrong with my code?  I tried to follow the docs as close as possible.

![2019-12-10_23-29-21](https://user-images.githubusercontent.com/41905851/70591704-f9ef0880-1ba4-11ea-892c-9f729aa81a1e.png)

**Comment by jgravois** [comment]
I can't repo that with your code snippet.

https://jsbin.com/wadazuj/edit?output

**Comment by lrpatterson** [comment]
After taking a closer look it seems that another plugin overrode the default leaflet CSS by adding `display: none` to `leaflet-control-layers-overlays`.  So after removing it is now working as expected. Thank you @jgravois!

**Comment by jwasilgeo** [comment]
Which plugin has that CSS, out of curiosity?

**Comment by pmacMaps** [comment]
This reminds me of the time I was having issues with the Renderers Plugin and published service symbology on a map embedded on a Drupal site.

**Comment by lrpatterson** [comment]
@jwasilgeo, This is the plugin that was in conflict: https://github.com/aebadirad/Leaflet.AutoLayers

**Comment by jwasilgeo** [comment]
Thanks for letting us know about that, @lrpatterson.
