### ISSUE TITLE
Annotation Layer 

### ISSUE THREAD

**Issue by lrpatterson** [Esri/esri-leaflet#1178]
Browser and version:
Chrome 78

Version of Leaflet (L.version):
1.6.0

Version of esri Leaflet (L.esri.VERSION):
2.3.2

I am trying to add an annotation layer to my leaflet map.  Is this even possible?  As it stands right now I have the esri leaflet render plugin but when I bring in the layer displays no image of the property measurements.  I am getting a 200 for this layer when the query completes.

This is part of a larger code snippet where I am adding layers to the `L.control.layer` tool.  So the annotation layer is mixed in with lots of other layers that are being looped through and added programmatically. I have include the snippet below:

Here is the layer in question: https://location.cabarruscounty.us/arcgisservices/rest/services/DataExplorerDatasets/MapServer/1

```if(layerLink === 'https://location.cabarruscounty.us/arcgisservices/rest/services/DataExplorerDatasets/MapServer'){
        fetch(layerLink + '/?f=pjson')
        .then(
          function(response) {
            if (response.status !== 200) {
              console.warn('Looks like there was a problem. Status Code: ' +
                response.status);
              return;
            }
      
            // Examine the text in the response
            response.json().then(function(data) {
              for(i=0; i < data.layers.length; i++) {
                let dataID = data.layers[i].id
                let layerName = data.layers[i].name
                let controllerData = esri.featureLayer({
                  url: layerLink + '/' + dataID,
                  useCors: false,
                  
                })

                layerController.addOverlay(controllerData, layerName)

              }
            });
          }
        )
        .catch(function(err) {
          console.log('Fetch Error :-S', err);
        });

      } ```

**Comment by pmacMaps** [comment]
I would try to add in the `lot dimensions` sub-layer as a `L.esri.DynamicMapLayer`.  Within the `layers` property, you could set the value to `[1]`.  

This would bring in the labels on your map as a dynamic map layer as opposed to a feature layer.  See the [API reference](https://esri.github.io/esri-leaflet/api-reference/layers/dynamic-map-layer.html) for more details.  

```javascript
const lotLabels = L.esri.dynamicMapLayer({
    url: 'https://location.cabarruscounty.us/arcgisservices/rest/services/DataExplorerDatasets/MapServer',
    layers: [1]
  }).addTo(map);
```

**Comment by lrpatterson** [comment]
@pmacMaps Thanks, that got it!!
