### ISSUE TITLE
Dynamic layer cannot use both f:image and token

### ISSUE THREAD

**Issue by jptheripper** [Esri/esri-leaflet#1180]
* Browser and version:

Chrome 51

* Version of Leaflet (`L.version`):

0.7.7, 1.0.0?

* Version of esri Leaflet (`L.esri.VERSION`):

1.0.4, 2.0.3, `master`?

Steps to reproduce the error:

1. create map
2. add server authenticated service that requires password. 
3. add parameter f:'json'
4. add parameter token: response.token

What happens is the image parameter is ignored and request is sent with type f=json

I was expecting f=image to be respected.  Feature service only loads half the time due to internal load balancer not having request on /arcgisoutput (which is why we need to use the f=image parameter)

https://jsbin.com/hiqequg/edit?html,output

**Comment by jwasilgeo** [comment]
Some more background and historical info would be helpful here from previous contributors to [`./src/Layers/DynamicMapLayer.js`](https://github.com/Esri/esri-leaflet/blob/master/src/Layers/DynamicMapLayer.js).

It appears to me that this is acting as designed in:

- https://github.com/Esri/esri-leaflet/blob/6cf758751e8c34b61415254fa23ec109400e8ec3/src/Layers/DynamicMapLayer.js#L23-L25
- https://github.com/Esri/esri-leaflet/blob/6cf758751e8c34b61415254fa23ec109400e8ec3/src/Layers/DynamicMapLayer.js#L177

**Comment by jgravois** [comment]
the`else` block below needs a `token` check similar to the `if` block above it, except it needs to optionally append the parameter to the original url.

https://github.com/Esri/esri-leaflet/blob/6cf758751e8c34b61415254fa23ec109400e8ec3/src/Layers/DynamicMapLayer.js#L194-L197

besides the service in @jptheripper's jsbin, you can also test with the one below.

username: user1
password: user1

http://sampleserver6.arcgisonline.com/arcgis/rest/services/Wildfire_secure_ac2/MapServer/export?token=foo&...

**Comment by jptheripper** [comment]
This is absolutely perfect.  We can confirm once this functionality is applied that f='image' and token work together as desired.

**Comment by jptheripper** [comment]
Sorry, I am new to the whole process.  How do we get the change applied to the source code?

**Comment by jgravois** [comment]
> How do we get the change applied to the source code?

[pull requests](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests) are _always_ welcome.

in this case, a new test similar to the one below would be extremely helpful.

https://github.com/Esri/esri-leaflet/blob/c3130441f949dc1125a18b047eea9620c9ed1e5b/spec/Layers/DynamicMapLayerSpec.js#L359-L367

**Comment by jwasilgeo** [comment]
@jgravois thanks for input. And what should we do to this block that overrides on construction?

https://github.com/Esri/esri-leaflet/blob/6cf758751e8c34b61415254fa23ec109400e8ec3/src/Layers/DynamicMapLayer.js#L23-L25

**Comment by jptheripper** [comment]
Yes I was about to comment that needs to be dealt with as well.  image type should not be overridden just because there is a token or proxy

**Comment by jwasilgeo** [comment]
Should it be dropped altogether? Or just override if there is a proxy available in the options? Not sure what the original intent was. Thanks!

**Comment by jgravois** [comment]
good catch @jwasilgeo. I forgot all about that.

to implement this new feature you'd need to remove the `options.token` check in the override.

if you want to take a stab at implementing the proxy logic for `f: 'image'` too, then you could get rid of it altogether.

> Not sure what the original intent was.

maybe Pat figured that if folks wanted to work with secure layers they could just use `f: 'json'`.
I'm not sure.

**Comment by jptheripper** [comment]
In our test (we only use image, with and without token) simply commenting out the override worked for us.  I imagine that may break other cases.  If it possible to just change the override to 

` if (((options.proxy || options.token) && options.f !== 'json')&&(!(options.token&& options.f == 'image'))) { 
   options.f = 'json'; 
 } `

**Comment by jptheripper** [comment]
So, (because i am new to all this), how long does this take to propagate into the CDN

**Comment by gavinr** [comment]
@jptheripper in order for the fix in that [Pull Request](https://github.com/Esri/esri-leaflet/pull/1182) to become available for your use on the CDN, we must publish a [new release](https://github.com/Esri/esri-leaflet/releases). We intend to cut a new release soon.

**Comment by gavinr** [comment]
@jptheripper https://github.com/Esri/esri-leaflet/releases/tag/v2.3.3

**Comment by timothycouchhsi** [comment]
Thanks a ton! This is great. And you were so quick to respond :)
