### ISSUE TITLE
DynamicMapLayer and ImageMapLayer with json/image + token/proxy support

### ISSUE THREAD

**Issue by jwasilgeo** [Esri/esri-leaflet#1184]
As of v2.3.3, `DynamicMapLayer.js` and `ImageMapLayer.js` (both of which extend from `RasterLayer`) do not fully support certain options combinations of `f: 'json'` or `f: 'image'` coupled with a token or a proxy.

#### `DynamicMapLayer`

token support

- [x] `f: 'json'` and token in source code
- [x] `f: 'json'` and token has unit test
- [x] `f: 'image'` and token in source code
- [x] `f: 'image'` and token has unit test

proxy support

- [x] `f: 'json'` and proxy in source code
- [x] `f: 'json'` and proxy has unit test
- [x] `f: 'image'` and proxy in source code
  - (would need to remove the entire `f` override in the `initialize` method)
- [x] `f: 'image'` and proxy has unit test

#### `ImageMapLayer`

token support

- [x] `f: 'json'` and token in source code
- [x] `f: 'json'` and token has unit test
- [x] `f: 'image'` and token in source code
- [x] `f: 'image'` and token has unit test

proxy support

- [x] `f: 'json'` and proxy in source code
- [x] `f: 'json'` and proxy has unit test
- [x] `f: 'image'` and proxy in source code
- [x] `f: 'image'` and proxy has unit test

#### Additional info and breadcrumbs
issue https://github.com/Esri/esri-leaflet/issues/1180
pr https://github.com/Esri/esri-leaflet/pull/1181
pr https://github.com/Esri/esri-leaflet/pull/1182

**Comment by gavinr** [comment]
@jwasilgeo I think we're good now after all those PRs. Could you please take a look and close if you think it's resolved.

**Comment by jwasilgeo** [comment]
I've taken another look and I agree. Thanks for all that--huge help!
