### ISSUE TITLE
2.3.2 -> 2.3.3 Breaks dynamicLayers 

### ISSUE THREAD

**Issue by Magn3s1um** [Esri/esri-leaflet#1185]
Steps to reproduce the error:

1. Use dynamicLayers in esri-leaflet 2.3.2.  Notice it is serialized correctly
2. Upgrade to 2.3.3, notice it is now serialized as [object, object].

2.3.2 serialization of request: 

[Comparison of serialization results](https://imgur.com/a/MQGoV5i)

**Comment by jwasilgeo** [comment]
Does this only happen when you are using `f: 'image'`? Can you also provide a live sample to help us investigate?

**Comment by Magn3s1um** [comment]
We have f: 'json' being set.   I'll try and get a sample up in the coming days.  Thanks for taking a look.

**Comment by jgravois** [comment]
I can't repro the behavior you describe. we'll definitely need more information in order to investigate.

![Screen Shot 2020-02-12 at 9 25 47 AM](https://user-images.githubusercontent.com/3011734/74360314-abfbaa00-4d79-11ea-9030-f54650c6e5fb.png)

**Comment by jwasilgeo** [comment]
@Magn3s1um can you please let us know if you're still seeing this issue at the latest version `2.4.0`? I'd like to close it out due to inactivity and if it isn't a reoccurring problem for you.

**Comment by Magn3s1um** [comment]
We aren’t seeing this on latest.  Ty for checking on this.
