### ISSUE TITLE
ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by hunnomad** [Esri/esri-leaflet#1186]
* Browser and version: Google Chrome 80.0.3987.100
* Version of Leaflet (`L.version`): 1.6.0
* Version of esri Leaflet (`L.esri.VERSION`):2.3.3

What happens is [X].

Very simple error, ESRI map is not loading.

Why:
Failed to load resource: net :: ERR_SSL_PROTOCOL_ERROR

![ArcGis_Online_SSL_Error_20200213](https://user-images.githubusercontent.com/2537005/74463202-c32dbb00-4e91-11ea-88cd-357f6881f7ef.jpg)

**Comment by jgravois** [comment]
https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/10/395/161

I can load the url above in Chrome 80 just fine. can you?

**Comment by hunnomad** [comment]
![ArcGis_Online_SSL_Error_20200213_2](https://user-images.githubusercontent.com/2537005/74464450-d3df3080-4e93-11ea-8ea7-1d9bdb93275c.jpg)

` 
var map = L.map('map').setView([37.75, -122.23], 10);

L.esri.basemapLayer('Imagery').addTo(map);

L.esri.basemapLayer('ImageryLabels').addTo(map);
`

**Comment by hunnomad** [comment]
![ArcGis_Online_SSL_Error_20200213_3](https://user-images.githubusercontent.com/2537005/74464817-8911e880-4e94-11ea-8dc9-7218d868c688.jpg)

**Comment by jgravois** [comment]
if your browser won't load the tile, there's nothing Esri Leaflet can do to fix that.

I don't really know where to begin troubleshooting something like that, but for starters I'd recommend testing
* different browsers
* another computer
* different WiFi networks
* using English as the OS language

**Comment by hunnomad** [comment]
I thank you for your help. The solution was: "different WiFi networks"
