### ISSUE TITLE
Undesired white background being added to dynamicMapLayer

### ISSUE THREAD

**Issue by teofilosalgado** [Esri/esri-leaflet#1187]
* Browser and version:

All supported browsers;

* Version of Leaflet (`L.version`):

1.6.0

* Version of esri Leaflet (`L.esri.VERSION`):

2.3.3

Steps to reproduce the error:

1. Add a `dynamicMapLayer` to a leaflet `map`  with the following code:
```
this.mapServer = esri.dynamicMapLayer({
        f: 'image',
        url: URL_MAPSERVER,
        transparent: true,
        maxZoom: DEFAULT_CONFIG.maxZoom,
        minZoom: DEFAULT_CONFIG.minZoom,
        layers: [0, 1, 2, 3, 4, 5]
      })
```
What happens is: every layer my ArcGIS MapServer provides are rendered with an opaque white background layer below them. 
![Captura de tela de 2020-03-17 11-55-46](https://user-images.githubusercontent.com/7178504/76868944-5ddd3900-6846-11ea-8162-7d8503569f45.png)

According to Firefox's network tab in developer options, the image returned by the ArcGIS service for the aforementioned screenshot is:
![export](https://user-images.githubusercontent.com/7178504/76869817-9a5d6480-6847-11ea-963f-2bf030bc6427.png)

I was expecting: esri-leaflet to render my layers just like AGOL does. 
![Captura de tela de 2020-03-17 12-15-54](https://user-images.githubusercontent.com/7178504/76870976-3e93db00-6849-11ea-9e56-c2e882e81d7c.png)

**Comment by gavinr** [comment]
@teofilosalgado can you please share the URL to the mapservice you are using?

**Comment by jwasilgeo** [comment]
@teofilosalgado also what `format` is being used?  Default of esri-leaflet should be `'png24'` but the white background makes me wonder if a `'jpg'` format is being used.

**Comment by jwasilgeo** [comment]
And a demo to help us debug would speak 1,000 words, too.

> (if possible, create a [jsbin](http://jsbin.com/dagilag/edit?html,output) that demonstrates the problem)

**Comment by teofilosalgado** [comment]
@gavinr Sure! The URL is http://sistemas.gt4w.com.br/arcgis/rest/services/SICARF/Camadas/MapServer/

**Comment by teofilosalgado** [comment]
@jwasilgeo I left `format` to the default settings, as you said, 'png24'. Actually it's not very hard to reproduce, the snippet below could reproduce the problem in any  enviroment:

```
const map = L.map('map', this.config)
const mapServer = esri.dynamicMapLayer({
        f: 'image',
        url: 'http://sistemas.gt4w.com.br/arcgis/rest/services/SICARF/Camadas/MapServer',
        transparent: true,
        maxZoom: 16,
        minZoom: 3,
        layers: [5]
      })
mapServer.addTo(map)
```

**Comment by teofilosalgado** [comment]
@jwasilgeo https://jsbin.com/timusiviqa/edit?html,output

**Comment by jwasilgeo** [comment]
@teofilosalgado thank you for the extra info and for the jsbin.

Can you try also this property in your layer options?

`format: 'png32'`

I _think_ that works better and seems to provide the visual output you want.  Must just be png24 vs png32.

**Comment by teofilosalgado** [comment]
@jwasilgeo it worked like a charm! Thank you! Me and my team were stuck with this problem for days!

**Comment by jwasilgeo** [comment]
I'm very happy to hear the good news. Do you happen to have any feedback or suggestions on improvements to the documentation, such as for the [`format` option](https://esri.github.io/esri-leaflet/api-reference/layers/dynamic-map-layer.html#options)?

**Comment by jgravois** [comment]
would it help to just default to `"png32"` 🤷‍♂

**Comment by teofilosalgado** [comment]
I agree with @jgravois, I really thought `png24` could handle transparency without any problems. We are used to correlate `png` (in any flavor of it's specification) with transparent images. Maybe add a note on `png32`/`png24` in the documentation would be helpful, or even explaining why this happens.

**Comment by jwasilgeo** [comment]
`L.esri.dynamicMapLayer` now defaults to `png32` for the `format` parameter. Thank you @pmacMaps.
