### ISSUE TITLE
L.esri is undefined while zooming in/out

### ISSUE THREAD

**Issue by danieloliveira117** [Esri/esri-leaflet#1191]
I'm using esri-leaflet as an import (webpack) instead extending the global `L`.

When zooming in or out I'm getting the error:
 `TypeError: L.esri is undefined`

The error is in the following line:

https://github.com/Esri/esri-leaflet/blob/6fb127534445424f34ece5ff9d8caac989bd739f/src/Layers/BasemapLayer.js#L305

It should be able to be fixed simply by importing the `request` function instead of using the global `L.esri`.

**Comment by jgravois** [comment]
great catch. a pull request with a fix would be _most_ welcome.

**Comment by gavinr** [comment]
This was released in v2.4.0: https://github.com/Esri/esri-leaflet/releases/tag/v2.4.0
