### ISSUE TITLE
L.esri.FeatureLayer where clause is not always persisting

### ISSUE THREAD

**Issue by jwasilgeo** [Esri/esri-leaflet#1196]
## Describe the bug

A `L.esri.FeatureLayer` where clause does not always persist when changes to it are made. Occasionally the previous where clause states of the layer reappears on the map.

This supersedes #966 at [version `2.4.0`](https://github.com/Esri/esri-leaflet/releases/tag/v2.4.0).

#996 may have had more to do with network request timings and race conditions; however, I suspect the similarly observed behavior has a different cause at version `2.4.0`.

Please also investigate #875 while researching this issue.

## Expected behavior

Using a feature layer's `setWhere` method should always persist on the map. Previously used where clauses should no longer influence what is shown on the map.

## Actual behavior

Using a feature layer's `setWhere` method does not always guarantee that the new where clause state will appear correctly on the map.

## To Reproduce

1. Go to <https://esri.github.io/esri-leaflet/examples/querying-feature-layers-1.html>.
2. Start out at the demo site with 'Any'.  Ensure all layer-specific network requests are finished.
3. Change to 'Parking'. Wait for requests to settle and finish.
4. Zoom out a bit. Again wait for requests to settle and finish.
5. Zoom back in to roughly where you started out. The 'Any' features where clause state will be shown for the layer instead of only 'Parking'.

## Screenshots

![image](https://user-images.githubusercontent.com/4933392/81181695-74645e80-8f72-11ea-8fa4-955845bfb435.png)

## Environment Information

- Version of Leaflet (`L.version`): `1.6.0`
- Version of Esri Leaflet (`L.esri.VERSION`): `2.4.0`
- Your OS: Windows
- Browser and Version: FF 76.0

## Other References

- [Geonet discussion](https://community.esri.com/thread/255032-zoom-change-causes-filter-reset)

**Comment by LouisFrayard** [comment]
Same problem. Any solutions ?

**Comment by LouisFrayard** [comment]
?

**Comment by gavinr** [comment]
This was fixed in [v2.5.0](https://github.com/Esri/esri-leaflet/releases/tag/v2.5.0).
