### ISSUE TITLE
ERR_NAME_NOT_RESOLVED while zooming in with ImageryClarity

### ISSUE THREAD

**Issue by danieloliveira117** [Esri/esri-leaflet#1197]
## Describe the bug

Invalid url (ERR_NAME_NOT_RESOLVED) while zooming in when using the ImageryClarity basemap.

URL: [https://clarity.maptilemaps.arcgis.com/arcgis/rest/services/World_Imagery/MapServer/tile/18/104319/67391/8/8?f=json](https://clarity.maptilemaps.arcgis.com/arcgis/rest/services/World_Imagery/MapServer/tile/18/104319/67391/8/8?f=json)

## To Reproduce

See bug in [jsbin](https://jsbin.com/fijoxohunu/edit?html,output)

1. Use _ImageryClarity_ basemap.
2. Zoom in a few times.
3. See error in console.

## Screenshots

![imagem](https://user-images.githubusercontent.com/8019593/81434197-b69dc380-915d-11ea-8ad5-9d099df8aea4.png)

## Environment Information

- Version of Leaflet (`L.version`): 1.6.0
- Version of Esri Leaflet (`L.esri.VERSION`): 2.4.0
- Your OS: Windows 10
- Browser and Version: Firefox 76, Chrome 81

**Comment by gavinr** [comment]
Doing a bit of research here:

1. The issue only happens on zoom-in, when zooming into level 14 or higher. 
2. The issue does not happen on pan.
3. The issue does not happen when zooming out
4. The issue does not happen when zooming into level < 14

See console here: https://jsbin.com/getalahoki/2/edit?html,output

**Comment by jgravois** [comment]
Clarity might not have a tilemap https://github.com/Esri/esri-leaflet/pull/1011

**Comment by mickeyjohn** [comment]
It is happening the same with me after version 2.2.4. Is this an expected feature or an issue? 
Thanks a lot.

**Comment by jgravois** [comment]
its a bug.

https://github.com/Esri/esri-leaflet/blob/92b462f40074c62d0ca2d1ff3afc1ed02175c08d/src/Layers/BasemapLayer.js#L254

the call above returns `true` for both the [`Imagery`](https://github.com/Esri/esri-leaflet/blob/92b462f40074c62d0ca2d1ff3afc1ed02175c08d/src/Layers/BasemapLayer.js#L103) and [`ImageryClarity`](https://github.com/Esri/esri-leaflet/blob/92b462f40074c62d0ca2d1ff3afc1ed02175c08d/src/Layers/BasemapLayer.js#L182) basemaps, but only the first actually has a tilemap.

**Comment by gavinr** [comment]
This should be addressed in the fixes to #1210

**Comment by jwasilgeo** [comment]
`ImageryFirefly` also falls under this. I've got something in the works soon.
