### ISSUE TITLE
CDN version is broken in IE11

### ISSUE THREAD

**Issue by destus90** [Esri/esri-leaflet#1198]
## Describe the bug

The hosted CDN version is not compatible with ES5 browsers. There are some ES2015 statements shipped from `@terraformer/arcgis`. This may have happened after merging #1194.

## Expected behavior

Should work in IE11. 

## To Reproduce

https://plnkr.co/edit/I7rNXwkWmITFwupi?open=lib%2Fscript.js

Observe the errors in the console.

**Comment by gavinr** [comment]
@destus90 thank you for the report and the PR. I do see that the latest version does not work in IE11. We will work on testing/verifying your PR. In the mean time you can use a previous version as a workaround: https://unpkg.com/esri-leaflet@2.3.3/dist/esri-leaflet.js

Example: https://plnkr.co/edit/8EGLnIKZ5UmPK3xE?open=lib%2Fscript.js

**Comment by gavinr** [comment]
This was addressed in https://github.com/Esri/esri-leaflet/releases/tag/v2.4.1. Thanks!
