### ISSUE TITLE
MinZoom is not removing the layers second time around

### ISSUE THREAD

**Issue by vangenechtenbert** [Esri/esri-leaflet#1207]
Use a FeatureLayer with the minZoom option.
At first the layers act as aspected.
When we zoom in : they are added.
When we zoom back out over the minZoom level: they are removed.

Try this a second time: they are not removed.

As of version 2.4 this behavior is not working as it should.
Maby because the recent featureLayer changes?

**Comment by gavinr** [comment]
@vangenechtenbert thanks for the report. Do you see any errors in the console when it stops working? Could you post a public example app that the error happens in? Thanks!

**Comment by vangenechtenbert** [comment]
https://jsfiddle.net/yqrd9e3h/
Zoom in
Zoom out
Zoom in
Zoom out

The markers will no longer have effect from the minZoom option

**Comment by pmacMaps** [comment]
I reviewed the Fiddler.  There was an error when the map first loaded: "Cannot read property 'extend' of undefined"; coming from Task.js.

I also noticed that sometimes the min/max zoom was honored, and other times, it was not.

![error-log-esri-leaflet](https://user-images.githubusercontent.com/12861454/85549604-283aaf80-b5ee-11ea-8ce6-a6a89e488a60.PNG)

**Comment by gavinr** [comment]
Thanks! In the JSFiddle, esri-leaflet is being loaded twice - once in the script tag, and once via the jsfiddle "resources" tab:

![image](https://user-images.githubusercontent.com/209355/85557074-f853d200-b616-11ea-97ac-ad69afb900c5.png)

If you remove one of those, the "Task.js" error does not happen.

After that change, I am able to replicate the issue where the minZoom does not seem to be re-applied after the initial zoom-in/zoom-out. I don't see any console errors.

**Comment by vangenechtenbert** [comment]
yep, no errors.
Just unexpected behavior :)

**Comment by jwasilgeo** [comment]
Closed in PR #1212.
