### ISSUE TITLE
Quick question regarding L.esri.FeatureLayer vs L.esri.DynamicMapLayer

### ISSUE THREAD

**Issue by Mak-NOAA** [Esri/esri-leaflet#1208]
@jgravois quick question here
for dynamic layers, I use the "layers" option to reference the layer in the URL
however is there something similar for https://esri.github.io/esri-leaflet/api-reference/layers/feature-layer.html ?

the URL is https://www.webapps.nwfsc.noaa.gov/server7/rest/services/Hosted/SoCalHookandLineSurvey/FeatureServer/0
can I do
```
                 L.esri.featureLayer({
                                          url: 'https://www.webapps.nwfsc.noaa.gov/server7/rest/services/Hosted/SoCalHookandLineSurvey/FeatureServer',
                                          layers: [0]
                                        }).addTo(map);
```

**Comment by Mak-NOAA** [comment]
with Feature Layer the above URL is showing up as
<img width="1318" alt="Screen Shot 2020-06-29 at 1 22 38 PM" src="https://user-images.githubusercontent.com/20570382/86053989-37669680-ba0e-11ea-9187-8cee113fccfb.png">

but they are supposed to appear as

<img width="1062" alt="NASC2012_grab (1)" src="https://user-images.githubusercontent.com/20570382/86054057-506f4780-ba0e-11ea-900c-9edef3662e16.png">

any thoughts on that?

using esri leaflet 2.4.1

**Comment by jwasilgeo** [comment]
@Mak-NOAA, you would use the URL that includes the ending of `...FeatureServer/0` in your feature layer constructor.

This is mentioned in that api docs page you refer to [here](https://esri.github.io/esri-leaflet/api-reference/layers/feature-layer.html).

> Feature Layer URLs always end in a number (ex: /FeatureServer/{LAYER_ID} or /MapServer/{LAYER_ID}).

Somewhat related to #1104. 

If I am on the same page with what you are trying to do, does this info help?

**Comment by Mak-NOAA** [comment]
@jwasilgeo yeah I figured so but just wanted to double check if there was no secret option to do it like dynamic layers. 

Any thoughts on why  https://www.webapps.nwfsc.noaa.gov/server7/rest/services/Hosted/SoCalHookandLineSurvey/FeatureServer/0 appears with points instead of like the 2nd map above?

**Comment by jwasilgeo** [comment]
If you're referring to the symbology--how those points are rendered and are styled on the map--then I think you can look at also using the [`esri-leaflet-renderers` plugin](https://github.com/Esri/esri-leaflet-renderers). That'll help your `esri-leaflet` featurelayer instance inherit symbology defined by the service at your url at FeatureServer/0 (which I noticed is defined as the red triangle symbol for all points).

You could also set your own symbology client-side with the `pointToLayer` or `style` [constructor function options of the feature layer](http://esri.github.io/esri-leaflet/api-reference/layers/feature-layer.html).

**Comment by Mak-NOAA** [comment]
Thank you @jwasilgeo that plugin solved the symbology problem.
