### ISSUE TITLE
Using esri widget on leaflet

### ISSUE THREAD

**Issue by prasetiko** [Esri/esri-leaflet#1213]
Hi nice to meet you,

I am new with esri and leaflet. I followed tutorial for using timeslider on esri (esri/widgets/timeslider) at https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-TimeSlider.html . I use this code to make timeslider

```
var timeSlider = new TimeSlider({
  container: "timeSliderDiv",
  view: view,
  // show data within a given time range
  // in this case data within one year
  mode: "time-window",
  fullTimeExtent: { // entire extent of the timeSlider
    start: new Date(2000, 0, 1),
    end: new Date(2010, 0, 1)
  },
  values:[ // location of timeSlider thumbs
    new Date(2000, 0, 1),
    new Date(2001, 1, 1)
  ]
});
view.ui.add(timeSlider, "manual");
```

Timeslider will created at map. Then I have question, if I using leaflet, can I combine that code with leaflet then present in leaflet map?

**Comment by gavinr** [comment]
Hi, thank you for your interest in both the ArcGIS API for JavaScript and esri-leaflet. In general, the widgets that are part of the ArcGIS API for JavaScript will not work with leaflet and esri-leaflet. 

If you're looking for a time slider plugin, you may want to search for a [leaflet timeslider plugin](https://duckduckgo.com/?t=ffab&q=leaflet+time+slider) - it looks like there are multiple options that may fit your case, although I have not personally used them with esri-leaflet layers.

**Comment by jwasilgeo** [comment]
Hi @prasetiko I'll close this question at this time with the hope that @gavinr's suggestion was useful to you. Thanks again for your interest in these mapping libraries.
