### ISSUE TITLE
Pop-ups Do Not Work with Leaflet 1.7.1 and Microsoft Legacy Edge

### ISSUE THREAD

**Issue by pmacMaps** [Esri/esri-leaflet#1230]
## Describe the bug

When clicking on a map feature layer, no pop-up opens.  This issue is occurring in Microsoft Legacy Edge (Microsoft Edge 44.x) with Leaflet.js 1.7.1.  

It does not happen in the Chromium-based Microsoft Edge or Internet Explorer 11.  It also does not happen with Leaflet.js 1.6.0.  It may be a Leaflet.js issue, I'm not sure.

And I recognize the issue is with Legacy Edge, by my organization (local government) still has our users using this version of Edge.   

## Expected behavior

A pop-up should open when clicking on the map feature.

## To Reproduce

1. Go to https://gis.ccpa.net/labs/edge-leaflet-issues/
2. Click on the orange circle icons

## Environment Information

- Version of Leaflet (`L.version`): 1.7.1
- Version of Esri Leaflet (`L.esri.VERSION`): 2.5.0
- Your OS: Microsoft Windows 10
- Browser and Version: Microsoft Edge 44.18362.449.0

**Comment by jgravois** [comment]
you should _definitely_ try and put together a repro case with plain old Leaflet. it'll be helpful in tracking down the root cause either way.

**Comment by pmacMaps** [comment]
It is a Leaflet-specific error.  Issue logged at https://github.com/Leaflet/Leaflet/issues/7262. Feel free to close this issue.
