### ISSUE TITLE
ESRI Leaflet Popup "invisible"

### ISSUE THREAD

**Issue by yjaffrain** [Esri/esri-leaflet#1231]
## Describe the bug

- I have a standard basemap : displays perfectly.
- I add a feature layer : displays perfectly too.
- Each feature from the featureLayer is associated with a popup.

Problem : when I click on the marker, the popup doesn't display. Though : I can see that it tries to display it, because I can see the map panning in order to display the popup correctly.....

## Expected behavior

The popup should display. (I've tried to see if it was a problem of z-index but the popup doesn't even seem to be part of the DOM.
## Actual behavior
Here is my very simple HTML page : 
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>ESRI LEAFLet Popup</title>
  <meta name="viewport" content="initial-scale=1,maximum-scale=1,user-scalable=no" />
  
  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
  integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
  crossorigin=""/>
  <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
  integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
  crossorigin=""></script>
  
  <script src="https://unpkg.com/esri-leaflet@2.5.0/dist/esri-leaflet.js"
  integrity="sha512-ucw7Grpc+iEQZa711gcjgMBnmd9qju1CICsRaryvX7HJklK0pGl/prxKvtHwpgm5ZHdvAil7YPxI1oWPOWK3UQ=="
  crossorigin=""></script>
  <style>
    body { margin:0; padding:0; }
    #map { position: absolute; top:0; bottom:0; right:0; left:0; }
  </style>
</head>
<body>
  <div id="map"></div>
  <script>
  //init
  var map = L.map('map').setView([48.855, 2.345], 9);
  //add vector tile custom basemap
  L.esri.basemapLayer("Topographic").addTo(map);
  //my esri hosted feature layer
  var mylayer = L.esri.featureLayer({
    url: 'https://services7.arcgis.com/KaRO2GE69SgnZrDU/arcgis/rest/services/BaseCARIDF_public/FeatureServer/0', 
    onEachFeature: createPopup
  }).addTo(map);  

  function createPopup(geojson, layer) {
     var popupText = "<div style='max-height:200px;'>TEST POP-UP</div>";
     layer.bindPopup(popupText);
   }
</script>
</body>
</html>
## Environment Information

- Version of Leaflet (`L.version`): 1.7.1
- Version of Esri Leaflet (`L.esri.VERSION`): 2.5.0
- Your OS: [e.g. iOS] Mac OS 10.15.6
- Browser and Version Safari 13.1.2

Thanks A LOT

**Comment by jgravois** [comment]
sounds a whole lot like #1230

**Comment by gavinr** [comment]
Closing as a leaflet issue, see https://github.com/Leaflet/Leaflet/issues/7266 - please let us know if not fixed by that.
