### ISSUE TITLE
Proxy not supported in FeatureLayer

### ISSUE THREAD

**Issue by francharbo** [Esri/esri-leaflet#1232]
## Describe the bug

Even though the documentation is mentioning a proxy parameter for the feature layer, it seems to not be able to use it when asking for the metadata at least.
Documentation : 
![image](https://user-images.githubusercontent.com/6029388/94910818-86a4e300-04a5-11eb-8ca8-4b71df1c80c1.png)

Request for metadata : 
![image](https://user-images.githubusercontent.com/6029388/94911008-c8ce2480-04a5-11eb-92b7-585184545cec.png)

## Expected behavior

The request for metadata should be able to use the proxy which could make the authentication for example.

## Actual behavior

Without going through the proxy, the service returns null because we require authentication

## To Reproduce

1. Create a feature layer with a secure service
2. Set the proxy options to a URL
4. See that the request to metadata is not prefixed with the proxy

**Comment by gavinr** [comment]
Thanks for the report! If you were able to add some examples of unit tests as a PR to illustrate this issue it would definitely be welcomed! (see https://github.com/Esri/esri-leaflet/issues/1184 for potential examples)

**Comment by francharbo** [comment]
Thanks for the reply!

However, it was a mistake I made that provoked this behavior.
So everything works fine in fact.

I am only struggling with custom headers, but that's another thing. I believe it's not yet supported in esri-leaflet, so I will probably look into that.
