### ISSUE TITLE
e.feature.properties is not always pulling

### ISSUE THREAD

**Issue by TheCre8r** [Esri/esri-leaflet#1237]
In my code, the deed and/or plat is not always loading from the parcels available here: `https://arcgis.mobile311.com/arcgis/rest/services/NorthCarolina/Vance/MapServer/163`

code excerpt (removed many lines to only highlight applicable issue)
```js
parcels.bindPopup(function(e){
    let popupTemplate = `<h3>Owner: {OWNNAME}</h3>Address: {PHYSADDRES}</br>PIN: {PIN}</br>D{DEED_REF}`;
    console.log("Deed "+e.feature.properties.DEED_REF)
    console.log("Plat "+e.feature.properties.PLAT_REF)
    return L.Util.template(popupTemplate, e.feature.properties);
});

```

**Comment by gavinr** [comment]
Hi, please use [jsbin](http://jsbin.com/dagilag/edit?html,output) to create a page that demonstrates the problem.

**Comment by TheCre8r** [comment]
Thank you.
Please see [here](https://jsbin.com/wefudav/edit?html,output)

**Comment by TheCre8r** [comment]
Rookie Mistake
Database owner has more than one location for Deed information and I was not using the correct one.
  DBOOK: 466,
  DEED_REF: "466-400",
  DPAGE: 400.

Amazing what a good night sleep will do.
