### ISSUE TITLE
Function Context on Query function

### ISSUE THREAD

**Issue by lrpatterson** [Esri/esri-leaflet#1240]
## Describe the bug

I cannot currently return features from an intersect query.

## Expected behavior

I have a few queries that need to be don't on separate layers each query will take data from the preceding query (ie B query needs data from A query).  I would like to be able to get data returned from the query and either store it in a variable within the main function or store in a global variable.

## Actual behavior

Currently I cannot get the data hoisted any higher than the callback function level
Here is a demo: https://codesandbox.io/s/sweet-knuth-dk3rx?file=/src/index.js

## To Reproduce

Open the console and you will see only `undefined` gets returned.

## Environment Information

- Version of Leaflet (1.7.1`):
- Version of Esri Leaflet (`2.5.1`):

**Comment by jgravois** [comment]
```js
var inter = await query.intersects(l);
```
methods like `Query.intersects()` do _not_ return a [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) so the `await` keyword you're inserting is ignored. as you said, results fetched in asynchronous tasks in Esri Leaflet are made available via callbacks. 

i'm hopeful that the page below (particularly the section titled 'Keep your code shallow') might help you pass around the information you're fetching asynchronously and accessing via callbacks.

http://callbackhell.com
