### ISSUE TITLE
Blank Imagery Returned

### ISSUE THREAD

**Issue by lrpatterson** [Esri/esri-leaflet#1244]
## Describe the bug

Imagery is being returned as blank and response is a 200.  

## Expected behavior

Should return an image of aerial

## To Reproduce

Minimal Example: https://codesandbox.io/s/vigilant-https-gr8mv?file=/index.html

1. Go to https://codesandbox.io/s/vigilant-https-gr8mv?file=/index.html
2. Should see a blank map (ie no imagery)

You can also visit this link to see the output constructed by the esri-leaflet library: https://location.cabarruscounty.us/arcgisservices/rest/services/cached_imagery/Aerial_2013/MapServer/export?bbox=-9058857.97018938%2C4280014.961800158%2C-8874797.606078675%2C4136771.970793739&size=1204%2C937&dpi=96&format=png32&transparent=true&bboxSR=3857&imageSR=3857&f=json

## Environment Information

- Version of Leaflet (`1.7.1`):
- Version of Esri Leaflet (`2.5.1`):

**Comment by jwasilgeo** [comment]
@lrpatterson this seems like a data projection issue perhaps. In Esri JSAPI and LeafletJS I see the non-empty image responses coming back and drawing in those maps, but in eastern Cameroon. Is that the intended overall location of the aerial imagery? Closing for now, but feel free to open again if you find an issue with esri-leaflet.
