### ISSUE TITLE
Request URL length <= 2000 checking does not escape `'`

### ISSUE THREAD

**Issue by Voileexperiments** [Esri/esri-leaflet#1246]
Tested on Leaflet 1.7.1, Esri Leaflet 2.5.1.

I've encountered a issue where a request to a Feature layer through resource proxy would fail with 404 error when filter condition reaches specific length. Looking at #983, I found that `Request.js` is calculating the length of the request to be less than the actual length, and it just so happens hit the 2000 (probably 2048?) character limit so it's incorrectly using GET request, which caused the fail.

https://github.com/Esri/esri-leaflet/blob/master/src/Request.js#L121

With a debugger I see that `paramString` did not escape `'` to `%27` while the actual request URL would, hence under-estimating the URL length.

**Comment by Voileexperiments** [comment]
Example fiddle: https://jsfiddle.net/t9onha6p/

The request URL sent out is

```https://sampleserver6.arcgisonline.com/arcgis/rest/services/Earthquakes_Since1970/MapServer/0/query?returnGeometry=true&where=%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27%20AND%20%271%27%20%3D%20%271%27&outSR=4326&outFields=*&inSr=4326&geometry=%7B%22xmin%22%3A-126.5625%2C%22ymin%22%3A36.59788913307022%2C%22xmax%22%3A-123.75%2C%22ymax%22%3A38.82259097617713%2C%22spatialReference%22%3A%7B%22wkid%22%3A4326%7D%7D&geometryType=esriGeometryEnvelope&spatialRel=esriSpatialRelIntersects&geometryPrecision=6&resultType=tile&f=json
```

Which has 2329 characters.

**Comment by gavinr** [comment]
esri-leaflet does call `encodeURIComponent` [here](https://github.com/Esri/esri-leaflet/blob/f572dbad34d6aef5b94eface5c0b73da5bbd9caa/src/Request.js#L31), but it seems like it does not encode `'` as well as some other characters:

![image](https://user-images.githubusercontent.com/209355/102276044-2f4bd600-3f1e-11eb-9ef1-ed86e318ce49.png)

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent#Description

Which in your case if the browser _does_ escape those characters, the calculated url length will not be correct. I agree with you that this is probably an issue. I'm not quite sure what to use if not `encodeURIComponent` though.

**Comment by Voileexperiments** [comment]
I think escaping `'` and other characters according to RFC 3986 is perfectly fine: it's better to overestimate request URL length than to underestimate it. In the former case you're just making POST requests instead, which is not a big deal at all; while in the latter case it can cause the request to *fail completely*. I'd prefer making a bit more POST requests than to have no features rendered on the map because the request failed for dumb reasons.

**Comment by gavinr** [comment]
> I'd prefer making a bit more POST requests than to have no features rendered on the map because the request failed for dumb reasons.

That seems reasonable to me - thanks for sharing your perspective. Unless any other maintainers have concerns, I'd be willing to accept a PR that implements the apostrophe encoding.

**Comment by gavinr-maps** [comment]
Fixed in [v3.0.12](https://github.com/Esri/esri-leaflet/releases/tag/v3.0.12).
