### ISSUE TITLE
Nearby queries incorrectly sending param "inSr" instead of "inSR"

### ISSUE THREAD

**Issue by Voileexperiments** [Esri/esri-leaflet#1250]
I'm debugging a issue where a `nearby` query on a ArcGIS Enterprise feature layer does not work at all if it's initiated from leaflet (it either returns full result or empty), but works completely fine when testing on REST API page. After some squinting I discovered the only difference between two requests is that ArcGIS REST API page send `inSR=4326` while Leaflet sends `inSr=4326`, which caused the `nearby` query to fail.

[The correct param](https://developers.arcgis.com/rest/services-reference/query-feature-service-layer-.htm) is `inSR`. Using `inSr` works for ArcGIS Online (https://esri.github.io/esri-leaflet/examples/querying-feature-layers-2.html) because presumably it's more lax with request params case-sensitivity.

I think there are a total of two places that needs to be changed, and the fix should be easy(?):

https://github.com/Esri/esri-leaflet/blob/master/src/Tasks/Query.js#L97
https://github.com/Esri/esri-leaflet/blob/master/src/Tasks/Query.js#L213

**Comment by jwasilgeo** [comment]
@Voileexperiments thank you for the clear description and doing some research on what's going on. We'll take a look.

**Comment by jwasilgeo** [comment]
@Voileexperiments can you also tell us what version of ArcGIS Enterprise you are seeing this issue with?

**Comment by jwasilgeo** [comment]
Related to PR #1168 and its issue #1167 which focused on the `outSR` param.

**Comment by jwasilgeo** [comment]
This will be available the next time we publish a new release.
