### ISSUE TITLE
map.removeLayer() leaves tiles in map

### ISSUE THREAD

**Issue by jpankoke** [Esri/esri-leaflet#1256]
## Describe the bug

Starting with version 2.5.2 a layer that was created via `L.esri.tiledMapLayer` and then removed with `map.removeLayer()` will continue to show on the map. 

## Expected behavior

On using `map.removeLayer()` all tiles of the layer should be removed from the map.

## Actual behavior

The layer object itself is removed from the map object but the graphical status of the map does not change. The tiles of the removed layer are still shown.

## To Reproduce

I created jsfiddle to demonstrate the problem: https://jsfiddle.net/hrtxja7p/1/

If you click "Remove layer" the country and city names are still shown on the map. When clicking on "Print layers" you can see that the layer actually was removed from the map.

## Environment Information

- Version of Leaflet (`L.version`): 1.7.1
- Version of Esri Leaflet (`L.esri.VERSION`): 2.5.2 & 2.5.3
- Your OS: Windows
- Browser and Version: Firefox 84.0.2

Note: When using version 2.5.1 and below the problem does not occur.

**Comment by jwasilgeo** [comment]
@jpankoke thanks for the detailed info and debugging demo.

I can confirm in a quick test that this is not an issue at version 2.5.1. We'll have to investigate how the change introduced in 2.5.2 affects this behavior. https://github.com/Esri/esri-leaflet/blob/master/CHANGELOG.md#252---2020-12-29

**Comment by jwasilgeo** [comment]
@jpankoke we have a fix in place for this and it will be available the next time we publish a new release.

https://github.com/Esri/esri-leaflet/blob/master/CHANGELOG.md#unreleased

**Comment by jpankoke** [comment]
@jwasilgeo Thank you very much for fixing it so fast. Really appreciate it!

**Comment by jwasilgeo** [comment]
https://github.com/Esri/esri-leaflet/releases/tag/v3.0.1

ready to go!
