### ISSUE TITLE
Using custom basemap styles

### ISSUE THREAD

**Issue by zbubric** [Esri/esri-leaflet#1259]
**Is your feature request related to a problem? Please describe.**
I have a project based on esri-leaflet and would like to use view as arcgis:Imagery (containing both satelite image as well as street routes and names). As far as I can understand, there are three ‘Imagery’ styles of leaflet maps bit none of them contains street grid/names.

**Describe the solution you'd like**
Option to fine-tune basemap layers used in leaflet (e.g. Possibillity to define composite basemap layers and custom styles).

**Describe alternatives you've considered**
I presume that street map can be added as feature layer but, on some projects, it is actually a base layer without need to be able to disable/enable street grid (or community borders or whatever)

**Additional context**
I actually wanted just to ask a question on how to achieve this but, since there is bug/feature direction I didn’t want to post it as a bug. I’m quite new to esri so, if answer to my question is already mentioned in some docs, please, point me to a right direction.

**Comment by pmacMaps** [comment]
Not sure if it's what you're looking for, but I have a [CodePen demo](https://codepen.io/pmckinney/pen/EVGRJY) where I use the `L.featureGroup` to create a basemap that contains imagery and streets.

With this new ArcGIS Platform, if Esri Leaflet will natively support vector basemaps, there is a `arcgis-imagery-labels` that is available in the [Esri JS API](https://developers.arcgis.com/javascript/latest/api-reference/esri-Map.html#basemap).  But Esri staff will need to comment on this.

**Comment by gavinr** [comment]
I think what you're asking can be achieved through [esri-leaflet-vector](https://github.com/esri/esri-leaflet-vector):

1. Imagery with labels: https://jsbin.com/menizes/2/edit?html,output
2. Imagery, no labels: https://jsbin.com/menizes/3/edit?html,output
3. Labels only: https://jsbin.com/menizes/5/edit?html,output

We have not done a good job documenting all the basemap names that you can pass via `L.esri.Vector.vectorBasemapLayer(...)` - I'm sorry for that, we will add those soon. Here they are for now:

1. `ArcGIS:Imagery`
1. `ArcGIS:Imagery:Standard`
1. `ArcGIS:Imagery:Labels`
1. `ArcGIS:LightGray`
1. `ArcGIS:LightGray:Base`
1. `ArcGIS:LightGray:Labels`
1. `ArcGIS:DarkGray`
1. `ArcGIS:DarkGray:Base`
1. `ArcGIS:DarkGray:Labels`
1. `ArcGIS:Navigation`
1. `ArcGIS:NavigationNight`
1. `ArcGIS:Streets`
1. `ArcGIS:StreetsNight`
1. `ArcGIS:StreetsRelief`
1. `ArcGIS:Topographic`
1. `ArcGIS:Oceans`
1. `ArcGIS:Oceans:Base`
1. `ArcGIS:Oceans:Labels`
1. `OSM:Standard`
1. `OSM:StandardRelief`
1. `OSM:StandardRelief:Base`
1. `OSM:Streets`
1. `OSM:StreetsRelief`
1. `OSM:LightGray`
1. `OSM:LightGray:Base`
1. `OSM:LightGray:Labels`
1. `OSM:DarkGray`
1. `OSM-DarkGray:Base`
1. `OSM-DarkGray:Labels`
1. `ArcGIS:Terrain`
1. `ArcGIS:Terrain:Base`
1. `ArcGIS:Terrain:Detail`
1. `ArcGIS:Community`
1. `ArcGIS:ChartedTerritory`
1. `ArcGIS:ColoredPencil`
1. `ArcGIS:Nova`
1. `ArcGIS:ModernAntique`
1. `ArcGIS:Midcentury`
1. `ArcGIS:Newspaper`
1. `ArcGIS:Hillshade:Light`
1. `ArcGIS:Hillshade:Dark`

**Comment by zbubric** [comment]
Hi @gavinr 

First of all, thank you for a prompt reaction and provided examples, I will dig into them.
However, when reading through #1160 I found that leaflet-vector is officially deprecated and strongly not recommended for use in production?

**Comment by jwasilgeo** [comment]
@zbubric sorry for any confusion. We are reviewing and making sure our documentation and guidance is updated soon. We are not deprecating [the esri-leaflet-vector plugin](https://github.com/esri/esri-leaflet-vector) and just released a new version (v3) which @gavinr is referring to above.

**Comment by zbubric** [comment]
> @zbubric sorry for any confusion. We are reviewing and making sure our documentation and guidance is updated soon. We are not deprecating [the esri-leaflet-vector plugin](https://github.com/esri/esri-leaflet-vector) and just released a new version (v3) which @gavinr is referring to above.

Thx for clarification. I'll try it!

**Comment by jwasilgeo** [comment]
@zbubric thanks for your patience here. In case it helps continue to clarify anything for you, we just refreshed the docs pages and changelogs to reflect what's new at esri-leaflet v3.

Live examples and API docs:

- https://esri.github.io/esri-leaflet

Related repo changelogs:

- https://github.com/Esri/esri-leaflet/blob/master/CHANGELOG.md
- https://github.com/Esri/esri-leaflet-geocoder/blob/master/CHANGELOG.md
- https://github.com/Esri/esri-leaflet-vector/blob/master/CHANGELOG.md

And check out the ArcGIS for Developers pages focusing on esri-leaflet:

- https://developers.arcgis.com/esri-leaflet/
