### ISSUE TITLE
Is Esri Leaflet Available for Commercial Use without Purchasing an ArcGIS License?

### ISSUE THREAD

**Issue by timothycouchhsi** [Esri/esri-leaflet#1260]
Hello, Esri Leaflet maintainers,

I have read through your license terms, and I am unsure about some details. Here are some questions to clarify:

Is the requirement cited in the Terms section (“For most public apps, a free Developer Plan is sufficient. If you're going to generate revenue, you'll need to purchase either a paid Developer Plan or one of the products below”) applicable to every use case of Esri-Leaflet, or are there some use cases that would not require a Developer Plan or purchase of the cited Esri products?

Does purchasing an ArcGIS license depend upon the use of the ArcGIS Online map services as detailed in ArcGIS terms, or does this refer specifically to using the Esri Leaflet library, even with ArcGIS map servers not hosted by Esri? In other words, would a developer (who intends to generate revenue) need to purchase an ArcGIS license if they want to use Esri Leaflet even without using ArcGIS Online map servers?

Thank you for your time. I look forward to hearing from you soon.

**Comment by martinschneider** [comment]
I would like to echo this question. I want to use the Esri National Geographic map on a personal webpage. I'm considering running ads in the future which I assume might qualify as commercial use.

I signed up for a Developer Plan but it's not clear how to use it because you can include the map layers without specifying an API key.

Leaflet:

    L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/NatGeo_World_Map/MapServer/tile/{z}/{y}/{x}', { attribution: 'Tiles &copy; Esri &mdash; National Geographic, Esri, DeLorme, NAVTEQ, UNEP-WCMC, USGS, NASA, ESA, METI, NRCAN, GEBCO, NOAA, iPC'  }).addTo(map);

Esri Leaflet library:

    L.esri.basemapLayer('NationalGeographic').addTo(map);

In such a setup how would the free usage quota (1 million tiles) be verified?

If I use the above setup which additional steps are necessary to comply with the ToCs and the license:

a.) for non-commercial usage
b.) for commercial usage.

**Comment by jf990** [comment]
The terms have recently changed and no one has gotten around to updating the [Esri leaflet terms](https://github.com/esri/esri-leaflet#terms) section of the readme. we have new documentation for Esri leaflet at https://developers.arcgis.com/esri-leaflet/

The new/current terms are here: https://developers.arcgis.com/documentation/mapping-apis-and-location-services/licensing/license-location-services/

* you must license with either an [API key](https://developers.arcgis.com/esri-leaflet/#get-started) or the [OAuth login](http://esri.github.io/esri-leaflet/examples/arcgis-online-auth.html)
* commercial use is no longer considered, so as long as you use one of the two methods above you can deploy a commercial app.
* The developer subscription with the free Essentials plan now allows up to 2 million tile transactions https://developers.arcgis.com/pricing/
* You are going to be required to use the new basemap services, the older services you were using are going to eventually depreciate. see https://developers.arcgis.com/esri-leaflet/maps/change-the-basemap-layer/

we will try to get the documentation on https://github.com/esri/esri-leaflet updated, but we also have https://developers.arcgis.com/esri-leaflet/ which is new to go along with the recent updates.

**Comment by jwasilgeo** [comment]
Adding to what has already been mentioned above, I wanted to share that we just refreshed the docs pages and changelogs to reflect what's new at esri-leaflet v3. Thank you for your patience @timothycouchhsi @martinschneider.

Live examples and API docs:

- https://esri.github.io/esri-leaflet

Related repo changelogs:

- https://github.com/Esri/esri-leaflet/blob/master/CHANGELOG.md
- https://github.com/Esri/esri-leaflet-geocoder/blob/master/CHANGELOG.md
- https://github.com/Esri/esri-leaflet-vector/blob/master/CHANGELOG.md

And check out the ArcGIS for Developers pages focusing on esri-leaflet:

- https://developers.arcgis.com/esri-leaflet/
