### ISSUE TITLE
Documentation and Release Notes for 3.0?

### ISSUE THREAD

**Issue by slutske22** [Esri/esri-leaflet#1262]
Version 3.0 came out about a month ago and I see today we're moving on to 3.0.1.  I watched the new arcgis developers product launch, and I've dug around quite a bit in the esri-leaflet tutorials on the esri website.  But so far I don't see any official API docs about the new version.  There seem to be some big changes (`L.esri.Vector.vectorBasemapLayer` and the need for an api key where there wasn't before).  Can we expect a comprehensive docs update soon?

**Comment by gavinr** [comment]
Thanks for the question. It's definitely on our todo list to get the 3.0 changes better documented - sincere apologies if this has been challenging for you. Currently the best place to find examples of the v3.0 changes are on the [developers.arcgis.com site](https://developers.arcgis.com/esri-leaflet/). Also, the [README of esri-leaflet-vector](https://github.com/Esri/esri-leaflet-vector#esri-leaflet-vector-tile-plugin).

We realize that's not sufficient though and plan to update with better release notes and updates to https://esri.github.io/esri-leaflet. https://esri.github.io/esri-leaflet/ in particular is running on some old technology so it's slowing us down unfortunately.

**Comment by slutske22** [comment]
I know this is sort of a side-question, but my understanding was that `L.esri.Vector.layer` and `L.esri.Vector.basemap` were plugins for esri-leaflet, and experimental ones at that.  Are the new `L.esri.Vector.vectorBasemapLayer` and `L.esri.Vector.vectorTileLayer` components considered experimental?  They seem fairly well established / canonized in the few bits of documentation I'm seeing in the new esri developers site.

**Comment by jwasilgeo** [comment]
@slutske22 thank you for your patience on this. We are currently working on updating the https://esri.github.io/esri-leaflet doc site to include updated demos and API documentation for the v3 release.

To clarify, the esri-leaflet-vector plugin is no longer considered experimental at its new v3 release, and you are encouraged to use `L.esri.Vector.vectorBasemapLayer` or `L.esri.Vector.vectorTileLayer` if they meet your needs. I echo @gavinr's suggestions on where to find documentation and tutorial samples on this in the meantime.

**Comment by jwasilgeo** [comment]
Thanks for your patience @slutske22 and anyone else watching this issue conversation!

We just refreshed the docs pages and changelogs to reflect the esri-leaflet v3 changes introduced earlier in the year.

Live examples and API docs:

- https://esri.github.io/esri-leaflet

Related repo changelogs:

- https://github.com/Esri/esri-leaflet/blob/master/CHANGELOG.md
- https://github.com/Esri/esri-leaflet-geocoder/blob/master/CHANGELOG.md
- https://github.com/Esri/esri-leaflet-vector/blob/master/CHANGELOG.md

**Comment by slutske22** [comment]
Amazing.  Thank you guys for this update and this library!
