### ISSUE TITLE
Rendering Image Service with Color Ramp in Esri Leaflet

### ISSUE THREAD

**Issue by NickLacunha** [Esri/esri-leaflet#1267]
We are trying to use esri-leaflet to display this Image Service on a web application:

https://gis.dnrc.mt.gov/imagery/rest/services/SageGrouse/HQT_Mosaic/ImageServer/

The image service has a default grayscale symbology, but we're trying to use the renderingRule option of the L.esri.imageMapLayer method to use a different color ramp. The color ramp we want to display is essentially the inverse of the built-in "Red to Blue Diverging, Bright" color ramp. We've tried following the documentation in https://developers.arcgis.com/documentation/common-data-types/raster-function-objects.htm but cannot figure out how to configure the colors.

Here is how it should display:
![right](https://user-images.githubusercontent.com/26231929/114615664-ce79a380-9c5a-11eb-9e9b-9d699df5945a.PNG)

We assumed the colors were meant to be in HSVA format (could not find reference to color format in the documentation), and pulled the values out of ArcMap's color selector.

Here is some simple HTML demonstrating our attempt at building the color-ramp:

```<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" />
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>
    <script src="https://unpkg.com/esri-leaflet@3.0.1/dist/esri-leaflet.js"
        integrity="sha512-JmpptMCcCg+Rd6x0Dbg6w+mmyzs1M7chHCd9W8HPovnImG2nLAQWn3yltwxXRM7WjKKFFHOAKjjF2SC4CgiFBg=="
        crossorigin=""></script>
</head>

<body>
    <div id="map" style="min-height: 400px">

    </div>

    <script>

        var map = L.map('map').setView([46.8797, -110.3626], 7);

        L.esri.basemapLayer('Topographic').addTo(map);

        const options = {
            service: "WMS",
            transparent: true,
            version: "1.1.1",
            format: "image/png",
            info_format: "application/json",
            tiled: true,
            srs: "EPSG:4326"
        };
        options.layers = '0';
        options.opacity = .7;

        options.noData = "0";
        options.renderingRule = {
            "rasterFunction": "Colormap",
            "rasterFunctionArguments": {
                "colorramp": {
                    "type": "multipart",
                    "colorRamps": [
                        {
                            "type": "algorithmic",
                            "fromColor": [214, 62, 71, 255],
                            "toColor": [60, 25, 100, 255],
                            "algorithm": "esriCIELabAlgorithm"
                        },
                        {
                            "type": "algorithmic",
                            "fromColor": [60, 25, 100, 255],
                            "toColor": [3, 82, 84, 255],
                            "algorithm": "esriCIELabAlgorithm"
                        }
                    ]
                }
            }
        };

        options.url = "https://gis.dnrc.mt.gov/imagery/rest/services/SageGrouse/HQT_Mosaic/ImageServer";
        var hqtLayer = L.esri.imageMapLayer(options);
        hqtLayer.addTo(map);

    </script>
</body>

</html>

**Comment by gavinr** [comment]
Thanks for the question. I opened your example code, and it appears that Esri Leaflet is passing your options (`rendingRule`, `noData`, etc) through to the ImageService correctly:

![image](https://user-images.githubusercontent.com/209355/114727161-7eb7dc80-9d2d-11eb-8933-62a64d54e1e1.png)


So at this point it seems like your main challenge is tuning your `renderingRule` to have the ImageService generate your desired output. This place is not the best place to get that solved - the best place would probably be [GeoNet > Imagery](https://community.esri.com/t5/imagery-and-remote-sensing/bd-p/imagery-and-remote-sensing-questions), or [Esri Tech Support](https://support.esri.com/en/). Please try there - I'm sure they'll be able to help out with your ImageService-secific issue.

If you have a specific issue where Esri Leaflet is not passing through the parameters to the ImageService, please feel free to comment here or open a new issue. Thanks!
