### ISSUE TITLE
ImageryClarity - no tiles for level 14+ outside the US

### ISSUE THREAD

**Issue by mickeyjohn** [Esri/esri-leaflet#1282]
Hi,
Today, I found out 'ImageryClarity' tile layer does not have tiles images for level 14 and over any longer. This happens only for places outside of the US. Does any one know what was wrong?

Thank you very much.

**Comment by jwasilgeo** [comment]
@mickeyjohn in terms of esri-leaflet we're not sure about that. Can you perhaps check with some of these basemap content resources or discussion threads?

https://www.arcgis.com/home/item.html?id=ab399b847323487dba26809bf11ea91a

accessed from https://www.esri.com/arcgis-blog/products/imagery/imagery/world-imagery-clarity-a-clearer-view-of-the-world/

**Comment by mickeyjohn** [comment]
I checked here https://www.arcgis.com/apps/mapviewer/index.html?webmap=da10cf4ba254469caf8016cd66369157. ImageryClarity base layer still working. I guess they must made changes on the servers or endpoints used by the plugin.
