### ISSUE TITLE
addfeature event is not firing for layers with min zoom

### ISSUE THREAD

**Issue by main-kun** [Esri/esri-leaflet#1297]
## Describe the bug

I'm trying to add feature labeling to a layer with `minZoom` option following the docs example: https://esri.github.io/esri-leaflet/examples/labeling-features.html
When the zoom level decreases, `removefeature` event fires as expected and the labels are removed together with the markers. When zoom is increased again, markers come back but `addfeature` event does not fire so labels cannot be added back to the map.

## Expected behavior

- `addfeature` event fires when features are brought back on zoom level change

## Actual behavior

- `addfeature` does not fire after `removefeature` on zoom change

## To Reproduce

Please share and fill in the steps below to reproduce the behavior.

**THIS IS REQUIRED** - If you do not provide the steps for others to reproduce the issue you're seeing, it is impossible for them to assist you. Please create a [jsbin](https://jsbin.com/yewimat/edit?html,output) that demonstrates the problem and include the steps to see the issue:

[Example](https://jsbin.com/qulizusaju/edit?html,output)

1. Go to the map
2. Zoom out
3. Zoom back in
4. See that there is no `console.log` for the `addfeature` event and the labels are not brought back

## Environment Information

- Version of Leaflet (`L.version`): 1.7.1
- Version of Esri Leaflet (`L.esri.VERSION`): 3.0.3
- Your OS: [e.g. iOS] Mac OS
- Browser and Version [e.g. chrome 80.0, safari 12.1.1] Chrome 94.0

## Additional context

Add any other context about the problem here. If you're are *not* using the [CDN](http://www.jsdelivr.com/projects/leaflet.esri), please note what loading/bundling library you are using ([webpack](https://webpack.github.io/), [browserify](http://browserify.org/), [RequireJS](http://requirejs.org/))?

**Comment by gavinr** [comment]
I think there may be something unexpected happening with the "removefeature" event too. For example, in your jsbin, if youzoom out once, and then zoom out a few more times, the removefeature event still gets called (expected: should only be called once when the features went invisible).

**Comment by gavinr** [comment]
I've created a more general issue report to replace this one with a few more specifics on what I've found: #1298. Please follow that for updates.
