### ISSUE TITLE
Is information at wiki/FAQ#which-services-require-authentication valid?

### ISSUE THREAD

**Issue by vvoovv** [Esri/esri-leaflet#1333]
### Describe the bug

It's written at the wiki page https://github.com/Esri/esri-leaflet/wiki/FAQ#which-services-require-authentication:
```
Esri Basemaps are free to use and do not require authentication.
```

Is this information still valid? Is no authentication required to use ESRI Basemaps?

At the page https://developers.arcgis.com/faq/#licensing one can find:
```
both standard and enhanced endpoints require authentication with an API keys or OAuth 2.0
```

### Reproduction

not relevant

### System Info

```shell
not relevant
```

**Comment by patrickarlt** [comment]
The wiki is definitely wrong here. The developers site has the latest up to date information. I'll work on getting the wiki updated.

**Comment by vvoovv** [comment]
I am confused.

Now that section on wiki states:
```
Accessing public services hosted on ArcGIS Online or ArcGIS Enterprise does not require authentication.
```

Does using _Imagery_ base layer by ESRI in general require authentication?
Does using _Imagery_ base layer by ESRI with esri-leaflet require authentication?

**Comment by pmacMaps** [comment]
What I have found is that the vector tile basemaps from Esri/ArcGIS Online require an API key.  But the old, deprecated raster basemaps do not (but may contain outdated information).  Also, if you can find a REST endpoint for a basemap service, and that organization's terms of service or license do not prevent you from using that service, that also would not require and API key.

**Comment by vvoovv** [comment]
The legacy Imagery base layer seem to stop operating reliably on April 30.

There is an article [Open source developers: Time to upgrade to the new ArcGIS basemap layer service!](https://www.esri.com/arcgis-blog/products/developers/developers/open-source-developers-time-to-upgrade-to-the-new-arcgis-basemap-layer-service/) in the ESRI website.

**Comment by moan525** [comment]
你好，已收到邮件！谢谢！
