### ISSUE TITLE
Way to display Esri Vector Basemaps without mapbox-gl-js

### ISSUE THREAD

**Issue by dandormont** [Esri/esri-leaflet#1337]
### Describe the problem

In my application I have been successfully using Vector basemaps from the ArcGIS Living Atlas using esri-leaflet-vector. But I have been running into issues on certain browsers and some complications with some of the functionality, which seems to be due to the reliance on mapbox-gl-js. 

I admit this is a little vague because I'm not super familiar with how vector tile data really works, but I am wondering if there is  a way to show Esri vector basemaps on a Leaflet map without relying on mapbox-gl-js and instead using a plugin such as https://gitlab.com/jkuebart/Leaflet.VectorTileLayer/ that appears to be more "native" to Leaflet.

### Describe the proposed solution

a way of displaying Esri vector basemaps in a Leaflet map without the use of mapbox-gl-js.

**Comment by patrickarlt** [comment]
@dandormont unfortunately https://gitlab.com/jkuebart/Leaflet.VectorTileLayer/ isn't a complete solution. There are several limitations that we cannot overcome:

* It renders everything in a 2d canvas without hardware acceleration.
* No support for points. See [limitations](https://gitlab.com/jkuebart/Leaflet.VectorTileLayer/#limitations)
* No support for sprites or text layers (as far as I can tell in the code)
* No support for interpolated stops in types (i.e. use color X at zoom Y)

Ideally we need full support for all of this the render the basemaps. This really is a non-starter. We will migrate to MapLibre in the future which would be a path to resolve some of these.

Feel free to open up a new issue to discuss the issues you are having with MapBox GL JS and specifically what browsers you are having issues with.

**Comment by dandormont** [comment]
@patrickarlt thanks for replying. I wasn't familiar with MapLibre, will check that out.
The specific issue I remember running into was not being able to extract feature properties from a vector tile layer, but that isn't really a basemap question and I believe there's already an issue for it in esri-leaflet-vector
