### ISSUE TITLE
Popups broken with esri-leaflet 3.0.10 and leaflet 1.7.1

### ISSUE THREAD

**Issue by gavinr** [Esri/esri-leaflet#1354]
### Describe the bug

When we fixed #1348 via PR #1350, it fixed the popups for Leaflet v1.9.3, but we inadvertently broke popups when using older versions of Leaflet, for example Leaflet@1.7.1.

### Reproduction

This issue is specifically about the top-right quadrant here - we expect popups to work for Leaflet 1.7.1 and Esri Leaflet 3.0.10, but they are broken.

|                | Esri Leaflet 3.0.9                                                | Esri Leaflet 3.0.10 (fix for #1348 - PR #1350)                    |
|----------------|-------------------------------------------------------------------|-------------------------------------------------------------------|
| Leaflet 1.7.1  | Popups work ✅ - https://jsbin.com/binicekole/1/edit?html,output   | <pre>**Popups broken** ❌ </pre>  https://jsbin.com/kuliliqaga/3/edit?html,output |
| Leaflet 1.9.3 | Popups broken ❌ - https://jsbin.com/gabobuxuto/1/edit?html,output | Popups work ✅ - https://jsbin.com/lumofuwoga/1/edit?html,output   |

### System Info

```shell
Leaflet version 1.7.1
Esri Leaflet version 3.0.10
```

**Comment by gavinr-maps** [comment]
Since nobody else has had this issue, closing.
