### ISSUE TITLE
Points on the map are not being shown when zoomed in

### ISSUE THREAD

**Issue by makahmad** [Esri/esri-leaflet#1356]
### Describe the bug

Points on the map are not being shown when zoomed in. This app has been working fine for almost 10 years now. The code hasn't been changed so curious if anyone knows why the points would just not appear anymore.

@jgravois you helped me with this many years ago 

### Reproduction

1. go to https://www.webapps.nwfsc.noaa.gov/data/map
2. search for dover sole in the upper left species field
3. click on Trawl in the Layers menu then Catch
4. try to zoom in to any point that's shown
5. As you zoom in the points vanish however when you click around that region, the tooltip for that point opens up with the data. So the points
<img width="1310" alt="1" src="https://user-images.githubusercontent.com/19351474/221803501-a1a6cb85-503e-40a4-af86-e24be8f0ef30.png">
<img width="1196" alt="2" src="https://user-images.githubusercontent.com/19351474/221803534-3868824b-c9e2-4876-8a61-18e6376480e8.png">
<img width="1558" alt="3" src="https://user-images.githubusercontent.com/19351474/221803557-6a1f55ae-bd95-4549-9d5e-cc48aee5685c.png">
 are there but invisible

### System Info

```shell
Leaflet version: 1.3.1
Esri Leaflet version: 2.4.1
Browser (with version): Chrome 110.0.5481.177
OS/Platform (with version): MacOS Ventura
```

**Comment by jgravois** [comment]
> As you zoom in the points vanish however when you click around that region, the tooltip for that point opens up with the data.

not sure what to tell you. i can't repro the behavior you describe in Safari.
![Screen Shot 2023-03-01 at 9 35 23 AM](https://user-images.githubusercontent.com/3011734/222218178-82b1bb6f-7d26-4f38-97bf-406cb9310a98.png)

my best guess is that maybe someone republished the map service using transparent symbols for that layer and then reverted the change?

**Comment by makahmad** [comment]
Interesting @jgravois did you use a Windows or Mac? I just tried Safari and can't see the points.
Glad that in some configuration people can see the points

**Comment by jgravois** [comment]
> did you use a Windows or Mac?

OSX 12.6.3

(kinda wishing i was rockin [5.1 on windows](https://www.intowindows.com/how-to-install-safari-browser-on-windows-10/) though)

**Comment by makahmad** [comment]
Interesting ok, yeah I'm on OSX 13.2.1 oh well....weird how safari works for you but didn't work for me

**Comment by gavinr** [comment]
@makahmad we are having a hard time understanding the issue. Can you please post a simpler minimal reproductions case for this? Maybe in codepen using this template: https://jsbin.com/yewimat/edit Thanks!

**Comment by makahmad** [comment]
@gavinr I'm not sure how to reproduce it without copying pasting most of the code from here https://www.webapps.nwfsc.noaa.gov/data/view2/view2.js 

I made this app 6+ years ago ....if there's nothing we can do, I can close it. Suspect @jgravois 's comment https://github.com/Esri/esri-leaflet/issues/1356#issuecomment-1450566261 is accurate but not sure how to even debug for that.
