### ISSUE TITLE
Documentation for tiledmapLayer is not strictly accurate. Can use alternatives to epsg:3857

### ISSUE THREAD

**Issue by scaddenp** [Esri/esri-leaflet#1357]
### Description

The docs state: "Your map service must be published using the [Web Mercator Auxiliary Sphere tiling scheme (WKID 102100/3857)](https://epsg.io/3857) and the default scale options used by Google Maps, Bing Maps and [ArcGIS Online](https://services.arcgisonline.com/arcgis/rest/services). Esri Leaflet will not support any other spatial reference for tile layers."

This is not strictly true. Other epsg can be used but you have to also use the proj4leaflet plugin. Many tiled layers are published in NZ with EPSG:2193 (a national grid) and I consume these with leaflet without issue provided they use the same tilesize. (and working on a fix for that too).

**Comment by jgravois** [comment]
yup. there's an example here: https://developers.arcgis.com/esri-leaflet/samples/non-mercator-projection/

my impression is not that what you're saying isn't possible, just that they don't take responsibility for it working correctly.

**Comment by gavinr** [comment]
@scaddenp thank you for the report. In your original post you said, "The docs state". What is the URL to the page from where you got that wording?

**Comment by scaddenp** [comment]
On the docs for tiled map layer. [https://developers.arcgis.com/esri-leaflet/api-reference/layers/tiled-map-layer/]

**Comment by patrickarlt** [comment]
@scaddenp I propose we update to this:

> Your map service should be published using the [Web Mercator Auxiliary Sphere tiling scheme (WKID 102100/3857)](https://epsg.io/3857) and the default scale options used by Google Maps, Bing Maps and [ArcGIS Online](https://services.arcgisonline.com/arcgis/rest/services). Esri Leaflet does not officually support any other spatial reference for tile layers, however unofficial support maybe obtained though the the [Proj4Leaflet](https://github.com/kartena/Proj4Leaflet) plugin as shown in the [projection samples].

Can you write up a sample showing the use of a non-mercator tileset that we can add to the samples? Currently we only show feature layers and dynamic map layers.

**Comment by scaddenp** [comment]
Should be able to  but not immediately. Last weeks of FY has huge pressure on...

**Comment by pmacMaps** [comment]
I have a [CodePen sample ](https://codepen.io/pmckinney/pen/ambpgj) that uses Proj4Leaflet and a tiled map service using state plane projection.

**Comment by gavinr-maps** [comment]
Thanks @pmacMaps! We are working on updating the warning language [here](https://developers.arcgis.com/esri-leaflet/api-reference/layers/tiled-map-layer/) and updating the non-mercator projection samples.

**Comment by gavinr-maps** [comment]
The documentation has been updated:

https://developers.arcgis.com/esri-leaflet/api-reference/layers/tiled-map-layer/

![image](https://github.com/Esri/esri-leaflet/assets/137905994/4e0851f7-9343-4968-8627-7c158c75db88)

... and samples for Tile Layer, Feature Layer, and Dynamic Map Layer are now available:
https://developers.arcgis.com/esri-leaflet/samples/non-mercator-projection/
![image](https://github.com/Esri/esri-leaflet/assets/137905994/69a3abbc-76ef-45cb-a9c8-1042b97a6511)
