### ISSUE TITLE
Dynamic Map Layer layerDefs force POST

### ISSUE THREAD

**Issue by EnasDiabYouxel** [Esri/esri-leaflet#1363]
### Describe the bug

When sending a query string that is around 4 KB size (4000 characters), The '/export' API get called and return status 200 OK, but it doesn't return the image generated
is there a limitation on the call & what can I do ?
if I made it a POST call not GET, this will fix the issue? and how can I make it a POST call?

### Reproduction

https://jsbin.com/tiqomapaju/6/edit?html,output

### System Info

```shell
"leaflet": "^1.9.3",
"esri-leaflet": "^3.0.10",
```

**Comment by EnasDiabYouxel** [comment]
I found that if I'm using f:'json' when getting the image the call method converts to POST if it is large and the server responds with the object contains the href image path when call the image link to display the server respond with noting, although when taking the link and open it in the browser it displays the image

**Comment by EnasDiabYouxel** [comment]
I found that the server firewall blocked the request

**Comment by gavinr** [comment]
@EnasDiabYouxel Are you saying this was an issue with your firewall and not with Esri Leaflet? If so we'll close this issue. Thanks!
