### ISSUE TITLE
Husky update

### ISSUE THREAD

**Issue by gavinr-maps** [Esri/esri-leaflet#1369]
### Describe the bug

We are getting a warning during the build:
![image](https://github.com/Esri/esri-leaflet/assets/137905994/6e459376-50b4-4f64-b50b-40c65ccd8593)

### Reproduction

` git commit -m "build $VERSION"`

### System Info

```shell
Latest
```

**Comment by Richarizaard** [comment]
@gavinr-maps I created #1374 to update how we define our pre-commit in our package.json.
