### ISSUE TITLE
From ArcGIS Enterprise: Zooming in at maximum extent the layer stops loading

### ISSUE THREAD

**Issue by isaacviel** [Esri/esri-leaflet#1370]
### Describe the bug

Zooming in at maximum extent the layer stops loading

### Reproduction

1. Set up ArcGIS Data Appliance as a new user with ArcGIS Enterprise
2. Unpack the components of ArcGIS Data Appliance
3. Launch ArcGIS Pro, sign in to ArcGIS Enterprise and open the 'Share Package' geoprocessing tool
4. Fill in the input parameter as follows:
5. - Input package : Provide the path of vector tile package
6. - Summary : Esri Vector Basemap for ArcGIS Data Appliance 2023
7. Run the tool and share the package to Portal
8. Navigate to item details page of this vector tile package in Portal and click 'Publish' to publish hosted tile layer
9. In ArcGIS Pro, add a toolbox named 'VectorStylePublisher.tbx' and open the geoprocessing tool 'Vector Style Publisher'
10. Fill in the input parameter as follows:
11. - Folder containing vector styles : Provide the folder location of vector styles
12. - Vector Tile Service URL : Provide the REST URL of hosted tile layer published in the previous steps.
13. Run the tool to publish vector styles to Portal
14. Create a web map using anyone of the hosted tile layer and add it as a basemap
15. Try to zoom in at maximum extent and note that the tiles are visible without any issues (NOTE: Similar behavior is observed in ArcGIS JavaScript Viewer)
16. Now, add this webmap to Esri Leaflet application and upon zooming in at maximum extent the layer stops loading (i.e. some tiles load whereas some tiles are blank and do not load)

### System Info

```shell
- ArcGIS Enterprise 11.1 (Windows Server 2022 & Windows Server 2019)
- ArcGIS Enterprise 10.9.1 (Windows Server 2022 & Windows Server 2019)
- ArcGIS Data Appliance 2023
- Esri Leaflet application
```

### Additional Information

- Issue occurs only with hosted tile layers coming from ArcGIS Enterprise
- Whereas hosted tile layers published to ArcGIS Online works as expected

Filed for jpdoherty@esri.com

**Comment by gavinr-maps** [comment]
This bug was assigned to the incorrect team. This is not an issue with Esri Leaflet as far as we currently understand. Closing.
