### ISSUE TITLE
esri-leaflet api required and freely allowed (terms of use)?

### ISSUE THREAD

**Issue by Danny-dK** [Esri/esri-leaflet#1388]
### Description

I have been trying to figure out for a week now whether esri basemap World Imagery is free to use. Many users on online platforms indicate different things and uncertainty. Within R in the leaflet library, the World Imagery map can be loaded without providing any api key which is also visible at https://leaflet-extras.github.io/leaflet-providers/preview/#filter=Esri.WorldImagery. The site https://developers.arcgis.com/esri-leaflet/ indicates you need an api key, while your readme indicates it only requires attribution, while https://www.arcgis.com/home/item.html?id=10df2279f9684e4a9f6a7f08febac2a9 indicates it falls under the master license agreement, while https://downloads2.esri.com/arcgisonline/docs/tou_summary.pdf indicates you can only use it through esri software. This esri news https://www.esri.com/news/arcnews/spring11articles/new-arcgis-online-content.html indicated "As of the end of January 2011, ArcGIS Online basemaps published and hosted by Esri have been freely available to all users for internal or external use. This means that users have free access to ArcGIS Online basemaps including World Imagery, World Street Map, World Topographic Map, USA Topographic Maps, and DeLorme World Basemap, as well as demographic, reference, and other specialty maps [......] Users who do not have these products can still access ArcGIS Online basemaps through other clients and applications, including ArcGIS Mobile SDKs and ArcGIS Web APIs."

If I can use and load these maps without any API key (through the rest service https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer), how is esri tracking validity of use? Can I use the maps for personal use? Please clarify the documentation on this? Online and in this repo's closed issues list, it apparently is extremely confusing whether you can use these maps without an arcgis account and through other clients.

**Comment by pmacMaps** [comment]
I've found that the raster-based basemaps can be used without requiring an API key.  But the vector basemaps require an API key.  I'm not an Esri employee, so I'm just sharing my experience.

**Comment by Danny-dK** [comment]
Thanks for sharing! I also found that the raster-based one can be used without an API key (which I was happy with). Hoping it is allowed to use for personal usage without any license limitation.

**Comment by jf990** [comment]
Thanks @Danny-dK as you note over the various documentation sources the licensing story is confusing.  The article from 2011 is out of date and doesn't represent the current licencing requirements. You uncovered the two most relevant articles:

- [World Imagery item page](https://www.arcgis.com/home/item.html?id=10df2279f9684e4a9f6a7f08febac2a9) points to **Use** and **Terms of use**. _You can add this layer to the ArcGIS Online Map Viewer, ArcGIS Desktop, or ArcGIS Pro._ which are Esri softwares, and the Terms of use.
- Esri provides a [Summary](https://downloads2.esri.com/arcgisonline/docs/tou_summary.pdf) of the Terms of Use regarding basemap service usage as follows:

> Use with Esri software and comply with its terms of use. If you do not have Esri software, you must purchase an ArcGIS or Developer subscription

This means you can use the basemap service either with existing Esri software, or if you are building your own app, a subscription to an Esri product, together with authentication (e.g. an API key.) Therefore the instructions on https://developers.arcgis.com/esri-leaflet/ are correct and developers should follow that.

An Esri developer subscription is free and gives you access to 2 million tiles per month.

**Comment by Danny-dK** [comment]
@jf990 But why should I sign up for a subscription? I don't need an api key or any form of authentication to access the ESRI World imagery. I can use leaflet in R, create a leaflet map requesting the ESRI world imagery basemap, and save as an html file, and I can use the map without ever having to authenticate in any way. How would ESRI or AcGis know about any user using the map without ESRI software or an ESRI developer subscription (as there is no indication that you need any information from a subscription to be included in your code)? On the documentation (https://developers.arcgis.com/esri-leaflet/authentication/apikeys/) it says an API key is required "in order to access the service(s) or content item(s) required in your application", which would indicate that without an API key you can't access the services, which (again) is not true.

**Comment by Danny-dK** [comment]
Added reprex can be found at https://rstudio.github.io/leaflet/articles/basemaps.html. Which is the exact same thing I can replicate locally and save as working html without ever having to authenticate or using an API. Whereas the previous link shows the STADIA maps as not functioning due to lack of an API.

Don't get me wrong. I like that it is completely open source and open accessible, I think that is just very nice. But I want to make sure that I'm not doing anything wrong (and I'm only using it for myself personally without ever wanting it to be put online anywhere or be used in any app or software, only be able to open it on my own laptop; just tracking my own travels over the world).

**Comment by Danny-dK** [comment]
@ajturner Just throwing a name out there. Do you know anyone that has an answer to my question? To summarize:
- ESRI World Imagery at https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer can be reached without the requirement of an API (as in I can create a map and save as working html without ever having to supply an API key). 
- Is this according to terms of use for personal use (not business or any commercial use)?
- I'm not talking about you need an API key to access the map content, as I can access it without an API key.

**Comment by Danny-dK** [comment]
I have been in contact with the Dutch branch of customer service (who btw don't hide their email customer service behind a login like the American version does). They told me that although the mapserver with amongst others the Esri WorldImagery map will be transitioned to be locked behind an API key. They just haven't had the time to do so. So although an API key is not required right now, it will be in the future, and the license indicates that the API key is required.
