### ISSUE TITLE
"Powered by Esri" does not show up in some basemaps starting from v3.0.11

### ISSUE THREAD

**Issue by sherylgiovanni** [Esri/esri-leaflet#1396]
### Describe the bug

"Powered by Esri" does not appear at the footer of the map when displaying static basemap tiles or custom basemap style in Esri Leaflet v3.0.11, 3.0.12, and 3.0.13.

It used to appear in Esri Leaflet v3.0.10.

"Powered by Esri" still appears when displaying basemap styles service.

![image](https://github.com/user-attachments/assets/a79007bd-1d35-4832-afb9-95c5821db647)

### Reproduction

Display static basemap tiles (need access token)
Try this with 3.0.12 and 3.0.10 and see the difference in the footer.
https://codepen.io/sherylgiovanni/pen/emOOQeo?editors=1010

Display custom basemap style (need access token)
Try this with 3.0.12 and 3.0.10 and see the difference in the footer.
https://codepen.io/sherylgiovanni/pen/ogvvQpx?editors=1010

### System Info

```shell
leaflet@1.9.4
esri-leaflet@3.0.12
```

### Additional Information

cc @alaframboise @gavinr-maps @patrickarlt @gowin20

**Comment by gavinr-maps** [comment]
Thanks for logging this issue. If this started happening at Esri Leaflet v3.0.11, it was probably introduced in this PR https://github.com/Esri/esri-leaflet/pull/1366 since that release only contained that PR. I can look into this.

**Comment by gavinr-maps** [comment]
@sherylgiovanni 

- for the first case ("Display static basemap tiles") can you please log a bug here: https://github.com/Esri/esri-leaflet-static-basemap-tile/issues
- for the second case, I have logged a bug here: https://github.com/Esri/esri-leaflet-vector/issues/228

and then we can close this issue. Thanks!

**Comment by gavinr-maps** [comment]
@sherylgiovanni 

- for the first case ("Display static basemap tiles"), I have logged a bug here: https://github.com/Esri/esri-leaflet-static-basemap-tile/issues/2
- for the second case, I have logged a bug here: https://github.com/Esri/esri-leaflet-vector/issues/228

and now we can close this issue, and will track in those others. Thanks!
