### ISSUE TITLE
Plugin Candidate: Support ArcGIS renderer objects

### ISSUE THREAD

**Issue by patrickarlt** [Esri/esri-leaflet#181]
As mentioned by @paulhedlund in https://github.com/Esri/esri-leaflet/issues/179 it would be be nice to be able to use renderers from the service definition.

I think this is to large to be included in the Esri Leaflet core. It might work as a separate repo that uses the `L.esri.Renderers` namespace.

Below is an example of what this might look like...

```js
var url = "http://...";

L.esri.get(url, function(response){

	var renderer = L.esri.Renderer.fromJSON(response.drawingInfo.renderer);

	var featureLayer = new L.esri.FeatureLayer(url, {
		style: function(feature){
			return renderer.render(feature);
		}
	}).addTo(map);

});
```

Given the scope of this I will not be able to work on this. It will be up to the community to implement this if there is interest.

**Comment by jgravois** [comment]
closing this, as repo is now live.
