### ISSUE TITLE
Plugin Candidate: Loading WebMap JSON

### ISSUE THREAD

**Issue by patrickarlt** [Esri/esri-leaflet#182]
There was a lot of discussion in https://github.com/Esri/esri-leaflet/issues/33 about supporting the [ArcGIS Web Map JSON Format](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Web_map_format/02r30000004n000000/). While there is a lot of interest in this feature the spec its ultimately too large to implement in Esri Leaflet.

However this is a good candidate for a separate plugin that could implement `L.esri.mapFromJSON(containerId, mapId)` and be included separately.

**Comment by ynunokawa** [comment]
I roughly made a mock-up to load and display ArcGIS WebMap into Leaflet. Please see the repo.
https://github.com/ynunokawa/L.esri.WebMap

**Comment by jgravois** [comment]
awesome work @ynunokawa!  

i'll be able to take a deeper look soon.  i'd like to add a link to your repository in the [plugins](http://esri.github.io/esri-leaflet/plugins/) page of the doc site.  i'd also be great to include a sample along with our others [here](http://esri.github.io/esri-leaflet/examples/)

**Comment by ynunokawa** [comment]
@jgravois Thanks!
You're welcome to add a link to my repo and a sample into your doc site. :smiley:
