### ISSUE TITLE
Investigate richer layer stacking options with Leaflet 0.8

### ISSUE THREAD

**Issue by patrickarlt** [Esri/esri-leaflet#208]
`L.Map` in Leaflet 0.8 gives us a `createPane` method which might allow richer options for solving layer stacking that have come up before in https://github.com/Esri/esri-leaflet/pull/207 and https://github.com/Esri/esri-leaflet/issues/149.

**Comment by jgravois** [comment]
once `1.0-beta1` is tagged, we should take another look at what would be necessary in the API to ensure developers can do something like below and get control over the draw order as easily as possible.

```javascript
var polygons = L.esri.featureLayer('http://services.arcgis.com/uCXeTVveQzP4IIcx/arcgis/rest/services/PDX_Neighborhoods_Styled/FeatureServer/0').addTo(map);
 
 var lines = L.esri.featureLayer('http://services.arcgis.com/uCXeTVveQzP4IIcx/arcgis/rest/services/PDX_Rail_Lines_Styled/FeatureServer/0').addTo(map);
  
var points =  L.esri.featureLayer('http://services.arcgis.com/uCXeTVveQzP4IIcx/arcgis/rest/services/PDX_Rail_Stops_Styled/FeatureServer/0').addTo(map); 

>>points display on top of polylines on top of polygons, rather than whichever comes back last drawing on top (which is very likely to be the most complicated geometry)
```

**Comment by benstoltz** [comment]
@patrickarlt I'd love to get working on this. Have you started working on this, or is it fair game?

**Comment by jgravois** [comment]
go for it @benstoltz.

**Comment by benstoltz** [comment]
@jgravois Sounds good. Should I work out of the 1.0 branch?

**Comment by jgravois** [comment]
its always best to use a discrete named branch for your work.  in this case, you'd want your named branch to be tracking the `1.0` branch as opposed to `master`

http://git-scm.com/docs/git-checkout

**Comment by patrickarlt** [comment]
@benstoltz Fantastic to hear you want to work on this. Yes please base any work on the [leaflet-1.0 branch](https://github.com/Esri/esri-leaflet/tree/leaflet-1.0) since nothing will work otherwise.

The API for this will be a little complex since it involves use of the new `map.createPane` API. Working from @jgravois example above the ideal order from top to bottom is points, lines, polygons.

```js
var map = L.map('map').setView([45.526, -122.667], 13);

var polygonPane = map.createPane('polygons');
polygonPane.style.zIndex = 5;

var linePane = map.createPane('lines');
linePane.style.zIndex = 6;

var pointPane = map.createPane('points');
pointsPane.style.zIndex = 7;

var polygons = L.esri.featureLayer('http://services.arcgis.com/uCXeTVveQzP4IIcx/arcgis/rest/services/PDX_Neighborhoods_Styled/FeatureServer/0', {
  pane: 'polygons'
}).addTo(map);
var lines = L.esri.featureLayer('http://services.arcgis.com/uCXeTVveQzP4IIcx/arcgis/rest/services/PDX_Rail_Lines_Styled/FeatureServer/0'{
  pane: 'lines'
}).addTo(map);
var points =  L.esri.featureLayer('http://services.arcgis.com/uCXeTVveQzP4IIcx/arcgis/rest/services/PDX_Rail_Stops_Styled/FeatureServer/0'{
  pane: 'points'
}).addTo(map); 
```

This means that we will have to pass the `pane` option through to whatever we create inside all the layers (L.Polyline, L.Polygon, L.Marker, L.ImageOverlay, ect...).

I also have an issue open for a wider z-index spread on the default panes https://github.com/Leaflet/Leaflet/pull/3591

**Comment by patrickarlt** [comment]
@benstoltz let me know if you are still up for this. If not I'll do it as a part of my 1.0 upgrade work.

**Comment by benstoltz** [comment]
@patrickarlt I think I am, though I'm not fully up on how esri-leaflet inherits from Leaflet. I would be needing to add panes for polygons, lines, and points correct? Rather than lumping them in with just the mapPane?

**Comment by patrickarlt** [comment]
@benstoltz I think the best way would be to let users figure out how to create the pane and just pass the option through to whatever actually gets drawn.

Right now there is a mix of inheritance and encapsulation depending on what type of layer you are looking at:

* `BasemapLayer` or `TiledMapLayer`: Inherits from `L.TileLayer` this shouldn't need any modifications for `pane`
* `FeatureLayer`: Inherits from `L.esri.FeatureManager` but creates its own internal `L.Polyline`, `L.Polygon` objects or uses `pointToLayer` to create `Marker` or `CircleMarker` options
* `DynamicMapLayer` or `ImageMapLayer`: Inherits from `L.esri.RasterLayer` which manages a set of `L.ImageOverlay` objects which would need `pane` passed to them.

**Comment by patrickarlt** [comment]
@benstoltz I implemented this since it was also needed for a few other 1.0 changes.

**Comment by benstoltz** [comment]
@patrickarlt Gotcha.
