### ISSUE TITLE
Sample showing filter on featureLayer

### ISSUE THREAD

**Issue by rowanwins** [Esri/esri-leaflet#214]
Hi there,

I was wondering if you could provide me with an example showing how you'd filter a feature layer.

For example I'm trying to filter the parks layer by PROPERTYID in the attribute table but I'm an absolute javascript noob.

Thanks,
Rowan

```
L.esri.featureLayer("http://services.arcgis.com/rOo16HdIMeOBI4Mb/arcgis/rest/services/Parks_pdx/FeatureServer/0", {
       filter: function (feature){
        return 'PROPERTYID = "127"'},
       style: function (feature) {
          return { color: "#70ca49", weight: 2 };
        },
        onEachFeature: function (feature, layer) {
          layer.bindPopup(L.Util.template(template, feature.properties));
        }
      }).addTo(map);
```

**Comment by jgravois** [comment]
i'm not sure why, but `filter` doesn't work as a constructor option anymore.

either way, it makes more sense to fetch _only_ the features from the service that you want (using the [`where`](http://esri.github.io/esri-leaflet/api-reference/layers/feature-layer.html#options) constructor option) than it does to filter on the client anyway.

```js
L.esri.featureLayer({
  url: "http://sampleserver6.arcgisonline.com/arcgis/rest/services/Census/MapServer/3",
  where: "STATE_NAME = 'Kansas'",
}).addTo(map);
```

Querying features [live demo](http://esri.github.io/esri-leaflet/examples/querying-feature-layers-1.html)
