### ISSUE TITLE
Latest ArcGis jsapi library resamples images, this doesn't

### ISSUE THREAD

**Issue by tsungg** [Esri/esri-leaflet#240]
Latest versions of the ArcGis jsapi seem to be able to resample tiles at high zoom levels to prevent the annoying "no data available" images being shown to users if they are not available; but this library doesn't seem to have this capability. Are there any plans to add this feature? I'm not actually sure how the ArcGis library detects when it's received a "no data" image, so I've no idea how hard this might be.

best

**Comment by patrickarlt** [comment]
Closing this because it will likely be too difficult to implement and with vector basemaps coming soon, this should be going away.

**Comment by jgravois** [comment]
found a pretty cool plugin that resamples tileLayers this morning...

https://github.com/ghybs/Leaflet.TileLayer.Fallback
