### ISSUE TITLE
Document basics of building the documentation site and writing doc for contributors

### ISSUE THREAD

**Issue by patrickarlt** [Esri/esri-leaflet#277]
Mentions by @rdjurasaj-usgs.

**Comment by jgravois** [comment]
i can try and tackle this.

**Comment by jgravois** [comment]
reminder that i was surprised @NoashX needed to install Ruby...

**Comment by jgravois** [comment]
obviously there's still room for improvement, but ruby is no longer required and we've shared general steps for running the site so i'm going to go ahead and close.

https://github.com/esri/esri-leaflet-doc#instructions
