### ISSUE TITLE
Attribution from dynamic map layer is not displayed on map

### ISSUE THREAD

**Issue by rhewitt22** [Esri/esri-leaflet#333]
The documentation for [L.esri.dynamicMapLayer](http://esri.github.io/esri-leaflet/api-reference/layers/dynamic-map-layer.html#options) suggests that this layer type extends [L.imageOverlay](http://leafletjs.com/reference.html#imageoverlay), which accepts an attribution option.  When I include this option it is not displayed in the bottom right hand attribution div.

```
var url = 'https://www.sciencebase.gov/arcgis/rest/services/Catalog/512cf142e4b0855fde669828/MapServer'
L.esri.dynamicMapLayer(url, {
    attribution: 'MSU, USGS, NFHP'
}).addTo(map);
```

**Comment by blomm** [comment]
Was this ever fixed? I can't see attribution as an option for L.esri.Layers.DynamicMapLayer, and I don't see DynamicMapLayer attribution referenced in the changelog.

**Comment by blomm** [comment]
Actually, I see now that it is an option in the parameters, it's just the api reference is a bit out of date I guess.

**Comment by jgravois** [comment]
@bloom thanks for pointing out the problem!

i updated the doc in 5377e52.  we will be pushing a whole bunch of Leaflet 1.0.0b1 changes to the live site soon so the correction will appear after #620 is merged to `gh-pages`
