### ISSUE TITLE
Basemap Usage

### ISSUE THREAD

**Issue by ghost** [Esri/esri-leaflet#338]
Is there restrictions on basemap usage with esri-leaflet? Does it matter if its commercial use verses personal? Is there an upper limit?

As best I can tell, you do not require an arcgis online account to view basemaps, but the other services do require an authenticated account.

There appears to be no mention of the terms of use.

**Comment by php4fan** [comment]
What do I have to do in order to see my usage data??

https://community.esri.com/t5/esri-leaflet-questions/can-t-see-any-usage-data/m-p/1153772
