### ISSUE TITLE
Ability to Create Legend from Services

### ISSUE THREAD

**Issue by davidrs** [Esri/esri-leaflet#389]
Here is a gist of some JavaScript and HTML template for creating a legend from a service endpoint. I'm not sure if there is enough demand for this to be a possible plugin, but I thought I'd share in case.

https://gist.github.com/davidrs/e3dc314c7e230f40b813

**Comment by rowanwins** [comment]
Gday @patrickarlt  and @jgravois ,

I've taken a first stab at this. At the moment I've just get it setup as an esri-leaflet task in 
[this fork](https://github.com/rowanwins/esri-leaflet) but I guess it could be split out into its own plugin if thats the way you wanted to go. In the root folder you'll see a file called legend.html which provides a sample of it in action.

There is some additional work that could be done to improve it such as only retrieving the legend items for the chosen layers but I thought I'd send this through as a few stab and get your thoughts.

Cheers
Rowan

**Comment by w8r** [comment]
@rowanwins, nice job!

**Comment by patrickarlt** [comment]
@rowanwins this looks nice! I still think legends should be a separate plugin with a few parts.

* `legend` method on `MapService` - you already did this
* `legend` method on `DymanicMapLayer` - easy now that you did this
* `L.esri.Controls.Legend` which accepts an array of layers would probably be the way most people would want to go.

Maybe @jgravois would have time to help you turn this into a separate plugin? I can assist with the API design and general direction but have a pretty limited ability to help beyond that.

**Comment by w8r** [comment]
@patrickarlt, @rowanwins, guys, in the meanwhile I created this https://github.com/w8r/esri-leaflet-legend
It's a work in progress in what regards symbol rendering, actually I got stuck there

**Comment by w8r** [comment]
let me explain my idea - I wanted it also to be able to render legends for featurelayers and ArcGIS servers <= 10.0

**Comment by patrickarlt** [comment]
@w8r You can probably re-use a bunch of the work that @jgravois and @kneemer have done in https://github.com/Esri/esri-leaflet-renderers if you want to support FeatureLayers. For example initialize `L.esri.Renderers.ClassBreaksRenderer(rendererJSON)` and call `renderer.attachStylesToLayer(yourFeatureLayer)` then pass that same `rendererJSON` to the backend to get back the legend that matches those styles.

**Comment by w8r** [comment]
@patrickarlt, so you say I can get base64 for a symbol from some other endpoint?

**Comment by w8r** [comment]
besides that your suggestions are pretty much in the plugin and it's published, so if somebody wants to team up with me to create a decent legend template for `Control.Legend` - welcome. I wasn't focusing on that part, cause I needed to put that into use fast.

**Comment by patrickarlt** [comment]
@w8r shoot nevermind. I thought there was a `legend` operation on FeatureLayer :frowning: 

If you have renderer json though it shouldn't be terribly hard to generate the symbols yourself using canvas though.

**Comment by kneemer** [comment]
@w8r the base64 information can be found in the metadata of the feature layer in the symbol's imageData in drawingInfo, I've truncated for brevity:
```javascript
drawingInfo: {
  renderer: {
    type: "simple",
    symbol: {
      angle: 0,
      xoffset: 0,
      yoffset: 0,
      type: "esriPMS",
      url: "f70267e8-10f9-4a98-92ca-cc47953a3ec4",
      imageData: "iVBORw0KGgoAAAANSUhEU...",
      contentType: "image/png",
      width: 23.25,
      height: 23.25
    }
  }
}
```

You could hook into the FeatureLayer initialization and grab the information like we do in the renderer plugin: https://github.com/Esri/esri-leaflet-renderers/blob/master/src/FeatureLayerHook.js#L7-L8

Hope that helps a little for the icon symbols.

**Comment by w8r** [comment]
@kneemer, true, thanks, I guess I got all mixed up with the older ArcGIS versions, some of the esri sampleservers are still running that, and that's where I got stuck. I believe esri js api also uses some external resource to render symbols in that case.

**Comment by jgravois** [comment]
not to volunteer them or anything, but i think its an awesome idea and that @w8r and @rowanwins would make a good team.  

if you guys are up for it and need a hand, please let em know.

**Comment by rowanwins** [comment]
Sounds like @w8r has taken this a heck of a lot further than I ever envisaged so well done! I'll check out his repo and see if I have anything useful to contribute. I guess at some stage when we're ready we can add a demo to the esri-leaflet examples pointing people to the plugin.

Thanks for the suggestions @patrickarlt  and the "encouragement"  @jgravois :)
