### ISSUE TITLE
authenticationrequired event not being fired in IE9

### ISSUE THREAD

**Issue by Greigrm** [Esri/esri-leaflet#409]
The authenticationrequired event isn't being fired in IE9 as far as I can determine.  I think it may have to do with the need to use JSONP instead of CORS in IE9 but can't be sure.

I am not supplying the token as part of the config to the featureLayer when I am creating it, instead I wait until the authenticationrequired event is fired then get the token and then call the authenticate method.

This method works in firefox and IE11, but not IE9.

**Comment by mpetcu-dg** [comment]
The json request trick works only if CORS is enabled (which it is by default). Otherwise it still completely ignores the error code and  proceeds to download the image from an undefined href, which of course will throw an exception.
Thanks for the info!

**Comment by patrickarlt** [comment]
Instead of just updating the docs the default is now JSON so this should happen automatically.
