### ISSUE TITLE
Inherit min/max scale from service

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet#426]
I think this makes a good 'micro' plugin candidate (as opposed to bolting it on to esri-leaflet-renderers) for a couple reasons
1. minScale and maxScale are not part of the drawing options within the FeatureLayer [metadata](http://sampleserver6.arcgisonline.com/arcgis/rest/services/Census/MapServer/0?f=pjson)
2. its trivial enough that it would be well suited as a reference in much needed plugin development documentation.

at the very least it would be cool to have a sample which shows how to retrieve the information using FeatureLayer.metadata().

**Comment by tomwayson** [comment]
I tend to agree w/ @alaframboise's [comment](https://github.com/Esri/esri-leaflet-renderers/issues/9#issuecomment-68396840) in that to me it "feels" like this should be built into the core as an optional setting that defaults to true. I see his point about the min/max scales being linked to the rendering, but I can also see times when the service author would just set one or the other, so I don't think the best place for this in the renderers plugin. Just my two cents.

**Comment by jgravois** [comment]
closing, but i still may get around to this some year.

**Comment by zachatrocity** [comment]
@jgravois @tomgasson I know this is closed, but i'm having a hard time following the trail/status on this item.

If this isn't going to be implemented as a plugin, what's the best way to manually calculate the `minZoom` from an ArcGIS FeatureLayer `minScale` value? Having a hard time with this one.

**Comment by jgravois** [comment]
@zachatrocity no worries.

```js
// use scale to calculate level
level = Math.log(591657550.500000/scale) / Math.log(2) + 1
```
this is the inverse of the [StackExchange](https://gis.stackexchange.com/questions/7430/what-ratio-scales-do-google-maps-zoom-levels-correspond-to/81390#81390) formula i linked to earlier:
```js
// use level to calculate scale
scale = 591657550.500000 / Math.pow(2, level - 1)
```

**Comment by jgravois** [comment]
another update from 2019, it appears that ArcGIS Online is now deprecating minZoom/maxZoom in favor of (the significantly less obtuse) minLOD/maxLOD.

![minLOD/maxLOD](https://user-images.githubusercontent.com/3011734/52029518-5f279700-24c8-11e9-91e7-5010c2183b79.png)

https://tiles.arcgis.com/tiles/DO4gTjwJVIJ7O9Ca/arcgis/rest/services/Digital_Globe_Imagery_Dec_11th/MapServer

**Comment by zachatrocity** [comment]
Great, thank you so much!

**Comment by ewlarson** [comment]
Hi all, just curious if this issue is still on the project developer's minds.

Many libraries have adopted the [GeoBlacklight](https://geoblacklight.org/) application as a search and discovery tool for their geographic datasets, and GeoBlacklight uses esri-leaflet to render feature layer previews. It can be common to have records like a state-wide parcel map that return upwards of 3.5 million items, which just overwhelms the browser when all those results are returned without any adherence to scale.

Some additional conversation about this issue as it pertains to GeoBlacklight is online here:
https://github.com/WIStCart/GeoDataV2/issues/191

Happy to chat further if anyone is curious to hear more. Thanks!

**Comment by jgravois** [comment]
hi @ewlarson :wave:

i've helped with a few GeoBlacklight / Esri things in the past. it should be pretty straightforward for y'all to adapt the code sample i shared above to fetch feature layer metadata immediately before adding the layer to a map in order to set the scale levels or LODs for it to draw.

i'm happy to chat about it more if/when someone decides they want to try and tackle it.

**Comment by ewlarson** [comment]
Thanks so much for the reply @jgravois 

I'll take a closer look at the GeoBlacklight javascript to see if I can find the right place to inject some metadata logic. We'll likely revisit this issue this winter when our community has a two-week code sprint, too. Cheers!
