### ISSUE TITLE
Preload feature.

### ISSUE THREAD

**Issue by domialex** [Esri/esri-leaflet#436]
The features are only drawn after the map has panned, is there a way to prerender the entire SVG of a feature so that when you move the map around, there is no lag?
Example: http://esri.github.io/esri-leaflet/examples/querying-feature-layers-2.html

**Comment by jgravois** [comment]
```var map = L.map('map').setView([40, -100], 4);
...
var query = new L.esri.Tasks.Query('http://sampleserver6.arcgisonline.com/arcgis/rest/services/Census/MapServer/3');
//where('1=1') is default and returns all features
query.run(function(error, results) {
  L.geoJson(results).addTo(map);
});
```

please check out #414 for a little more info and let me know if you have any other questions.

**Comment by domialex** [comment]
Yes I already knew that could preload all the features.
But I'm actually talking about the rendering of the actual SVG on the map, it still only draws the polygons after the panning, not during since it is not completely in the HTML document yet.

**Comment by jgravois** [comment]
what version are you testing?
have you seen #408 ? 
as of RC5, we pushed a change that should ensure features just outside the viewport are already visibile when panning.

**Comment by domialex** [comment]
I edited my last comment and closed the issue.

**Comment by jgravois** [comment]
awesome.  thanks for sharing.
