### ISSUE TITLE
How can I get a list of features in a featureLayer?

### ISSUE THREAD

**Issue by timwis** [Esri/esri-leaflet#440]
Hello again! My [lane closures app](http://timwis.com/lane-closures) has a text panel in addition to the map, where I list the features as text. I'm currently using [featureLayer._layers](https://github.com/timwis/lane-closures/blob/gh-pages/scripts/main.js#L32) but this object seems to allow duplicate features as you pan around. Is there a way to get an array/object of the features currently on the map (ideally within the current bounds)? Something like `featureLayer.getFeatures()` that I can then render on a list.

If not, any direction for me would be great and I can submit a pull request if I sort it out. Thanks!

EDIT: By the way, the features are in Philadelphia in case you're looking at the app and wondering where to zoom to ;)

**Comment by odoe** [comment]
I think what you're looking for is the `eachFeature` [method](http://esri.github.io/esri-leaflet/api-reference/layers/feature-layer.html). That will loop you through the features and return the info. Although this seems to pull from the `_layers` property too, so not sure if you'll still get the duplicate feature issue.

**Comment by patrickarlt** [comment]
@timwis I can't seem to get duplicated features to show up in the `_layers` array. Can you post a JS Fiddle or similar with what you are seeing?

**Comment by patrickarlt** [comment]
@timwis it has been awhile since this was last active I'm going to close this. If you are still seeing this issue you can either reopen or file a new issue.
