### ISSUE TITLE
Demo's broken

### ISSUE THREAD

**Issue by rowanwins** [Esri/esri-leaflet#442]
Hi guys,

It appears that a few of the feature services in the demo's are broken as the demo server changed from 
http://services.arcgis.com/rOo16HdIMeOBI4Mb/arcgis/rest/services
to
https://services.arcgis.com/rOo16HdIMeOBI4Mb/arcgis/rest/services

I did one pull request and then released it was an issue for a few of the demos. Not sure if you can do bulk changes rather than me sifting through a making individual changes.

Cheers
Rowan

**Comment by jgravois** [comment]
thanks for the heads up @rowanwins.

**Comment by patrickarlt** [comment]
I think someone turned on SSL only for the org where all the services are hosted. I'll try to take a look at this today.

@jgravois can you update everything in the site/src/pages/examples folder on master? I can rebuild the gh-pages site then. https://github.com/Esri/esri-leaflet/tree/master/site/source/pages/examples

**Comment by jgravois** [comment]
yup yup.

**Comment by jgravois** [comment]
looks like someone's already switched off ssl-only.  you still want me to submit a PR to move feature service urls from 'rOo16...' to https?

**Comment by patrickarlt** [comment]
@jgravois yes please! Thats the Esri PDX org and i want to have ssl only on for it.

**Comment by jgravois** [comment]
fixed has been laid down as a unique commit in #444
