### ISSUE TITLE
add mapserver layer id to GeoJSON properties returned from dynamic map layer

### ISSUE THREAD

**Issue by bcooperw** [Esri/esri-leaflet#443]
currently when returning GeoJSON from dynamic map layer (http://esri.github.io/esri-leaflet/api-reference/layers/dynamic-map-layer.html) the layer id is not available in the bindPopup, so from the properties you cannot tell which mapserver id the feature is from. 

this would be handy for using the full url for other requests, for instance retrieving attachments for specific features from the dynamic map service

../arcgis/rest/services/servicename/MapServer/*layeridplease*/OBJECTID

**Comment by patrickarlt** [comment]
@jgravois this should be pretty easy to accomplish. I had to do it in the Esri Leaflet Geocoder. https://github.com/Esri/esri-leaflet-geocoder/blob/master/src/Providers/MapService.js#L22-L30

**Comment by jgravois** [comment]
I just figured out what you guys were talking about the other day.  happy to knock it out now.
