### ISSUE TITLE
L.esri.dynamicMapLayer and L.esri.tiledMapLayer mismatch using map with custom CRS?

### ISSUE THREAD

**Issue by lotrmj** [Esri/esri-leaflet#449]
Hello,

I created a map with custom CRS. Then I added L.esri.tiledMapLayer as a baseLayer. Everything seemed to be fine. Then I added L.esri.dynamicMapLayer and I noticed a mismatch between these two layers. Mismatch is especially noticeable on small scales. As you zoom in, the mismatch seems to go off. Is it a known bug?
And L.esri.dynamicMapLayer changes its position while you pan.
I guess it's related with .leaflet-image-layer CSS height, width, transform values.
L.esri.VERSION = "1.0.0-rc.5"
L.version = "0.7.3"

**Comment by lotrmj** [comment]
The services are public, but it's is not allowed to use them in apps. I guess it's not a crime to use them for testing reasons. The services are http://www.geoportal.lt/arcgis/rest/services/geoportal_public/background_Lietuva-3346/MapServer, http://www.geoportal.lt/arcgis/rest/services/NZT/DIRV_DB10LT-GRANUL/MapServer.

**Comment by Volcomix** [comment]
This seems to be related to a Leaflet issue: Leaflet/Leaflet#3045.

A partial workaround could be:
```javascript
L.ImageOverlay.include({
    _reset: function () {
        var image = this._image;
        var topRight = this._map.latLngToLayerPoint(this._bounds._northEast);
        var lowerLeft = this._map.latLngToLayerPoint(this._bounds._southWest);
        var lowerRight = new L.Point(topRight.x, lowerLeft.y);
        var topLeft = new L.Point(lowerLeft.x, topRight.y);
        var size = lowerRight._subtract(topLeft);
        L.DomUtil.setPosition(image, topLeft);
        image.style.width = size.x + 'px';
        image.style.height = size.y + 'px';
    }
});
```

This only fix the image position but not the zoom animation.

**Comment by patrickarlt** [comment]
Since this deals with custom projections which aren't supported and there are upstream bugs in Leaflet I'm doing to close this.
