### ISSUE TITLE
Dynamic Layer rendering issue on Zoom level 1 and 2

### ISSUE THREAD

**Issue by visionbegin** [Esri/esri-leaflet#450]
Please see your example as reference:  http://esri.github.io/esri-leaflet/examples/simple-dynamic-map-layer.html.  Zoom all the way out and keep your eye on Alaska.  When you zoom all the way out, the layer becomes misplaced/pushed down.  We have noticed this on all dynamic layers that we are using as well.  I apologize if this is an existing issue, but I don't see this anywhere else.  Just need to know if this issue has been or will be addressed.  Thanks.

**Comment by jgravois** [comment]
thanks for the report.  it looks like the overlay distorts as soon as the extent of the map includes space not covered by existing tiles.  we'll look into this.

**Comment by jgravois** [comment]
my first guess was to try manipulating the bounds of DynamicMapLayer export requests to the equivalent of 85 degrees north and south in web mercator coordinates, but it doesn't solve the problem.
