### ISSUE TITLE
Identifying Imagery sample doesn't work in Firefox

### ISSUE THREAD

**Issue by JeffJacobson** [Esri/esri-leaflet#451]
This sample does not work in Firefox: https://github.com/Esri/esri-leaflet/blob/master/site/source/pages/examples/identifying-imagery.hbs

Clicking on the map does not update the text box with the elevation data as it does in Chrome.

**Comment by tomwayson** [comment]
Good catch @JeffJacobson, I think I see the issue. Will have a fix tonight.

**Comment by jgravois** [comment]
`pane.innerHTML = identifiedPixel.properties.value + 'm';`

**Comment by tomwayson** [comment]
yep, that's it, just need a f/r on `pane.innerText` w/ `pane.innerHTML`

**Comment by jgravois** [comment]
looks like we've got four other samples that need the same treatment...

**Comment by jgravois** [comment]
thx again for that catch @JeffJacobson
