### ISSUE TITLE
When switching basemaps, unexpected errors occur

### ISSUE THREAD

**Issue by roemhildtg** [Esri/esri-leaflet#455]
I apologize if this has already been brought up. I ran into an issue creating a basemap switcher. The issue occurs after the basemap is switched multiple times. 
For example see: http://esri.github.io/esri-leaflet/examples/switching-basemaps.html 
The issue appears when switching from these basemaps:
-Oceans
-Gray
-Dark Gray
-Imagery
-Shaded Relief

I am using Google Chrome to test this, and it appears to be occuring [here](https://github.com/Esri/esri-leaflet/blob/master/src/Layers/BasemapLayer.js#L231)

` Uncaught TypeError: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.
leaflet.js:9 
o.Control.o.Class.extend.removeFrom
leaflet.js:9 
o.Map.include.removeControl                        
BasemapLayer.js:231 
a.Layers.BasemapLayer.L.TileLayer.extend.onRemove
leaflet.js:6 
o.Map.o.Class.extend.removeLayerswitching-basemaps.html:205 
setBasemap
switching-basemaps.html:218 (anonymous function)`

**Comment by jgravois** [comment]
I thought I fixed this problem in #427 which was rolled into Release Candidate 5, but I still see problems in our live sample after switching to the imagery basemap.

I'll look into it and let you know what I find.

**Comment by roemhildtg** [comment]
Sounds good. Thanks @jgravois

**Comment by jgravois** [comment]
in BasemapLayer.js, we just need to check for `this._logo._container` instead of  `this._logo` to avoid the problem.
```
onRemove: function(map){
    if(this._logo._container){
    ...
```
i'm going to hold off on submitting a pull request though because i'd like to take a stab at writing a corresponding test first.
