### ISSUE TITLE
Load ArcGIS online map into Leaflet

### ISSUE THREAD

**Issue by rossthedevigner** [Esri/esri-leaflet#456]
This might be counterintuitive, but can you pull in a map that was built in ArcGIS into Leaflet? Meaning, I've added the tiles, markers, popups, etc. and want to use it in Leaflet.

**Comment by jgravois** [comment]
if you are referring to loading webmaps via ID as you can in the JSAPI, the functionality has not been implemented and there are no immediate plans to do so as the spec is rather expansive.

please see #182 for more info.

**Comment by rossthedevigner** [comment]
Perhaps then what I need is a Feature Layer with those points like here; http://esri.github.io/esri-leaflet/examples/simple-feature-layer.html

**Comment by jgravois** [comment]
absolutely.  happy to help more if you get stuck.
