### ISSUE TITLE
Extend the bounds() method to non ArcGIS Online services

### ISSUE THREAD

**Issue by mjigmond** [Esri/esri-leaflet#458]
It would be great if the **bounds()** method (http://esri.github.io/esri-leaflet/api-reference/tasks/query.html) was extended to support customer's own ArcGIS Server. Are there any plans for this or are there existing limitations preventing it from being deployed broadly? Thanks.

**Comment by jgravois** [comment]
this option is already also available for queries against ArcGIS Server 10.3 (when the corresponding parameter `returnExtentOnly` became available). i'll update the API reference to reflect that.

more info can be found [here](http://resources.arcgis.com/en/help/arcgis-rest-api/index.html#/Query_Feature_Service_Layer/02r3000000r1000000/)

**Comment by mjigmond** [comment]
I don't have access to 10.3 and the upgrade path is rather slow :). The benefit/beauty of **bounds()** is that it returns WGS84 lat/lng ready to be used by Leaflet. I thought **extentToBounds()** would do the trick but it only creates  a Leaflet L.LatLngBounds. Or I'm missing something. Does L.esri.featureLayer support **outSR**?

**Comment by jgravois** [comment]
i'm not sure i understand what you're asking.  

the bounds() method is used to retrieve a WGS84 geometry representing the extent of the features that match your filter.  without the bounds() method, you are querying for actual features (also in WGS84).

is your question how to determine the extent of a given collection of graphics?

**Comment by mjigmond** [comment]
My goal is to retrieve the extent of the feature in WGS84 when the feature is published in a different projection. Based on one of your examples it appears that bounds() accepts non-WGS84 input and returns WGS84. See console output for http://jsfiddle.net/wm12us0q/.

**Comment by jgravois** [comment]
my suggestion in this scenario is to loop through the features that are returned by a normal query and use them to construct your own `LatLngBounds` object.

```
yourFeatureLayer.query().run(function (error, response) {
  var bounds = new L.LatLngBounds();
  //loop through the array of features returned and dig out their corresponding geometries
  for (var i = 0; i < response.features.length; i++) {
    var coords = response.features[i].geometry.coordinates;
    //invert the latitude and longitude and call extend() to incorporate them into the feature
    bounds.extend(L.latLng(coords[1], coords[0]));
  }
map.fitBounds(bounds);
});

```
i updated your fiddle [here](http://jsfiddle.net/1f6xsnns/1/).

**Comment by mjigmond** [comment]
Ah, I see why the bounds returned a WGS84. The service metadata reports Web Mercator but the actual geometry of the points is WGS84. I will use your example on the response of a GET request where I can pass the outSR. I misinterpreted the behavior of bounds(). Thanks John.

**Comment by jgravois** [comment]
you don't need to both passing outSR in your request.  the API handles this for you automatically.
