### ISSUE TITLE
replace on documentation createFeature for  addfeature 

### ISSUE THREAD

**Issue by cesarbasurto** [Esri/esri-leaflet#459]
Good Afternoon

I would like to congratulate you for this excellent project, also report that in the documentation of L.esri.Layers.FeatureLayer speaks of createFeature method but this does not exist, but use addFeature and this worked well. believe to be replaced in the documentation createFeature for addFeature.

thanks you

**Comment by jgravois** [comment]
https://github.com/Esri/esri-leaflet/blob/master/src/Layers/FeatureLayer/FeatureManager.js#L386-L396
you're correct.  i'll fix shortly.
