### ISSUE TITLE
Leaflet is silently replaced by Esri-leaflet in an envivonment with browserify and a special leaflet version.

### ISSUE THREAD

**Issue by burmisov** [Esri/esri-leaflet#463]
Say I use my own Leaflet library version based on master branch or some other patched one.
For instance, we add it to browserify bundle like so:
```js
require('my-special-leaflet'); // Creates window.L with my own Leaflet version (as a side-effect).
```
Then I try to add Esri-leaflet to play:
```js
require('esri-leaflet'); // Supposed to patch window.L and put window.L.esri there.
```
But as far as I get it, given this environment, Esri-leaflet bootstrap code (which checks for amd/commonjs/...) replaces window.L with its own bundled Leaflet version (0.7.2 as of today), which is not a behavior I would expect. Moreover, I can't think of a proper workaround to force use my own Leaflet version.

**Comment by jgravois** [comment]
i can't reproduce this error.  check out the console in [this](https://dl.dropboxusercontent.com/u/59331579/js/browserify-test/index.html) sample app.

in my package.json, i am loading 0.7.0 explicitly
```
{
  "name": "browserifyTest",
  "main": "index.js",
  "author": "John Gravois <jgravois@esri.com> (http://johngravois.com)",
  "license": "Apache 2.0",
  "readmeFilename": "README.md",
  "dependencies": {
    "leaflet": "0.7.0",
    "esri-leaflet": "1.0.0-rc.5"
  }
}
```
this is my node app
```
require('leaflet');
require('esri-leaflet');

var mapDiv = document.createElement('div')
mapDiv.setAttribute('id', 'mapDiv');
mapDiv.setAttribute('style', 'position: fixed; top: 0; bottom: 0; left: 0; right: 0;')
document.body.appendChild(mapDiv);

var map = L.map('mapDiv').setView([42.36, -71.06], 13);
L.esri.basemapLayer('Gray').addTo(map);

console.log(L.version);
console.log(L.esri.VERSION);
```
i'm happy to chat more if you can provide more information.  at the very least, its helpful to know that its time for us to bump esri-leaflets internal leaflet dependency to `0.7.3`

**Comment by jgravois** [comment]
the key here is that you have to `require('leaflet')` whether you are working with an older tagged version or any other specific patch.  this is what let's esri-leaflet know to rely on the module you've already loaded for its own dependency.

**Comment by burmisov** [comment]
Thanks for a prompt reply, John.
I see, my case is exactly the worst one - the patched Leaflet version has an alternative name (not `leaflet`). The only "legal" way (that I know of) to name own package `leaflet` is a "git"-type dependency in package.json, which is kind of a restriction. OK, maybe I'll think of some workaround. Like making a patched version of Esri-leaflet also)

**Comment by burmisov** [comment]
Investigating further, in fact I reproduced exactly the simple code you mentioned, and when browserifying that script, the result is L.version == 0.7.2.
That is the behavior of node modules - it uses the version in its own package.json, not some global one.

**Comment by burmisov** [comment]
Created a repo to showcase that: https://github.com/burmisov/test-esri-leaflet

**Comment by burmisov** [comment]
Apparently it appears that the Leaflet version published on npm as 0.7.3 has a file versioned 0.7.2 i the dist directory. So this also might be a leaflet mistake of some kind.

**Comment by jgravois** [comment]
you're right.  when i `npm install leaflet` in an empty folder and inspect the contents of "node_modules/leaflet/src/Leaflet.js".  the version is listed as '0.7.2'.

**Comment by patrickarlt** [comment]
@burmisov why do you need a patched version of Leaflet that does not use `leaflet` as a package name? Going with a git dependency is probably the best way to go here, you can even lock your git dependency to a tag for specific commit to keep it stable.
