### ISSUE TITLE
IE9 - cannot create a new feature on ArcGIS Online feature service

### ISSUE THREAD

**Issue by StepAlexander** [Esri/esri-leaflet#470]
Hi all,
I have an application, which allows a user to put markers on the map and then 'save' to a AGOL feature web-service. Everything works fine in Chrome, Safari and Firefox. In IE9, I am getting this error:
SCRIPT5: Access is denied and reference to service.addFeature( JSONfeature, ..). 

I also checked this example with IE9: 
http://patrickarlt.github.io/uc-2014-esri-leaflet/demos/editing.html

it gets the same error and refers to:

esri-leaflet-src.js, line 462 character 9 -> 

L.esri.Request = {
    post: {
      XMLHTTP: function (url, params, callback, context) {
        var httpRequest = createRequest(callback, context);
        httpRequest.open('POST', url);
        httpRequest.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
        httpRequest.send(serialize(params));

        return httpRequest;
      }
    },

I appreciate any advice on how to make it (CORS) work with IE9 and ArcGIS online services.

Thank you,
Alexander

**Comment by jgravois** [comment]
IE9 does not support CORS, so you'd have to use a proxy in order to allow users to POST across domains.

http://caniuse.com/#search=cors

**Comment by brightrain** [comment]
I have not had this very same issue BUT I have been able to get around the lack of CORS support in IE by simply changing f=json to f=jsonp in the url, in a GET request. Again, not in this same situation but making an ajax request to an AGS dynamic map service. Hope it helps.

**Comment by jgravois** [comment]
thanks for chiming in @brightrain.  the difference in this situation is that [applyEdits](http://resources.arcgis.com/en/help/arcgis-rest-api/index.html#/Apply_Edits_Feature_Service_Layer/02r3000000r6000000/) only supports POSTS.

**Comment by StepAlexander** [comment]
Thank you for your input. Just to clarify: my feature service is published on ArcGIS Online (for our University).

**Comment by jgravois** [comment]
ArcGIS Online Hosted Feature Services definitely support CORS, but in order to utilize it, the browser has to support it as well.  IE9 does not support CORS.  thats why you need a [proxy](https://developers.arcgis.com/javascript/jshelp/ags_proxy.html).
