### ISSUE TITLE
bringToBack is long gone

### ISSUE THREAD

**Issue by hbostic** [Esri/esri-leaflet#479]
I see that you no longer inherit from L.GeoJson which means FeatureLayers no longer have brintToBack and some other stuff.  This is causing me issues when trying to show and hide layers.  For this, have any array with my data, I take the array and populate a FeatureGroup.  The FeatureGroup does not maintain the order by which I add layers, therefore using bringToBack as I add layers is essential to maintain the order of the layers in the FeatureGroup.

If there an alternative implementation?

**Comment by hbostic** [comment]
ok, so I updated leaflet to 0.8-dev and updated esri leaflet to v1.0.0-rc.2 based on the leaflet 1.0 branch.

I did this so I can experiment with the new panes implementation, so I can reorder layers (all types) by drag and drop.  

Just to get started I did this:
var pane = map.createPane('leaflet-pane-' + layer.id, map.getPanes().mapPane);

where layer.id is unique

then I did this:
mapLayer = L.esri.dynamicMapLayer(layer.url, {
                                opacity: layer.opacity,
                                layers: layer.layers,
                                name: layer.name,
                                vId: layer.id,
                                pane:leaflet-pane-' + layer.id
                            });

but the newly add layer (after adding to the map of course), was still under the overlays pane.

I also tried this in case I did something wrong in referencing my new pane:

mapLayer = L.esri.dynamicMapLayer(layer.url, {
                                opacity: layer.opacity,
                                layers: layer.layers,
                                name: layer.name,
                                vId: layer.id,
                                pane:'tilePane'
                            });

but still the layer was placed under the overlays pane rather than my new pane

I do see my pane in the done, just empty.

What might I be doing wrong?

**Comment by patrickarlt** [comment]
It looks like the `pane` option isn't getting properly passed through the API https://github.com/Esri/esri-leaflet/blob/leaflet-1.0/src/Layers/RasterLayer.js#L122-L124. I've got some other syncing to do with Leaflet master/1.0 so I'll get to this soon.

**Comment by hbostic** [comment]
ok, cool, thanks!

**Comment by patrickarlt** [comment]
@hbostic I'm adding `bringToFront` and `bringToBack` in the next version. Closing this to track the changes to support `pane` in https://github.com/Esri/esri-leaflet/issues/208.

**Comment by hbostic** [comment]
Great
