### ISSUE TITLE
Reconsider the behavior of featureLayer.resetStyle()

### ISSUE THREAD

**Issue by patrickarlt** [Esri/esri-leaflet#488]
Working with a developer recently I ran into a whole bunch of issues with `resetStyle()` mostly that its behavior is difficult to predict. Currently it resets the style to whatever the `style` option on the feature layer is. This means that calling `setStyle()` will change the behavior of `resetStyle()`.

What the developer was trying to do was this.

1. On hover make a feature more prominent
2. When a feature was selected make it extremely prominent
3. When a feature was selected make all other features less prominent

Using `setStyle()` for 3 made it impossible to use `resetStyle()` on the previously hovered/selected features in 1 and 2.

I think `resetStyle()` should always reset back to the first style ever applied to a layer rather then whatever `style` option is. This would make the above use case much easier and allow allow better compatibility with Esri Leaflet Renderers for scenarios like the following.

1. Load a feature layer with a complex renderer.
2. Create separate styles for when features are selected/hovered
3. When a feature is selected/hovered change styles of all other features
4. `resetStyle()` will now restore the original complex renderer.

@jgravois @kneemer What do you think?

**Comment by patrickarlt** [comment]
This also aligns more with `L.GeoJSON` https://github.com/Leaflet/Leaflet/blob/master/src/layer/GeoJSON.js#L49-L54

**Comment by kneemer** [comment]
Seems reasonable to me.

**Comment by jgravois** [comment]
agreed!

**Comment by patrickarlt** [comment]
Resolved in https://github.com/Esri/esri-leaflet/pull/516
