### ISSUE TITLE
should we be gzip encoding on our CDN? 

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet#489]
i just took a quick look at RC6 and noticed we aren't setting a 'content-encoding' gzip header.  
![screenshot 2015-03-20 13 31 56](https://cloud.githubusercontent.com/assets/3011734/6760415/7e2944a4-cf05-11e4-9a3b-dc2cc1ffd0ce.png)
* wouldn't there be a performance benefit to gzipping? 
* would there be any drawbacks?

**Comment by patrickarlt** [comment]
Lets add Esri Leaflet to https://github.com/jsdelivr/jsdelivr and switch to using that everywhere.

**Comment by patrickarlt** [comment]
Got this registered so it should show up on our next release.
