### ISSUE TITLE
Strange copy on labeling example page

### ISSUE THREAD

**Issue by swingley** [Esri/esri-leaflet#495]
http://esri.github.io/esri-leaflet/examples/labeling-features.html, specifically https://github.com/Esri/esri-leaflet/blob/master/site/source/pages/examples/labeling-features.hbs#L3

> This does not performat automatic label placement!

What is that trying to say and what is a better way to say it?

**Comment by jgravois** [comment]
maybe something like 'this is not the same as fitting labels dynamically'?

**Comment by swingley** [comment]
Probably easier to say what it's doing as opposed to what it's not. How about something like: 

> Labels are placed at the center of the bounding box of each feature.
