### ISSUE TITLE
remove/demote L.esri.Services.FeatureLayer from API reference

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet#497]
i think the current placement of [L.esri.Services.FeatureLayer](http://esri.github.io/esri-leaflet/api-reference/services/feature-layer.html) in the API reference is unnecessarily confusing.  i find myself landing there time and time again when i really want to be reading up on what's available to `L.esri.Layers.FeatureLayer`

if we're going to include it, we should be more explicit in the note at the top and link back to `L.esri.Layers.FeatureLayer` 

alternatively, perhaps we could/should doc `FeatureGrid` and `FeatureManager` as well and make a point of explicitly segregating all three of them.

**Comment by patrickarlt** [comment]
I'm more in favor of demoting/moving base classes below everything else. They really need guides to explain HOW to extend them into your own custom thing.
