### ISSUE TITLE
Minor issue - scrolling down on the examples page

### ISSUE THREAD

**Issue by andygup** [Esri/esri-leaflet#499]
Since the map is kinda large, when attempting to scroll down on the page it's a bit challenging to find a location for the mouse where the scroll event doesn't get captured by the map.

Recommendation: shrink down the map on the page to allow for white space to left and right.

http://esri.github.io/esri-leaflet/examples/

**Comment by jgravois** [comment]
thats always annoyed me too, but i think a smaller map would be kind of a bummer too.  we're going to redo the website at some point and move it into its own dedicated repo, so i'll make a note to think more about how to improve this then.

#370
