### ISSUE TITLE
TypeError: a is undefined in line 20, col 4636 in version 1.000 RC6

### ISSUE THREAD

**Issue by developingcountries** [Esri/esri-leaflet#503]
I'm getting a "TypeError: a is undefined in line 20, col 4636" in version 1.000 RC6. Everytime I load an ArcGIS feature layer of Greater Toronto area, it throws this error. Every other city feature layer loads properly except this one. It is very frustrating, please fix! Thanks.

It is unable to render this ArcGIS feature layer:
http://services1.arcgis.com/PcevIObMOTNlnhqj/arcgis/rest/services/Geography_Greater_Toronto/FeatureServer/0

It is ABLE to load this feature layer:
http://services1.arcgis.com/PcevIObMOTNlnhqj/arcgis/rest/services/Geography_West/FeatureServer/0

I am using this javascript function to render the layer:

            L.esri.featureLayer(serviceLayer, {
                style: function (feature) {
                    return { color: 'yellow', weight: 2 };
                }
            }).addTo(map);

**Comment by jgravois** [comment]
i can't repro your error in the simple app [here](https://dl.dropboxusercontent.com/u/59331579/js/feature-layer-styled.html)

**Comment by patrickarlt** [comment]
@developingcountries you can get a better error message by turning on source maps in the chrome debugging tools. This will give you a line number that points to the actual source. https://developer.chrome.com/devtools/docs/javascript-debugging#using-source maps

We can use this to help you debug better but a reproduction case would be helpful.

**Comment by developingcountries** [comment]
Hi,
Here is a reproduction of the error: http://jsbin.com/puyiqexihi/1/edit?html,console,output
The jsbin only says script error line 0. 

But when I run the same code using Firebug extension in Firefox (similar to chrome debugger):
It says "TypeError: a is undefined (line 20, col 4636)". Thanks for your help.

**Comment by jgravois** [comment]
i caught your error by setting a breakpoint within your own code at the following line

```javascript
return regions[propertyName];
```
this is undefined for GTA because you have a typo in

**Comment by developingcountries** [comment]
Thanks for your help! I solved it. 

I also noticed that adding a 1 to the REST layer address will also return 404's. E.G.:
This works: http://services1.arcgis.com/PcevIObMOTNlnhqj/ArcGIS/rest/services/Geography_Greater_Toronto/FeatureServer/0

This does not work: http://services1.arcgis.com/PcevIObMOTNlnhqj/ArcGIS/rest/services/Geography_Greater_Toronto/FeatureServer/1

**Comment by jgravois** [comment]
I can confirm that directly in the browser.  what makes you think you have a feature service published and accessible via the second URL?

**Comment by developingcountries** [comment]
I thought the 1 meant something, just like in coding, sometimes 1 means "on", and 0 means "off".  Anyways, I know better now.
