### ISSUE TITLE
esri logo doesn't scale, too big on small maps

### ISSUE THREAD

**Issue by tcastelli** [Esri/esri-leaflet#505]
I wonder if this is possible, since when i try to show small maps (less than 100x100) the attribution code+ esri logo fill the whole picture. Another option would be to use something like mapbox library strategy using {infoControl: true} when creating the map, but making esri logo the "enabler" instead of the small i icon. (yoou probably have seen this but here's an example)
https://www.mapbox.com/blog/mapboxjs-150/

**Comment by jgravois** [comment]
totally valid concern.  the [JSAPI](http://developers.arcgis.com/javascript/samples/map_simple/) automatically scales down to a 46x22 logo when the map is less than 400px wide so we can definitely do something similar here.
