### ISSUE TITLE
CORS error is not handled properly when using identify

### ISSUE THREAD

**Issue by chriserickson** [Esri/esri-leaflet#512]
I'm doing an identify operation on a layer, which is failing due to cross origin policy. However, the error never bubbles back to the caller due to being masked by a secondary error:

![image](https://cloud.githubusercontent.com/assets/1971519/7235456/8722fe98-e74b-11e4-9cac-567ac2093b73.png)

![image](https://cloud.githubusercontent.com/assets/1971519/7235472/a56a6e7c-e74b-11e4-99d2-04015aa7d108.png)

**Comment by chriserickson** [comment]
Looks like this might not be related to the CORS error. I'm getting it on other layers now.

In IdentifyImage, the run method doesn't check for an error, and in the debugger I have a 500 error with a null response.

![image](https://cloud.githubusercontent.com/assets/1971519/7235693/fef60720-e74c-11e4-9f60-a5fe48613957.png)

**Comment by chriserickson** [comment]
I've found the following version of the method to correctly pass back the error:

```
run: function (callback, context){
    return this.request(function(error, response){
      if (!error) {
          var featureCollection = EsriLeaflet.Util.responseToFeatureCollection(response);
          var count = featureCollection.features.length;
          // tag each feature with the Id of its parent layer
          if (count > 0) {
              response.results = response.results.reverse();
              for (var i = 0; i < count; i++) {
                  var feature = featureCollection.features[i];
                  feature.layerId = response.results[i].layerId;
              }
          }
      }
      callback.call(context, error, (response && featureCollection), response);
    }, context);
  }
```

**Comment by jgravois** [comment]
thanks for the catch @chriserickson.  would you like to submit this as a PR?  if not, thats okay too.

**Comment by chriserickson** [comment]
I can try at some point. I don't have github installed and we're in the middle of a production push :)

**Comment by patrickarlt** [comment]
@jgravois this looks like a solid fix. Can you turn it into a PR?

**Comment by jgravois** [comment]
absolutely.  id like to write tests and check some other similar methods for this type of problem at the same time.
