### ISSUE TITLE
lots of polygon features from services are not being drawn

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet#536]
problem is visible in `debug/sample.html` and [this](http://esri.github.io/esri-leaflet/examples/styling-feature-layer-polygons.html) sample as well.

![screenshot 2015-05-19 10 13 34](https://cloud.githubusercontent.com/assets/3011734/7709134/c70e8de4-fe0f-11e4-9733-0e028ee60809.png)

problem introduced sometime after rc6 (potentially from work on polygons with holes)

**Comment by patrickarlt** [comment]
Damn I will investigate.

**Comment by patrickarlt** [comment]
For whatever reason it looks like the early returns here https://github.com/Esri/esri-leaflet/blob/master/src/Layers/FeatureLayer/FeatureLayer.js#L90 and https://github.com/Esri/esri-leaflet/blob/master/src/Layers/FeatureLayer/FeatureLayer.js#L95 break this. I will keep working on figuring this out.

**Comment by jgravois** [comment]
i was hoping it might be as easy as substituting a `break` instead, but alas..

**Comment by Kalix86** [comment]
Potentially related to #546, although could be a separate problem.
?

**Comment by patrickarlt** [comment]
Fixed in https://github.com/Esri/esri-leaflet/commit/d8903bff1acd264cd7a6a93656bff459a62133d8
