### ISSUE TITLE
simple feature layer sample is broken

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet#537]
points don't display in [this sample](http://esri.github.io/esri-leaflet/examples/simple-feature-layer.html)

looks like the problem is [here](https://github.com/Esri/esri-leaflet/blob/0ed2638bf6a14a0b2a910fff3effad3c5f856cb0/site/source/partials/header.hbs#L39)

```html
<!-- instead of -->
<script src="http://cdn.jsdelivr.net/g/leaflet@0.7.3,leaflet.esri,jsdelivr-rum"></script>
<!-- needs to be -->
<script src="//cdn.jsdelivr.net/leaflet/0.7.3/leaflet.js"></script>
```

**Comment by patrickarlt** [comment]
Taking a peak at the console it look like `Uncaught Error: Couldn't autodetect L.Icon.Default.imagePath, set it manually.`

**Comment by patrickarlt** [comment]
This is because I am requesting a single combined download of Leaflet + Esri Leaflet + JS Delivr metrics. You could just break all those out separately to fix this.

**Comment by jgravois** [comment]
agreed.  i'll patch shortly.
