### ISSUE TITLE
FeatureLayer 'load' is sometimes called before individual features are available

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet#545]
i had an expectation that it would always be safe to write something like below before realizing that the ['load' event](https://github.com/Esri/esri-leaflet/blob/master/src/Layers/FeatureLayer/FeatureManager.js#L123) can be fired before we've stepped into [createLayers()](https://github.com/Esri/esri-leaflet/blob/master/src/Layers/FeatureLayer/FeatureLayer.js#L80)
```javascript
fl.on('load', function(evt) {
  fl.eachFeature(function(layer) {
    // do amazing things (if there are features to loop through)
  });
});
```
it'd be pretty trivial to emit an entirely new event (Iike the JSAPI's ['update'](https://developers.arcgis.com/javascript/jsapi/featurelayer-amd.html#event-update)) in the second location i mentioned and it seems essential that we have a dependable hook for developers to do X with the features that are retrieved but i'm curious whether anyone else has any better ideas

my use case was writing a blog to show how to zoom to the extent of a collection which doesn't support calling bounds() on page load.

**Comment by patrickarlt** [comment]
Fixed in https://github.com/Esri/esri-leaflet/commit/1e336d3e887d22b8a274148db84c0db1cddc4c21

**Comment by jgravois** [comment]
just did a quick check and the `load` event isn't firing at all in one of my simple applications.  reopening so i can take a look.

**Comment by patrickarlt** [comment]
@jgravois can you give me a reproduction of this issue? Its working properly in http://esri.github.io/esri-leaflet/examples/spatial-queries.html

**Comment by jgravois** [comment]
good news.  i can't reproduce the error anymore.

**Comment by jgravois** [comment]
nevermind.  if i add [this](http://services.arcgis.com/uCXeTVveQzP4IIcx/arcgis/rest/services/VaquitaProtection/FeatureServer/0) feature service to debug/[sample.html](https://github.com/Esri/esri-leaflet/blob/master/debug/sample.html) on `master`, the load event isn't fired, even after all responses from the service have been received.

```js
var fl = L.esri.featureLayer('http://services.arcgis.com/uCXeTVveQzP4IIcx/arcgis/rest/services/VaquitaProtection/FeatureServer/0').addTo(map);

fl.on('load', function(){
  console.log('please fire');
});
```

**Comment by patrickarlt** [comment]
Fixed this. Should be in the next release.

**Comment by jgravois** [comment]
confirmed.  awesome!
