### ISSUE TITLE
L.esri.Featurelayer overlays don't load when turned off and on again...?

### ISSUE THREAD

**Issue by Kalix86** [Esri/esri-leaflet#546]
Hi,

I have searched all day for a solution but couldn't find any, so sorry is this is user error, rather than a codebase issue. Basically, I am adding FeatureLayers as overlays using a map service, and then adding those layers to Leaflets Layers control.

When I turn on these overlays for the first time it works fine, but when I turn them off and on again, only a handful of the markers are drawn. It only occurs with overlays that are created by the L.esri.featureLayer. My regular geoJson layers have no issues. 

Is this something I've done wrong? Some caching settings with the map service?
Any help is greatly appreciated!

Code below:

```
var MyIcon = L.icon({
        iconUrl: '@Url.Content("~/Content/Images/Markers/MyMarker.png")',
            iconSize: [30, 36], // size of the icon
            iconAnchor: [15, 36], // point of the icon which will correspond to marker's location
            popupAnchor: [6, 0] // point from which the popup should open relative to the iconAnchor
        });

    var items = L.esri.featureLayer('http://www.mapservicehere.com/arcgis/rest/services/Networks/MapServer/12', {

        pointToLayer: function (feature, latlng) {
            var itemMarker = L.marker(latlng, { icon: MyIcon, title: feature.properties.name });
            return itemMarker;
        },
        onEachFeature: function (feature, layer) {
            var popupHTML = createItemPopup(feature.properties);
            layer.bindPopup(popupHTML, { offset: new L.Point(0, -12) });
        }
    });

```

And below that:

```
    var overlayMaps = {
        "Items": items,
        "Items2": items2,
        "Items3": items3,
    };

    L.control.layers(null, overlayMaps).addTo(map);
```

**Comment by Kalix86** [comment]
I've also noticed in Firebug that a lot of the service requests are returning "304 Not Modified" messages.

**Comment by jgravois** [comment]
we've merged a potential fix into `master`.  can you please test with the latest and let us know how it goes?

**Comment by Kalix86** [comment]
It works! :)

**Comment by jgravois** [comment]
sweet.
