### ISSUE TITLE
adding a layer to a map using name

### ISSUE THREAD

**Issue by ferdaousse** [Esri/esri-leaflet#547]
hello, 
i 'm using dynamicMaplayer to add my layer to the map .
the problem is that i want to use layer's name instead of its id.
is there a way to retrive the id of the layer by its name ??

**Comment by patrickarlt** [comment]
@ferdaousse could you explain this some more? I'm not sure what you mean by adding it to the map by name.

**Comment by patrickarlt** [comment]
@ferdaousse I'm closing this. If you want to find the names of the layers in a service they are in the metadata response.

```js
var layer = L.esri.dymanicMapLayer(...);

layer.metadata(function(error, response){
  console.log(response.layers);
});
```
