### ISSUE TITLE
jsdelivr 'latest' is responding with rc.7

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet#560]
http://cdn.jsdelivr.net/leaflet.esri/latest/esri-leaflet.js

**Comment by jimaek** [comment]
`/latest/` is cached on the CDN for 7 days for performance reasons. Today is the 8th day since the update so you should be getting the latest version across all locations we have.

**Comment by jgravois** [comment]
confirmed.  thanks @jimaek!
