### ISSUE TITLE
document that ruby is a prerequisite to build the esri-leaflet website

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet#561]
https://github.com/gruntjs/grunt-contrib-sass#sass-task

**Comment by patrickarlt** [comment]
I just swapped `grunt-contrib-sass` (Ruby SASS) for `grunt-sass` (Node SASS) so we don't have to have Ruby anymore!

**Comment by jgravois** [comment]
now **that**s the way to close an issue.  (confirmed working on my ruby-less Windows VM)
