### ISSUE TITLE
Projection

### ISSUE THREAD

**Issue by rbonillajr** [Esri/esri-leaflet#562]
I have this service ArcGIS Server convert the point where GeoJSON . to convert moving slightly upward

![image](https://cloud.githubusercontent.com/assets/8268226/8123499/41934a68-1090-11e5-8fcb-4ffef7595860.png)

i use esri leaflet is goog 

![image](https://cloud.githubusercontent.com/assets/8268226/8123483/ec5faabe-108f-11e5-867f-5fb517c515ba.png)

```
angular
    .module('geomarketing.services')
    .factory('utilityService', ['$q', '$log','$http',
function ($q, $log,$http) {
    var utilityService = {};
    utilityService.arcgisToFeatureCollection = '';
    utilityService.arcgisToFeatureCollection = function (url, callback) {
       
        $http.get(url).
          success(function (data, status, headers, config) {
              callback(null, createGeoJson(data));
              // this callback will be called asynchronously
              // when the response is available
          }).
          error(function (data, status, headers, config) {
              callback(null, null);
          });

        
        createGeoJson = function (json) {
            
            var features = json.features;
            //var idField = response.operationalLayers[0].featureCollection.layers[0].layerDefinition.objectIdField;

            // empty geojson feature collection
            var featureCollection = {
                type: 'FeatureCollection',
                features: []
            };

            for (var i = features.length - 1; i >= 0; i--) {
                // convert ArcGIS Feature to GeoJSON Feature
               
                var feature = {
                    "type": "Feature",
                    "geometry": { "type": "Point", "coordinates": [features[i].geometry.x, features[i].geometry.y] },
                    "properties": features[i].attributes
                };
                
                // unproject the web mercator coordinates to lat/lng
                var latlng = L.Projection.Mercator.unproject(L.point(feature.geometry.coordinates));
                feature.geometry.coordinates = [latlng.lng, latlng.lat];
              
                featureCollection.features.push(feature);
            }

           return featureCollection
        };

    };



    return utilityService;
}]);
```

**Comment by jgravois** [comment]
it sounds like you are saying esri-leaflet is behaving appropriately and you're having trouble with `L.Projection.Mercator.unproject()`.  is that correct?

**Comment by rbonillajr** [comment]
http://esri.github.io/esri-leaflet/examples/parse-feature-collection.html in this sample using L.Projection.Mercator.unproject() for convert to geojson.
I need convert for generate buffer with turfjs but marker moved upward.

thanks

**Comment by jgravois** [comment]
im pretty sure that the answer to my first question is 'yes'.  can you provide a link to the live service or a subset of the data?

**Comment by rbonillajr** [comment]
http://gis.geoinfo-int.com/arcgis/rest/services/MOBIL/MOBIL/MapServer/0/query?where=objectid+%3D+objectid&outfields=*&f=json

**Comment by patrickarlt** [comment]
@rbonillajr If you are querying from the server try using `L.esri.Tasks.Query` to request the features. http://esri.github.io/esri-leaflet/api-reference/tasks/query.html this will request the features in 4326 (standard for geojson) and give you the features in GeoJSON ready to be passed to TurfJS.

If you are interested I have a demo of creating a hexbin with TurfJS and Esri Leaflet https://github.com/patrickarlt/dev-summit-2015-esri-leaflet-with-leaflet-plugins/blob/gh-pages/demos/turf-hexbin.html that uses `L.esri.Tasks.Query`.

**Comment by rbonillajr** [comment]
thanks I'll try

**Comment by rbonillajr** [comment]
work fine!!! thanks

**Comment by ibrahimawadhamid** [comment]
> http://esri.github.io/esri-leaflet/examples/parse-feature-collection.html in this sample using L.Projection.Mercator.unproject() for convert to geojson.
> I need convert for generate buffer with turfjs but marker moved upward.
> 
> thanks

@rbonillajr  I can't thank you enough, I've been stuck in this issue for a whole day.

**Comment by rbonillajr** [comment]
Hi @ibrahimawadhamid, one of the problems may be the projection with which you have published the ArcgisSever service.
If you can send me some code with pleasure I can help you.

This is my code to consume the service (Require the Leaflet / esri-leaflet.js library):

```
utilityService.getFeature = function (url, filter, callback) {

                L.esri.Tasks.query({
                    url: url
                }).where(filter).run(function (err, result, response) {
                    callback(null, result);
                });
            };
```
