### ISSUE TITLE
'ArcGIS Online OAuth' sample is busted

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet#564]
STR:
1. open [sample](http://esri.github.io/esri-leaflet/examples/arcgis-online-auth.html) and try to 'Sign in'
2. notice that a valid token is not displayed afterward.

this is caused by an uncaught error encountered within the callback inside `window.oauthCallback(token)`.  i'm not sure exactly why yet.

@KristinaWeis confirmed this isn't just happening to me.

**Comment by tomwayson** [comment]
ditto here - I see a CORS error on the call to self:

![image](https://cloud.githubusercontent.com/assets/662944/8447717/bee9233a-1f71-11e5-960a-4db3ba75130f.png)

**Comment by patrickarlt** [comment]
Fixed apparently we should always be using https://www.arcgis.com as a base URL.
