### ISSUE TITLE
add support for dynamicLayers

### ISSUE THREAD

**Issue by pauldzy** [Esri/esri-leaflet#566]
Hello,

I was wondering if Esri-Leaflet would support some method to populate the dynamicLayers parameter.  The use case is that I would like to reorder the internal feature classes in a AGS dynamic layer as shown here
http://developers.arcgis.com/javascript/samples/layers_dynamic_reorder/

I think this is 10.1 feature and just letting us sort out and drop in our own JSON string would be fine.

Thanks,
Paul

**Comment by jgravois** [comment]
i'm not sure whether or not it'd be a good idea to add official `support` for dynamic-layers in the API thats just an opportunity to pass in your own hand constructed JSON, but i did a quick test and it was pretty simple to add in...

```js
getDynamicLayers: function(){
  return this.options.dynamicLayers;
},

setDynamicLayers: function(dynamicLayers){
  this.options.dynamicLayers = dynamicLayers;
  this._update();
  return this;
}
// ... 
_buildExportParams: function () {
  // ...
  if(this.options.dynamicLayers){
    params.dynamicLayers = this.options.dynamicLayers;
  }
```
https://github.com/jgravois/esri-leaflet/commit/9ff18e84849d4aa8aa411c26d8d71aebb004e20c

let me know if you have any more questions about it

**Comment by tomwayson** [comment]
Well, it's not on [the roadmap](https://github.com/Esri/esri-leaflet/wiki/Roadmap), and from my experience, working w/ the [LayerDrawingOptoins](https://developers.arcgis.com/javascript/jsapi/layerdrawingoptions-amd.html) can be complex (esp w/r/t [renderers](https://developers.arcgis.com/javascript/jssamples/renderer_dynamic_layer_class_breaks.html)). I won't speak for @patrickarlt, but I wouldn't count on specific support for this.

I think your idea of "dropping in your own JSON string" is a good one though. So [L.esri.Layers.DynamicMapLayer](http://esri.github.io/esri-leaflet/api-reference/layers/dynamic-map-layer.html) (and even all the other layers/tasks) could have a method like `extraParamters()` that you could pass a hash of prop/value pairs that would be sent along w/ every request to until you modified or cleared them. That could be a catch all for some of the less common params.

**Comment by jgravois** [comment]
i like the idea @tomwayson, but what else did you have in mind in the way of uncommon parameters?

**Comment by tomwayson** [comment]
I don't have anything else in mind. Really it's just things like this, where the implementation of a specific parameter could be complicated and not often used. Would be nice to have a way for the user to specify custom parameters as an extensibility point.

**Comment by jgravois** [comment]
i like the idea.  im just going to rename the issue, add a FAQ tag and shelf for now, but the next time someone wants to insert a custom parameter into a request i'll take a :hocho: at implementing your suggestion.

**Comment by patrickarlt** [comment]
@tomwayson You got it wrong! I actually like the idea of supporting  `dynamicLayers`. I know `dynamicLayers` is ludicrously complex but I'll need `dynamicLayers` support for being able to customize the traffic layer in the routing plugin and for the demographic maps. Adding a generic `extraParameters()` helper just seems kind of sloppy like we didn't think of everything and just added a catchall. I would rather just wrap everything up as methods and be done with it.

**Comment by jgravois** [comment]
>> I actually like the idea of supporting `dynamicLayers`

hah.  color me surprised.  

are you saying you want what i already demoed above (which requires the developer to know what JSON they'd like to pass in) or actual helper methods to create JSON for them?

**Comment by patrickarlt** [comment]
As much as I would love to have helper methods for the JSON its just to much of a mess to support everything. Its one of those advanced features that only a few people use and is really easy to implement so just needing to know the JSON object is fine by me.

**Comment by jgravois** [comment]
i agree.  actual support would be a beast.

i'll PR based on my suggestion above sometime soon, and make sure to include the appropriate documentation updates and corresponding tests.

if anyone else wants to help, that would be dandy too
cc/ @benstoltz @NoashX @natas333x2 etc. etc.

**Comment by tomwayson** [comment]
can't be right all the time ¯\_(ツ)_/¯

**Comment by pauldzy** [comment]
Thanks everyone!

**Comment by bbehling** [comment]
Similar to the JSAPI, is it possible to get the initial Dynamic Layer Infos using this leaflet plugin?

After the layer is loaded and call getDynamicLayers(), nothing is returned.

**Comment by jgravois** [comment]
> is it possible to get the initial Dynamic Layer Infos using this leaflet plugin?

we don't provide a wrapper method, but you can fetch the [metadata](https://sampleserver6.arcgisonline.com/arcgis/rest/services/USA/MapServer?f=pjson) for the service pretty easily and dig in for the 'layers' using [`L.esri.request`](http://esri.github.io/esri-leaflet/api-reference/request.html)
```js
var mapUrl = 'http://sampleserver6.arcgisonline.com/arcgis/rest/services/Census/MapServer';

L.esri.request(mapUrl, {}, function (error, response) {
  console.log(response.layers);
})
```
