### ISSUE TITLE
Should we allow initializing items by item ids?

### ISSUE THREAD

**Issue by patrickarlt** [Esri/esri-leaflet#570]
I stumbled across this when looking at the Esri Leaflet Renders issues https://github.com/Esri/esri-leaflet-renderers/issues/51 which brought back something that has always bugged me.

If we are trying to get everyone to use portal and register items why do we always make people know service URLs?

I'm debating this as a separate plugin but this could work in Esri Leaflet as well there could be 3 ways to initialize any layer in the API:

``` js
L.esri.featureLayer({
  url: 'http://...'
});

// takes more requests (since we have to request the item info first)
L.esri.featureLayer({
  id: 'ArcGIS Online Item ID'
});

// takes more requests (since we have to request the item info first)
L.esri.featureLayer({
  portal: 'the root URL for your on premise portal'
  id: 'Item ID in your portal',
});
```

This approach is really convenient but authentication could be a problem.

However this also has appeal as a separate plugin (because of the auth component)

``` js
var portal = L.esri.portal({
  // some auth credentials
});

// add any item to the map from ArcGIS Online
portal.getItem({
  id: 'ArcGIS Online Item ID'
}).addTo(map);

// add any item to the map
L.esri.getItem({
  portal: 'the root URL for your on premise portal'
  id: 'Item ID in your portal',
}).addTo(map);
```

**Comment by jgravois** [comment]
happy to revisit, but i'll take the lack of response as an indication that its not a priority for most users.

adding the `FAQ` label and closing.
