### ISSUE TITLE
Should we release a stable version compatible with leaflet 0.7.3?

### ISSUE THREAD

**Issue by patrickarlt** [Esri/esri-leaflet#577]
Since it is looking likely that Leaflet will release a 1.0-beta.1 soon I have to ask myself if Esri Leaflet should publish a stable (non-beta, non-prerelease, non-rc) release for use with Leaflet 0.7.3? 0.7.3 has been remarkably stable and with a few exceptions like https://github.com/Esri/esri-leaflet/issues/574 and https://github.com/Esri/esri-leaflet/issues/575 I feel confident calling the next release stable.

However this raises some questions, if we do a stable release now:

* What should the version number on that release be?
* What should the version number on the upcoming release that is compatible with Leaflet 1.0.0-beta.1 be?

My call is to do this:

1. Release the next version as 0.9.0, mark it as stable and move it to it's own branch so we can continue releasing bug fixes for Esri Leaflet 0.9.X + Leaflet 0.7.3.
2. Merge `leaflet-master` into master
3. Release Esri Leaflet 1.0.0-rc.9 as the next release that is ONLY compatible with the Leaflet 1.0.0-beta.1
4. Keep releasing Esri Leaflet 1.0.0-rc.X versions until Leaflet 1.0 is stable.
5. Keep releasing Esri Leaflet 0.9.X versions as we find bugs.

**Comment by jgravois** [comment]
> 2. Merge `leaflet-master` into master
he meant 'merge `leaflet-1.0` into `master`'

im okay with your suggestion but it might mitigate confusion related to some of our release candidates targeting 0.7.3 and some targeting 1.0.0-beta.1 if we just started bumping actual patches (ie. 1.0.1 instead.)

there are certainly pros and cons to breaking Leaflet's own convention here, but i've really never understood freezing the entire version and appending qualifiers when SemVer gives you three perfectly good opportunities to differentiate releases.

**Comment by patrickarlt** [comment]
@jgravois so followign your suggestions we would have:

* 0.9.X - Leaflet 0.7.3
* 1.X.X - Leaflet 1.0.0

and just do away with `beta` and `rc` labels. Semver actually does allow for this.

> A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version

Basically this comes down to do we consider the combo of Esri leaflet 1.0.0 with Leaflet 1.0.0-beta.1 to be a "pre-release"?

Since Leaflet still considers itself "beta" and the API is still subject to change I'm not comfortable dropping our pre-release designation since that means (according to SemVer) that we would have to bump the major if a change in Leaflets API causes a breaking change for us.

**Comment by jgravois** [comment]
> we would have to bump the major if a change in Leaflets API causes a breaking change for us.

on the flip-side, what if we need to introduce our own breaking change someday while leaflet is sitting stable at `1.0.0`?

i honestly don't like either option.  i'm just using the opportunity to point out that we aren't really **doing** Semver if we perpetually hold at a `beta` or `rc` to reserve the right to make breaking changes to the API without bumping.

what do you think @ngoldman? @swingley?

**Comment by patrickarlt** [comment]
> on the flip-side, what if we need to introduce our own breaking change someday while leaflet is sitting stable at `1.0.0`?

Then WE get to make the determination to bump major not Leaflet which I feel better about. It still sucks but I'm ok with switching over to your suggestion if we think it will reduce confusion.

Interested to hear what @ngoldman thinks.

**Comment by ngoldman** [comment]
**I would recommend bumping to `1.0.0`.**

The reasons:

1. It's a stable release
1. This project has been tied to 0.7.3 for a *long* time now
1. It will be easier to push minor/patch fixes to 1.x if you publish a 2.x for Leaflet 1.x
1. 0.x breaks / is meaningless in SemVer
  - See https://nodesource.com/blog/semver-tilde-and-caret
  - In particular https://nodesource.com/blog/semver-tilde-and-caret#1-0-0-anxiety & https://nodesource.com/blog/semver-tilde-and-caret#recommendation-start-at-1-0-0
  - This means moving to 1.x will make Esri-Leaflet work correctly with package managers and things like `~` and `^`

@patrickarlt @jgravois

**Comment by JerrySievert** [comment]
agree with @ngoldman

**Comment by swingley** [comment]
Hi everyone! I guess @jgravois called me out since I was ribbing him the other day about all the release candidates for this project...

Anywho, I agree that you all should ship what you have as 1.0.0.

**Comment by jgravois** [comment]
:+1: for @ngoldman's suggestion.  i think his suggestion is right on the mark.
