### ISSUE TITLE
1.0.0 Release

### ISSUE THREAD

**Issue by patrickarlt** [Esri/esri-leaflet#585]
@jgravois in case you are interested.

* [x] geocoder added on JS Delivr https://github.com/jsdelivr/jsdelivr/pull/5752
* [x] esri-leaflet 1.0 release on Github/NPM/Bower
* [x] run travis build for heatmap-feature-layer
* [x]  heatmap-feature-layer 1.0 release on Github/NPM/Bower
* [x] run travis build for clustered-feature-layer
* [x] clustered-feature-layer 1.0 release on Github/NPM/Bower
* [x] run travis build for geocoder
* [x] geocoder 1.0 release on Github/NPM/Bower
* [x] update website with new CDN URLs
* [x] update website build sizes (jg in #586)
* [x] update website download links  (jg in #586)
* [ ] Announce!

**Comment by jgravois** [comment]
absolutely happy to help with all this!

i was thinking since it takes 7 days to clear the cache for the cdn `latest` we should hardcode `1.0.0` into the samples at least temporarily.

**Comment by patrickarlt** [comment]
@jgravois I actually figured out how to hardcode the version number automatically so we can quit worrying about it!

**Comment by jgravois** [comment]
saweet.

strangely, right now the url below is returning rc.8.
http://cdn.jsdelivr.net/leaflet.esri/1.0.0/esri-leaflet.js

i inspected the contents of the `.zip` file included with the actual github release and its correct.

**Comment by jgravois** [comment]
and the one below is returning rc.4:
http://cdn.jsdelivr.net/leaflet.esri.geocoder/1.0.0/esri-leaflet-geocoder.js

which doesn't surprise me, because Esri/esri-leaflet-geocoder/pull/#75 hasn't been merged yet.

**Comment by jgravois** [comment]
red herring.  jsdelivr just lets you truncate the string in the release folder
http://cdn.jsdelivr.net/leaflet.esri/1.0.0-rc/esri-leaflet.js

**Comment by patrickarlt** [comment]
@jgravois rest of the releases are good to go but I want to remove the old CDN upload from the process before release. Everything should be out before the end of the day.

**Comment by patrickarlt** [comment]
I realized that grunt-releasable had a bug in it that prevented some releases from working. Waiting on JS Devlir to fetch the latest release then ill update the doc site.

**Comment by patrickarlt** [comment]
@jgravois I think everything is up to date and ready. I'll announce this on Monday!

**Comment by jgravois** [comment]
I'm still seeing rc.8 returned by 
http://cdn.jsdelivr.net/leaflet.esri/1.0.0/esri-leaflet.js

shouldn't it be returning the latest?

**Comment by jgravois** [comment]
nm.  must have been browser cache.
