### ISSUE TITLE
Authentication request works in firefox but 500 error in chrome.

### ISSUE THREAD

**Issue by SlwStdySqz** [Esri/esri-leaflet#590]
Hi,
Hopefully you guys can help me with some trouble I'm having with my map authentication. Working off of a modified form of the [example](http://esri.github.io/esri-leaflet/examples/arcgis-server-auth.html) in the documentation, I can successfully authenticate and get a valid token in firefox. However the same code returns a 500 error in chrome. 

```javascript
//make login box
function makeLoginBox() {
  var loginDiv = document.createElement('div');
  loginDiv.id = 'loginbox';
  loginDiv.innerHTML = "<center><b>Login</b></center><form id=\"l-form\" name=\"login-form\">Username<br><input name=\"username\"/><br>Password<br><input name=\"password\" type=\"password\"/><br><input type=\"submit\" id=\"login-btn\" value=\"login\"/></form>"; 
  var mapDiv = document.getElementById('map'); 
  document.body.insertBefore(loginDiv, mapDiv);
  };
makeLoginBox() //insert into DOM

//retrieve credentials
function getCredentials() {
  var x = document.getElementById('l-form');
  var authN = x.elements[0].value;
  var authP = x.elements[1].value;
  return [authN, authP]
  };

//validate supplied credentials & load app if valid
function validateCred(){
  var cred = getCredentials();
  if (cred[0].length === 0 || cred[1].length === 0) {
    alert("Username and Password are required!");
    }
  else {
    //remove loginbox if credentials valid
    var body = document.getElementsByTagName('body');
    var loginbox = document.getElementById('loginbox');
    body[0].removeChild(loginbox);
    //add credentials to server request
    function serverAuth (callback) {
      L.esri.post('http://sampleserver6.arcgisonline.com/arcgis/tokens/generateToken', {
        username: cred[0],
        password: cred[1],
        f: 'json',
        expiration: 6, //minutes
        client: 'referer',
        referer: window.location.origin},
        callback);
      };
    //send request
    serverAuth(function (error, response) {
      console.log(error);
      console.log(response);
    });
  }
}
//attached validate function to login button
var loginSubmit = document.getElementById("login-btn");
loginSubmit.onclick = validateCred;
```
My results in chrome:
```
Object {code: 500, message: "Could not parse response as JSON. This could also be caused by a CORS or XMLHttpRequest error."}
```
In firefox:
```
Object { token: "-4R2m_dw_zarm4pGQ0yYIltZFkb7PeQN8u1…", expires: 1436981012163 }
```

**Comment by jgravois** [comment]
a CORS problem is definitely the most likely culprit.
are you testing with a secure map service on sampleserver6 or on your own server?

**Comment by SlwStdySqz** [comment]
I've tested against both sampleserver6 as well as my own and get the same error.

**Comment by jgravois** [comment]
can you reproduce with something as simple as [this](https://dl.dropboxusercontent.com/u/59331579/js/token.html)?
```js
L.esri.post('//sampleserver6.arcgisonline.com/arcgis/tokens/generateToken', {
    username: 'user1',
    password: 'user1',
    f: 'json',
    expiration: 6, //minutes
    client: 'referer',
    referer: window.location.origin
},
myCallback);

function myCallback(error, response){
    document.write('error: ' + error + '<br>');
    document.write('token: ' + response.token);
};
```

**Comment by SlwStdySqz** [comment]
Yes, with only this I am able to return a token.

**Comment by jgravois** [comment]
for some reason your own request from chrome is missing a header that i'm faily sure we can't/shouldn't be setting from within the API.

> **Host**    sampleserver6.arcgisonline.com

i saw some success after moving your callback into an **outside** function (see example [here](https://dl.dropboxusercontent.com/u/59331579/js/token-modified.html)), but now i'm seeing the error again.

**Comment by SlwStdySqz** [comment]
I attempted similar to your example but no success either.

**Comment by patrickarlt** [comment]
@SlwStdySqz the issue is actually in your HTML. Esri Leaflet is working fine. In this fiddle http://jsbin.com/nexodi/edit?html,output try user1/user1 and clicking login vs user1/user1 and hitting enter.

Hitting enter will submit the form which refreshes the page which cancels all rending requests to be canceled triggering the error message. Clicking the login button however triggers your action which you can see because the token response gets appended into the body. However because you are not preventing the default action on the click the event also bubbles up to the `<form>` and triggers the submit event and the page refreshes.

An updated version of this is working here http://jsbin.com/fenunam/edit?html,output. I've added   `e.preventDefault();` inside `validateCred` to stop the default form submission from happening and attached `validateCred` to the `submit` event rather then the click event and used `addEventListener`.

**Comment by jgravois** [comment]
if you just want a button click to trigger an AJAX web request, you could also switch to an input 'button' instead of worrying about default event listeners bubbling up.

```html
<input type="button" id="login-btn" onclick="validateCred()">login</button>
```
example [here](https://dl.dropboxusercontent.com/u/59331579/js/token-button.html).

**Comment by SlwStdySqz** [comment]
Thanks for the pointers guys, much appreciated!
