### ISSUE TITLE
Update API Docs Examples for 1.0

### ISSUE THREAD

**Issue by mikefedak** [Esri/esri-leaflet#602]
I noticed that you are passing url and options as separate arguments to create a layer (dynamic, tiled, image or feature). URL should be passed as a property of the options object. 

See here: 
https://github.com/Esri/esri-leaflet/blob/297478916d3bca5cb98dcab4a15a03791a8f1ac3/site/source/pages/api-reference/layers/dynamic-map-layer.md

**Comment by jgravois** [comment]
thanks for pointing this out.  I'll fix really soon.

**Comment by patrickarlt** [comment]
@jgravois looks like all the examples in the API ref need to get changed. I always forget about those.

**Comment by jgravois** [comment]
no worries.  I'll go through and fix em.

**Comment by jgravois** [comment]
fixed via 361a8323a1af28c474c421e859c5463bd4e1835d
thanks again!
