### ISSUE TITLE
"main" field in package.json points to non-existent file (re v2.0.0-beta.4 published on npm)

### ISSUE THREAD

**Issue by burmisov** [Esri/esri-leaflet#604]
`"main"` field in `package.json` points to "src/EsriLeaflet.js" which is not present in the published package, hence  `require('esri-leaflet')` doesn't work as expected.

Steps to reproduce:
```sh
npm i esri-leaflet@2.0.0-beta.4
cat node_modules/esri-leaflet/package.json | grep main # ..."src/EsriLeaflet.js"
ls node_modules/esri-leaflet/ # no 'src' folder
```

**Comment by jgravois** [comment]
confirmed that 2.0.0-beta.5 includes the appropriate `src` folder content. 
see @patrickarlt's explanation [here](https://github.com/Esri/esri-leaflet/pull/607#issuecomment-125638805)

thanks for reporting!
