### ISSUE TITLE
Feature layer logs to console (possibly mistakenly left debug info) (Re master version)

### ISSUE THREAD

**Issue by burmisov** [Esri/esri-leaflet#605]
https://github.com/Esri/esri-leaflet/blob/master/src/Layers/FeatureLayer/FeatureLayer.js#L151
https://github.com/Esri/esri-leaflet/blob/master/src/Layers/FeatureLayer/FeatureLayer.js#L165

Thus to reproduce: Create and use a FeatureLayer. See browser console - lots of `true` log entries.

**Comment by patrickarlt** [comment]
Yup these got missed in the last version. Thanks for filing this.

**Comment by patrickarlt** [comment]
Removed these in 2.0 beta 5

**Comment by jgravois** [comment]
fixed via e42705ea9a88aa3d77160b2735b81eeb0aaf32df

**Comment by jgravois** [comment]
jinx!
