### ISSUE TITLE
Uncaught TypeError: L.esri.dynamicMapLayer is not a function

### ISSUE THREAD

**Issue by erg-web** [Esri/esri-leaflet#606]
Hi

Created a Drupal leaflet map module that uses esri-leaflet to display Dynamic ArcGIS layers. 

http://nrmm.london/nrmm/nrmm-map

`drupal_add_js('//cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.3/leaflet.js','external');`
`drupal_add_js('//cdn.jsdelivr.net/leaflet.esri/latest/esri-leaflet.js', 'external');`

Suddenly stopped working with JS errors, probably as latest CDN esri JS file has been updated:

**Uncaught TypeError: Cannot read property 'extend' of undefined**

 **Uncaught TypeError: L.esri.dynamicMapLayer is not a function**

Tried to roll back to v1.0 but creates different error:

`drupal_add_js('//cdn.jsdelivr.net/leaflet.esri/1.0.0/esri-leaflet.js', 'external')`

**Uncaught TypeError: Cannot read property 'replace' of undefined**

Cant find which version of the esri js it was that worked? Any ideas?

**Comment by patrickarlt** [comment]
@erg-web as noted in the breaking changes section https://github.com/Esri/esri-leaflet/releases/tag/v1.0.0 in the 1.0.0 release the method signature for all layer types changed from 

```
L.esri.dynamicMapLayer(url, options);
```

to 

```
L.esri.dynamicMapLayer({
  url: url
});
```

This was done for a few reasons detailed in https://github.com/Esri/esri-leaflet/issues/578

If you rollback to the last release candidate you should be ok until you decide to upgrade.

**Comment by erg-web** [comment]
thank you - all fixed
