### ISSUE TITLE
Feature layer fires an error when removed from map (re 2.0.0-beta.4)

### ISSUE THREAD

**Issue by burmisov** [Esri/esri-leaflet#609]
Specifically, `Uncaught TypeError: Cannot read property 'getBounds' of null` happening [here](https://github.com/Esri/esri-leaflet/blob/master/src/Layers/FeatureLayer/FeatureLayer.js#L171)

Reproduce:
1. Set up map
2. Add a FeatureLayer
3. Remove this FeatureLayer.

[fiddle](http://jsfiddle.net/64pympm0/) (see console)

Unfortunatelly I still didn't get a good idea of how the thing works to submit a descent PR, sorry.

**Comment by patrickarlt** [comment]
Fixed in 2.0 beta 5 but I'm leaving this open so I can write a unit test to catch this in the future.
