### ISSUE TITLE
WGS84 basemap - End Tile missing

### ISSUE THREAD

**Issue by scottlepp** [Esri/esri-leaflet#611]
Does the esri-leaflet plugin support WGS84 basemaps?  http://services.arcgisonline.com/arcgis/rest/services/ESRI_Imagery_World_2D/MapServer

In this example it appears the End Tile is missing:  http://plnkr.co/edit/3AttKI?p=preview

**Comment by jgravois** [comment]
from the [API Reference](http://esri.github.io/esri-leaflet/api-reference/layers/tiled-map-layer.html)
> Your map service must be published using the Web Mercator Auxiliary Sphere tiling scheme (WKID 102100/3857) and the default scale options used by Google Maps...

see also #171, #105, #194

**Comment by patrickarlt** [comment]
@scottlepp also from the service data

> This map is in Extended Support and is no longer updated. Esri recommends that you use World_Imagery instead (ArcGIS 9.3 or higher is required)

which is as easy as 

```js
L.esri.basemapLayer('Imagery').addTo(map);
```

**Comment by scottlepp** [comment]
Thanks guys, unfortunately the actual service is private to the organization, so I can't just use 'Imagery'.

As a side note, It does work directly with Leaflet 1.x beta:  http://plnkr.co/edit/2KZdXt?p=preview

**Comment by jgravois** [comment]
projection support was overhauled completely in leaflet 1.x, so i wouldn't be surprised if everything *just works* when you drop our compatible plugin on top too. :)

we're still in the middle of updating the website, but you can find a CDN copy [here](//cdn.jsdelivr.net/leaflet.esri/2.0.0-beta.5/esri-leaflet.js)

**Comment by patrickarlt** [comment]
> Thanks guys, unfortunately the actual service is private to the organization, so I can't just use 'Imagery'.

It never is that easy huh... 

It does "just work" now at least for WGS84 basemaps. http://plnkr.co/edit/T6ZX1KQJQg0b8BCZa137?p=preview.

```js
var map = L.map('map',{crs: L.CRS.EPSG4326}).setView([0,0], 0);

L.esri.tiledMapLayer({
  url: 'http://services.arcgisonline.com/arcgis/rest/services/ESRI_Imagery_World_2D/MapServer'
}).addTo(map);
```

We need to test the new projections stuff throughly and reevaluate what we say we support. This probally means retesting all the layer types with a WGS84 basemap and making sure all the features line up.

**Comment by scottlepp** [comment]
I can't upgrade yet unfortunately.  I did get it working with leaflet 0.7.x by creating a custom crs based on the EPSG4326 crs defined in Leaflet 1.0.  http://plnkr.co/edit/3AttKI?p=preview

**Comment by jgravois** [comment]
glad to hear it @scottlepp.  

@patrickarlt i tested a few `L.esri.featureLayer` and `L.esri.dynamicMapLayer`s in 2.0.0 and they lined up great.  i did notice though that the browser choked out almost immediately when i tried to draw 1k points.  this seems strange, especially since there is **no** reprojection required to draw lat/long geojson on a lat/long map.

**Comment by patrickarlt** [comment]
@jgravois can you put togather a js fiddle or similar of the performance issue?

**Comment by patrickarlt** [comment]
Since this is generally working now I'm going to close it. We can investigate reprojection performance in another issue.
