### ISSUE TITLE
Understanding ArcGIS Online auth

### ISSUE THREAD

**Issue by rowanwins** [Esri/esri-leaflet#616]
Gday @patrickarlt & @jgravois ,

I'm just working on an application that requires ArcGIS online authentication to access secure services that are hosted by AGO. I've managed to successfully use the [OAuth2 approach as per your demo](https://esri.github.io/esri-leaflet/examples/arcgis-online-auth.html) however Im wondering if it's possible to have more of an standard login page for my app rather than flashing up that oauth2 page in a separate window. Is it possible (& secure) to do something more like the [AGS auth demo](https://esri.github.io/esri-leaflet/examples/arcgis-server-auth.html) to do a post request to generate my token for AGO based on input from a custom form?

Any tips would be greatly appreciated,

Thanks,
Rowan

**Comment by aaronpk** [comment]
@rowanwins It's not safe to ask for the user's username and password. However you don't need to pop up the login page in a separate window, you can redirect to it instead. There are some more docs on that here: https://developers.arcgis.com/authentication/browser-based-user-logins/

**Comment by rowanwins** [comment]
Thanks @aaronpk , From the sounds of your description I could have my application follow a workflow a bit like [this argis js api example](http://developers.arcgis.com/javascript/samples/portal_oauth_inline/). 

I'm still not entirely sure what the unsafe part of a form is but I think that's a whole other lesson in auth for another day, probably an important one!

Anyway I'll have a play and see how I go! 
Thanks

**Comment by patrickarlt** [comment]
> I'm still not entirely sure what the unsafe part of a form is

@rowanwins the idea is to prevent phishing attacks that attempt to spoof sign in forms. By showing the URL the user allowed to know 2 things

1. That the connection I am sending my credentials over is secure.
2. That I am sending my credentials to a domain I trust.

If you dont show the URL bar (like asking for username/password in a modal vs popup) that modal could technically send those credentials anywhere and be malicious without you or the user knowing.

**Comment by aaronpk** [comment]
Developers should *never* ask users for their ArcGIS or any other passwords. Think of it this way, would you feel comfortable giving a random application your Email login and password? I sure hope not! That's the problem OAuth solves.

**Comment by rowanwins** [comment]
Thanks for the fuller explanations @patrickarlt and @aaronpk , that is starting to make more sense now!
