### ISSUE TITLE
Handling empty responses from feature service edits

### ISSUE THREAD

**Issue by mikefedak** [Esri/esri-leaflet#621]
I noticed some issues with addFeatures in esri-leaflet 1.0.0

Error and success are handled properly, however the library throws a type error if an empty object is returned from the server. I would suggest handling the empty return as an error.

**Comment by jgravois** [comment]
I only recall having seen `success` and `err` responses.  would you be able to elaborate?

**Comment by mikefedak** [comment]
It may just be the server configuration I am working with but attempting to use esri-leaflet the published featureservices and addFeature results in an empty object response from the server. I started to try and narrow the issue down but decided instead to just write my own call for handling editing.

**Comment by jgravois** [comment]
i'd be happy to try and trap the problem here if you can provide a repro case or more information about exactly what's wrong with your requests.

**Comment by jgravois** [comment]
closing, but happy to chat more if you can provide more info.
