### ISSUE TITLE
continual requests for image map layer when panning/zooming

### ISSUE THREAD

**Issue by dodriscoll** [Esri/esri-leaflet#622]
I have a map with 2 layers, these layers are from a single image Map service with the data rendered in two different ways using raster functions.  The requests for the layers fire continually when I zoom or pan quickly and they all need to be completed before the image is shown which slows down the rendering of the map considerably.  If there was a way to check if the next pan/zoom occurs before all the tiles are loaded and that request is cancelled or not post the request if a new request is made within a few seconds of the last one that would be great. 

Is this possible to do?  I've tried removing the layers on map move and readding on map zoom end but it just makes things worse!  Sorry if this has been done and is obvious I'm not a competent programmer.  Attached is a screen grab of what I'm talking about you can see the calls in the bottom of the page
![imagemaplayer](https://cloud.githubusercontent.com/assets/13163573/9387612/4d001eb2-4759-11e5-9a91-74ba9b54ab80.png)

**Comment by jgravois** [comment]
does the version of the API you are using include the fix described in #498?

**Comment by dodriscoll** [comment]
Yes it does, it's the most recent release esri-leaflet-v2.0.0-beta.5.  I've put the following into my code:
  map.on("zoomstart", function (e){
	map.spin(true);
	Bathy.removeFrom(map);
	BathyShaded.removeFrom(map);
	 });	
  map.on("zoomend", function (e) {
	Bathy.addTo(map);
	BathyShaded.addTo(map); 
 });	
  map.on("dragstart", function (e){
	map.spin(true);
	Bathy.removeFrom(map);
	BathyShaded.removeFrom(map);
	  
});	
  map.on("dragend", function () {
	Bathy.addTo(map);
	BathyShaded.addTo(map); 
 });	
Bathy.on('load',function(e){
          map.spin(false);
      }, 3000);

**Comment by dodriscoll** [comment]
Also I was seeing some jumpiness when panning or zooming especially on mobile devices and when panning/zooming would complete the page didn't seem to refresh with the final destination.  It would display intermittent tiles so although I have 2 layers that should overlay exactly; a greyscale and a colour images, these would be offset so I'd get something like the screenshot below.  This seems to be fixed with the above code but is it maybe a bit overkill removing and re-adding layers?

![screenshot_2015-08-18-22-30-10](https://cloud.githubusercontent.com/assets/13163573/9404183/1ad85d82-47e5-11e5-9afb-5f0d3460784a.png)

**Comment by patrickarlt** [comment]
@dodriscoll I'm going to just guess that you server is REALLY slow (your screenshot shows it taking 800-1000ms) to respond.

I would try incresing the `updateInterval` option on `dynamicMapLayer`

```js
var layer = new L.esri.dynamicMapLayer({
  url: "whatever",
  updateInterval: 500 // only make new requests every half second at most.
}).addTo(map);
```

I think you are just overwhelming your server which makes subsequent call slow.

Going to close this for now. If problems persist please reopen with an example if possible.

**Comment by dodriscoll** [comment]
thanks Patrick I changed the update interval which helped but it is still quite slow so I may look into that.

I have made the website available as it was required to be presented during our annual project conference so if you are interested you can see it on http://maps.marine.ie/infomarbathymetry.

Any feedback welcome!

**Comment by jgravois** [comment]
looks really good!

* a little jarring that you can't pan west
* would be cool if the tools in top righthand corner were toggles (instead of displaying a second button when they're activated
* would be helpful if the ocean depth tooltip was clearer that you have to click on your own bathymetry overlay to get a result
* would be cool if activating a second tool automatically toggled the first off

**Comment by patrickarlt** [comment]
@dodriscoll App looks good. I'm going to close this since I think you can resolve a lot of this just by making your server respond faster.
