### ISSUE TITLE
Broken links to FeatureLayerService in documentation 

### ISSUE THREAD

**Issue by nawatts** [Esri/esri-leaflet#623]
On http://esri.github.io/esri-leaflet/api-reference/, in the "Base Classes" section of the sidebar, the link to "FeatureLayerService" is broken.

It points to http://esri.github.io/esri-leaflet/api-reference/services/feature-layer.html whereas it looks like it should point to http://esri.github.io/esri-leaflet/api-reference/services/feature-layer-service.html.

Also, on http://esri.github.io/esri-leaflet/api-reference/layers/feature-layer.html under the table in the "Events" section there is another link with the same issue.

**Comment by jgravois** [comment]
@sidewalkballet fixed those problems a couple days ago in #618.  we'll be pushing her changes to the live site shortly.

**Comment by nawatts** [comment]
Awesome. Sorry about the duplicate, didn't think to look at pull requests before submitting.

**Comment by jgravois** [comment]
no worries at all.  thanks for taking the time to report!
