### ISSUE TITLE
How Can I Update Attibution

### ISSUE THREAD

**Issue by Behseini** [Esri/esri-leaflet#627]
I am using Leftlet and creating a Map Like this

<code>
var map = L.map('map').setView([54.793577, -126.687482], 6);
          L.esri.basemapLayer('NationalGeographic').addTo(map);
</code>

now can you please let me know how I can update the leaflet-control-attribution  to display the following information
<code>
 attribution: '&copy; <a href="http://www">Thesite</a> contributors, Points &copy 2012 LINZ'
</code>

I tried this way 
<code>
var map = L.map('map').setView([54.793577, -126.687482], 6, {attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors, Points &copy 2012 LINZ'});

</code>

but it didn't worked

**Comment by jgravois** [comment]
if you'd like to insert generic mapwide text that is **not** associated with one layer in particular, you can/should utilize the `addAttribution()` method of Leaflet's own [Attribution Control](http://leafletjs.com/reference.html#control-attribution-addattribution) which is available via the map object by default.

```js
map.attributionControl.addAttribution('hello there!');
```

**Comment by Behseini** [comment]
Thanks jgravois
