### ISSUE TITLE
how to overlay multiple tile layers with different starting origin ?

### ISSUE THREAD

**Issue by ReneeLai** [Esri/esri-leaflet#630]
if there's a way to overlay multiple tile layers with different tile origin .

origin1
![1](https://cloud.githubusercontent.com/assets/8597127/9728773/e15dda80-563c-11e5-94df-ce898ca73f3d.png)

origin2
![2](https://cloud.githubusercontent.com/assets/8597127/9728776/e75f5a94-563c-11e5-802d-372d45400749.png)

I had try this 
but I have no idea how to overlay the second layer with different tile origin 

<code>

    var  _CRS3826 =new L.Proj.CRS('EPSG:3826',
            '+proj=tmerc +lat_0=0 +lon_0=121 +k=0.9999 +x_0=250000 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs', {
           origin: [-2000000.0 ,7000000.0],
           resolutions: [
             793.7515875031751,
             264.5838625010584,
             132.2919312505292,
             66.1459656252646,
             39.687579375158755,
             26.458386250105836,
             13.229193125052918,
             6.614596562526459,
             3.9687579375158752,
             2.6458386250105836,
             1.9843789687579376,
             1.3229193125052918,
             0.6614596562526459,
             0.26458386250105836
           ]
         });

     var _map = L.map(HTMLMap, {
                      scrollWheelZoom: true,  
                      maxZoom: 13,
                     minZoom: 0,
                    inertiaDeceleration: 2000,
                    crs:_CRS3826,
                     drawControl: false
                  }).setView([ centerX, centerY], level);

                 var  _layer = L.esri.tiledMapLayer( _servicesURL, {
                               token: _Token,
                               useCors: true,
                               opacity: 1,
                               id:LayerOption.ID,
                               continuousWorld: true, 
                               attribution: _mapDes
                            }).addTo(_map);
</code>

**Comment by jgravois** [comment]
since custom CRS properties like origin are assigned directly to the map, I don't see how we could support overlaying two TiledMapLayers with different schemas.

I could be mistaken, but I don't think this is possible in our flagship JSAPI either.

**Comment by jgravois** [comment]
just out of curiousity, whats the benefit in publishing different esri tiled map services using the same projected coordinate system but different origins?

**Comment by patrickarlt** [comment]
@jgravois has it right you cannot use 2 different CRSs on the same map. You best bet would be to republish one service so the origin is the same.

**Comment by jgravois** [comment]
closing this issue, but happy to chat more if it'd be helpful

**Comment by ReneeLai** [comment]
Our company publishes web mapping services of Taiwan only rather than a global scale.
 
If there's no standard for cases like this, we would have different origins using Services from different sources.

**Comment by jgravois** [comment]
publishing services with different reference data doesn't mean each needs to have its own unique coordinate system with unique origin.  whether you adopt one of the local projections for taiwan that comes installed with ArcGIS or define an alternative, you aren't obligated to cache tiles for the whole world.

**Comment by ReneeLai** [comment]
We haven't come across such issue before while using Esri Javascript API and Esri API for Flex, not unitl recently when we start using leaflet. I will discuss further with our GIS personnel regarding this and seek for alternative approach. Thank you for your reply.
