### ISSUE TITLE
Should be able to pass identify options into bindPopup for a dynamic layer

### ISSUE THREAD

**Issue by anatolyg** [Esri/esri-leaflet#633]
Right now there are defaults that are applied to the identify call from a dynamic layer. It would be great to be able to pass an options object that overwrote some of those. For example, I might not want to return the geometry for the feature, or, I might want to make the tolerance higher (or lower).

**Comment by jgravois** [comment]
we typically expect people to call the [available methods](http://esri.github.io/esri-leaflet/api-reference/tasks/identify-features.html) for setting identify request properties in advance of calling `run()`.

```js
L.esri.Tasks.identifyFeatures({
    url: 'http://sampleserver6.arcgisonline.com/arcgis/rest/services/WorldTimeZones/MapServer'
})
.on(map)
.at([45.543, -122.621])
.layers('visible:1')
.returnGeometry(false)
.tolerance(3)
.run(function(error, featureCollection, response){
    console.log("UTC Offset: " + featureCollection.features[0].properties.ZONE);
});
```
is there a reason why this isn't ideal for you?

**Comment by anatolyg** [comment]
I create the layer using `L.esri.dynamicMapLayer` and then use the `bindPopup` to set up popup. I may do this to multiple layers on the same map, so it's really convenient that the layer itself handles the identify service creation (via `_getPopupData` function). But I don't see a way to pass options to the identify task from instanciating the layer this way. Totally possible I am missing something.

**Comment by jgravois** [comment]
thanks for clarifying..  i'll have to think about this a bit to try and decide the best way to expose an opportunity to get more fine grained control (ie: dynamicMapService initialization, when calling `bindPopup()` etc.)

would it be sufficient to be able to pass identifyParameters that applied to *all* layers, or are you expecting to set things differently layer by layer?

**Comment by anatolyg** [comment]
I hope layer by layer. Use case is time-based identify calls -- maybe you want to see data for a layer a year in the future of data for another layer. The single parameter set won't do there. But bigger picture, it would be useful to set a variety of parameters that are currently exposed via methods as parameters into the `identifyFeatures` call (and then allow for an `identify` field to be set during `dynamicMapLayer` init).

**Comment by jgravois** [comment]
but for the time being you can just listen for the map click, fire your own identifyFeatures request and display the results in a popup, correct?

**Comment by anatolyg** [comment]
Oh, for sure! This isn't blocking me, just a nice to have. I really like the bindPopup feature, just thought you guys might be interested in some feedback.

**Comment by jgravois** [comment]
> thought you guys might be interested in some feedback.

always. thank you for it. :smile:

**Comment by pdiddyb** [comment]
Is there any more thought to adding the ability to set tolerance per dyn layer?  I would actually take it on all dyn layers because on the phone people are having trouble hitting the features.

**Comment by jgravois** [comment]
> @pdiddyb: I would actually take it on all dyn layers because on the phone people are having trouble hitting the features.

its already possible to modify tolerance when [identifying](http://esri.github.io/esri-leaflet/api-reference/tasks/identify-features.html) on *all* layers using the corresponding method that has always been exposed.

```js
var map = new L.Map('map').setView([ 45.543, -122.621 ], 5);
L.esri.identifyFeatures({
    url: 'http://sampleserver6.arcgisonline.com/arcgis/rest/services/WorldTimeZones/MapServer'
})
  .on(map)
  // ...
  .tolerance(5) // default value is 3 screen pixels 
  .run(function(error, featureCollection, response){
    // ...
  });
```

**Comment by carrbrpoa** [comment]
@jgravois, I wish to do the same thing (modify tolerance parameter), but didn't get how this:

```
var mySpecificLayer = L.esri.dynamicMapLayer({
		url: ".../MapServer",
		layers: [0]
	});
mySpecificLayer.bindPopup(function (error, featureCollection) {
	if (error || featureCollection.features.length === 0) {
		return false;
	} else {
		// plot popup contents
	}
});
```

is related to your example

```
var map = new L.Map('map').setView([ 45.543, -122.621 ], 5);
L.esri.identifyFeatures({
    url: 'http://sampleserver6.arcgisonline.com/arcgis/rest/services/WorldTimeZones/MapServer'
})
  .on(map)
  // ...
  .tolerance(5) // default value is 3 screen pixels 
  .run(function(error, featureCollection, response){
    // ...
  });
```

Should I do that declaration for every specific layer I have? What about the `.at(<LatLng> latlng)`? I just want it working like `bindPopup`; is it possible?

**Comment by jgravois** [comment]
> but didn't get how this is related to your example

@carrbrpoa check out https://github.com/Esri/esri-leaflet/issues/919#issuecomment-276435165 for more information about that

until we decide on a way to expose more configuration options when calling `bindPopup()`, `identifyFeatures` gives you an opportunity to get more fine grained control. 

> Should I do that declaration for every specific layer I have?

you don't have to call it over and over because the operation is capable of returning results from multiple layers.

```js
var serviceUrl = 'http://sampleserver6.arcgisonline.com/arcgis/rest/services/WorldTimeZones/MapServer';

var id = L.esri.identifyFeatures({ url: serviceUrl })
  .on(map)
  // http://esri.github.io/esri-leaflet//api-reference/tasks/identify-features.html#methods
  .layers("all:0,1,2")
  .tolerance(5) 

map.on('click', function (evt) {
  id.at(evt.latlng);
  id.run(function(error, featureCollection, response){
    console.log(featureCollection);
  });
});
```

**Comment by jgravois** [comment]
i had another look at this today and i think we'd get the most bang for our buck by giving developers an opportunity to supply their own custom [IdentifyFeatures](http://esri.github.io/esri-leaflet/api-reference/tasks/identify-features.html) object when they instantiate their dynamicMapLayer
```js
var customBehavior = L.esri.identifyFeatures({ url: serviceUrl })
  .layers("all:0,1,2")
  .tolerance(5)
  // etc.

var dynamicLayer = L.esri.dynamicMapLayer({
  url: serviceUrl,
  popup: customBehavior
}).addTo(map);

dynamicLayer.bindPopup(/* ... */)
```

this would allow for more fine-grained control over the `/identify` request triggered by 'bindPopup()' *without* increasing the surface area of the API.

**Comment by Biboba** [comment]
Hi @jgravois,

I gave it a try there: [c750ac](https://github.com/Biboba/esri-leaflet/commit/c750ac7935ce8b4f82e166d5fe47ea775fd09537)

What do you think ?

Thanks

**Comment by jgravois** [comment]
@Biboba very cool! 

please open up a PR so i can take a deeper look, hopefully later this week.

**Comment by jgravois** [comment]
in #1031 @biboba implemented my pseudo-code in https://github.com/Esri/esri-leaflet/issues/633#issuecomment-316863090 in the actual library.

thank you for another excellent contribution! 🎉
