### ISSUE TITLE
add sample to demonstrate controlling drawOrder

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet#634]
show people how to add layers in order with panes.

**Comment by patrickarlt** [comment]
I nominate @nikolaswise for this since he was really excited to use it.

**Comment by alaframboise** [comment]
Is there something beyond listening for when the layer is finished loading to force the draw order you want?

**Comment by nikolaswise** [comment]
Whoops thats me. In the new leaflet 1.0, you can add panes to a map and add layers to the pane.

```
map.createPane('one')
var layerOne = L.geoJson(data, {
  pane: one
})
layerOne.addTo(map)

map.createPane('two')
var layerTwo = L.geoJson(data, {
  pane: two
})
layerTwo.addTo(map)
```

**Comment by jgravois** [comment]
as of Leaflet 1.0, you can specify a pane by name when you construct your objects.  this isn't documented on the public site yet (and won't be until Leaflet declares final), but you can spin up the website locally using `grunt`.

**Comment by nikolaswise** [comment]
https://github.com/Esri/esri-leaflet/pull/669
