### ISSUE TITLE
L.esri.request() questions

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet#640]
##### what exactly is the point of `L.esri.get.JSONP` and `L.esri.get.CORS`?  

i thought the only time you have to worry about CORS support (or a fallback) was for POST requests.
am i missing something?

##### don't we need to introduce the ability to reference a proxy when calling `L.esri.request()` directly if we say we support JSONP?  

right now support for proxies is only built directly into [`L.esri.Services.Service`](http://esri.github.io/esri-leaflet/api-reference/services/service.html).
it looks like you can stuff a proxy into the url itself when calling `L.esri.request()`, but that's pretty ugly.

```js
L.esri.request('http://localhost/myproxy.php?http://sampleserver6.arcgisonline.com/arcgis/rest/services/', {
  fakeParam: 'value to the push request past 2000 characters'
}, function (error, response) {
  if (error) {
    console.log(error)
  } else {
    console.log(response)
  }
})
```

**Comment by patrickarlt** [comment]
If a browser doesn't support CORS you need JSONP for GET requests too, this means IE 9.

**Comment by patrickarlt** [comment]
Reopening because I didn't respond to the proxy issue.

So should we/do we need to support proxies in the request methods?

It would be pretty simple to do

```js
L.esri.request('http://sampleserver6.arcgisonline.com/arcgis/rest/services/', {
  useProxy: 'http://localhost/myproxy.php'
}, callback)
```

This is a little weird because then you mix request options with request params even something like

```js
L.esri.request('http://sampleserver6.arcgisonline.com/arcgis/rest/services/', {
  $proxy: 'http://localhost/myproxy.php'
}, callback)
```

still feels odd but if you think it is needed.

**Comment by jgravois** [comment]
> If a browser doesn't support CORS you need JSONP for GET requests too, this means IE 9.

thanks for clarifying.  i assumed (incorrectly) that since you *only* need to configure a proxy in the [jsapi](https://developers.arcgis.com/javascript/jshelp/ags_proxy.html) to help form JSONP **POST** requests when CORS was not supported, that a GET was just a GET.

i can see now that it is necessary, as you said, to utilize JSONP even even when making a simple GET request to a non cors enabled ArcGIS Server instance.

```js
// L.esri.request( will fail
L.esri.get.JSONP('http://sampleserver1.arcgisonline.com/ArcGIS/rest/services/Demographics/ESRI_Census_USA/MapServer', {}, function(error, response){
    if(error){
      console.log(error);
    } else {
      console.log(response);
    }
  });
```

with regard to tacking on a constructor option to L.esri.request(), i think we're probably okay with the workaround described in my first comment for now, but i'll add a FAQ tag to this thread and hope that if anyone else wants/needs more explicit proxy support in the future, they'll let us know.
