### ISSUE TITLE
Force requests to be POST

### ISSUE THREAD

**Issue by tinksthomas** [Esri/esri-leaflet#641]
Is there a way to force the requests to be POST requests always? I know there are conditions that esri-leaflet forces this (E.G. if CORS is enabled and request length is over 2000 etc) but it would be good if there this was a parameter that could be set. I imagine it's probably easy enough to patch esri-leaflet in my case but I thought other people may like this feature too.

**Comment by jgravois** [comment]
have you tried using `L.esri.post()`?

**Comment by jgravois** [comment]
oh, nevermind.  sounds like you are talking about other methods that invoke requests as well...

what is an example use case in which invoking a POST automatically would be useful?

**Comment by tinksthomas** [comment]
Unfortunately our use case is pretty lame - it's a workaround for a request that fails every second time when using get requests. I guess there may not be too many valid use cases for forcing to POST requests.

https://geonet.esri.com/thread/64835

So in my case (contrived example):

```javascript

var  myFeatureLayer({
     url: 'http://.../MapServer/0'
   });

function myFunction() { //this will fail every second time it's called due to the ArcGIS server bug
    myFeatureLayer.query().where("OBJECTID IN (1894,2019)");
}
```

Cheers

Andrew

**Comment by jgravois** [comment]
that's an old bug, but it was a doozie!

if you really can't upgrade ArcGIS Server, you can also do something like this to make sure each request is unique

```js
// add a unique timestamp to each request
myFeatureLayer.query().where("OBJECTID IN (1894,2019) " + Date.now() + "=" + Date.now());
```

**Comment by tinksthomas** [comment]
That should work for me. Cheers.

**Comment by jgravois** [comment]
cool.  just make sure and overwrite your `where` clause each time you plan on calling `run()` to ensure that the requests are unique.
