### ISSUE TITLE
we need a sample which demonstrates use of L.esri.query()

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet#642]

**Comment by vielmetti** [comment]
Is it just a matter of adapting the docs at http://esri.github.io/esri-leaflet/api-reference/tasks/query.html ?

**Comment by jgravois** [comment]
I was thinking of another whole page example similar to the ones [here](http://Esri.github.io/esri-leaflet)

**Comment by patrickarlt** [comment]
@jgravois could be an adaptation of http://esri.github.io/esri-leaflet/examples/feature-layer-snapshot.html
