### ISSUE TITLE
Feature Layer maxZoom not respected when zooming out

### ISSUE THREAD

**Issue by SamDrummond** [Esri/esri-leaflet#643]
I have encountered a few issues with the FeatureLayer minZoom and maxZoom. In trying to set up a test case, I actually encountered a situation where the maxZoom appears to be ignored when the map is zoomed out beyond the maxZoom level parameter.

Steps to recreate:
1. Open http://codepen.io/anon/pen/MaewrR
2. Zoom in two or three levels
3. The feature layer markers should be visible
4. Zoom to the original extent

Issue - the marker symbols stay visible not respecting the maxZoom parameter.

**Comment by patrickarlt** [comment]
It looks like this specifically has to do with https://github.com/Esri/esri-leaflet/blob/master/src/Layers/FeatureLayer/FeatureLayer.js#L164

We can probably modify this conditional to make it so it will still schedule remove if the layer is out of zoom range.

**Comment by SamDrummond** [comment]
Do you mind if I take a look at it?

**Comment by patrickarlt** [comment]
@SamDrummond @rowanwins already took a look at it in https://github.com/Esri/esri-leaflet/pull/660 and I did a review https://github.com/Esri/esri-leaflet/pull/660#issuecomment-151680624 and figured out that this is more complex then it first appears.

You could certainly decide to tackle it alongside @rowanwins or separately if you want. @rowanwins wanted some time to take a look at it so I wont be tackling it for awhile.

**Comment by rowanwins** [comment]
If you're keen @SamDrummond go for it, if you get stuck or can't find the time let me know and Im happy to take another look.
Cheers

**Comment by SamDrummond** [comment]
Cheers @rowanwins. I'll have a look at it and let you know how I get on.
