### ISSUE TITLE
Is ES6 Promise object okay to use in esri-leaflet plugins?

### ISSUE THREAD

**Issue by phpmaps** [Esri/esri-leaflet#646]
Is this pattern ok to use?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise

**Comment by jgravois** [comment]
if youre okay with your plugin [not working in IE](http://caniuse.com/#feat=promises), thats okay with me, you'll just need to mention it in your doc.

**Comment by phpmaps** [comment]
@jgravois  - Ok, thanks.  No further questions.
