### ISSUE TITLE
Race condition due to asynchronous initialization of TiledMapLayer

### ISSUE THREAD

**Issue by blq** [Esri/esri-leaflet#649]
TiledMapLayer uses the asynchronous metadata MapService call in the onAdd method. 
But there seem to be no way to get notified when the async service call is finished. 
This leads to the case were the map's "layeradd" event fires before the TileMapLayer setup is actually ready, which might cause race condition in initialization. I.e other code that starts to manipulate the map/layer will risk doing so before the Leaflet (Grid)layer's base "onAdd" call has run.

**Comment by patrickarlt** [comment]
I would like to be able to avoid this race condition but I'm also having a hard time seeing how this would cause anyone to have an error in a real application. The only alternative I can see is to override `createTile` in addition to `getTileUrl`, maybe something like this will work:

```js
createTile:  function (coords, done){
  var tile = document.createElement('img');

  L.DomEvent.on(tile, 'load', L.bind(this._tileOnLoad, this, done, tile));
  L.DomEvent.on(tile, 'error', L.bind(this._tileOnError, this, done, tile));

  if (this.options.crossOrigin) {
    tile.crossOrigin = '';
  }

  /*
   Alt tag is set to empty string to keep screen readers from reading URL and for compliance reasons
   http://www.w3.org/TR/WCAG20-TECHS/H67
  */
  tile.alt = '';

  // if the lod mapping is done load the tile sync
  // otherwise wait for the lod map and then set the tile URL.
  if(this._lodMap) {
    tile.src = this.getTileUrl(coords);
  } else {
    this.once('lodmap', function () {
      tile.src = this.getTileUrl(coords);
    })
  }

  return tile;
}
```

**Comment by patrickarlt** [comment]
Assigning myself to investigate this.

**Comment by patrickarlt** [comment]
I've got this fixed locally as a part of https://github.com/Esri/esri-leaflet/issues/668 since there was also a bug in `TileLayer` with the LOD stuff anyway.

**Comment by patrickarlt** [comment]
This will be resolved in the next version.
