### ISSUE TITLE
Break out dependencies

### ISSUE THREAD

**Issue by patrickarlt** [Esri/esri-leaflet#652]
Currently several things in the Esri Leaflet source code could be their own small modules.

* [x] `FeatureGrid` should just be included from https://github.com/patrickarlt/leaflet-virtual-grid
*  [x] `BinarySearchIndex` form https://github.com/Esri/esri-leaflet/blob/master/src/Layers/FeatureLayer/FeatureManager.js#L482-L531 could also be included.
*  [x] The GeoJson/ArcGIS JSON utils https://github.com/Esri/esri-leaflet/blob/master/src/Util.js#L3-L350 I've gotten lots of interest in breaking this out from Terraformer as well.

This would mean that a lot of the tests might run better since we could remove tests for all of these things and it would create some other useful libraries that we could reuse in other applications.

**Comment by jgravois** [comment]
i'm happy to chip in.  

i was thinking the other day of taking a crack at extending http://geojson.io to show/draw esri.json anyway and your third bullet sounds like exactly the dependency that'd be helpful :smile:

**Comment by jgravois** [comment]
do you want me to knock out de-coupling `BinarySearchIndex` in preparation for releasing 2.0.0-beta.7?  i can also kick the can down the road and do it afterward.

**Comment by jgravois** [comment]
beat me to it.
