### ISSUE TITLE
L.esri.Util.arcgisToGeojson could not convert polygon?

### ISSUE THREAD

**Issue by bestpika** [Esri/esri-leaflet#653]
I am using esri-leaflet v1.0.0 and leaflet v0.7.5.
I trying to use L.esri.Util.arcgisToGeojson(Feature), but it always return null...
like this
![console](http://i.imgur.com/NuJKYUI.png)

code
```javascript
var findRun = function (txt, layers, layer, field) {
    fg.clearLayers();
    layers.find().layers(layer).text(txt).fields(field)
          .run(function (e, fc, r) {
              if (e) {
                  return false;
              }
              else {
                  L.geoJson(fc, {
                      onEachFeature: function (f, l) {
                          var type = f.geometry.type,
                              id = f.id,
                              center;
                          console.log(f);
                          console.log(L.esri.Util.arcgisToGeojson(f));
                      }
                  })
              }
          });
}
```

**Comment by jgravois** [comment]
the method youre calling expects you to pass in a feature described using Geoservices/Esri JSON and will convert it to GeoJson.

even though not all ArcGIS services emit GeoJson natively (yet), the features returned by Esri Leaflet functions are always *already* GeoJson
so there's no need for you to convert them yourself.
