### ISSUE TITLE
geometries of returned features in identify sample don't look right

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet#656]
click on joshua tree in the sample [here](http://esri.github.io/esri-leaflet/examples/identifying-features.html) and notice that the returned feature is just a bunch of oversimplified triangles.
![screenshot 2015-10-19 09 34 25](https://cloud.githubusercontent.com/assets/3011734/10583956/9a998c2a-7644-11e5-8bd5-827b32466c13.png)

it doesn't look like we are asking for an altered geometry in our request, so maybe its just the service?
if so, it'd probably be easiest to just point at a different one.

**Comment by patrickarlt** [comment]
@jgravois this service is terrible anyway. If you can find a better one please switch to it!

**Comment by patrickarlt** [comment]
@jgravois http://hydrology.esri.com/arcgis/rest/services/WorldHydroReferenceOverlay/MapServer is pretty good... we could switch all the samples over to it...

**Comment by patrickarlt** [comment]
[Federal User Community](https://www.arcgis.com/home/search.html?q=owner%3AFederal_User_Community&start=1) and [Esri Disaster Response](https://www.arcgis.com/home/search.html?q=owner%3AEsri_DisasterResponse_DM&start=1) also have some pretty good stuff.

**Comment by jgravois** [comment]
closed via 3bd3f56

hydrology service is sweet, but i only used it for display because its sublayers are obfuscated.
