### ISSUE TITLE
enhancement: make sure text search in 'finding features' sample isn't case-sensitive

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet#657]
'texas' doesn't return a match in the sample [here](http://esri.github.io/esri-leaflet/examples/finding-features.html), but 'Texas' does.

it'd be cool if we had logic in the sample to ensure that the match **isn't** case-sensitive.  at a bare minimum, we should include placeholder text that demonstrates a search string which will return a result.

**Comment by patrickarlt** [comment]
@jgravois can you actually just remove this demo. We can think of a better one to show off `find`.

**Comment by jgravois** [comment]
28380f5
