### ISSUE TITLE
Invalid links in documentation site

### ISSUE THREAD

**Issue by kneemer** [Esri/esri-leaflet#661]
I believe the documentation is still for 1.0.0, correct?  I could correct these links but I'm not sure what branch to be using and how to build the site.  I'm going to put them all here for whomever tackles it.

http://esri.github.io/esri-leaflet/api-reference/ 
 * In the sidebar FeatureLayerService points to services/feature-layer.html not services/feature-layer-service.html
 * The sidebar does not have RasterLayer but the main section does and that link 404s

http://esri.github.io/esri-leaflet/api-reference/layers/feature-layer.html
http://esri.github.io/esri-leaflet/api-reference/layers/clustered-feature-layer.html
http://esri.github.io/esri-leaflet/api-reference/layers/heatmap-feature-layer.html
 * The note under events refers to L.esri.Services.FeatureLayer and points to services/feature-layer.html 

http://esri.github.io/esri-leaflet/api-reference/layers/tiled-map-layer.html
 * In Methods/identify() there is a reference to L.esri.services.IdentifyFeatures that 404s

http://esri.github.io/esri-leaflet/api-reference/tasks/query.html
 * FeatureLayer in constructor has 404 and in the description next to it the ImageService 404s

http://esri.github.io/esri-leaflet/api-reference/util.html
 * In the description for responseToFeatureCollection, the L.esri.Tasks.Identify 404s

http://esri.github.io/esri-leaflet/api-reference/services/map-service.html
 * In the identify description, the L.esri.Tasks.Identify 404s

**Comment by jgravois** [comment]
> the documentation is still for 1.0.0, correct?

yup.  most of the bad links are already fixed in #620, but i didn't realize initially that we were going to wait for Leaflet 1.0.0 final before pushing our own documentation updates.

there are several different ways to fix the problems in the interim
1. fix the site, merge into `master` and push to `gh-pages` (i can resolve conflicts in #620 afterward if necessary)
2. create a new isolated branch, build the site, PR against `gh-pages` manually and skip merging to `master`
3. checkout `gh-pages`, fix the html itself and push a new commit (which would be incredibly tedious)

**Comment by kneemer** [comment]
I could try the second approach for a temporary fix and branch off v1.0.0.

**Comment by alaframboise** [comment]
If possible, gh-pages fix would be appreciated for demo purposes. Thanks!

**Comment by kneemer** [comment]
@alaframboise I'll try again today.  I had made an attempt off the 1.0.0 release but those docs were even more out of date.  I need to figure out which commit to work from.

**Comment by kneemer** [comment]
Found another broken link just now on http://esri.github.io/esri-leaflet/api-reference/layers/feature-layer.html the link for `create a Feature Service from a CSV or Shapefile` is no longer valid. @patrickarlt any ideas what I should change this to?

**Comment by kneemer** [comment]
I'm going to change it to https://doc.arcgis.com/en/arcgis-online/share-maps/publish-features.htm unless you have a better link.
