### ISSUE TITLE
Can not set bboxSR and imageSR when create DynamicMapLayer.

### ISSUE THREAD

**Issue by bestpika** [Esri/esri-leaflet#662]
https://esri.github.io/esri-leaflet/api-reference/layers/dynamic-map-layer.html

DynamicMapLayer have option bboxSR and imageSR.
I set bboxSR and imageSR, but it not work.
```javascript
L.esri.dynamicMapLayer({ url: '...', bboxSR: 3857, imageSR: 3826 }).addTo(map);
```
But It always send
```
bboxSR=3857&imageSR=3857
```

I am using v1.0.0.

**Comment by jgravois** [comment]
i think this is because we're setting `bboxSR` and `imageSR` using the map.options in [`L.esri.RasterLayer`](https://github.com/Esri/esri-leaflet/blob/master/src/Layers/RasterLayer.js#L19-L23).

are you loading your DynamicMapLayer on top of an Esri basemap or other tiled layer? if so, what is its coordinate system?

**Comment by bestpika** [comment]
But API ref. says it have these options?

**Comment by patrickarlt** [comment]
@bestpika @jgravois we should probably remove these options from the API reference. We have to use the spatial reference from `map.options.crs` to make sure the image is output at the correct spatial reference for display on the map and that the bbox that we pass to the server is actually in a format the server can understand. So these options are actually ignored.

This probably needs a review now that we have a stable Proj4Leaflet project we can test against. We need to make sure people know how to override these options when using Proj4Leaflet.

> And my arcgis server output image is empty by bboxSR=3857&imageSR=3857.

@bestpika can you try the solution mentioned in https://github.com/Esri/esri-leaflet/issues/273 and manually set them after adding to the map?

Also are you using Proj4Leaflet to use a non web-mercator spatial reference?

**Comment by patrickarlt** [comment]
@bestpika I'm making progress on this as a part of #668, but it is going to require a rewrite an a pretty decent amount of testing so it might be a few days.

**Comment by patrickarlt** [comment]
@bestpika this should be fixed in the next version. You will not need to set `bboxSR` or `imageSR` they will be set for your based on `map.options.crs.code`. Look for more docs in the changelog when we release the next version.
