### ISSUE TITLE
Reference CDN in example

### ISSUE THREAD

**Issue by alaframboise** [Esri/esri-leaflet#663]
It would be helpful if the example [here](https://github.com/Esri/esri-leaflet) had a ref to the CDN instead of a local ref. Just like the examples.

```
<!DOCTYPE html>
<html>
  <head>
     <!-- Load Leaflet from CDN-->
    <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-1.0.0-b1/leaflet.css" />
    <script src="http://cdn.leafletjs.com/leaflet-1.0.0-b1/leaflet.js"></script>

    <!-- Load Esri Leaflet locally, after cloning this repository -->
    <script src="esri-leaflet/dist/esri-leaflet.js"></script>
```

**Comment by jgravois** [comment]
pull requests are being accepted.

**Comment by jgravois** [comment]
url would be:
`https://cdn.jsdelivr.net/leaflet.esri/2.0.0-beta.6/esri-leaflet.js`
at beta 2, leaflet changed their url syntax as well:
`http://cdn.leafletjs.com/leaflet/v1.0.0-beta.2/leaflet.js`

**Comment by jgravois** [comment]
done in #620
