### ISSUE TITLE
Error: Map Container Is Already Initialized

### ISSUE THREAD

**Issue by bibeputt** [Esri/esri-leaflet#666]
refreshing a  map giving Error: Map Container Is Already Initialized

**Comment by jgravois** [comment]
> refreshing a map

* what do you mean by that?  refreshing the page?  calling a map method like [`invalidateSize()`](http://leafletjs.com/reference.html#map-invalidatesize)?
* what version of esri-leaflet are you using?
* can you share a repro case?

**Comment by jgravois** [comment]
happy to help if you can provide more information.
