### ISSUE TITLE
Adding a Feature Layer does not use published symbology, but Dynamic Layer does

### ISSUE THREAD

**Issue by daniel-sabourin** [Esri/esri-leaflet#681]
If I add a Feature Layer, the symbology that is published is not displayed. If I add the same service, but as a Dynamic Layer, the symbology is displayed fine. Is this a bug, or is it intended behavior?

(Ignore the random grey symbol in both the images.)

## Example as Feature Layer

```javascript
var options = {
    url: "http://sampleserver1.arcgisonline.com/ArcGIS/rest/services/Louisville/LOJIC_PublicSafety_Louisville/MapServer/2",
    useCors: false,
};

map.addLayer(L.esri.featureLayer(options));
```

![Feature Layer] (http://i.imgur.com/qq8c4M6.jpg)

## Example as Dynamic Layer

```javascript
var options = {
    url: "http://sampleserver1.arcgisonline.com/ArcGIS/rest/services/Louisville/LOJIC_PublicSafety_Louisville/MapServer",
    layers: [2],
    useCors: false,
};

map.addLayer(L.esri.dynamicMapLayer(options));
```

![Dynamic Map Layer](http://i.imgur.com/xiQYHhR.jpg)

**Comment by jgravois** [comment]
its 'as designed'.  the second example asks ArcGIS Server to render its own .png and send it along to the client.  if you'd like to work with vector graphics and maintain the symbology of the service itself, please check out our [renderers plugin](http://esri.github.io/esri-leaflet/examples/renderers-plugin.html).

**Comment by daniel-sabourin** [comment]
Nice! Maybe I should have been browsing the documentation more. I got this working for my feature layers now.

Is there support for the clusteredFeatureLayer?

**Comment by jgravois** [comment]
if it doesn't, i can't imagine it would be a monumental undertaking to get it working.  can you log an issue [here](https://github.com/esri/esri-leaflet-renderers) please?

**Comment by kneemer** [comment]
There is not currently support but please do make an issue @daniel-sabourin.
