### ISSUE TITLE
bindPopup example not correct

### ISSUE THREAD

**Issue by stevehmig** [Esri/esri-leaflet#682]
On this page:
http://esri.github.io/esri-leaflet/api-reference/layers/feature-layer.html

The bindPopup example doesn't work:
featureLayer.bindPopup(function(features){
  return
    "Name: " + features.properties.NAME;
});

Putting the popup text on the same line as return does work. This works:
featureLayer.bindPopup(function(features){
  return "Name: " + features.properties.NAME;
});

**Comment by jgravois** [comment]
thanks again for this.  we'll fix shortly

**Comment by jgravois** [comment]
fix in 2cefbc20c7d1f2fb552a892bbd38c3854c3e9b32 will be live next time we push to `gh-pages`
