### ISSUE TITLE
Supporting tile map service with different LoDs

### ISSUE THREAD

**Issue by tc558** [Esri/esri-leaflet#687]
I'm trying to make a start on being able to use a tiled map service which has different levels of detail than the ArcGIS Online Schema and I'm running into issues that I can't quite fathom.

I've a tiled map service which shares the same schema as an ArcGIS Online service, except that the scales at the different LoDs are different.

I've updated the resolutions in the TileMapLayer.js to reflect the resolutions of this map service and whilst it would seem to initially work as you zoom in and out the geography changes. By that I mean you could zoom into France and as the map scale changes you are suddenly looking at Australia - or worse the app is requesting tiles that don't exist (getting 404's)......tile also seem to arranged incorrectly (so a tile for Australia may be put next to a tile from somewhere else so the map looks like gibberish)

Is there something in particular that I'm missing? Can anyone offer any pointers?

Thanks, Tony

BTW, the reason we're looking to do this is that we have a corporate standard for LoDs that all of our leaflet apps are being written to use and so loosing the ability to use AGOL services is not a significant issue at this stage.  Eventually I'd like to see if we can produce an update to the TileMapLayer.js that dynamically builds the necessary resolutions from the service's metadata each time a new layer is created / added - would this generally be of use?

**Comment by jgravois** [comment]
in general i'd recommend taking a hard look at whether or not you can adapt your *corporate* standard to get more in line with the universal web mercator standard.

that being said, you should be able to accomplish this without modifying the source of esri leaflet with [Proj4Leaflet](http://kartena.github.io/Proj4Leaflet/).  have you seen [this sample](http://esri.github.io/esri-leaflet/examples/non-mercator-projection.html)?

**Comment by tc558** [comment]
Thanks John - the corporate standard is to use Web Mercator, it just that the caches are produced with more rounded scales than the ArcGIS Online scheme.

For example, the first 6 scales used are:

1:500,000,000
1:250,000,000
1:130,000,000
1:125,000,000
1:64,000,000
1:32,000,000
etc.

I have the corresponding pixel resolutions and was using them as a direct replacement for the resolutions within the TileMapLayer.js as a starting place.

Since posting I've done a little more digging and there may be a discrepancy with the Tile Scheme Origin that has been used by ArcGIS Desktop that I'm investigating and will hopefully get a chance to test over the weekend or early next week.

I've also been trying to locate an up-to-date Tiling Scheme file for ArcGIS Online without success - would anyone know where one could be found?  I've seen there is one from 2007 in the blogs, but this lacks some of the levels now present in AGOL caches.

Thanks, Tony

**Comment by jgravois** [comment]
you can find the LODs (and other metadata) from our world streetmap [here](http://services.arcgisonline.com/arcgis/rest/services/World_Street_Map/MapServer?f=pjson).

**Comment by tc558** [comment]
Ideal - thanks for the pointer.

Will update the thread on progress next week.

**Comment by jgravois** [comment]
@tc558 can we provide any additional assistance?

**Comment by patrickarlt** [comment]
@tc558 I'm going to close this since there is no response.
