### ISSUE TITLE
create a 'make your first map' tutorial

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet#688]
show people how to mashup more than one plugin, etc..
maybe include some text that draws parallels/differentiates with the jsapi

**Comment by pmacMaps** [comment]
Do you mean more than one ESRI-Leaflet plugin, or using ESRI-Leaflet plugins with other ESRI plugins?  

Also, are you looking for contributors for this?  I've transitioned some embedded AGOL <iframe> maps to Leaflet maps, so I may be able to assist with this.

**Comment by jgravois** [comment]
> Do you mean more than one Esri-Leaflet plugin?

anything really.  thanks for the offer!  i just want to demonstrate the pattern that leaflet provides a lightweight core and requires its own script tag and `.css`, that esri-leaflet provides a bit more (and requires its own `.js`) and that other plugins follow the same pattern.

the place to stick this is in the new 'tutorials' section which has been stubbed out in our updated website, (in this repo but not yet pushed to production).

![tutorials](https://dl.dropboxusercontent.com/u/59331579/Screenshot%202015-12-31%2012.20.40.png)

if you have any trouble getting it set up [locally](https://github.com/Esri/esri-leaflet#development-instructions), please let me know.
