### ISSUE TITLE
Some samples are failing at https://esri.github.io/esri-leaflet due to mixed content

### ISSUE THREAD

**Issue by slead** [Esri/esri-leaflet#690]
This is just an FYI - some samples are failing on the esri-leaflet page, eg https://esri.github.io/esri-leaflet/examples/simple-dynamic-map-layer.html

`Mixed Content: The page at 'https://esri.github.io/esri-leaflet/examples/simple-dynamic-map-layer.html' was loaded over HTTPS, but requested an insecure script 'http://maps1.arcgisonline.com/ArcGIS/rest/services/USA_Federal_Lands/MapSer…e&bboxSR=3857&imageSR=3857&callback=window._EsriLeafletCallbacks.c0&f=json'. This request has been blocked; the content must be served over HTTPS.a.Request.get.JSONP @ Request.js:140`

**Comment by jgravois** [comment]
because we can't guarantee that all the sample services we use will be available over https, and because we aren't ever asking users for credentials, part of me thinks we should just force redirect everyone to [http](https://konklone.com/post/github-pages-now-sorta-supports-https-so-use-it).

**Comment by jgravois** [comment]
we've already replaced that sample, but i went ahead just know and made sure we load the new one explicitly using `https`.  thanks for reporting @slead!
