### ISSUE TITLE
should we establish a timeline to drop bower support?

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet#700]
most of bower's original maintainers have moved on, but the project has undergone a rally for funded support lately so proclamations that it is [dead](https://twitter.com/nachocoloma/status/663622545162280960) seem a bit dramatic to me.

i don't use bower, so from my point of view, keeping things in order here to ensure other people can is a [small pain](https://twitter.com/tmcw/status/587687343231934464). not because its a *lot* of work, but because the work needs to be done in
* esri-leaflet-renderers
* esri-leaflet-geocoder
* esri-leaflet-clustered-feature-layer
* esri-leaflet-heatmap-feature-layer
* esri-leaflet-gp
* esri-leaflet-related

you get the idea.

do we want to support installing via bower forever?
should we consider dropping support at `2.0.0` final?
maybe it would be better to add information to the FAQ warning that we'll ditch it at some specific point in the future?
perhaps we could just pass on the maintenance responsibility to those in the community that rely on it?

looking for feedback from anyone/everyone here.

**Comment by patrickarlt** [comment]
As much as a I would love drop bower support i think we need to keep it around. A lot of people requested it initially and that is why it is there. I agree with the reasoning but I think planning is a little premature.

**Comment by jgravois** [comment]
thats good enough for me.  i'll break it up again in 2017 :smile:
