### ISSUE TITLE
disableClientCache

### ISSUE THREAD

**Issue by bbinckes** [Esri/esri-leaflet#706]
This was an issue that Jeff G. added 12/22/2015 "How do you disable client caching in L.esri.Layers.DynamicMapLayer?"

The actual issue was related to the QueryTask on a FeatureLayer caching images.

**Comment by jgravois** [comment]
my reply to Jeff G. can be found [here](https://geonet.esri.com/thread/170100)

QueryTasks/FeatureLayers don't return images, but rather JSON features so it'd be really helpful if you are able to provide additional clarification and/or a code snippet to explain in more detail.

**Comment by bbinckes** [comment]
Continued....  Sorry I sent this prematurely.
Background:  The SDE data source that is backing this service is updated every 2 minutes so we need a mechanism to disable cache on the Query. 

I have updated esri leaflet and tested out the changes below which provides the behavior we are looking for but not sure if this is the correct way to approach this.

Added options to the instantiation of a FeatureLayer
MapModel.js
  conditions: L.esri.featureLayer({
    url: dts.config.map.layers.conditions,
    position: 'back',
    disableClientCache: true
  })


Added ts parameter EsriLeaflet.Tasks.Query
Set it to zero, if disableClientCache = false this value will never be updated.

  params: {
    returnGeometry: true,
    where: '1=1',
    outSr: 4326,
    outFields: '*',
    ts: 0
  },


Update timestamp parameter _setGeometry 
Common function that is called in Query Task.  Update parameter if TRUE.
  _setGeometry: function(geometry) {

    if (this.options.disableClientCache) { this.params.ts = Date.now();

Thanks,

**Comment by jgravois** [comment]
that sounds like what i was suggesting.

if you'd like to help us get the functionality into the API for others to use, i'd be happy to review a pull request.  extreme bonus points if you can include relevant documentation updates and some corresponding test coverage as well.

**Comment by jgravois** [comment]
i'm always happy to review a PR which introduces the functionality i sketched out in my reply above if anyone ever wants to take a stab at it.
