### ISSUE TITLE
L.esri.featureLayer is firing duplicate simultaneous queries

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet#719]
#### STR:

1. launch [this sample](http://esri.github.io/esri-leaflet/examples/simple-feature-layer.html)
2. click the '+' button to zoom in once (6 query requests will be issued)
3. click the '+' button to zoom in again

12 requests are issued, 6 of which have identical query geometry.

![screenshot 2016-01-04 12 31 43](https://cloud.githubusercontent.com/assets/3011734/12099728/29c00de4-b2df-11e5-81a4-01f3a9ee88b8.png)

reordered to show duplication (ie: 1 and 7 are identical, 2 and 8, etc.)
```js
"xmin":-122.6953125,   "ymin":45.521743896993634,"xmax":-122.6513671875,"ymax":45.55252525134013
"xmin":-122.6953125,   "ymin":45.521743896993634,"xmax":-122.6513671875,"ymax":45.55252525134013

"xmin":-122.7392578125,"ymin":45.521743896993634,"xmax":-122.6953125,   "ymax":45.55252525134013
"xmin":-122.7392578125,"ymin":45.521743896993634,"xmax":-122.6953125,   "ymax":45.55252525134013

"xmin":-122.6513671875,"ymin":45.521743896993634,"xmax":-122.607421875, "ymax":45.55252525134013
"xmin":-122.6513671875,"ymin":45.521743896993634,"xmax":-122.607421875, "ymax":45.55252525134013


"xmin":-122.6953125,   "ymin":45.49094569262732, "xmax":-122.6513671875,"ymax":45.521743896993634
"xmin":-122.6953125,   "ymin":45.49094569262732, "xmax":-122.6513671875,"ymax":45.521743896993634

"xmin":-122.7392578125,"ymin":45.49094569262732, "xmax":-122.6953125,   "ymax":45.521743896993634
"xmin":-122.7392578125,"ymin":45.49094569262732, "xmax":-122.6953125,   "ymax":45.521743896993634

"xmin":-122.6513671875,"ymin":45.49094569262732, "xmax":-122.607421875, "ymax":45.521743896993634
"xmin":-122.6513671875,"ymin":45.49094569262732, "xmax":-122.607421875, "ymax":45.521743896993634
```

more problematically, none of the requests result in a `304` status indicating browser cache was utilized.  they all `200`.

**Comment by patrickarlt** [comment]
It looks like this an upstream bug in Leaflet https://github.com/Leaflet/Leaflet/issues/4023. I'm going to see if I can rewrite part of VirtualGrid to not rely on `zoomend` to fix this.
