### ISSUE TITLE
'npm run build' fails on windows

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet#722]
mentioned [here](https://github.com/Esri/esri-leaflet/issues/712#issuecomment-169508877) and confirmed on my own machine.

**Comment by rowanwins** [comment]
Gday @jgravois 

So the first fail when i run 'npm run build' that i hit is `Failed at the esri-leaflet@2.0.0-beta.7 prebuild script 'mkdirp dist'.`  I've tried deleting the line `"prebuild": "mkdirp dist",` as the dist folder is already present when I check out the repo.

I then tried to rerun things but I get `[TypeError: Cannot read property '0' of null]` which seems to be related to the rollup process (although I'm not 100% sure)....

Urgh not a fun one sorry :(

**Comment by jgravois** [comment]
are you describing the behavior when building from `master` or my proposed solution in #723?

**Comment by rowanwins** [comment]
Gday @jgravois 
I didn't see your solution in #723 earlier but have just given it a whirl and it works! So yep that seems to have done the trick, will now get back to the original task of checking those breakpoints :)

**Comment by jgravois** [comment]
thanks for confirming @rowanwins.  i appreciate the help.
