### ISSUE TITLE
Dynamic Map Layer on windows edge

### ISSUE THREAD

**Issue by rntdrts** [Esri/esri-leaflet#724]
I have some problems on browser edge with dynamic map layers, every time there's a request for this service it returns a json with the image associated to the map requested, after that on the other browsers the map is applied to the div, but on edge there's no change.

It can be something on my side, but on other browsers it acts like it is supposed to. Can anyone try it and see if it can be replicated?

I'm using the v1.0.0...

**Comment by jgravois** [comment]
the service is a tad sluggish at times, but i'm having no trouble loading the sample below.
http://esri.github.io/esri-leaflet/examples/simple-dynamic-map-layer.html

did you close this issue because you're no longer having problems?

**Comment by rntdrts** [comment]
yes, the problem i had, was in a closed and with very specific environment. When i got my hands on a windows OS without this restrictions i was able to realize that this wasn't a issue. 

Thanks.
