### ISSUE TITLE
Opacity for FeatureLayer and TiledMapLayer

### ISSUE THREAD

**Issue by thezelus** [Esri/esri-leaflet#729]
Hi,

I am trying to implement a functionality to change layer opacity for ``FeatureLayer`` and ``TiledMapLayer`` but it seems like that property only exists for ``ImageMapLayer`` and ``DynamicMapLayer``. This property exists in [Javascript API] (https://developers.arcgis.com/javascript/jsapi/featurelayer-amd.html#opacity) from Esri. Is there a plan to implement this functionality in future? Further, at present is there a quick way to work around this?

**Comment by jgravois** [comment]
since `L.esri.FeatureLayer` extends `L.GeoJson`, you can already apply opacity to both [markers](http://leafletjs.com/reference.html#marker) and [paths](http://leafletjs.com/reference.html#path-options) using existing options.

since `L.esri.TiledMapLayer` and `L.esri.BasemapLayer` extend [`L.TileLayer`](http://leafletjs.com/reference.html#tilelayer-l.tilelayer), you can use its existing `opacity` constructor option to control the same.

**Comment by daniel-sabourin** [comment]
I ran into a similar issue with my project.

I'm using esri-leaflet with esri-leaflet-renderers. This could be an esri-leaflet-renderers issue. What I would like is a way to change the opacity of the entire layer without reseting the style esri-leaflet-renderers applied to display the layer with the symbology it was published with.

# No Opacity
![](http://imgur.com/hL3X2x1.png)
[JSFiddle](http://jsfiddle.net/skoqkdu6/6/) without opacity. Notice how renderers is changing the style to match how it's published
```javascript
$(function() {

    var map = L.map('map').setView([38.249, -85.759], 4);
    var layer = L.esri.basemapLayer('Streets').addTo(map);

    var options = {
        url: "http://sampleserver1.arcgisonline.com/ArcGIS/rest/services/Specialty/ESRI_StatesCitiesRivers_USA/MapServer/2",
        useCors: false,

    };

    map.addLayer(L.esri.featureLayer(options));

});
```
---
# With Opacity
![](http://imgur.com/Sn4I0Bn.png)
[JSFiddle](http://jsfiddle.net/skoqkdu6/7/) with opacity. Notice how the style is back to the default leaflet styling with the opacity set.
```javascript
$(function() {

    var map = L.map('map').setView([38.249, -85.759], 4);
    var layer = L.esri.basemapLayer('Streets').addTo(map);

    var options = {
        url: "http://sampleserver1.arcgisonline.com/ArcGIS/rest/services/Specialty/ESRI_StatesCitiesRivers_USA/MapServer/2",
        useCors: false,
        style: function(feature) {
        	return {
          	opacity: 0.25
          }
        
        }
    };

    map.addLayer(L.esri.featureLayer(options));

});
```
Is there anyway to get renderers working with opacity? I can post this as an issue on the renderers page if needed.

**Comment by jgravois** [comment]
@daniel-sabourin what you're seeing is expected because we haven't tagged a release of esri-leaflet-renderers since we added support for mixing in style options in layer constructors for polyline/polygon feature services (see Esri/esri-leaflet-renderers#100)

i'll tag/release 2.0.1 soon and we can make sure its working the way it should be.

cc/ @kneemer

**Comment by daniel-sabourin** [comment]
@jgravois @kneemer thank you both for your quick reply. Just a heads up, we're working off leaflet 0.7.7

**Comment by jgravois** [comment]
@daniel-sabourin i tagged version [`2.0.1`](https://github.com/Esri/esri-leaflet-renderers/releases/tag/v2.0.1) of esri leaflet renderers, which is compatible with Leaflet 1.0 beta.2 and introduces support for mixing in style options in the feature layer constructor with what is already defined for the service.  

we weren't able to backport the new feature to a `1.x` release (which could be used with Leaflet `0.7.x`) but if you are **not** manipulating individual feature styles after the layer has been added to the map, you can find a [branch](https://github.com/Esri/esri-leaflet-renderers/blob/add-static-style-mixin/CHANGELOG.md) that you could use to roll your own custom build.

thank you @kneemer for your help with this!  i'm going to close this issue, but i'm happy to chat more if anyone has any other questions.

**Comment by daniel-sabourin** [comment]
Hi, I've added a related issue to the esri-leaflet-renderers page

https://github.com/Esri/esri-leaflet-renderers/issues/106
