### ISSUE TITLE
Adding a dynamicMapLayer prevents popups on geojson layers

### ISSUE THREAD

**Issue by svancise** [Esri/esri-leaflet#731]
Hello,

I've looked around for a way around this but have not been able to find or figure anything out.

I currently have a map with a geojson layer that has a popup when clicked. When I add a dynamic layer with a bindPopup function, the geojson's click/popup does not fire anymore. It seems the event is not propagating to the geojson layer. I've put together a [jsFidle](http://jsfiddle.net/z05jty7b/) to demonstrate the issue.

Correction: Seems to do it when a dynamicLayer is added, regardless of if it having a bound popup or not.

Is there something I'm missing? 

Thanks,
Spencer

**Comment by svancise** [comment]
Of course, as soon as I posted this I figured it out. I applied this [fix](http://gis.stackexchange.com/questions/116065/how-to-let-leaflet-layer-events-to-propagate-to-layer-below) to the other layers which seems to fix the issue. Sorry for the pointless issue!

**Comment by agaffiga** [comment]
I'm having the same issue, so this definitely wasn't pointless @svancise ! Can you tell me how you were able to fix this with CSS? The fix you link to is for a tile layer, and I'm not sure that applies to what I (or you) were doing?

**Comment by jgravois** [comment]
@svancise's fiddle loads a pretty old version of Leaflet (`0.6.4`).  

i can't repro the behavior in [`0.7.7`](http://jsbin.com/sezike/edit?html,output), let alone [`1.x`](http://jsbin.com/peyava/edit?html,output) (which introduced substantial improvements in controlling layer draw order).  i'm happy to investigate further if anyone can provide more info.

**Comment by agaffiga** [comment]
I figured it out. The issue of not being able to open a popup from a button outside the map started once I upgraded to ESRI Leaflet 2.0.0. So I thought this note in the release notes was what I needed:

	• By default basemap layers GrayLabels, DarkGrayLabels, OceansLabels, ImageryLabels, ImageryTransportation, ShadedReliefLabels, TerrainLabels will now be rendered on top of polygons and polylines if the browser supports CSS Pointer Events. You can disable this behavior by passing {pane: "tilePane"} in the L.esri.basemapLayeroptions.

But alas, adding the pane: option did nothing. I figured out it was actually that I needed to bind the Popup in the constructor of the feature layer (as opposed to after that call) using onEachFeature. When I did that, the problem went away. I’m not sure why there was a difference in this between ESRI Leaflet versions, but this is probably the better way for me to bind the Popup anyway.

**Comment by jgravois** [comment]
> I’m not sure why there was a difference in this between ESRI Leaflet versions

this is actually an improvement to Leaflet core in `1.0.x` made by our very own @patrickarlt! (Leaflet/Leaflet/pull/3109).  

there's certainly nothing *wrong* with binding popups for each and every feature in the constructor if you don't have too many, but i quite like the new behavior of limiting binding to features that have seen interaction.

i put together a simple application which binds a popup for a feature partially obscured by a basemap label and had no trouble opening the popup even when clicking directly on the basemap label.

http://jsbin.com/tibuvoq/edit?html,output

as i said before...

> i'm happy to investigate further if anyone can provide more info.
