### ISSUE TITLE
Refactor build process

### ISSUE THREAD

**Issue by patrickarlt** [Esri/esri-leaflet#733]
I increasingly don't like shipping a [custom build script](https://github.com/Esri/esri-leaflet/blob/master/scripts/build.js) with every Esri Leaflet repo. It would be able to use https://github.com/Esri/esri-leaflet-bundler to bundle leaflet and all its plugins. Since everything is Rollup-based I don't think this will be too hard.

**Comment by patrickarlt** [comment]
This should also include:

* Upgrade to `rollup@latest`
* Utilize rollup plugins as much as possible
* Add a `--debug` build with unminified code and sourcemaps to resolve https://github.com/Esri/esri-leaflet/issues/712

**Comment by rowanwins** [comment]
Hey @patrickarlt  let me know if you need someone to test on a windows machine
