### ISSUE TITLE
Refactor module bundling and packaging process

### ISSUE THREAD

**Issue by patrickarlt** [Esri/esri-leaflet#734]
While the experiments in shipping ES 6 code for various system has been a pretty big success it is proving too difficult to maintain and given recent changes to babel (and all its implementations) I have been unable to test it shipping ES 6 modules still works with babelify, ect...

The approaches explored in this repo do work, but it is ultimately much simpler to just ship the following:

* Compiled ES 5 UMD module, for CDN, browserify, webpack, AMD. This lives in `main` in the `package.json`
* Compiled ES 6 module with `import/export` for JSPM and Rollup. We will keep the `jspm` and `jsnext:main` fields in `package.json` for compatibility with those systems.

Background info https://github.com/Esri/arcgis-to-geojson-utils/issues/3#issuecomment-167886814

**Comment by jgravois** [comment]
this was closed by #754
