### ISSUE TITLE
Include USA Topo Maps in L.esri.basemapLayer

### ISSUE THREAD

**Issue by evanthoms** [Esri/esri-leaflet#736]
Title pretty much says it all. How about a shortcut string to reference the USA Topo Maps basemap in L.esri.basemapLayer? To be clear:

http://usgs.maps.arcgis.com/home/item.html?id=931d892ac7a843d7ba29d085e0433465

New to esri-leaflet as of today and I am liking it!

**Comment by patrickarlt** [comment]
@jgravois this seems like a great first time contributor issue if you could take the time to write up how to do it.

**Comment by jgravois** [comment]
sure!

just as a reminder, we do this with inspiration from the folks at @yourfirstpr and hope to receive a patch from someone that is just getting started with contributing to open source. if you're interested, but need help [getting started](https://github.com/Esri/esri-leaflet#development-instructions), **please** don't be shy!

the collection of basemaps we already support can be found [here](https://github.com/Esri/esri-leaflet/blob/master/src/Layers/BasemapLayer.js#L11-L190).  an upstanding young citizen could use the [USGS topographic service metadata](http://services.arcgisonline.com/ArcGIS/rest/services/USA_Topo_Maps/MapServer) to fill in the appropriate properties for an additional entry.

test coverage isn't much, but an update [here](https://github.com/Esri/esri-leaflet/blob/master/spec/Layers/BaseMapLayerSpec.js#L47-L54) would be appropriate.

additionally, you'd just want to make sure and confirm manually that the new basemap works as expected in a test application before submitting a Pull Request.

**Comment by phxpdx** [comment]
I'll take a crack at it.

**Comment by evanthoms** [comment]
Ok! I found that file and figured that's where one would add to the
collection.

On Wed, Feb 3, 2016 at 9:59 AM, john gravois <notifications@github.com>
wrote:

> sure!
>
> just as a reminder, we do this with inspiration from the folks at
> @yourfirstpr <https://github.com/yourfirstpr> and hope to receive a patch
> from someone that is just getting started with contributing to open source.
> if you're interested, but need help getting started
> <https://github.com/Esri/esri-leaflet#development-instructions>, *please*
> don't be shy!
>
> the collection of basemaps we already support can be found here
> <https://github.com/Esri/esri-leaflet/blob/master/src/Layers/BasemapLayer.js#L11-L190>.
> an upstanding young citizen could use the USGS topographic service
> metadata
> <http://services.arcgisonline.com/ArcGIS/rest/services/USA_Topo_Maps/MapServer>
> to fill in the appropriate properties for an additional entry.
>
> test coverage isn't much, but an update here
> <https://github.com/Esri/esri-leaflet/blob/master/spec/Layers/BaseMapLayerSpec.js#L47-L54>
> would be appropriate.
>
> additionally, you'd just want to make sure and confirm manually that the
> new basemap works as expected in a test application before submitting a
> Pull Request.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Esri/esri-leaflet/issues/736#issuecomment-179404845>.
>



-- 

Evan Thoms
US Geological Survey, Alaska Science Center
4210 University Drive, Anchorage,  AK 99508
voice: 907-786-7409	fax: 907-786-7401
ethoms@usgs.gov

**Comment by jgravois** [comment]
> I'll take a crack at it.

awesome!

**Comment by jgravois** [comment]
thank you @mattficke for the fix.

@phxpdx if you're interested/available to help, i created a new issue in our website repository (https://github.com/Esri/esri-leaflet-doc/issues/19) to request help documenting the change to the API.
