### ISSUE TITLE
L.esri.mapService is not a function

### ISSUE THREAD

**Issue by ATran31** [Esri/esri-leaflet#737]
When attempting to use L.esri.mapService() I am getting TypeError: L.esri.mapService is not a function.
This is running against a secured service and I have it inside the authentication callback.

        var ACPQuery  = L.esri.mapService({url: serviceURL, token: tk}).query()
          .layer(0)
          .where("OBJECTID IS NOT NULL")
          .run(function (error, featureCollection, response){
          if (error){
            console.log(error);
          } else {
            console.log(featureCollection);
          }
        });

**Comment by patrickarlt** [comment]
@ATran31 can you please include the following in your issue:
* Browser
* Browser version
* Leaflet version `L.version`
* Esri Leaflet version `L.esri.VERSION`
* Bundling tool (webpack, browserify, Require JS) if any

**Comment by ATran31** [comment]
@patrickarlt I am using the following:
Browsers: Firefox 43.0.4, Chrome 47.0.2526.111
Leaflet 0.7.3
Esri Leaflet 1.0.0
Bundling tool - None

**Comment by kneemer** [comment]
Hi @ATran31, it looks like you are using the Esri Leaflet 2.0.x syntax that is specified in the current docs.  The older syntax can be found [here](https://github.com/Esri/esri-leaflet/blob/v1.0.0/site/source/pages/api-reference/services/map-service.md).  

Let us know if you are still having issues using the older syntax.

**Comment by ATran31** [comment]
That did it. Thank you!
