### ISSUE TITLE
How to optimize for performance?

### ISSUE THREAD

**Issue by daniel-sabourin** [Esri/esri-leaflet#738]
Hi,

I'm writing an application that allows for users to add their own feature layers to a map. As such, the application has to be performant under any condition. Some layers might have 100,000+ features. What I've noticed is that the map panning can get laggy/choppy/unresponsive under intense conditions. Sometimes the browser tab will just crash. What are some optimizations that I can do to make things faster?

- precision: Currently have it set at 5
- simplifyFactor: Currently have it set at 0.1. Is this number reasonable?
- renderer: How can I use this? Docs say that setting it to L.canvas can result in performance improvements, but I keep getting console errors. I tried by adding renderer: L.canvas to the options.
- fields: Only ObjectID, instead of returning all fields
- Is there a way to limit the number of features on the screen at once? Say to 5,000 or so
- The SR for this service is 102100, where the map is 4326. This would cause the response from the server to take longer, but it shouldn't affect the map panning, right?

http://jsfiddle.net/skoqkdu6/15/

Is this just the nature of it being a web library? Is the layer in the fiddle just too much? I came from using the ArcGIS WPF/.NET SDK and the performance was much better.

**Comment by rowanwins** [comment]
Gday @daniel-sabourin 

Bringing a layer like tax parcels in as a feature layer for a large area is probably not the best idea. A feature layer means transferring **all** the data (eg every single vertice of each polygon in the map extent etc).

Rather than bringing in your large layer as a feature layer you'd be better of trying to use it as a [Dynamic Map Layer](http://esri.github.io/esri-leaflet/examples/simple-dynamic-map-layer.html). Using this approach the server sends an image (eg a png) rather than the actual data which takes a whole lot less data. 

That's probably fairly general advice but hopefully it helps a little, this will obviously depend a bit on how your app is structured as to what is practical.

Good luck,
Rowan

**Comment by daniel-sabourin** [comment]
Hi @rowanwins 

Displaying the layer as a Dynamic Map Layer is only possible when the service is a MapServer service, correct? For example, if I wanted to display [this layer](http://gis-gfw.wri.org/arcgis/rest/services/local_projections/wgs_1984/MapServer/19), I would do the following

```javascript
L.esri.dynamicMapLayer({
      url: 'http://gis-gfw.wri.org/arcgis/rest/services/local_projections/wgs_1984/MapServer',
      layers: [19]
});
```

However, for layers published as a [FeatureServer](https://services1.arcgis.com/PRoAPGnMSUqvTrzq/arcgis/rest/services/TaxParcel/FeatureServer/0), it is not possible to add it to the map as a Dynamic Layer, correct? We are not in control of the services, so it is not possible to republish them as MapServer.

**Comment by rowanwins** [comment]
Gday @daniel-sabourin 

There was a [good writeup](https://github.com/Esri/esri-leaflet/issues/403) in the past here from the maintainers about the differences between feature layers and dynamic layers.

Short answer though is yes a url will containing 'MapServer' will have the ability to be a dynamic layer.

Your other option when working with feature layers is to set a [minZoom](http://esri.github.io/esri-leaflet/api-reference/layers/feature-layer.html) option on your feature layer, this will prevent the layer from drawing at zoomed out scales. See this updated fiddle
http://jsfiddle.net/skoqkdu6/16/

Hope this is helping somewhat...

**Comment by daniel-sabourin** [comment]
Yes, thank you @rowanwins. It certainly is helping.

Since I'm allowing the user to add their own services to the map, I'll have to take all situations into account.

If the service is going to be slow, and it supports adding it as a DynamicLayer (/MapServer), I'll add it as a DynamicLayer.

If the service is going to be slow, but it doesn't support DynamicLayer (/FeatureServer), I'll do the simplifyFactor, but the performance is still going to be bad for some services. The minZoom option is less than ideal, as I found your edit to the fiddle to still not be performant.

**Comment by patrickarlt** [comment]
@daniel-sabourin I'm sorry it look me so long to respond to this but the points @rowanwins made above are all valid. Loading ~250k polygons is REALLY rough on the browser. The ArcGIS API for JavaScript also falls down loading this feature service http://www.arcgis.com/home/webmap/viewer.html?url=https://services1.arcgis.com/PRoAPGnMSUqvTrzq/ArcGIS/rest/services/TaxParcel/FeatureServer/0&source=sd. I even managed to get a few server runtime errors which generally means that the process running they has crashed.

Practically speaking you could write the book on optimizing a big service. Setting `simplifyFactor` and `precision` as well as limiting `outFields` are all solid steps to take.

As @rowanwins pointed out most parcel viewer applications that I have seen use a Map Service as a backend rather then a feature service for this reason. You cannot host Map Services (and thus use `DymanicMapLayer`) on ArcGIS Online but you can publish tiles from a feature service and use the resulting raster tiles. You can find direction on how to do this [in the docs](https://doc.arcgis.com/en/arcgis-online/share-maps/publish-tiles.htm#ESRI_SECTION1_F68FCBD33BD54117B23232D41A762E89) and you will need the `ArcGIS Online item](http://www.arcgis.com/home/item.html?id=e7b3c303a54c4a10aa1d1a585e4c05f2) that represents this FeatureServer. You will also need an ArcGIS Online account, you can get a free account at https://developers.arcgis.com/.

If you still really want to try this as a feature layer you could do the following:

* Upgrade to the latest Esri Leaflet 2.0 beta, this also requires the latest Leaflet 1.0 beta. There are a lot of general performance improvements.
* Add a min zoom to the map as @rowanwins suggested
* Listen to the `zoomend` event on the map and add the layer only at a particular zoom level

**Comment by patrickarlt** [comment]
@daniel-sabourin I'm closing this. Please reopen if you have any additional questions.
