### ISSUE TITLE
z-Index problem with map services 

### ISSUE THREAD

**Issue by rhys-d** [Esri/esri-leaflet#739]
I'm using Esri Leaflet to add several map services to my Leaflet map via a Layer Group which is already added to my Leaflet Map e.g. L.esri.dynamicMapLayer({ url: ..../MapServer }).addTo(myLayerGroup);

When I add the layers to the Layer Group, they do not render in the correct order.  If I add map service 1 first, then map service 2 second, I expect to see map service 2 on top of map service 1 on the map, like how Esri's JSAPI works.  Also, when I pan the map the map service on the bottom draws on the top for a second then goes back to the bottom.  Should I be using a Layer Group or is there another way to do this?  I will need to reference the layers later so I can set the visible layers on them.

**Comment by patrickarlt** [comment]
If you need explicit layer ordering we have an example using the upcoming Esri Leaflet 2.0 release. http://esri.github.io/esri-leaflet/examples/layer-ordering.html Just create a pane for each layer and pass the name of the pane as the `pane` option on each layer. By default panes or ordered in the same order they are created.

**Comment by rhys-d** [comment]
Thanks for the example.  This is exactly what I needed.  I still have two issues though:
1) Most of the time when I want to hide layers, I can use the map.setLayers method, however sometimes I will need to remove the layer completely.  I tried using L.DomUtil.remove(pane) - https://github.com/Leaflet/Leaflet/issues/1742 but it doesn't seem to work.
2) When I use map.setLayers, it works most of the time, but occasionally the map does not refresh, especially if I zoomed right out.  For example, if my visible layers were 1 and 2, and I turn off 2 via map.setLayers, when I zoomed out to the full extent a country, 1 and 2 would still be visible until I panned the map by a few pixels.  Is there a way to force the map/layer to refresh after setLayers is called?  
I'm not too worried about the first issue but it would be good if I could resolve the second.

Date: Tue, 2 Feb 2016 09:54:11 -0800

**Comment by jgravois** [comment]
sorry for the extremely delayed reply.  i just noticed that L.esri.featureLayer method ['refresh()'](https://github.com/Esri/esri-leaflet/blob/master/src/Layers/FeatureLayer/FeatureManager.js#L289-L303) isn't documented but that's definitely the one you're looking for.

Esri/esri-leaflet-doc#40
