### ISSUE TITLE
Tiles disappear when zooming beyond 'maxNativeZoom'

### ISSUE THREAD

**Issue by octavm** [Esri/esri-leaflet#743]
After the 'maxNativeZoom' level set on a tile loaded with **L.esri.tiledMapLayer** is reached, the tiles disappear instead of being loaded from the maxNativeZoom level and auto-scaled.

If the tile is loaded using the Leaflet **L.tileLayer** 'maxNativeZoom' works correctly.

I've prepared a [demo](https://jsfiddle.net/6b7tq6ea/2/) to see the issue.

Two tiles have been added using the ESRI Leaflet addon and again using just Leaflet. After zooming in beyond the maximum zoom level where the tile has data (15) the ESRI tiles disappears whereas the Leaflet tile is scalled properly.

**Comment by jgravois** [comment]
thanks for this.  the behavior definitely looks inappropriate to me.  i should be able to take a closer look soon.

**Comment by patrickarlt** [comment]
I took a look. I think this is related to changes we made to handle web mercator services at non-standard scale levels.

I think we need to use `this._getZoomForUrl()` instead of `tilepoint.z` in https://github.com/Esri/esri-leaflet/blob/master/src/Layers/TiledMapLayer.js#L62-L69. @jgravois Assigning to you so you can investigate.

**Comment by jgravois** [comment]
> I think we need to use `this._getZoomForUrl()`

based on my first pass, additional changes will be necessary to implement a fix.

**Comment by chriserickson** [comment]
Any updates on this? 

Ran into this upgrading to Leaflet 1.0 and all of our layers with a maxNativeZoom stopped working correctly.

**Comment by jgravois** [comment]
i took another look at this and was able to identify a fix, mostly due to @patrickarlt's characteristically good clue. the proposed patch can be found in #904.
