### ISSUE TITLE
Map service not showing: dynamicMapLayer

### ISSUE THREAD

**Issue by arnaufp** [Esri/esri-leaflet#748]
I am trying to display this layer https://tmservices1.esri.com/arcgis/rest/services/LiveFeeds/Hurricane_Active/MapServer/4

using

  L.esri.dynamicMapLayer({
    url: 'https://tmservices1.esri.com/arcgis/rest/services/LiveFeeds/Hurricane_Active/MapServer/',
	layers:[4]
  }).addTo(map);

I get back an completely blank png, while in ArcGIS Online I can perfectly see the layer.

Is there anything I am not doing correctly? Thanks

**Comment by GISDev01** [comment]
Tried to repro. your issue, but everything is working well in this sample map:
https://gist.github.com/GISDev01/024d58a63d65134eac0b

Can you show us all of your code?

**Comment by jgravois** [comment]
i suspect @arnaufp is seeing the affect of dynamicMapLayers not currently wrapping around the dateline (#672).

until we get the proposed fix in, you might consider setting [`noWrap: false`](http://leafletjs.com/reference.html#tilelayer-nowrap) on whatever your tiled basemap you're using (and perhaps even constraining the extent) to ensure the image overlays properly.

https://dl.dropboxusercontent.com/u/59331579/js/tms.html

**Comment by jgravois** [comment]
check out @SVoyt's great new plugin. https://github.com/SVoyt/esri-leaflet-dynamic-advanced

closing this issue, but happy to talk more if anyone has any further questions.
