### ISSUE TITLE
Please add full paths to libraries

### ISSUE THREAD

**Issue by jwitcoski** [Esri/esri-leaflet#750]
//cdn.leafletjs.com/leaflet/v1.0.0-beta.2/leaflet.js

does not render when i use local browser on laptop. please change all your code to add https
https//cdn.leafletjs.com/leaflet/v1.0.0-beta.2/leaflet.js

**Comment by jgravois** [comment]
thanks @jwitcoski, this is a good suggestion.

not sure everyone agrees, but it's considered an anti-pattern to use protocol relative URLs and the suggested alternative is to hardcode `https` instead whenever possible.

the problem with cdn.leafletjs.com is that it actually doesn't *support* `https`, so I suggest that we update the sample app in the README to point at the copy of leaflet hosted on [jsdelivr](https://cdn.jsdelivr.net/leaflet/1.0.0-beta.2/leaflet.js) instead.

a PR from anyone would be extremely appreciated.  if no one submits in the near future, I'll go ahead and fix myself.

**Comment by jgravois** [comment]
just realized that the references that actually need updated are not in the README, they are [here](https://github.com/Esri/esri-leaflet-doc/blob/master/src/layouts/example.hbs#L24-L28)

**Comment by jgravois** [comment]
i've hardcoded links in our documentation site to use `https` when the resource is available over [TLS/SSL](https://en.wikipedia.org/wiki/Transport_Layer_Security).

thanks again for the feedback.
