### ISSUE TITLE
Set the Order or ZIndex of L.esri.DynamicMapLayer 

### ISSUE THREAD

**Issue by somsub** [Esri/esri-leaflet#753]
I am still using **Leaflet 0.7.7** (can't use the latest beta since other plugins may break). All I want to do _set the order of a DynamicMapLayer_. Basically, I am building a custom component that will allow users to search a geo data catalog and add multiple layers on the map, then **drag and reorder the layers**. The layers could be L.esri.DynamicMapLayer or L.esri.ImageMapLayer.(Served up from Arcgis Services). I need a way to reorder the layers. It was easy to do this with Arcgis JSAPI but with Esri Leaflet I am out of luck. I tried using the **map._createPane** function with the current version of leaflet I have and passed the pane to the Layer creation but that did not work. I followed the layer construction just like the Feature Layer ordering example. Inspecting the dom I did see the panes getting created but the layers still get added to the default overlay pane. Please help me if you have a solution or demo to this. I can't use the latest leaflet version until a non beta version is released

**Comment by SVoyt** [comment]
@somsub Pane is only container for layer's images. DynamicMapLayer and ImageMapLayer works with overlay pane as default.

**Comment by somsub** [comment]
Thanks for your response. So how can I set an order to the layer ? Can you give me an example please

**Comment by jgravois** [comment]
i don't have a good answer for you.  you'll need to upgrade to leaflet `1.0.0` if you want/need to take advantage of the more advanced functionality for controlling the display order of the layers in your map that was added.

http://esri.github.io/esri-leaflet/examples/layer-ordering.html
