### ISSUE TITLE
time metadata for imagelayers 

### ISSUE THREAD

**Issue by somsub** [Esri/esri-leaflet#756]
I have layers like this http://imagery.arcgisonline.com/arcgis/rest/services/LandsatGLS/NDVI_Colorized/ImageServer that I need to filter by start and end dates. Thank you for posting this excellent sample https://esri.github.io/esri-leaflet/examples/visualizing-time-on-dynamic-map-layer.html. My question is there a method by which I can get metadata if the layer is time enabled and what's the range to preset useful defaults?

Thanks for your help

**Comment by patrickarlt** [comment]
@somsub You can use the exact same `setTimeRange` method on `ImageMapLayer` that you can on `DynamicMapLayer`. It is documented in the API reference https://esri.github.io/esri-leaflet/api-reference/layers/image-map-layer.html.

You can also use the `layer.metadata(callback)` method https://esri.github.io/esri-leaflet/examples/getting-service-metadata.html to get layer metadata. For your service http://imagery.arcgisonline.com/arcgis/rest/services/LandsatGLS/NDVI_Colorized/ImageServer?f=pjson.

It would be nice to have an example of time enabled `ImageMapLayer` so I'm leaving this open.

**Comment by somsub** [comment]
Thanks a lot...I'll try to come up with an example for time-enabled ImageMapLayer.
