### ISSUE TITLE
Broken thumbnails with tile layers

### ISSUE THREAD

**Issue by hhkaos** [Esri/esri-leaflet#759]
I think I have found a bug:
http://esri-es.github.io/JavascriptAPI/problems/morethan1000entities/tiled_feature_leaflet.html

Cheers,
Raul

**Comment by jgravois** [comment]
thanks @hhkaos.  i'll take a look soon.

**Comment by jgravois** [comment]
soon we'll handle this for you, but in the meantime you can supply a blank .png to substitute via the [`errorTileUrl`](http://leafletjs.com/reference-1.0.0.html#tilelayer-errortileurl) in the *tiledMapLayer* constructor.

```js
L.esri.tiledMapLayer({
  url: "yourservice",
  errorTileUrl: './missing256.png' // hosted alongside your app
}).addTo(map);
```
you can find placeholder images available for download in the Esri Knowledge Base article below

Article ID:	36939
http://support.esri.com/en/knowledgebase/techarticles/detail/36939

**Comment by hhkaos** [comment]
Thx John! :), I'll try this way :))
