### ISSUE TITLE
How to enable subdomains url and use EXPORT function

### ISSUE THREAD

**Issue by grighome** [Esri/esri-leaflet#761]
Hello!

How to enable subdomains url and use EXPORT function?

Demo url - 

http://b.maps.rosreestr.ru/arcgis/rest/services/Cadastre/Cadastre/MapServer/export?bbox=-2872096.770357728,8568832.34605541,3.0041076113004357E7,2.387091391251745E7

**Comment by grighome** [comment]
Sorry... i am use "json" format. Set f: 'PNG8'.

How to use  subdomains at url?

**Comment by jgravois** [comment]
the only subdomain support currently in esri-leaflet is inherited from [`L.tileLayer`](http://leafletjs.com/reference.html#tilelayer-subdomains).

i've never heard of their use with dynamicMapLayers, but if its a common thing, we might consider exposing a mechanism to pass them in via the constructor and subsitituting different ones when making individual `export` requests.

**Comment by jgravois** [comment]
i'll consider digging in deeper if others reply in the future.

in general, standard practices for scaling/load balancing requests to your ArcGIS Server instance are your best bet to optimize performance for `export` operation responses.
