### ISSUE TITLE
JSONP Error: function cX does not exist on window._EsriLeafletCallbacks

### ISSUE THREAD

**Issue by scottsanzo** [Esri/esri-leaflet#762]
In certain cases the script tag loads and attempts to execute before the callback property is set. Creating the JSONP script tag after the callback property is set on the 'window._EsriLeafletCallbacks' object eliminates that possibility:
window._EsriLeafletCallbacks[callbackId] = function (response) {...};

var script = L.DomUtil.create('script', null, document.body);...
script.id = callbackId;

**Comment by jgravois** [comment]
thanks for logging the issue!  just to be clear, you're suggesting that we reverse the order of operations in the code block [here](https://github.com/Esri/esri-leaflet/blob/master/src/Request.js#L160-L188), correct?

> In certain cases the script tag loads and attempts to execute before the callback property is set.

in what circumstances are you seeing this?  what is the resulting behavior?

**Comment by scottsanzo** [comment]
No problem, thanks for the quick reply. Yes, those are the code blocks I'm referring to. 
 
When using IE9, or in IE9 mode (though it could affect any browser that doesn't support CORS) the script tag returns and loads before the "window._EsriLeafletCallbacks[callbackId]" is set. When the resulting script is evaluated it attempts to execute the function (in this case "window._EsriLeafletCallbacks.c0") , which hasn't been set, the "Object doesn't support property or method 'c0'" error is thrown (attached image). 
              
 We're seeing it when the _getAttributionData function is called during initialization, but that's only because it's the first JSONP call being made. 
 
Oddly enough, I can't reproduce this when the developer panel is open in IE, probably because it's more of a timing issue. I didn't see any closures inside the callback, so it seemed safe enough to reverse the order of operations, and testing seems to confirm that so far. 
 
Date: Mon, 21 Mar 2016 12:14:03 -0700

**Comment by jgravois** [comment]
awesome. thanks for all the info. i'll test a little myself and submit a patch shortly unless anyone else wants to take a stab at submitting their own pull request with the fix you outlined.
