### ISSUE TITLE
Document basics of setting up clone for contributors

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/esri-leaflet#767]
https://github.com/Esri/esri-leaflet#development-instructions has
Development Instructions
3. Install the dependencies with `npm install`

[edit] For those of us who are somewhat new to node, perhaps a slightly-expanded line that indicates that `npm install` uses the repo's package.json file to set up all dependencies?  A newbie might try `npm install pkg1`, `npm install pkg2`, etc., and wonder what the set of dependencies is.

**Comment by jgravois** [comment]
closing via 6338a15 but happy to keep tweaking if you think more would be helpful.
