### ISSUE TITLE
Where to find Unique Styling properties after FeatureLayer is restyled using setStyle()

### ISSUE THREAD

**Issue by Nick-t-go** [Esri/esri-leaflet#768]
- Browser and version:

Version 49.0.2623.87 
- Version of Leaflet (`L.version`):

v1.0.0-beta.2
- Version of esri Leaflet (`L.esri.VERSION`):

2.0.0-beta.7

I'm using setStyle() to switch between different Unique Renderings for a specifice `esri.featureLayer`. I would like to know if those changes are written to a property on the `featureLayer` object. I see that there is a `feature._map._originalStyle` property with an object that has the original style the feature layer was added to the map with but this doesn't seem to change when the style is changed. I want to make a legend that is dynamic and to do so I need to be able to grab the specifics of each `featureLayer`'s styling i.e what colors, weights, opacity, and unique fields each styling is based on. Is there something available for this? Is it in the map object?

**Comment by jgravois** [comment]
sorry it took me so long to see this.

anything you pass to setStyle() is available afterwards in [`featureLayer.options.style`](https://github.com/Esri/esri-leaflet/blob/9ad267e62410c7c1c7229a6cb77fcd80c660d3ad/src/Layers/FeatureLayer/FeatureLayer.js#L220)

**Comment by jgravois** [comment]
closing this, but happy to chat more if anyone has any further questions.
