### ISSUE TITLE
Non-mercator example is referencing soon-to-be deprecated tile service

### ISSUE THREAD

**Issue by stdavis** [Esri/esri-leaflet#771]
Just wanted to give you guys a heads up that the tiled service in `examples/non-mercator-projection.html` (http://mapserv.utah.gov/arcgis/rest/services/BaseMaps/Lite/MapServer) is going away at the end of the year. We are transitioning all of our base maps to Web Mercator and moving them to a new server.

Not sure where to point you to for a stable replacement. Maybe ESRI has something on a sample server?

Keep up the great work on this awesome project!

**Comment by jgravois** [comment]
@stdavis thanks for the heads up (and for the initial help)!

not ours, but [the service here](http://webmaps.nottinghamcity.gov.uk/ArcGIS/rest/services/basemap/Greyscale/MapServer?f=jsapi) is so cool i might just risk it.

[this one](http://maverick.arcgis.com/ArcGIS/rest/services/World_Mollweide/MapServer?f=jsapi) is another option.
