### ISSUE TITLE
Latest 2.0.0 release contains .DS_Store that breaks bower Windows

### ISSUE THREAD

**Issue by nathanhilbert** [Esri/esri-leaflet#779]
* Browser and version:

Chrome 49

* Version of Leaflet (`L.version`):

1.0.0-rc.1

* Version of esri Leaflet (`L.esri.VERSION`):

2.0.0

* I'm loading/bundling the library using:

bower 

Steps to reproduce the error:
1. bower install esri-leaflet on Windows
2.

What happens is [X].

```
bower checkout      esri-leaflet#v2.0.0
bower ECMDERR       Failed to execute "git clone https://github.com/Esri/esri-le
aflet.git -b v2.0.0 --progress . --depth 1", exit code of #128 Cloning into '.'.
...
error: unable to create file dist/.DS_Store (Permission denied)

```

I was expecting [Y].

**Comment by jgravois** [comment]
> the joys of bower.

thanks for reporting this.  luckily i was able to leave the npm release alone and [retag](https://github.com/Esri/esri-leaflet/releases/tag/v2.0.0) here in github and the problem appears to be resolved.

i'll wait for you to confirm before closing this thread.

**Comment by nathanhilbert** [comment]
Looks good now.  Thanks for the quick turnaround.

```
esri-leaflet#2.0.0 bower_components\esri-leaflet
└── leaflet#1.0.0-rc.1

```
