### ISSUE TITLE
Rapidly running setWhere on featureLayer sometimes shows previous result and the new result

### ISSUE THREAD

**Issue by nathanhilbert** [Esri/esri-leaflet#780]
**Browser and version**:

Chrome 49

**Version of Leaflet (`L.version`)**:

1.0.0-rc.1

**Version of esri Leaflet (`L.esri.VERSION`)**:

`master`

**I'm loading/bundling the library using**:

[CDN](http://www.jsdelivr.com/projects/leaflet.esri) and npm  built

Steps to reproduce the error:
1. Use [my branch](https://github.com/nathanhilbert/esri-leaflet/tree/setwhere)
2. npm start
3. navigate to index.html in root repo
4. It will do some fast reloading for a few seconds to recreate the issue.  If you don't see overlapping polygons, try clicking Change Layer rapidly 

**What happens?**
Running setWhere on a feature does not fully clear the previous request before the next is processed creating some collision of objects.  I'm guessing the [addLayers function](https://github.com/nathanhilbert/esri-leaflet/blob/setwhere/src/Layers/FeatureLayer/FeatureManager.js#L221) within the callback is processing on both calls after the same both calls finish their removeLayers functions.

See the [JS Bin](http://jsbin.com/jabacahipi/edit?html,output), although I've had less luck recreating there than on my local web server. 

![image](https://cloud.githubusercontent.com/assets/718283/15045778/1463c1b6-12a2-11e6-83e9-fd995f1fd412.png)

**Suggestion**
My initial thought was to not run the callbacks on non-active setWheres using some kind of logic with the FeatureManager object, but we would still want to remove the old layers accurately without removing any newly added ones.  Maybe something with an onAbort XMLhttpRequest  callback?  Maybe better tracking with versioning of active requests opposed to incremented numbers? I'm sure there are better approaches than these.

**Comment by jgravois** [comment]
will continue to investigate in #875
