### ISSUE TITLE
Dynamic Service Load Error

### ISSUE THREAD

**Issue by aaronkilbey** [Esri/esri-leaflet#782]
Chrome 50

```
<html>
<head>
  <meta charset=utf-8 />
  <title>Esri Leaflet Quickstart</title>
  <meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />

  <!-- Load Leaflet from CDN-->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/leaflet/1.0.0-rc.1/leaflet.css" />
  <script src="https://cdn.jsdelivr.net/leaflet/1.0.0-rc.1/leaflet-src.js"></script>

  <!-- Load Esri Leaflet from CDN -->
  <script src="https://cdn.jsdelivr.net/leaflet.esri/2.0.0/esri-leaflet.js"></script>

  <style>
    body { margin:0; padding:0; }
    #map { position: absolute; top:0; bottom:0; right:0; left:0; }
  </style>
</head>
<body>

<div id="map"></div>

<script>
  var map = L.map("map").setView([45.5156646729, -122.678695322], 15);

  L.esri.tiledMapLayer({
    url: 'https://www.portlandmaps.com/arcgis/rest/services/Public/Basemap_Color_Complete/MapServer'
  }).addTo(map);

  /* NO WORKIE: 404 to undefined */
  L.esri.dynamicMapLayer({
    url: 'https://www.portlandmaps.com/arcgis/rest/services/Public/Hazard/MapServer',
    layers: [6],
    opacity: .6
  }).addTo(map);

  /* WORKIE: forcing 'image' output format */
  L.esri.dynamicMapLayer({
    url: 'https://www.portlandmaps.com/arcgis/rest/services/Public/Hazard/MapServer',
    layers: [6],
    opacity: .6,
    f: 'image'
  }).addTo(map);
</script>

</body>
</html>
```

Please let me know if it's a configuration issue on the service.  Thanks!

**Comment by jgravois** [comment]
i took a little bit deeper look after we talked yesterday afternoon and the [REST spec](
http://resources.arcgis.com/en/help/arcgis-rest-api/index.html#/Export_Map/02r3000000v7000000/) doesn't indicate that base64 images supplied in an `imageData` parameter within the [JSON](https://www.portlandmaps.com/arcgis/rest/services/Public/Hazard/MapServer/export?bbox=-1.366684172771099E7%2C5704143.625896585%2C-1.3646945021250913E7%2C5713922.645454622&bboxSR=&layers=&layerDefs=&size=&imageSR=&format=png&transparent=false&dpi=&time=&layerTimeOptions=&dynamicLayers=&gdbVersion=&mapScale=&f=pjson) are normal.

```js
{"href" : "<href>","width" : <width>,"height" : <height>,"extent" : {<envelope>},"scale" : <scale>}
```
my hunch that the service is misconfigured is reinforced by the fact that even the html operation page displays a broken [Download Image](https://www.portlandmaps.com/arcgis/rest/services/Public/Hazard/MapServer/export?bbox=-1.366684172771099E7,5704143.625896585,-1.3646945021250913E7,5713922.645454622) link.

to be perfectly honest, i'm not sure how you'd go about trying to fix the service up.  if you and your folks take a crack and can't figure it out, feel free to drop me another line here and i'll try to rope in additional resources to help.

**Comment by aaronkilbey** [comment]
It's looking like something changed in 10.3.1 with this imageData VS href in the JSON return.  I see a [couple](http://gis.stackexchange.com/questions/172944/arcgis-export-map-operation-is-returning-imagedata-string-not-the-expected-png) [mentions](https://geonet.esri.com/thread/174914).  Does ESRI have a 10.3.1 sampleserver?  I was able to find [one of ours that does return href](https://www.portlandmaps.com/arcgis/rest/services/Public/COP_OpenData/MapServer/export?bbox=-1.3672038636279594E7%2C5708517.246187274%2C-1.3634891061984446E7%2C5729273.850200483&bboxSR=&layers=&layerDefs=&size=&imageSR=&format=png&transparent=false&dpi=&time=&layerTimeOptions=&dynamicLayers=&gdbVersion=&mapScale=&f=pjson) but almost all return imageData.

**Comment by aaronkilbey** [comment]
The only noticeable difference I'm seeing between the services that return href and those returning imageData in the config is the former all have AntialiasingMode: "None" vs the latter all having some mode of anti-aliasing turned on.  I confirmed this on all.   We're bringing up one of the imageData-returning services on a 10.3 box to see if there's any difference

**Comment by jgravois** [comment]
i've got my own [cheatsheet of sample servers](https://gist.github.com/jgravois/577cb4556fd1f2e73f88) and unfortunately none are 10.31.  that being said, i'll look into it and let you know what i find out.

**Comment by aaronkilbey** [comment]
It was just a hunch but we restored one of the service definitions to a 10.3 box earlier and it still returned imageData.  Then I thought it was consistent that the services with anti-aliasing disabled were the ones returning href vs anti-aliasing on and imageData, but I found exceptions.  I'm out of ideas.

**Comment by jgravois** [comment]
Setting map service properties: http://resources.arcgis.com/en/help/main/10.2/index.html#/Setting_map_service_properties/0154000003p1000000:
> If no **output directory** is specified, map images are returned to client applications using MIME data.

based on my research it looks like publishing a service from an `.mxd` ensures that the **output directory** will be defined by the service editor. when publishing from an `.sd` file, i guess its up to you to provide one.

**Comment by aaronkilbey** [comment]
All services have the same output dir.  ESRI API must be accounting for imageData because we haven;t seen this until esri-leaflet.  We have the f: 'image' workaround though for the people here wanting to use dynamic services so it's not a big deal.    Thanks for looking into it.

**Comment by mquetel** [comment]
I verified that the services exhibiting this behavior already had output directories set. They were for the entire time that we have been looking at this issue.

![screen shot 2016-05-20 at 6 48 03 am](https://cloud.githubusercontent.com/assets/214979/15431639/abdcc934-1e5f-11e6-9f6a-d328eaa22141.png)

If AGS is apt to return data in this manner and the Esri JS API consumes it without incident, would't this project want to do the same?  🤷 ¯\_(ツ)_/¯

**Comment by jgravois** [comment]
> @mquetel If [...] the Esri JS API consumes it without incident, would't this project want to do the same? 🤷 ¯_(ツ)_/¯

the approach @aaronkilbey outlined in his initial post ensures that raw images are requested from ArcGIS Server (as opposed to a JSON object).  this is the same technique the JSAPI uses to display dynamic map services.

that said, even if base64 encoded images in response JSON are rare, i'll try and find time soon to test with your services to determine just how difficult it would be for this API to decode them when they're encountered.
