### ISSUE TITLE
Feature Layer Click Event Unexpected Behavior

### ISSUE THREAD

**Issue by joelhickok** [Esri/esri-leaflet#785]
* Browser and version: Chrome 50 and Firefox 46

* Version of Leaflet (`L.version`): 1.0.0-rc.1

* Version of esri Leaflet (`L.esri.VERSION`): 2.0.0

* I'm loading/bundling the library using:
Tested both with local webpack, babel, es6 setup and on JSBin using CDN.
http://jsbin.com/jecuci/edit?js,console,output

Steps to reproduce the error:
1. Instantiate Leaflet map.
2. Add any basemap.
3. Add an Esri Feature layer (tested myself with points and polygons).
4. Create a click event on the ftr layer.
5. Click on map pane.

What happens is:
a. In my webpack local server setup, no event seems to fire, no console output.  Nothing.
b. In JSBin the event object looks like A LOT a Window object and some other data.

I was expecting:
Normal click event data including the feature/layer, etc.

**Comment by jgravois** [comment]
we don't fire an `L.esri.featureLayer` 'click' event.  this is Leaflet's own `L.marker` [MouseEvent](http://leafletjs.com/reference.html#marker-click).

can you do me a solid and confirm whether or not you can reproduce this behavior in webpack with Leaflet all by itself? 

```js
var map = L.map('map').setView([45,-122], 16);
var marker = L.marker([45,-122]).addTo(map)

marker.on('click', function (e) {
  console.log(e);
});
```

**Comment by joelhickok** [comment]
Sorry... looks like the problem is with Leaflet 1.0.0-rc.1.  Everything works fine in the Webpack dev environment, as I have been doing for months.

The problem occurred when I started my first project using Esri-Leaflet 2.0.0, which forces the use of Leaflet 1.0.0-rc.1.  Mouse events work fine with Marker layers, GeoJSON layers, Esri FeatureLayers, and more, but as soon as you upgrade to 1.0.0-rc.1 the mouse events stop firing.

I'll post the issue in the right place!

Thanks.

**Comment by joelhickok** [comment]
Not sure why the unexpected behavior is occurring... set up test project where it was absolutely black and white: 
* Comment in Leaflet 1.0rc1 and mouse clicks did NOT work
* Comment out Leaflet 1.0rc1 and mouse clicks worked
    * This is on a GeoJSON layer with style transparency enabled.
    * Nothing else changed -- just which Leaflet version I was bringing in (0.7.7 vs 1.0rc1)

Meanwhile, in my original project, I have mouse clicks working again with Esri Leaflet 2.0.0 and Leaflet 1.0.0-rc.1!?

Overall, unexpected behavior still with the Leaflet release candidate, and will be using more stable versions in production for now.
