### ISSUE TITLE
L.esri.FeatureLayer addfeature and removefeature events not fired at all

### ISSUE THREAD

**Issue by denydias** [Esri/esri-leaflet#788]
* Browser and version: Chromium 51.0.2704.84
* Version of Leaflet (`L.version`): 0.7.7
* Version of esri Leaflet (`L.esri.VERSION`): 1.0.3
* I'm loading/bundling the library using: [CDN](https://cdn.jsdelivr.net/leaflet.esri/1.0.3/esri-leaflet.js)

Steps to reproduce the error:
1. Run this [jsbin](http://jsbin.com/mazagipage/1/edit?html,output).
2. In layer control, disable Neighborhoods.

What happens is that labels are kept on map even after the parent layer was disabled.

I was expecting that `addfeature` and `removefeature` could work to add and remove labels when enabling/disabling the parent layer. These events are never fired tough, as even the `console.log` messages aren't throw. Is there a bug with these events?

**Comment by jgravois** [comment]
currently, 'add' and 'remove' events are only fired when individual features are appended or dropped from the current collection of a `featureLayer` that is still being drawn on the map.  that said, it seems totally appropriate that the same corresponding events also fire when the entire layer is toggled on/off too.

a proposed fix can be found in #790.  once its merged, it will appear in our next tagged release (2.0.1) afterward, i should be able to find some time to backport and create a `1.x` release as well if it'd be helpful.

**Comment by denydias** [comment]
Hi, @jgravois!

**Comment by jgravois** [comment]
the fix has been merged into `master` and backported to [`1.0.4`](https://github.com/Esri/esri-leaflet/blob/master/CHANGELOG.md#104).  thanks for reporting.

**Comment by denydias** [comment]
That's beautiful, @jgravois! Thank you very much for your quick action and backporting.
