### ISSUE TITLE
L.esri.featureLayer in control.layers doesn't redraw layer without changing zoom (1.0.0-rc.1 / 2.0.0-beta.8; Chrome 51.0.2704.79 and FF 46.0.1)

### ISSUE THREAD

**Issue by Guerillero** [Esri/esri-leaflet#789]
I am pulling both ESRI leaflet and leaflet from jsdelivr.

[Here](http://atlas.washcoll.net/~tdf/Easy-ESRI-Map/leaflet/) is a sandbox that shows the issue. The short version is that if you have a `L.esri.featureLayer` in a `control.layer` and you turn it off and then on again the layer does not draw.

https://github.com/Leaflet/Leaflet/issues/4622 may also be of interest. I don't really know what the fix would be except listening for an `overlayadd` and forcing a fresh call to the server.

**Comment by jgravois** [comment]
this problem is not reproducible in [`2.0.0`](http://cdn.jsdelivr.net/leaflet.esri/2.0.0/esri-leaflet.js) :sparkles:.
