### ISSUE TITLE
wanted: additional project maintainers/contributors (all experience levels welcome)

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet#791]
even if you don't consider yourself an experienced Leaflet developer, having additional eyes on this project would be extremely helpful.

if you're willing, even sporadically, to review Pull Requests, help keep the [documentation](https://github.com/esri/esri-leaflet-doc/issues) up to date, and/or chip in with a bug fix, please let me know.
- https://github.com/Esri/esri-leaflet
- https://github.com/Esri/esri-leaflet-doc
- https://github.com/Esri/esri-leaflet-geocoder
- https://github.com/Esri/esri-leaflet-cluster
- https://github.com/Esri/esri-leaflet-heatmap
- https://github.com/Esri/esri-leaflet-vector
- https://github.com/Esri/esri-leaflet-renderers
- https://github.com/Esri/Leaflet.shapeMarkers
- https://github.com/jgravois/esri-leaflet-gp
- https://github.com/jgravois/esri-leaflet-related
- https://github.com/jgravois/lrm-esri

if you'd _like_ to get involved, but need a little guidance, that would be great too!

**Comment by eallenOP** [comment]
I have some students who are looking for projects to help with. They are not yet really programmers but are keen to help with documentation etc. They start in a month. Is there anything they can help with?

**Comment by jgravois** [comment]
awesome! we track documentation issues in https://github.com/esri/esri-leaflet-doc/issues

i'm more than happy to give guidance if any of them have questions.

**Comment by tyleralves** [comment]
@jgravois 
I've been playing with ArcGIS JS API, Leaflet and ESRI-leaflet and have about three years professional experience with ArcGIS Desktop (hopefully helpful?). I would love to contribute/ review/ document as needed. I have a solid command of JS, but will probably start with documentation/ minor code contributions until I get a better handle on the code base.

**Comment by jgravois** [comment]
@tyleralves your contributions so far have been really helpful.  keep em coming!

**Comment by robertd** [comment]
I can donate some of my time under @robertd or @rdjurasaj-usgs

**Comment by sethlewis** [comment]
@jgravois 

I'd like to assist, beginning with documentation until I become more proficient with the codebase.

**Comment by jgravois** [comment]
i'm glad to see so many offers to help.  don't be shy if you have any questions about getting started.

**Comment by roemhildtg** [comment]
Esri leaflet is awesome. I'd like to help. The project is important to me because it works with jspm and works so well with other loaders.

**Comment by theashyster** [comment]
@jgravois By the way, the link to the `esri-leaflet-gp` library is wrong in the first post. :)
I can also probably chime in from time to time to help out if needed.

**Comment by nickpeihl** [comment]
I'm actively watching the `esri-leaflet` repo and will help out where I can.

**Comment by jgravois** [comment]
@nickpeihl you've already been a big help. thank you!

ps. is there a group that you know of in Seattle that might cohost a #GeoDev meetup with us in late September? we already have a venue, just looking for more good folks to invite.

**Comment by nickpeihl** [comment]
@jgravois A few possible suggestions:
* [Maptime Seattle](http://maptimesea.github.io/)
* [PyLadies](http://seattle.pyladies.com/) - Python specific
* [SeattleJS](https://www.meetup.com/seattlejs/) - JavaScript specific
* [Cugos](http://cugos.org) - open source geo

**Comment by jgravois** [comment]
this would be a great issue to 'pin' 😉
