### ISSUE TITLE
Query a feature layer by drawing on a map.

### ISSUE THREAD

**Issue by AATinc** [Esri/esri-leaflet#792]
Browser: Chrome
Leaflet: 7

I'm relatively new to leaflet and brand new to posting on GitHub so any help would be greatly appreciated.

Currently I am looking at querying a feature layer by drawing on a map in Esri Leaflet referencing our ARCgis 10.4 server. 

Basically we want to do what Apartments.com does with their polygon search where they show what houses are for sale via markers inside that polygon, but using leaflet and referencing our ArcGis server. There are plenty of examples of people doing this, but I have not seen ones where they use Arc.

Again, any help, tips or advice will be appreciated.

**Comment by jgravois** [comment]
the easiest thing to do would be to use something like [Leaflet.draw](https://github.com/Leaflet/Leaflet.draw) to enable users to sketch on your map.  afterward, you'd need to pass along the GeoJSON and pass it in a spatial query.

http://esri.github.io/esri-leaflet/examples/spatial-queries.html
http://esri.github.io/esri-leaflet/api-reference/tasks/query.html

**Comment by jgravois** [comment]
closing, but happy to chat more if you have any additional questions.
