### ISSUE TITLE
Question: L.esri.Request undefined?

### ISSUE THREAD

**Issue by bassena** [Esri/esri-leaflet#793]
I couldn't find a definitive answer online. Is there a specific time in the file load process at which L.esri.Request is defined? It seems that at anytime I try to use L.esri.Request (i.e. to force L.esri.get to be set to use JSONP, such as described [here](https://esri.github.io/esri-leaflet/api-reference/request.html#l-esri-get-url-params-callback-)). I get an undefined error on L.esri.Request. I tried creating a new blank project with only leaflet + esri-leaflet and this still occurs. Am I being silly and missing something? If it's worth anything, I'm in the process of updating scripts from previous versions of Leaflet and esri-leaflet.

This issue is while using Leaflet 1.0.0-rc.1 and esri-leaflet v2.0.0. Any insight would be great, thanks!

**Comment by jgravois** [comment]
We removed L.esri.**R**equest() in [`2.0.0-beta.1`](https://github.com/Esri/esri-leaflet/blob/master/src/Request.js#L218-L220).  L.esri.**r**equest() is defined immediately.  

From the [Changelog](https://github.com/Esri/esri-leaflet/blob/master/CHANGELOG.md#200-beta1):
> L.esri.Request has been removed. Please use L.esri.get, L.esri.get.CORS, L.esri.get.JSONP, L.esri.post or L.esri.request directly.

**Comment by bassena** [comment]
I see, thanks! I think the website should be updated to reflect these new changes to avoid future confusion, seeing as 2.0.0 seems to be the current stable release.
