### ISSUE TITLE
Attribution can disappear when map getBounds( ) return out range values

### ISSUE THREAD

**Issue by sinaru** [Esri/esri-leaflet#798]
* Browser and version: 
Firefox 47

* Version of Leaflet (`L.version`):  
0.7.2

* Version of esri Leaflet (`L.esri.VERSION`): 
1.0.3

* I'm loading/bundling the library using: 
Own server.

Steps to reproduce the error:
1. Go to near meridian
2. Be in a zoom level that is around 16
3. Scroll left

What happens is since `map.getBounds()` can return an out of range longitude value from leaflet behavior as noted in [https://github.com/Leaflet/Leaflet/issues/1885](https://github.com/Leaflet/Leaflet/issues/1885), the attribution value will be set as empty on these occasions. 

Check the method definision `_updateMapAttribution` and how `getBounds( )` is used.

I was expecting to use `wrap( )` method inside `_updateMapAttribution` so that the bound ranges will be in a valid range.

**Comment by sinaru** [comment]
Hi i also had same behavior on for a bing layer plugin and reported the same issue. They have fixed it with wrap() approach. 
https://github.com/shramov/leaflet-plugins/issues/229

**Comment by sinaru** [comment]
Ping @jgravois

**Comment by jgravois** [comment]
you're reporting the same behavior i described [here](https://github.com/Esri/esri-leaflet/pull/797#issue-164186589).  

like you said, its a trivial fix. i've included it in [`1d4d7c8`](https://github.com/jgravois/esri-leaflet/blob/1d4d7c8874b59ab164a16452e015d3db909ac7f9/src/Util.js#L172-L182) and will backport to `1.x` sometime soon.

**Comment by sinaru** [comment]
Hi @jgravois I came to look into the issue. I realized that you have made the changes to 2.0.x but not for 1.0.x? When can I expect the changes for 1.0.x. 
Thanks

**Comment by jgravois** [comment]
Leaflet appears to finally be nearing an official `1.0.0` so i don't think i'll bother tagging an `0.7.x` compatible release of Esri Leaflet solely for this change.
