### ISSUE TITLE
Faulty Basemap Crashes JavaScript

### ISSUE THREAD

**Issue by jordanparfitt** [Esri/esri-leaflet#803]
The issue isn't browser or version specific but I'm using ESRI leaflet 2.0.

I have a basemap layer that is a bit of a pill. The endpoint acts just fine so I don't get any data back. I get this error though.

![image](https://cloud.githubusercontent.com/assets/1232294/16856585/2f6274b8-49d8-11e6-9c4c-e6c599a3a981.png)

I fixed it quickly by checking for the spatial reference 

> if (metadata.spatialReference) {}

```
onAdd: function(map){
    if (!this._lodMap && this.options.correctZoomLevels) {
      this._lodMap = {}; // make sure we always have an lod map even if its empty
      this.metadata(function (error, metadata) {
          if (metadata.spatialReference) {
              if (!error) {
                  var sr = metadata.spatialReference.latestWkid || metadata.spatialReference.wkid;

                  if (sr === 102100 || sr === 3857) {
                      //create the zoom level data
                      var arcgisLODs = metadata.tileInfo.lods;
                      var correctResolutions = EsriLeaflet.Layers.TiledMapLayer.MercatorZoomLevels;

                      for (var i = 0; i < arcgisLODs.length; i++) {
                          var arcgisLOD = arcgisLODs[i];
                          for (var ci in correctResolutions) {
                              var correctRes = correctResolutions[ci];

                              if (this._withinPercentage(arcgisLOD.resolution,
                                  correctRes,
                                  this.options.zoomOffsetAllowance)) {
                                  this._lodMap[ci] = arcgisLOD.level;
                                  break;
                              }
                          }
                      }
                  } else {
                      EsriLeaflet.Util
                          .warn('L.esri.TiledMapLayer is using a non-mercator spatial reference. Support may be available through Proj4Leaflet http://esri.github.io/esri-leaflet/examples/non-mercator-projection.html');
                  }
              }
          }
          L.TileLayer.prototype.onAdd.call(this, map);
      }, this);
    } else {
      L.TileLayer.prototype.onAdd.call(this, map);
    }
  },

```

The real bug is in my basemap but now when it fails to load my users can still use the application.

**Comment by jgravois** [comment]
can you share a url?  what version of ArcGIS Server?  what spatial reference?

**Comment by jgravois** [comment]
also, maybe i'm just being pedantic, but i wouldn't say the application is *crashing*.  

you're describing an uncaught exception in the console, but its not preventing additional code from executing, (at least on my side)

```js
// throws an exception (because the service doesn't include a tile cache)
var base = L.esri.tiledMapLayer({
  url:'http://sampleserver6.arcgisonline.com/arcgis/rest/services/DamageAssessment/FeatureServer'
}).addTo(map);

// next layer still loads
var fl = L.esri.featureLayer({
  url:'http://sampleserver6.arcgisonline.com/arcgis/rest/services/Census/MapServer/3'
}).addTo(map);
```

**Comment by jordanparfitt** [comment]
My service is internal and doesn't fail consistently. 

The only way I've found to replicate the bug is to set a URL to the services directory, something like this:

```
var base = L.esri.tiledMapLayer({
  url:'http://sampleserver6.arcgisonline.com/arcgis/rest/services'
}).addTo(map);

```

I'm runnning on 10.2.2 still. All my services are in spatial reference 4269. Metadata is an object it just doesn't have spatial reference. After I get the error none of my other basemaps will load, so the user can't use the application. Some JavaScript isn't running on my end.

**Comment by jordanparfitt** [comment]
Any chance you will add that line of code?

**Comment by jordanparfitt** [comment]
Didn't mean to close it

**Comment by jgravois** [comment]
> Any chance you will add that line of code?

absolutely.
i'm in the middle of trying to figure out to get our test suite passing in Node `v6`.  i'll plan on patching afterward unless i see a PR from you or some other industrious person first.
