### ISSUE TITLE
Leaflet version should match

### ISSUE THREAD

**Issue by timwis** [Esri/esri-leaflet#805]
Just wanted to document some troubleshooting I just did to save anyone else some time.

I was trying to use esri-leaflet in my browserify setup to add a `tiledMapLayer`. First, I imported via:

```javascript
const L = require('leaflet')
require('esri-leaflet')
```
But then `L.esri.tiledMapLayer` was undefined, so I used `const esri = require('esri-leaflet')` and added the layer via `esri.tiledMapLayer` (no `L.` prefix).

It was no longer undefined, but I was getting an error about `_getPane` in the leaflet source code. After a while googling and debugging, I realized it was because esri-leaflet uses `v1.0.0-rc.1` of leaflet, while the current `npm install leaflet` gives you `v0.7.7` [see npm](https://www.npmjs.com/package/leaflet). So if you instead `npm install leaflet@1.0.0-rc.1` esri-leaflet will work. Argh peer dependencies! :P

Anyway, hopefully this saves someone some time. I'll close the issue since it's resolved, but feel free to open it if I can elaborate on anything.

**Comment by jgravois** [comment]
thx @timwis.  we actually have both `0.7.x` and `1.0.rc.x` compatible esri-leaflet releases.

https://github.com/esri/esri-leaflet#dependencies

if you looked somewhere else for this information in vain, we could probably link to it
