### ISSUE TITLE
ImageLayer Token Authentication

### ISSUE THREAD

**Issue by alexpatow** [Esri/esri-leaflet#807]
Hi All,

For a project I'm working on I needed to authenticate an ImageService using esri-leaflet. I have code to fix this issue if the maintainers would like a pull request (see below).

* Browser and version:

Chrome 51/52, Safari 9.1.2

* Version of Leaflet (`L.version`):

0.7.7, 1.0.0-rc.1, 1.0.0-rc.2

* Version of esri Leaflet (`L.esri.VERSION`):

1.0.3, 2.0.1

Steps to reproduce the error:

1) Create a new html file with the contents of: http://esri.github.io/esri-leaflet/examples/arcgis-server-auth.html

2) Replace L.esri.dynamicMapLayer with L.esri.imageMapLayer

3) Replace URLs and Username/Password with your server and credentials

4) Open file in browser

What happens is:

1)  Browser gets token correctly (200 status)

2) Browser performs GET call to the service's "?exportImage" endpoint with token, bounding box, format, and other parameters

3) Browser receives an object with href, width, height, extent, and scale properties

3) Browser attempts to get the .png image using the href string in the previous response, but it returns a 499 error (Token Required)

I was expecting the service to return the image for leaflet to display.

I'd be happy to make a plunkr if you have an Image Service with public credentials.

I've tried with both CDN and [browserify](http://browserify.org/)

*Fix:*

I discovered that appending the token to the "href" returned by the image service will correctly return the image.

Adding:
if (this.options.token) {
  response.href += ('?token=' + this.options.token);
}

After:
if (error) { return; }

in src/Layers/ImageMapLayer.js seems to work.

Thanks,

Alex

**Comment by jgravois** [comment]
> if the maintainers would like a pull request...

sounds great!

**Comment by alexpatow** [comment]
Please see pull request #811

**Comment by alexpatow** [comment]
Please see #812

**Comment by alexpatow** [comment]
Thanks for merging and closing this! I'd love to continue contributing, is there any issue in particular I can help with?

Thanks,

Alex

**Comment by jgravois** [comment]
> is there any issue in particular I can help with?

thanks for offering!  anything from the open issues list in this repo or our documentation repo are fair game.

https://github.com/esri/esri-leaflet/issues
https://github.com/esri/esri-leaflet-doc/issues

we're also always interested in general guinea pigging and exploratory testing.  getting feedback regarding whatever points of confusion you encounter along the way would be totally helpful.
