### ISSUE TITLE
Loadtimes on Mobile

### ISSUE THREAD

**Issue by MKellyEsri** [Esri/esri-leaflet#813]
Hello Team esri-leaflet,

I have been doing some testing from a mobile perspective around Esri Leaflet. One of the things I have noticed is that it can be quite slow to load on mobile when not on WiFi. I am using the latest versions of Leaflet and Esri Leaflet - code in links below:

[Loading Leaflet but not Esri Leaflet](http://esri-ireland.azurewebsites.net/withoutEsriLeaflet/)
[Video loading the above page on iPhone 6](https://www.youtube.com/watch?v=USD7Z8BUWQo)

[Loading Leaflet and Esri Leaflet](http://esri-ireland.azurewebsites.net/withEsriLeaflet/)
[Video loading the above page on iPhone 6](https://www.youtube.com/watch?v=3VryB1UXQLc)

The link which includes the Esri Leaflet library loads fine on Desktop. However, when loading on mobile, the load times rise significantly. Take a look at the videos above to compare. Note: the Esri Leaflet library isn't being used in the JavaScript above - it's just being added as a script tag in the html.

Any thoughts on how I could improve this behaviour? The end goal here is to display a secured basemap via a proxy or with a long lived token, but these load times are holding us back as mobile responsiveness is important to the customer in question.

Kind regards,

Michael

**Comment by andygup** [comment]
Have you tried testing with Esri-Leaflet hosted on your azure instance? Could be a CDN issue in your region as related to your cellular network.

**Comment by jgravois** [comment]
i suspect that gupper is on the right track.  kinda strange though, given that you're also pulling Leaflet from the same CDN.  

just to give you a basis for comparison.  with network speeds throttled to 'Regular 4G' in Chrome, here in Southern California it only takes 129ms for me to load `esri-leaflet.js`.

please let us know the impact of bundling the library alongside your application.
![screenshot 2016-07-29 09 29 31](https://cloud.githubusercontent.com/assets/3011734/17255655/fe9d54ea-556e-11e6-82a7-a600f943c640.png)

**Comment by MKellyEsri** [comment]
Cheers for the suggestions guys - I'll definitely give that a shot once I'm back in the office on Tuesday. It's a strange one alright - it was loading fine when throttling through Chrome as well. I must compare the load times with yours! It was even loading fine when thethering the wifi off my phone! Anyway I'll give an update once I get another look!

**Comment by MKellyEsri** [comment]
Just a quick update on this - hosting the Esri-Leaflet library didn't quite do it. Hosting via Azure seems to be part of the problem. I changed to Register365 hosting and the load times were as expected!

I changed some things so everything is requested over either http or https. I also checked out the network traffic via a Mac and there was a serious latency (up to 20s) on one file each time varying from css to js to font files!

I'll do some more testing and once I'm sure the problem is resolved I'll let you know.

**Comment by andygup** [comment]
I've seen that behavior before with a variety of CDNs. 

A few more suggestions:
- You might try purging the cache. 
- Recheck your cache settings for Expiry Policies and Times.
- Verify the primary servers CPU and bandwidth load. If the CDN is refreshing from a primary server based on Expiry rules and that server is bogged down it can affect the overall CDN performance.
- Run traceroutes from the server outbound and also from external clients to the server. Sometimes there are intermediary routing issues that can be identified by this simple test.

**Comment by jgravois** [comment]
closing since there are no action items on our end, but happy to chat more if it'd be helpful.

**Comment by MKellyEsri** [comment]
Thanks John - this has taken the back seat over the past while as other things have come in. I do plan to get back to it at some stage and will let you know when I do get to the bottom of it!
