### ISSUE TITLE
Identify Features returning no features for certain CRS (SR)

### ISSUE THREAD

**Issue by alexgleith** [Esri/esri-leaflet#817]
* Browser and version:

ie: Chrome 51, IE11

* Version of Leaflet (`L.version`):

0.7.7, 1.0.0-rc.1?

* Version of esri Leaflet (`L.esri.VERSION`):

2.0.1

My Code: https://github.com/alexgleith/tasmap.org/blob/master/app/scripts/main.js

The map with layer in question: https://tasmap.org/?layers=list-Public/Indexes-62;list-Public/TopographyAndRelief-27#12/-42.8771/147.3361

Steps to reproduce the error:

1. I have a MapServer: http://services.thelist.tas.gov.au/arcgis/rest/services/Public/TopographyAndRelief/MapServer/ using layer 27
2. I can display it fine
3. I set up an identify features request like this:
```
  L.esri.identifyFeatures({
    url: layer.url
  })
  .on(map)
  .at([clickCoords.lat, clickCoords.lng])
  .layers('layers=visible:' + layer.meta.id)
  .run(function(error, data, response){
      handleData(layer, data)
  });
```

Result is an empty response is returned.

Here's an example of a working one:
```
http://services.thelist.tas.gov.au/arcgis/rest/services/Public/TopographyAndRelief/MapServer/identify?f=json&geometry=16401771.159617,%20-5294107.8565869&sr=3857&layers=visible:27&tolerance=3&geometryPrecision=0&maxAllowableOffset=2&mapExtent=16393344.126497,-5297808.140769,16412587.148367,-5290489.2953108&imageDisplay=1302,%20383,%2096&returnGeometry=true&callback=jQuery17208365000503506728_1470088535457&_=1470089606882
```

And a failing one:
```
https://services.thelist.tas.gov.au/arcgis/rest/services/Public/TopographyAndRelief/MapServer/identify?sr=4326&layers=layers%3Dvisible%3A27&tolerance=3&returnGeometry=true&imageDisplay=1007%2C377%2C96&mapExtent=147.16323852539065%2C-42.92450315305873%2C147.50896453857425%2C-42.82965295224943&geometry=147.33283996582034%2C-42.87168681085845&geometryType=esriGeometryPoint&f=json
```

I'm not sure how to change the identifyFeatures method to handle all cases regarding CRSs, if that's the issue. Note that the mapping system works for some layers, and I wonder if it is working for those layers using WGS?

**Comment by jgravois** [comment]
the failing request contains in invalid parameter value.

> &layers=**layers%3D**visible%3A27

its easier to see the problem when the url is decoded.

> &layers=**layers=**visible:27

this is because you are passing the same string unnecessarily to `IdentifyFeatures.layers()`
```js
L.esri.identifyFeatures({
    url: layer.url
  })
  .on(map)
  // operator + layer identifier - http://resources.arcgis.com/en/help/arcgis-rest-api/index.html#/Identify_Map_Service/02r300000113000000/
  .layers('visible:' + layer.meta.id)
  .run(function(error, data, response){
      handleData(layer, data)
  });
```

**Comment by alexgleith** [comment]
I don't understand. I can see I have an extra layers= there.

Can you show me what I should be including instead? Sould I just be including `.layers(layer.meta.id)` (which would be 27) ?

And, oddly, a layer like this one works: https://tasmap.org/?layers=list-Public/OpenDataWFS-13#18/-42.83343/147.28379

```
https://services.thelist.tas.gov.au/arcgis/rest/services/Public/OpenDataWFS/MapServer/identify?sr=4326&layers=layers%3Dvisible%3A13&tolerance=3&returnGeometry=true&imageDisplay=1007%2C403%2C96&mapExtent=147.281089425087%2C-42.83422032797487%2C147.286491394043%2C-42.83263496362249&geometry=147.28230714797976%2C-42.83292607575776&geometryType=esriGeometryPoint&f=json
```
