### ISSUE TITLE
tiledMapLayer should fetch/display service attribution

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet#831]
it wouldn't be hard to handle updating attribution using metadata from tiled map services
✨  *automagically* ✨ 

* if the developer passed `attribution` in the object constructor, don't overwrite it
* if they didn't, we're already making a [`metadata`](https://github.com/Esri/esri-leaflet/blob/master/src/Layers/TiledMapLayer.js#L104-L122) request when the layer is added to the map

```js
// something like this should work...
if (!layer.options.attribution && map.attributionControl) {
  layer.options.attribution = metadata.copyrightText;
  map.attributionControl.addAttribution(layer.getAttribution());
}
```

**Comment by tyleralves** [comment]
I'll take it.

**Comment by jgravois** [comment]
thx @tyleralves
