### ISSUE TITLE
dynamic layers throwing 500 errors and masking other map marker events

### ISSUE THREAD

**Issue by cgalvarino** [Esri/esri-leaflet#833]
* Browser and version:

Chrome 52.0.2743.116 m (64-bit)

* Version of Leaflet (`L.version`):

0.7.7

* Version of esri Leaflet (`L.esri.VERSION`):

1.0.4

Hello, I am having the same problem described here http://gis.stackexchange.com/questions/186013/handling-errors-with-esri-leaflet-dynamic-map-layers when adding a publically (token based) service from here https://www.arcgis.com/home/item.html?id=5b84e159dace4bf8ad9e9154085ba45d.  Even their Map Viewer throws 500 errors.

I add the layers then authenticate(), and all is fine.  But then the tiles are fetched and 500 errors are thrown.  These strangely mask my ability to handle completely unrelated mouse clicks and mouseovers on markers in my leaflet map.  I don't see a way to either handle these errors gracefully or ask esri-leaflet not to fool w/ anyone else's mouse events.

Any ideas?

TIA.

Charlton

**Comment by cgalvarino** [comment]
Sorry, that argcis tile source link wasn't the right one.  I updated it in the original text.

**Comment by jgravois** [comment]
> Even their Map Viewer throws 500 errors.

i'm able to see the live hurricane data displayed in the map viewer after opening the link below and signing in with my organizational credentials.

https://www.arcgis.com/home/webmap/viewer.html?layers=5b84e159dace4bf8ad9e9154085ba45d

> I add the layers then authenticate(), and all is fine. But then the tiles are fetched and 500 errors are thrown. 

what layer type are you using to try and display the service in esri leaflet?  since no tiles have been cached for this service, i used a `dynamicMapLayer` and it displays just fine.

```js
var secureDynamic = L.esri.dynamicMapLayer({
  url: "http://livefeeds.arcgis.com/arcgis/rest/services/LiveFeeds/Hurricane_Active/MapServer/"
});
secureDynamic.authenticate("...");
secureDynamic.addTo(map);
```

**Comment by cgalvarino** [comment]
At the time it was erroring out. During active storms naurally. I'll try to spin up a dummy svc here that does nothing other than 300s and report back.

**Comment by jgravois** [comment]
happy to dig in further to see what we can do in the repo if anyone can share a repro case.

**Comment by cgalvarino** [comment]
Rats. Sorry I let this one grow stale. I saw the same behavior for a working dynamic layer that I had NOT applied a valid token to use. It would block the popups like the 503 seemed to do. I'll try to put an example together in the next day.
