### ISSUE TITLE
Displaying a L.dynamicMapLayer in  leaflet 0.7.7 fails with 404

### ISSUE THREAD

**Issue by marsmith** [Esri/esri-leaflet#847]
* Browser and version:
52.0.2743.116 m

* Version of Leaflet (`L.version`):
0.7.7

* Version of esri Leaflet (`L.esri.VERSION`):
1.0.4

Steps to reproduce the error:

1. Check out this plnkr:
https://plnkr.co/edit/8nLyNHrOsR0dZqYsiYGc?p=preview

Getting a 404 error while trying to load a NOAA dynamic map layer.  The map service IS returning an image if inspected in the developer console, but something along the way is throwing a 404 'undefined'

The strange thing is that it works if I swap out the dependencies to leaflet 1.0.0-rc3 and esri-leaflet 2.0.2:
https://plnkr.co/edit/QfxfbPI094eLGdB2fGpH?p=preview

**Comment by jgravois** [comment]
this is because the JSON response from the service returns base64 encoded imageData instead of a url to fetch the image.
```js
{ "imageData":"iVBORw0KGgoAAAANSUhEUgAAAg8AAAHKCAYAAACE6Kg4AAAAAXNSR0IB2..."
```
i introduced support for that particular *feature* in [`v2.0.1`](https://github.com/Esri/esri-leaflet/releases/tag/v2.0.1) (more info in #782)

**Comment by marsmith** [comment]
For future reference-- after checking out the referenced thread, I solved the issue by adding an option:
`f:'image'` to the L.dynamicMapLayer.  

See modified working plunkr here:
https://plnkr.co/edit/ShqRWA5aR8GCXLQEPqF4?p=preview
