### ISSUE TITLE
omit namespace when calling calcAttributionWidth from within 'Util'

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet#850]
~~L.esri.Util.~~`calcAttributionWidth(map)`

https://github.com/Esri/esri-leaflet/blob/bf2e7d9bb61e0b18e74d654dd88e697139aa4974/src/Util.js#L161
https://github.com/Esri/esri-leaflet/blob/bf2e7d9bb61e0b18e74d654dd88e697139aa4974/src/Util.js#L169

**Comment by jgravois** [comment]
this breaks bundles downstream that want to selectively import a tree-shaken ES6 module

**Comment by jgravois** [comment]
thanks for volunteering to help with this one @hamhands!  if you're still having trouble calling karma from the CLI next time you crack your laptop locally let me know.

**Comment by hamhands** [comment]
@jgravois yeah karma is still giving me hell. Ima push the changes and let travis handle it for now.
