### ISSUE TITLE
Trying to load a private feature layer using authentication with ArcGIS Server

### ISSUE THREAD

**Issue by JRosh33** [Esri/esri-leaflet#851]
Chrome Version 52.0.2743.116 m (64-bit)
leaflet@1.0.0-rc.3
esri-leaflet@2.0.3

Thanks in advance for the help. Only have a little experience with HTML/JS. Can provide more information if needed.

**Steps to reproduce the error:**
Edit code using [ArcGIS Server username/password](https://esri.github.io/esri-leaflet/examples/arcgis-server-auth.html) template using my URLs, username, password, referer.

**Relevant script sample:**
![image](https://cloud.githubusercontent.com/assets/8837379/18760946/5255d5e0-80c0-11e6-9c38-2e6f4e242b7f.png)

**What happens is:**
Feature doesn't load.
I get this error: ArcServer_username_password.html:50 Uncaught TypeError: Cannot read property 'token' of undefined

**I was expecting:**
A polygon to appear in the map extent.

**Comment by jgravois** [comment]
use the browser network debugging tools to isolate the request for the token and see what the response was.  it sounds like it didn't include a token.

**Comment by JRosh33** [comment]
I'm not seeing the token in the response object. 
![image](https://cloud.githubusercontent.com/assets/8837379/18762096/a639eee0-80c4-11e6-8bfc-5b03f8061967.png)

Do my inputs into the template look right?

**Comment by jgravois** [comment]
* you need to tack `/generateToken` onto the end of that URL.
* the `referer` should be the URL of your own app (see the doc below for more info)

http://resources.arcgis.com/en/help/arcgis-rest-api/index.html#/Generate_Token/02r3000000m5000000/

also, please keep in mind that you shouldn't be including plain text usernames and passwords in production apps.

**Comment by jgravois** [comment]
@JRosh33 are you sorted out now?

**Comment by JRosh33** [comment]
Thanks for the help. I wasn't able to get it working so I just had the administrator change the feature service to public.

**Comment by jgravois** [comment]
long live open data 🎏
