### ISSUE TITLE
typings for esri-leaflet

### ISSUE THREAD

**Issue by ajainvivek** [Esri/esri-leaflet#860]
Is there any typings package for esri-leaflet to support typescript module?

**Comment by jgravois** [comment]
there is not.  if anyone from the community is interested in contributing TypeScript module definitions, that would be really cool.

**Comment by jgravois** [comment]
adding the `FAQ` label and closing since there are no action items for the maintainers, but feel free to chime in with your own 👍  (preferably as a reaction instead of a comment) to show your support for the idea.

**Comment by strajuser** [comment]
I've done definitions based on latest API reference. 
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17864

Branch was merged, it will be available in future releases.

**Comment by jgravois** [comment]
excellent!  thanks **so** much!

**Comment by jgravois** [comment]
i've updated the README with a new [FAQ](https://github.com//Esri/esri-leaflet/wiki/FAQ#typescript-typings) question related to the typings and shared a note in our most recent release [announcement](https://geonet.esri.com/groups/geodev/blog/2017/07/28/esri-leaflet-v210).

thanks again!
