### ISSUE TITLE
CORS Issue for Vector Maps

### ISSUE THREAD

**Issue by JamesMilnerUK** [Esri/esri-leaflet#861]
Hey folks, hope you're well, congrats on the new release. I'm having some issues with vector maps and CORS with Esri Leaflet.

* Browser and version:

ie: Chrome 51, IE11

* Version of Leaflet (`L.version`):

1.0.1

* Version of esri Leaflet (`L.esri.VERSION`):

2.0.3

Steps to reproduce the error:

Open up a Esri Leaflet map that uses Streets, Gray, Dark Gray vector basemap

You will see an error similar to:

22:17:23.010 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://www.arcgis.com/sharing/rest/content/items/4e1133c28ac04cca97693cf336cd49ad/resources/https://www.arcgis.com/sharing/rest/content/items/4e1133c28ac04cca97693cf336cd49ad/resources/styles/sprites/sprite.json. (Reason: CORS header 'Access-Control-Allow-Origin' missing).1(unknown)

I was expecting it to load the vector map. Assuming this is an issue with the server config?

You can reproduce this from the examples page: https://esri.github.io/esri-leaflet/examples/vector-basemap.html

Interestingly the Newspaper map works just dandy.

**Comment by jgravois** [comment]
thanks for reporting @JamesMilnerUK.  

i'll try swapping in a manual JSONP call [here](https://github.com/Esri/esri-leaflet-vector/blob/3d592e620f0bed995c9b4c2972134ace9f7db4b2/src/Basemap.js#L44) and let you know the outcome soon.

**Comment by jgravois** [comment]
previously all our vector basemap json denoted the location of glyphs and sprites using a relative path.

[Newspaper](https://www.arcgis.com/sharing/rest/content/items/4f4843d99c34436f82920932317893ae/resources/styles/root.json?f=json) still does this.
```json
"glyphs": "../fonts/{fontstack}/{range}.pbf",
"sprite": "../sprites/sprite",
```
at some point very recently, our primary vector basemaps (Gray, Streets, etc.) started using fully qualified paths.

[Topographic](https://www.arcgis.com/sharing/rest/content/items/6f65bc1351b7411588a8cb43fe23dad7/resources/styles/root.json?f=json)
```json
"glyphs": "https://basemaps.arcgis.com/b2/arcgis/rest/services/World_Basemap/VectorTileServer/resources/fonts/{fontstack}/{range}.pbf",
"sprite": "https://www.arcgis.com/sharing/rest/content/items/6f65bc1351b7411588a8cb43fe23dad7/resources/styles/../sprites/sprite",
```
i've proposed a simple check in esri-leaflet-vector to determine whether or not sprite/glyph urls for the basemap need to be modified, but i'm going to do a bit more research first to make sure that its a sufficient fix before i merge and tag a new release.
