### ISSUE TITLE
Image Requests for dynamicMapLayer are not going through Proxy

### ISSUE THREAD

**Issue by droverflow** [Esri/esri-leaflet#862]
- Browser and version:
  IE11
- Version of Leaflet (1.0.1):
- Version of esri Leaflet (2.0.3):

Steps to reproduce the error:

Call a dynamicMapLayer via a proxy

Results:
Service is correctly called via proxy
Image requests do not get called via proxy

Expected Results:
Image requests should also go through proxy

Reason:
Our Arcgis server is locked down, and the only access is via the proxy, images cannot be retrieved directly from the arcgis server.

**Comment by jgravois** [comment]
i can reproduce the error you've described.
until its fixed, try just requesting images directly (instead of fetching JSON which includes a url).

```js
L.esri.dynamicMapLayer({
  url: './proxy?http://server/arcgis/rest/services/Name/MapServer',
  f: 'image'
}).addTo(map);
```
