### ISSUE TITLE
How to understand the terms of use ? 

### ISSUE THREAD

**Issue by ojollivet** [Esri/esri-leaflet#863]
Hello,

I am new to leaflet and esri-leaflet and I am currently studying the possibility to use these two libraries in an application in a commercial context. I read the terms of use but I am not sure to fully understand them. When one wants to develop in a commercial context an application displaying a map with esri-leaflet (so with an ESRI basemap), shall I refer to [the terms of use of Esri-Leaflet](https://github.com/Esri/esri-leaflet#terms)  telling that I need to:
 1.   Sign up for a free developer account.
 2.  Display Esri attribution and recognize data providers.

Or to [the terms of use of ESRI](https://developers.arcgis.com/terms/), as suggested by Leaflet when using ESRI basemaps, implying to pay for an ArcGIS online account.

I read [one old post](https://github.com/Esri/esri-leaflet/issues/338) related to this but as it is two years old and I did not know if the terms of use were modified since, please be clement and possibly reconsider the answer.

Thanks a lot for your answer and the time took to answer !

**Comment by jgravois** [comment]
@patrickarlt's reply earlier is still 100% relevant.

for any commercial application (one that generates revenue) our terms of use require that you upgrade to a paid account. the price is still $20/month.

while you are in the development phase, you are welcome to use a free account.

**Comment by ojollivet** [comment]
Thanks for your answer.
