### ISSUE TITLE
Offline Feature Layer

### ISSUE THREAD

**Issue by dpinart** [Esri/esri-leaflet#864]
I'm planning to migrate an existing application that uses esri to esri-leaflt. The application is a phonegap that offers offline mode. I've seen I can use some leaflet plugin in order to cache tiles locally but I still need to store features in order to make the application fully functional when it goes offline

**Comment by jgravois** [comment]
this isn't something we have the bandwidth to support in the foreseeable future, but you're welcome to take a stab at managing a local database and syncing locally on your own.

reference open source JSAPI implementation: https://github.com/Esri/offline-editor-js

**Comment by dpinart** [comment]
offline-editor is the library that the application currently relies on for offline management. Any guide or documentation to start developing a custom FeatureLayer?

**Comment by andygup** [comment]
@dpinart Here are some basic considerations:

- Familiarize yourself with the esri-leaflet [FeatureLayer](https://github.com/Esri/esri-leaflet/tree/master/src/Layers/FeatureLayer) code. FeatureManager.js is where all the edit functionality lives. You'll most likely need to `extend` FeatureManager.js.
- You'll need to intercept feature ADDS, UPDATES and DELETES requests while the layer is in offline mode.
- You can either re-use the offline-editor-js feature storage/retrieval code and database or cook up your own.
- Underneath the hood, esri-leaflet is wrapping the ArcGIS REST API. To understand those calls, check out the REST API doc `applyEdits()` method [here](http://resources.arcgis.com/en/help/arcgis-rest-api/index.html#/Apply_Edits_Feature_Service/02r3000000nv000000/).
- You'll need a way to manually tell the FeatureLayer if it's online, offline and it will need a mechanism that loops thru any pending ADDS, UPDATES or DELETES and attempts to sync them with the Feature Service endpoint as well as catch an errors.
