### ISSUE TITLE
Query Task MultiPolygon support

### ISSUE THREAD

**Issue by whyvez** [Esri/esri-leaflet#865]
The current implementation of the geometry argument to the Query Task does not support the MultiPolygon GeoJSON geometry type. I have tested by simply including the type here: https://github.com/Esri/esri-leaflet/blob/master/src/Tasks/Query.js#L214 and all works great from what I can tell. Here is my change (https://github.com/tesera/esri-leaflet/commit/7dfb5d19d1da980139ffffb0a92f1bfbe57d4c3d) and I can create a PR if you think its an acceptable change.

**Comment by jgravois** [comment]
> I can create a PR if you think its an acceptable change.

please do.

**Comment by whyvez** [comment]
@jgravois there you go. Let me know if you see any issues with this but consequences seem pretty minor.

**Comment by jgravois** [comment]
closed via 91cc90b. thanks for the PR!
