### ISSUE TITLE
Getting error when using esri-leaflet with webpack

### ISSUE THREAD

**Issue by robinho81** [Esri/esri-leaflet#868]
* Browser and version: 
Chrome 51

* Version of Leaflet (`L.version`):
1.0.0

* Version of esri Leaflet (`L.esri.VERSION`):
2.0.3

Steps to reproduce the error:
1. Try to display a basemap using the ESRI Leaflet plugin:

```
var esri = require("esri-leaflet");
esri.basemapLayer("Topographic").addTo(map);
```

This code seems to run, and I can actually debug through it fine. 
However, the map is not loaded, and I get the following error:

> TypeError: Cannot read property 'Util' of undefined
>     at setEsriAttribution (http://localhost:5000/bundle.js:9709:30)
>     at NewClass.onAdd (http://localhost:5000/bundle.js:10756:7)
>     at NewClass._layerAdd (http://localhost:5000/bundle.js:16404:9)
>     at NewClass.whenReady (http://localhost:5000/bundle.js:16185:14)
>     at NewClass.addLayer (http://localhost:5000/bundle.js:16462:9)
>     at BaseMapLayer.addToMap (http://localhost:5000/bundle.js:8941:14)

I have searched through the the issues and I cannot see anyone else experiencing this issue. It seems that the plugin expects L.esri.Util to be available globally? 

My workaround is simply to export L.esri at the beginning of my app:
```
declare var L: any;
L.esri = require("esri-leaflet");
```

*  I'm *not* using the [CDN](http://www.jsdelivr.com/projects/leaflet.esri), I'm loading/bundling the library using: 

[webpack](https://webpack.github.io/)

**Comment by jgravois** [comment]
thanks for reporting.  i tested locally against master and couldn't reproduce (i *think* by #852), so i went ahead and tagged [`2.0.4`](https://github.com/Esri/esri-leaflet/releases/tag/v2.0.3).  

can you please retest when you have a moment and let me know the outcome?

**Comment by robinho81** [comment]
I can verify that this now works in version 2.0.4. 

I was able to remove the workaround.

Thanks for the fix and a great plugin :)
