### ISSUE TITLE
L.esri

### ISSUE THREAD

**Issue by nthhtn** [Esri/esri-leaflet#873]
I'm trying to use utilize this plugin to use reverse geocoding for my web HTML document

I'm writing in Java, my `jsp` file already includes `leaflet` and `esri`. But when I try to use any API function, it always throws error `property x is not a function`. I try to `console.log(L.esri)` and it always returns `undefined`

Much to this impossibility, I check the browser, HTML document does get files I included. I make no mistake including them, I always include leaflet before any other plugins. This really makes no sense at all. Why does it always throw error as if the HTML document does not receive the script file?

I include the CDN link. My `leaflet` version is 0.7

**Comment by jgravois** [comment]
can you share a simplified repro case?  i'd be curious to hear whether we'd be able to reproduce the same error outside of your Java environment.

**Comment by nthhtn** [comment]
I think I've found the solution. It is because of this:
```
<!--My resources file-->
<script src="https://unpkg.com/leaflet@1.0.0/dist/leaflet-src.js"></script>
<script src="https://unpkg.com/esri-leaflet@2.0.4"></script>
<script src="https://unpkg.com/esri-leaflet-geocoder@2.1.4"></script>
<!--My HTML document-->
<script src="js/lib/leaflet-src.js"></script>
<script src="js/plugins/L.Control.Locate.js" ></script>
<script src="js/plugins/Control.MiniMap.js" ></script>
<script src="js/plugins/leaflet.contextmenu.js"></script>
<script src="js/plugins/leaflet.usermarker.js"></script>
<script src="js/myscript.js"></script>
```

Perhaps `esri` is overidden by the `leaflet-src` below
