### ISSUE TITLE
Inconsistent behavior adding layers to map; often throws this.options.userDefinedStyle is not a function  

### ISSUE THREAD

**Issue by bGrass** [Esri/esri-leaflet#874]
- Browser and version:
  Chrome 53
- Version of Leaflet (`L.version`):
  1.0.0-beta.2
- Version of esri Leaflet (`L.esri.VERSION`):
  2.0.4

Summary:
  I'm experiencing inconsistent behavior when adding layers to the map; sometimes they load as expected while other times they throw the error 'this.options.userDefinedStyle is not a function' (on Renderer.js line 77) and load with default blue symbology.  I have not been able to attribute this error to any different behavior in my code; it occurs sporadically but sometimes 50% or more of the time on initial map loading.  This behavior is very streaky, meaning that it will often occur many times in a row once it starts happening.  I believe that this only affects polygon layers.

Specifics:
  My feature layers have their style defined by an object like this:
{color: "rgb(168,0,0)", weight: 3, fill: false}

  The error occurs after I call map.addLayer().  I was able to trace this to FeatureLayer.js line 115.  If the parameter this.options.style is an object then the layer loads normally.  Sometimes, however, it is a function and this leads to the error.

  This error seems very to similar to an earlier problem I had where point layers would sometimes load as icons (meaning that they could not be styled with setStyle() ) instead of as SVG; the problem seems to have been resolved when I upgraded to esri-leaflet 2.0.2.

**Comment by jgravois** [comment]
1. does updating to leaflet `1.0.1` improve things any?
2. you're reporting a problem with 'esri-leaflet-renderers', right?
2. can you repro the problem in a stripped down app you can share?

**Comment by bGrass** [comment]
1.  I have added leaflet 1.0.1 to the page and I'm not seeing any change in behavior.  I hadn't previously been explicitly adding leaflet, so I'm not sure what version I was working with.

2.  I'm not really sure.  I'm using setStyle() to define the style for each layer before the layers are added to the map.  I don't think this is relying on esri-leaflet-renderers.

3.  Yes, the issue is repeatable at this site: http://inventorysimulator.mbgapplications.com/
The page should load to display a series of yellow polygons; when the error occurs they will load as shaded blue polygons instead and throw the JavaScript error mentioned above.  Refreshing the page repeatedly should produce both results.

**Comment by bGrass** [comment]
I seem to have resolved my problem by rolling back to esri-leaflet-renderers 2.0.2 (I'm still using esri-leaflet 2.0.4.).  Interestingly, my problem with lines and polygons loading with the default style and throwing a 'this.options.userDefinedStyle is not a function' error goes away if I don't load esri-leaflet-renderers at all, but doing this introduces another intermittent problem with point layers. This problem seems related in that point features are returned as icons rather than as SVG points after adding a point layer to the map with map.addLayer(); this means that the features can't be restyled with setStyle().

Using esri-leaflet 2.0.4 in conjunction with esri-leaflet-renderers 2.0.2 is currently working for me for layers of all geometry types.

**Comment by jgravois** [comment]
i'm finally getting around to investigating this and i haven't been able to reproduce the error you're describing (yet). i even tried hardcoding a 3 second delay before service metadata is fetched.

```js
var fl = L.esri.featureLayer({
  url:"https://services1.arcgis.com/TODNt0c7hfy5HvPN/ArcGIS/rest/services/ODF_Stands/FeatureServer/0",
  ignoreRenderer: true
}).addTo(map);

fl.setStyle({
  color: 'rgb(255,255,0)',
  weight: 2.4,
  fill: false
});
```
i'm going to close the ticket here and continue tracking the problem in Esri/esri-leaflet-renderers#133.

if anyone can provide any more info or even just corroborate the error, it'd be extremely helpful.
