### ISSUE TITLE
Additional methods for L.esri.Query

### ISSUE THREAD

**Issue by rowanwins** [Esri/esri-leaflet#878]
Gday guys,

Just wondering if you'd be interested in extending L.esri.Query to include methods for outStatistics and groupByStatistics and some of those additional fields. I've got a use case where I've got to make some queries along those lines so I'm happy to submit a pull request if you guys are open to it.

Cheers
Rowan

**Comment by jgravois** [comment]
sounds useful to me.  maybe you can throw in something for #880 while you're at it.

**Comment by rowanwins** [comment]
Gday @jgravois 

I've made a start on this although Im having trouble running the tests as reported in #815 . I've played around for a bit with attempting to resolve the test timeout issue but haven't managed to work it out yet. 

Will keep you posted

Cheers

**Comment by jgravois** [comment]
i've resorted to just using `v4` (since there are a couple quick and painless ways to switch back and forth between versions).  if you want to wait until we get things working correctly in `v6`, thats fine too.

**Comment by jgravois** [comment]
closing this issue, but happy to review a Pull Request anytime. 🚀
