### ISSUE TITLE
Get unique values for an attribute

### ISSUE THREAD

**Issue by btpschroeder** [Esri/esri-leaflet#880]
Is there any way to get all of the unique values for an attribute in the vein of the "Get Unique Values" button in the ArcMap SQL query builder?

For my Web map project, I need to display a list of unique values from a Map Service hosted on ArcGIS Server. The only way I can think to do this is by querying _all_ of the features in the service, looping through the attribute in question for each feature, and throwing the first occurrence of each value into an array. The problem is, I'd prefer not to have to do process this all client-side, and the MaxRecordCount of the service in question is 1000, when the service itself has multiple thousands of features. (In other words, I can't even be sure I'd be getting every single unique value in that query of 1000.)

Is there an easier way to accomplish this currently using esri-leaflet? If not, perhaps something to consider in future releases. Thanks for your time and for this excellent plugin!

**Comment by jgravois** [comment]
The ArcGIS REST specification for `/query` actually *does* include a parameter to make sure results are limited to unique values for a particular field (its called [`returnDistinctValues`](http://resources.arcgis.com/en/help/arcgis-rest-api/index.html#/Query_Feature_Service_Layer/02r3000000r1000000/)).  In Esri Leaflet we don't currently expose a parameter to set the flag, but luckily you *can* pass in any custom parameter you want before you fire off your request.

```js
var distinctQuery = L.esri.query({
  url: "https://sampleserver6.arcgisonline.com/arcgis/rest/services/Census/MapServer/3"
})
distinctQuery.where("1=1")
distinctQuery.returnGeometry(false)
distinctQuery.fields(['SUB_REGION'])
distinctQuery.params.returnDistinctValues = true;

distinctQuery.run(function (err, res, raw) {
  console.log(res.features)
});
```
live sample: http://jsbin.com/fonevec/edit?html,output

**Comment by btpschroeder** [comment]
Excellent. That's infinitely helpful. Thank you!

**Comment by srappel** [comment]
Hey @btpschroeder and @jgravois , I've been trying to figure out why the Publisher and Series list on the [Geodex Web Map](http://webgis.uwm.edu/agsl/geodex-web-map/) were no longer working.  The map service seems to be working fine and the search function is still working, but these lists are not populating.  Ben's comments in the code led me to this thread.

I get an error to the console that implies that there are no results ("TypeError: results is null") for both lists.  The error is flagged on the lines 95 and 145 of [this file](https://github.com/srappel/geodex-web-map/blob/beta/geodex-web-map.js).  Any suggestions on troubleshooting?  It came out of nowhere, one day it worked and the next it didn't.

**Comment by gavinr** [comment]
@srappel if you look at the browser network tab, it appears that your service is often returning an error:

![image](https://user-images.githubusercontent.com/209355/61244531-0ebb9300-a710-11e9-8e81-299da022867c.png)

And then your code at line 140, `results` is null so when you try to get the `features` property on it, you're getting an error. Best to wrap that code in an if statement checking if your `error` variable has an error before moving on.

**Comment by srappel** [comment]
Thanks, @gavinr .  So I was able to resolve the issue by moving there where clause from the query.  I'm not sure why that would cause it to return no results, but it seems to be working now.

Would that cause the "failure to execute query" error that you mention?

**Comment by srappel** [comment]
Hi All, 

It appears this is an issue with our ArcGIS server as some of the other map services are not responding to queries.  However, thank you @gavinr for the suggestion to wrap the code in an if statement, I'm going to do that so I can let users know that the application is not functional if we aren't getting a response from the service.
