### ISSUE TITLE
IE11: InvalidStateError when adding tiled map layer

### ISSUE THREAD

**Issue by rbrtmrtn** [Esri/esri-leaflet#894]
* Browser and version: IE11

* Version of Leaflet (`L.version`): 1.0.1

* Version of esri Leaflet (`L.esri.VERSION`): 2.0.0-beta.8

Steps to reproduce the error:

1. Instantiate an `L.esri.tiledMapLayer`.
2. Add that to an `L.LayerGroup`.
3. Add that to a map.

If you visit [this page](https://cityofphiladelphia.github.io/atlas/) in IE11 you should see the issue.

What happens is: IE throws an `InvalidStateError` on [this line](https://github.com/Esri/esri-leaflet/blob/3b5ba0d39dcb297fa336061a7ad8aef4bf210872/src/Request.js#L112) of `esri-leaflet`.

I was expecting: no error :) Works fine in Chrome 54, Firefox 50.

Would appreciate any guidance on this!

**Comment by jgravois** [comment]
the patch for this issue was merged in April of 2016 (#770) and released as part of [`v2.0.0`](https://github.com/Esri/esri-leaflet/releases/tag/v2.0.0).

the most recent release of esri leaflet is `v2.0.6`

**Comment by jgravois** [comment]
@rbrtmrtn you all good?

**Comment by rbrtmrtn** [comment]
Yes! We swapped in the latest `esri-leaflet` and it worked! 

Many thanks @jgravois 👍 👍 👍
