### ISSUE TITLE
`removefeature` not triggered when moving map

### ISSUE THREAD

**Issue by kt-weyert** [Esri/esri-leaflet#895]
* Browser and version:
Chrome 54
* Version of Leaflet (`L.version`):
0.7.7
* Version of esri Leaflet (`L.esri.VERSION`):
1.0.4

Steps to reproduce the error:

1. Add a ESRI feature map
2. Move to a position where you are sure you have a polygon marker on the map
3. Now move away from this position so the polygon marker out of view from the map

What happens is [X].
Nothing happens

I was expecting [Y].
A `removefeature`-event to be triggered when the feature moves out of view from the map

(if possible, create a [jsbin](http://jsbin.com/wudoxe/edit?html,output) that demonstrates the problem)

* Optional: I'm *not* using the [CDN](http://www.jsdelivr.com/projects/leaflet.esri), I'm loading/bundling the library using:

[webpack](https://webpack.github.io/), [browserify](http://browserify.org/), [RequireJS](http://requirejs.org/)?

**Comment by jgravois** [comment]
we intentionally keep features in memory after they've been fetched from an ArcGIS service to improve performance when users pan back to a location that was previously displayed.

what is it exactly that you're trying to accomplish in your own app?

**Comment by kt-weyert** [comment]
I am having a list of incidents that I am getting back from ArcGIS Online. I would like to display the event type and description on the screen below the map in a list. The events are all polygons of an area. Also it looks like when use have `cacheLayers` to `false` for the feature layer. It's not refreshing the features when moving around the map. Causing the above description not to get updated correctly when it has been updated in ArcGIS.

**Comment by jgravois** [comment]
panning around the map and seeing different features displayed is *not* the same thing as removing a layer from the map.  both the `removefeature` event and the `cacheLayers` constructor property refer to the situation in which the entire layer is actually removed.

```js
var myFL = L.esri.featureLayer(/**/);
myFL.addTo(map); // or map.addLayer(myFL);
// ...
map.removeLayer(myFL); // or myFL.removeFrom(map);
```

if you want to trigger a new set of queries to the service *without* removing the layer, try `featureLayer.refresh()` (which apparently incorrectly listed in the API reference as `reset()`)

**Comment by patrickarlt** [comment]
@kt-weyert If you want your list to display ONLY features on the map use `FeatureLayer#forEach`:

```js
function updateList () {
  layer.forEach(function (layer) {
    if (map.hasLayer(layer)) {
      // this layer is shown on the map, note the layer MIGHT still outside the map bounds
    }
  });
}

map.on('moveend', updateList); // update the list whenever the map finishes moving
layer.on('loadend', updateList); // updat the list after we load new features
```

**Comment by weyert** [comment]
Cool, thank you! I have gotten a step closer now! And that's fantastic 💃
