### ISSUE TITLE
Combining query methods

### ISSUE THREAD

**Issue by btpschroeder** [Esri/esri-leaflet#897]
Is there any way to combine geography-based query methods?

In particular, I'd like to query an ArcGIS Map Service for features that _intersect_ a certain extent, but are also located _within_ another, larger extent.

My application allows users to search a collection of maps based on location. As it currently exists, searching a very small area (say, one city or village)  using the intersects method returns records containing maps of entire countries, continents, or the world -- which are of limited use to somebody only interested in a small area.

**Comment by jgravois** [comment]
[`/query`](http://resources.arcgis.com/en/help/arcgis-rest-api/index.html#/Query_Feature_Service_Layer/02r3000000r1000000/) operations only support selecting one spatial relationship/operator at a time so your best bet to *combine* is to chain one after the other.

**Comment by btpschroeder** [comment]
So, if I understand correctly, I could *not* do something like this:

```javascript
var search = L.esri.query({
	url: mapservice.com/0
});
search.intersects(queryBounds);
search.within(largerQueryBounds);`
````
If this is the case, what do you mean by chaining one after the other? Am I able to perform a second query on the results of another -- for instance, run the intersects query, and then run a within query *on those results*? Thanks for your help with this -- much appreciated.

**Comment by jgravois** [comment]
> what do you mean by chaining one after the other?

i meant something like this.

```js
var query1 = L.esri.query({
  url: 'mapservice.com/0'
});
query1.intersects(queryBounds);
query1.run(function (err, featureCollection, raw) {
  var query2 = L.esri.query({
    url: 'mapservice.com/0'
  });
  query2.within(largerQueryBounds);
  /* here you'd need to pass the objectIDs of the features returned by the first query
  this will help you fetch the features from the service that match *both* spatial conditions */
  query2.featureIds(/*  */);
  query2.run(/* then call the second query and handle the response  */);
});
```
if you're querying for points, another viable option would be to use a client-side geometry library like turf to determine whether features returned by a single *intersects* query are also [`inside`](http://turfjs.org/docs/#inside) a second bounding box.

**Comment by btpschroeder** [comment]
Worked like a charm -- many thanks.

**Comment by jgravois** [comment]
glad to hear it.  i took the liberty of putting a turf sample together too.

http://jsbin.com/wijuyap/1/edit?html,output

it might be a good idea to land it as a published sample...
