### ISSUE TITLE
Redraw a L.esri.DynamicMapLayer

### ISSUE THREAD

**Issue by Unceasingleek** [Esri/esri-leaflet#898]
I have recently started playing with leaflet-esri for a project using mapbox. I am requesting a map service from http://nowcoast.noaa.gov/ and creating a L.esri.DynamicMapLayer 

```js
var restRadar = L.esri.dynamicMapLayer({
    url: 'https://nowcoast.noaa.gov/arcgis/rest/services/nowcoast/radar_meteo_imagery_nexrad_time/MapServer',
    opacity: 0.8,
    time: new Date().getTime(),
    useCors: true
});
```

I am trying redraw the layer every 10 minutes with the the current request time so that the radar is ''current". I have already achieved this with their WMS service in mapbox but it is much slower than a arcgis rest request and would prefer to use this. Am I using the wrong layer object for this or is there a method of redraw that I have just not been able to discover?

**Comment by jgravois** [comment]
i'm not sure we haven't exposed a *public* method, but you're looking for [`_update()`](https://github.com/Esri/esri-leaflet/blob/9ad267e62410c7c1c7229a6cb77fcd80c660d3ad/src/Layers/RasterLayer.js#L215-L239), which is inherited from the parent class `L.esri.RasterLayer`.

**Comment by Unceasingleek** [comment]
Thanks that does create a new request. With the wms layers I used the L.TileLayer.wms method setParams() to set a time parameter to bust the cache to avoid using a cached layer. Is that a possibility with esri-leaflet?

**Comment by jgravois** [comment]
> Is that a possibility with esri-leaflet?

yes. calling [`dynamicMapLayer.setTimeRange()`](http://esri.github.io/esri-leaflet/api-reference/layers/dynamic-map-layer.html#methods) triggers `_update()` internally.

**Comment by patrickarlt** [comment]
@jgravois we should expose a public `redraw()` method for this. Seems like a pretty obvious oversight.
