### ISSUE TITLE
Edit Featurelayer Example is broken

### ISSUE THREAD

**Issue by roemhildtg** [Esri/esri-leaflet#899]
It looks like the example here is broken:

https://esri.github.io/esri-leaflet/examples/editing.html

Perhaps a different branch or commit of leaflet.draw should be used from rawgit since it looks like the dist files have been removed from the master branch.

**Comment by jgravois** [comment]
this issue was previously reported in Esri/esri-leaflet-doc/issues/15 so i'm going to close this issue and continue tracking there.

now that leaflet 1.0.x has been tagged, i'll *really* try to find time to fix it soon.
