### ISSUE TITLE
featureLayer click event propogates down to map

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet#901]
```js
map.on('click', function (e) {
  // when someone clicks on a feature, this listener fires too
})
```
live sample: http://jsbin.com/dotuci/edit?html,output

you can find my workaround in our editing sample here:
[../src/pages/examples/editing.hbs#L120-L121](https://github.com/Esri/esri-leaflet-doc/blob/73653beef1a9a2d0834ee70d558e4a1d465575d8/src/pages/examples/editing.hbs#L120-L121)

this is a bug, right? it certainly didn't occur in `0.7.7`/`1.0.4`.

**Comment by rowanwins** [comment]
Hi @jgravois 

The same behaviour occurs with other leaflet vector layers so I think it's actually expected, for example if you add in the following to your jsbin
````
    var circle = L.circleMarker([56.1304, -106.3468], {radius: 20}).addTo(map)
   
    circle.on('click', function (e) {
      alert('circle clicked');
    })
````
So maybe it's not a bug?

**Comment by jgravois** [comment]
@rowanwins thanks for that.  it helps to know that the behavior bubbles up (groan!) from Leaflet itself. it certainly *feels* foreign to me, but I can't say that its problematic.

based on my reading of the v1.0.0-beta.1 changelog and Leaflet/Leaflet/pull/3032 i'm relatively certain that this was a conscious design decision, so i'm happy to let sleeping dogs lie.
