### ISSUE TITLE
Tiled Map Layer does not load after page load but then it loads after panning/zooming

### ISSUE THREAD

**Issue by esoekianto** [Esri/esri-leaflet#912]
* Browser and version:

Edge

* Version of Leaflet (`L.version`):

1.0.2

* Version of esri Leaflet (`L.esri.VERSION`):

2.0.6

Steps to reproduce the error:

- Use this sample, http://esri.github.io/esri-leaflet/examples/tile-layer-1.html
- This sample works, and the layer in the sample works as well
- The issue only occurs using specific layer
- We can not make sample in jsbin, since the layer is not publicly accessible
- The layer does not load after page load, but after panning or zooming, then the layer loads, no error in console
- We know that this is related with that specific layer, but we have no other clue to why this is happening

Troubleshooting performed
- spatial reference OK
- Level details OK
- No scale dependent

Clue:
This layer does not work at all in chrome and firefox, due to weird windows authentication security error from the web server of the AGS layer. It says 401 error unauthorized. 

We are scratching our head, it is only happening to this layer, I am hoping others could point us to other things we can troubleshoot or if anyone else had the same issue before

Thank you!

**Comment by jgravois** [comment]
funny, we're already discussing displaying IWS secured dynamicMapLayers in #881.

off the top of my head i'd suggest trying something similar to what i described [here](https://github.com/Esri/esri-leaflet/issues/881#issuecomment-270217642) and tweak the leaflet source to pass [`crossOrigin=use-credentials`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Img) when it creates the actual `<img>` DOM node.

`L.TileLayer.createTile()`
https://github.com/Leaflet/Leaflet/blob/a1c1ea214f3077469ace7e9cef2d79225d757c97/src/layer/tile/TileLayer.js#L140

**Comment by jgravois** [comment]
you have any more info to share @esoekianto?

**Comment by esoekianto** [comment]
sorry, we can close this issue as server-specific related
