### ISSUE TITLE
Add contorl for `returnGeometry` to `dynamicMapLayer.bindPopup` to reduce (unnecessary) load

### ISSUE THREAD

**Issue by kunKun-tx** [Esri/esri-leaflet#919]
* Browser and version:

Chrome 55, IE11

* Version of Leaflet (`L.version`):

1.0.3

* Version of esri Leaflet (`L.esri.VERSION`):

2.0.7

Steps to reproduce the error:

1. layer published with large and complicated features from ArcGIS server
2. add layer as `DynamicMapLayer` in leaflet
3. add `bindPopup` to layer and return ~~feature's label `featureCollection.features[0].properties.Label `~~ `abc` as popup content
4. click feature

What happens is [long response time caused by `GET`-ing entire GeoJson object from server].

I was expecting [to get feature's properties alone without getting the whole `geometry` set. User should at least be able to choose if they want to get `geometry`. By choosing to load the layer as `dynamicMapLayer`, some (at least me) were avoiding prolonged loading time & complex svg's building time].

( [jsbin](http://jsbin.com/caperoqimo/1/edit?html,js,output) that demonstrates the problem, click on the polygon near City of Houston and you will recreate the freeze)

* Optional: I'm *not* using the [CDN](http://www.jsdelivr.com/projects/leaflet.esri), I'm loading/bundling the library using: [webpack](https://webpack.github.io/) but the jsbin example was set up using CDN.

**Comment by kunKun-tx** [comment]
I am new to this plugin and currently the only solution in my mind is similar to the user-interaction-on-canvas hack, which will add an invisible layer on top and capture the mouse location from onClick event on the invisible layer and use `within` to query the feature underneath the click point...

**Comment by jgravois** [comment]
we're actually already discussing this in #633, so i'm going to go ahead and close this ticket and continue tracking there.

until we settle on a way to expose more fine grained control via bindPopup, you should consider calling [`identifyFeatures.run()`](http://esri.github.io/esri-leaflet//api-reference/tasks/identify-features.html#methods) instead.
```js
map.on('click', function (evt) {
  districtMap.identify()
    .on(map)
    .at(evt.latlng)
    .returnGeometry(false)
    .run(function(error, featureCollection, response){
      console.log("abc");
    });
})
```
http://jsbin.com/coyejoy/edit?html,js,output

**Comment by jgravois** [comment]
its obviously not the same as skipping returning geometry entirely, but it would also be worth investigating applying a scale appropriate maxAllowableOffset to the identify request fired by bindPopup() automatically to help in edge cases where the original geometry is extremely vertex dense.
