### ISSUE TITLE
dynamic layer through proxy server

### ISSUE THREAD

**Issue by fawadsh1** [Esri/esri-leaflet#929]
Hi,

I am using proxy map server to create dynamic layers on top the map.
I set the proxy by providing proxy url when creating the dynamic layer.
For example

hazardLayer = esri.dynamicMapLayer({
url: 'some map url',
opacity: 0.7,
useCors: false,
minZoom: 4,
proxy: 'http://someserver.com/proxy.ashx'
});

When i add this hazard layer to map, the first request goes to the proxy server and returns the map related info in json format. First request fine, but subsequent requests which i do not control, for example map layers in png format goes direct to source server instead using the proxy server. 

My question is. Is there anyway, I can make leaflet esri to use proxy server for all requests.

Regards,

Fawad

**Comment by jgravois** [comment]
does the same behavior occur if you ask the server for raw images instead of .json which includes a url?

```js
hazardLayer = esri.dynamicMapLayer({
  url: 'some map url',
  proxy: 'http://someserver.com/proxy.ashx',
  f: 'image'
});
```

**Comment by fawadsh1** [comment]
Sorry, It does not work. actually problem is when we add the dynamic layer to map 

hazardLayer = esri.dynamicMapLayer({
url: 'some map url',
opacity: 0.7,
useCors: false,
minZoom: 4,
proxy: 'http://someserver.com/proxy.ashx'
});

Esri plug in API makes multiple requests. First request goes to the server and subsequent request bypass server which I do not control. it is the plug in.

Arcgis goes some settings as provided in this article. But using Leaflet Esri, I do not find any option.

https://developers.arcgis.com/javascript/3/jshelp/ags_proxy.html

Regards,

Fawad

**Comment by jgravois** [comment]
I thought I fixed this already but I'm happy to take another look.

in the meantime, try out the workaround I described in #862

**Comment by jgravois** [comment]
i haven't been able to reproduce the problem you reported.

```html
<script src="https://unpkg.com/esri-leaflet@2.0.7"></script>
```
```js
L.esri.dynamicMapLayer({
  url: 'https://sampleserver6.arcgisonline.com/arcgis/rest/services/Census/MapServer',
  proxy: './proxy.ashx' 
}).addTo(map);
```
![screenshot 2017-02-24 17 33 22](https://cloud.githubusercontent.com/assets/3011734/23326823/777603ec-fab7-11e6-93bb-93f8242dab8b.png)

if you can provide more info, i'd be happy to provide more assistance.
