### ISSUE TITLE
Query doesn't seem to honour "fields" parameter

### ISSUE THREAD

**Issue by slead** [Esri/esri-leaflet#930]
According to http://esri.github.io/esri-leaflet/api-reference/tasks/query.html it should be possible to specify the fields which are returned by a query:

> fields(_Array_ fields or _String_ fields) : An array of associated fields to request for each feature

I'm finding that query returns all fields, regardless of what's specified in the `fields` parameter. See the console in [this JS Fiddle](https://jsfiddle.net/nvabecrn/3/) to demonstrate. Am I using the parameter wrong, or is it not being honoured?

```
var query = L.esri.query({
  url:'https://sampleserver1.arcgisonline.com/ArcGIS/rest/services/Demographics/ESRI_Census_USA/MapServer/3',
  fields: ["NAME", "POP2000"],
  useCors: false
});

query.within(map.getBounds());
query.run(function(error, featureCollection, response){
  console.log(response.fields);
});
```

A possible problem is that within [/tasks/query.js](https://github.com/Esri/esri-leaflet/blob/master/src/Tasks/Query.js) the `outFields` parameter is hard-coded:

```
params: {
    returnGeometry: true,
    where: '1=1',
    outSr: 4326,
    outFields: '*'
  },
```

I think it needs to be set from the user's parameters but I'm not sure where to do this..

Thanks,
Steve

**Comment by jgravois** [comment]
`fields` is not a valid constructor option, but rather a method that hangs off of the Task.

```js
var query = L.esri.query({
  url:'https://sampleserver1.arcgisonline.com/ArcGIS/rest/services/Demographics/ESRI_Census_USA/MapServer/3',
  useCors: false,
  where: '1=1'
});

query.fields(["NAME", "POP2000"]);
query.where("1=1");
query.returnGeometry(false);

query.run(function(error, featureCollection, response){
  console.log(response.fields);
});
```

> within [/tasks/query.js](https://github.com/Esri/esri-leaflet/blob/master/src/Tasks/Query.js) the `outFields` parameter is hard-coded:

we do this to ensure that `*` is passed by default.
