### ISSUE TITLE
No event hook available exposing when featurelayer(s) finish painting

### ISSUE THREAD

**Issue by UsgsMonkey** [Esri/esri-leaflet#938]
## Description
I've explored several strategies to hook into the loading of a page, document, layers and the rendering of the map.  These include mapping to the 'document.ready' and 'window.load' events, the Leaflet layer 'load' events, and the Leaflet Renderer 'update' event.  Every one of these fire before the featurelayer(s) I'm working with have completed rendering to the browser screen.  The latest of these to fire appears to be the Leaflet Renderer 'update' event (see this [ESRI Leaflet JsFiddle example](https://jsfiddle.net/UsgsMonkey/21j6m98L/25/)).

What I'd like to do is expose a spinner graphic while the map is busy loading/rendering/painting/etc., and then disable the spinner when all this activity is complete (to properly indicate the application is busy).  While it's going on, Leaflet is unresponsive and we just end up caching user-clicks.

I brought this up on the Leaflet GitHub page, but since I'm already working with ESRI Leaflet, it's easier for me to present the data which is dense enough to cause the demonstrable delay using this tool.  I don't have a reproducible example using just the Leaflet API on it's own at this time.  Their developer recommended I post here in case there's something internal to the FeatureLayer component that might provide a hook.  Beyond that, I'd be enthusiastically interested in any additional recommendations or thoughts you might have to present a workable solution to this problem.

## Environment
* Browser: Chrome (56.0.2924.87)
* Leaflet Version: 1.0.3:
* ESRI Leaflet Version: 2.0.7

**Comment by jgravois** [comment]
hello!

testing with your service i'm only seeing a fraction of a second difference between the actual completion of painting and when `FeatureLayer.on('load') is triggered.

as @IvanSanchez explained, its definitely a non-trivial task to detect the exact moment when a browser is able to finish executing instructions. i'm happy to look into this further to see if there is a good opportunity to expose an additional event, but from the perspective of this plugin, the bulk of the wait is always going to be fetching the data from the service, so i feel pretty comfortable encouraging you to try binding your progress spinner to what you already have.

> Leaflet is unresponsive and we just end up caching user-clicks.

i'm not exactly sure what you're talking about here. the work we do to make requests, parse the response and draw isn't inherently blocking, so if you're entire browser is regularly freezing up during these operations its a good indication that you'd be better served to investigate ways to make sure you don't draw so many graphics at the same time (like setting up scale dependencies).

**Comment by UsgsMonkey** [comment]
Thanks for the response :) - actually We do have scale dependency and simplification set into the main application to facilitate rendering.  We may have to enforce it further, but there are limitations and the data itself is pretty dense.

> I'm not exactly sure what you're talking about here.

I recognize the tool is doing it's work and the user can click on the map, but if users click before the map has completed painting we aren't able to get any of our 'identify' actions to execute and those clicks just cache and the associated popups display after quite a delay (sometimes extending to ~15-20 seconds - so maybe there's more going on internally than I'm aware of).  We are using a number of plugin controls and the code is still in development so it's not fully minified/optimized, but I'm pretty confident based upon when the events fire that the data has already been retrieved long before the actual painting activity is done.

I appreciate it's a non-trivial request, but I figured I'd ask on the off-chance something might be possible :)  In the example I provided, on the initial load, from my browser I'm getting a delay of a few seconds between the time the popup is clicked and when the painting activity is completed.

**Comment by jgravois** [comment]
> I'm getting a delay of maybe 2-3 seconds between the time the popup is clicked and when the painting activity is completed.

3 seconds are passing *after* `featureLayer.on("load")` has fired but before the graphics in the current extent have actually drawn?

i'd be really curious to know better what is causing the lag.  i would expect the gridded calls to `/query?` **all** to have returned a response before `load` is emitted, but perhaps one or more are still in transit?

if there are no pending requests then its likely that either a large number of discrete features, vertex density of individual features or some complexity in the renderer is the culprit.  have you tried using [`L.canvas()`](http://esri.github.io/esri-leaflet/api-reference/layers/feature-layer.html) as the renderer for large polygon layers?

**Comment by jgravois** [comment]
since there are no action items for the lib, i'm going to close this issue. that said, i'm happy to chat more if anyone has any other questions.
