### ISSUE TITLE
Error Loading Dynamic Map Layer in an Angular App

### ISSUE THREAD

**Issue by bbehling** [Esri/esri-leaflet#940]
* Browser and version:

Chrome

* Version of Leaflet (`L.version`):

1.0.3

* Version of esri Leaflet (`L.esri.VERSION`):

v1.0.0

I'm trying to to load a dynamic map service into leaflet in an angular app, and the library is throwing an error.

Any ideas what could be going on? Can we use esri-leaflet inside angular?

TypeError: Cannot read property 'call' of undefined
    at e.whenReady (leaflet.js:6)
    at e.addLayer (leaflet.js:6)
    at e.addTo (esri-leaflet.js:20)
    at mapController.$onInit (MapComponent.js:34)
    at angular.js:9599
    at q (angular.js:365)
    at n (angular.js:9588)
    at angular.js:9980
    at angular.js:16648
    at m.$eval (angular.js:17972)

```
 var map = L.map("map").setView([46.0, -99.0], 4);

L.esri.basemapLayer("Gray").addTo(map);


L.esri.dynamicMapLayer({
                url: https://services.arcgisonline.com/arcgis/rest/services/Specialty/Soil_Survey_Map/MapServer",
                opacity: 1,
                useCors: false
}).addTo(map);
```

**Comment by jgravois** [comment]
its not the most intuitive numbering scheme in the world, but:
> * Esri Leaflet [`1.x`](https://github.com/Esri/esri-leaflet/releases/tag/v1.0.3) is compatible with Leaflet version `0.7.x`
> * Esri Leaflet [`2.x`](https://github.com/Esri/esri-leaflet/releases/tag/v2.0.8) is compatible with Leaflet version `1.x`

([reference](https://github.com/Esri/esri-leaflet#dependencies))

**Comment by bbehling** [comment]
Ok. If using esri-leaflet 1.x, this doesn't work. Need to use 2.x with the latest version of Leaflet.

Thanks @jgravois
