### ISSUE TITLE
Disable Caching / Calls To Cached Map Service Images

### ISSUE THREAD

**Issue by bbehling** [Esri/esri-leaflet#942]
Seems after the initial load of a dynamic map service, or until the browser's cache is cleared, esri-leaflet is making calls to URLs that look something like - 

`https://smapservices.ihs.com/wss/service/EMS_1_00/guest/extref_22620fcc-f7aa-4a1e-9a8f-18de3fa8b4aa/_ags_map5b8e4392eb6240bf84cc97439666324e.png`

I have to utilize internal map services that are refreshed every 60 minutes and those images are no longer on the server. After 60 mins, requests return a 404 until I clear the browser's cache.

Is there a way to disable this and make requests to the MapServer export end point for every request? 
I did came accross [this post](https://geonet.esri.com/thread/170100), but is there a better option than monkey patching? 

Perhaps in a future release, there could be a timespan-cache parameter.

EDIT - 

Setting the format type to 'image' seems to resolve this problem. Using the default format of 'j', JSON, causes the issues.

What the is the idea behind using JSON as the default response format?

Still would be cool if we could use the cached images on the server for a specified amount of time. I'd be willing to make a request for a timespan-cache param, or possibly contribute.

**Comment by bbehling** [comment]
Quick followup - seems this also has something to do when using the proxy parameter. If I remove it, we  get requests to the map service export end point as expected. 

I've worked with the proxy settings in the JSAPI, all that does is append a proxy address to beginning of each map request URL, it does not try to access cached images on the map server. Should this library behave in the same manner?

**Comment by jgravois** [comment]
> Is there a way to disable this and make requests to the MapServer export end point for every request?

it still seems like the best option to me to purse adding a constructor option which allows folks to disable client side caching by selectively appending a `_ts` parameter with a timestamp.

> is there a better option than monkey patching?

if you can put together a pull request to introduce the feature in esri leaflet core i'd be happy to review it and make sure its landed. if not, i'll get to it myself as soon as i can.
