### ISSUE TITLE
Support for Vector Tile Styles,

### ISSUE THREAD

**Issue by cmndrbensisko** [Esri/esri-leaflet#943]
Leaflet v.1.0.3
esri Leaflet v.2.0.8 (master)

Steps to reproduce the error:

When adding an ArcGIS Online Item for an alternate style created for an ArcGIS Vector Tile layer to the map, the root.json file of the basic style attached to the tile service is used, instead of alternate styles attached to the ArcGIS Online/Portal item.

The built-in basemap Vector Tiles added using L.esri.Vector.basemap properly fetch their alternate root.json files from "https://www.arcgis.com/sharing/rest/content/items/" + AGOL ID + "/resources/styles/root.json", while layers added using L.esri.Vector.layer will default to the default style of the cache referenced by the alternate style (Typically something like http://tiles.arcgis.com/tiles/XXX/arcgis/rest/services/XXX/VectorTileServer/resources/styles/root.json

Hopefully this is enough info; I can structure a working example if required.

**Comment by jgravois** [comment]
thanks for the report!

can you log this issue in the [`esri-leaflet-vector`](https://github.com/Esri/esri-leaflet-vector/issues) repo and include a link to a public ArcGIS Online item which references an alternate style please?

**Comment by jgravois** [comment]
nm, i ported it myself.  
if you can provide more info in https://github.com/Esri/esri-leaflet-vector/issues/29, that would be *super* helpful.
