### ISSUE TITLE
minZoom of TiledMapLayer overrides map

### ISSUE THREAD

**Issue by rbrtmrtn** [Esri/esri-leaflet#944]
* Browser and version:

Chrome 56

* Version of Leaflet (`L.version`):

1.0.3

* Version of esri Leaflet (`L.esri.VERSION`):

2.0.7

Steps to reproduce the error:

1. Create a Leaflet map with a `minZoom` value.
2. Add some `TiledMapLayer`s without specifying `minZoom`.
3. Start zooming out.

What happens is:

The map will zoom out past its `minZoom`.

I was expecting:

The Leaflet docs [say](http://leafletjs.com/reference-1.0.3.html#map-minzoom) that specifying a `minZoom` "overrides any minZoom option set on map layers", however it seems like the `minZoom` of my `TiledMapLayer` is trumping the map's. Thus the only way to get a global `minZoom` would be to specify the same value on every map layer.

**Comment by rbrtmrtn** [comment]
False alarm, I was just doing something silly :stuck_out_tongue:

**Comment by jgravois** [comment]
> I was just doing something silly 😛

you described every bug everywhere.
