### ISSUE TITLE
`eachActiveFeature` fails with TypeError

### ISSUE THREAD

**Issue by mpayson** [Esri/esri-leaflet#948]
* Browser and version: Chrome 57
* Version of Leaflet (`L.version`): 1.0.3
* Version of esri Leaflet (`L.esri.VERSION`): 2.0.8

When I call 'eachActiveFeature' on a feature layer, the following error is thrown:
 
Uncaught TypeError: this._layers[i].getBounds is not a function
    at NewClass.eachActiveFeature (esri-leaflet@2.0.8:3852)
    at NewClass.map.on (VM65 runner:12)
    at NewClass.fire (leaflet-src.js:587)

See JSBin: https://jsbin.com/kavoqukace/edit?html,output

**Comment by jgravois** [comment]
i'm 99% certain that we just need to implement a simpler check for point geometries to see whether they are inside the current map extent.

```js
// https://github.com/Esri/esri-leaflet/blob/6606d8e1bd95e5997064765e0946ee714af07c41/src/Layers/FeatureLayer/FeatureLayer.js#L251
for (var i in this._layers) {    
    // bounds can only be fetched from polylines and polygons
    if (activeBounds.intersects(this._layers[i].getBounds()) && this._currentSnapshot.indexOf(this._layers[i].feature.id) !== -1) {
        fn.call(context, this._layers[i]);
    }
}
```
not sure how i missed that when i added the new method.
