### ISSUE TITLE
Generating an incorrect url for ArcGis

### ISSUE THREAD

**Issue by ugurcanlacin** [Esri/esri-leaflet#951]
* Browser and version: Chrome 58

* Version of Leaflet (`L.version`): 0.7.3

* Version of esri Leaflet (`L.esri.VERSION`): 1.0.4

Steps to reproduce the error:

1. You can look at the example.
https://jsfiddle.net/nilgundag/gmbaa3vx/

What happens is the line commented works well. However, the url "https://sampleserver6.arcgisonline.com/arcgis/rest/services/DamageAssessment/MapServer" does not work.
It produces following url to fetch data which does not work. You can check the network to see it.
"https://sampleserver6.arcgisonline.com/arcgis/rest/directories/arcgisoutput/DamageAssessment_MapServer/x_____xWrFiSruXigvILncujVRyhA..x_____x_ags_map2e2cd851b5b64160b70a9492209115a1.png"

I was expecting that link works as well. You can look at the following ArcGis online map viewer which shows that link works.
http://www.arcgis.com/home/webmap/viewer.html?url=https%3A%2F%2Fsampleserver6.arcgisonline.com%2Farcgis%2Frest%2Fservices%2FDamageAssessment%2FMapServer&source=sd

You can also check network to see generated url.
https://sampleserver6.arcgisonline.com/arcgis/rest/services/DamageAssessment/MapServer/export?dpi=96&transparent=true&format=png32&layers=show%3A0&bbox=-17466613.247441605%2C3013453.4031140245%2C-3015734.427963168%2C8883817.175414&bboxSR=102100&imageSR=102100&size=1477%2C600&f=image

**Comment by jgravois** [comment]
not sure what's up with that map service, but you can work around the problem by asking for an image instead of json.

```js
L.esri.dynamicMapLayer({
  url: url,
  f: 'image'
}).addTo(map);
```

**Comment by ugurcanlacin** [comment]
@jgravois thanks a lot! It works well now.
