### ISSUE TITLE
introduce support for geometry types other than points in IdentifyFeatures

### ISSUE THREAD

**Issue by bbehling** [Esri/esri-leaflet#958]
Does the IndentifyFeatures class support using a polygon as the filter geometry? Or is it only a point?

**Comment by jgravois** [comment]
| method | returns | description |
| - | - | - |
| at(`<LatLng>` latlng) | `this` | Identifies feautres (sic) at a given `LatLng` |

reference: http://esri.github.io/esri-leaflet/api-reference/tasks/identify-features.html#methods

our current implementation definitely expects a point.

that said, nearly identical logic to pass through _any_ geometry type can already be found in [`L.esri.Query._setGeometry()`](https://github.com/Esri/esri-leaflet/blob/04bde48/src/Tasks/Query.js) so i'd be more than willing to accept a pull request to incorporate the same type of introspection in `L.esri.identifyFeatures`.

ideally, the existing function should be moved to [`L.esri.Util`](http://esri.github.io/esri-leaflet/api-reference/util.html) and reused.

**Comment by bbehling** [comment]
Pull Request submitted

**Comment by bbehling** [comment]
@jgravois
Is there a known issue with the build process where it fails on trailing spaces? I don't see any trailing spaces at line 22, but the build says there is.

**Comment by jgravois** [comment]
yup, the linter doesn't allow trailing spaces

![screenshot 2017-06-02 14 10 52](https://cloud.githubusercontent.com/assets/3011734/26745122/f0cb2b72-479d-11e7-8b91-b4d6c4946134.png)
running `npm run lint` on your branch locally, you'd encounter the same error.

**Comment by jgravois** [comment]
closed via #962 🎉
