### ISSUE TITLE
L.layerGroup equivalent in ESRI Leaflet for AGO feature service?

### ISSUE THREAD

**Issue by jwhaney** [Esri/esri-leaflet#965]
Hi,

I've been looking around for some time now for solutions to my problem and haven't gotten anywhere, so any clarification/help would be greatly appreciated. I could definitely be missing something. I'm creating four variables from the same feature service (AGO) because I want to separate them into four separate layers even though they come from the same service - different attribute values. I'm doing this by the where option in L.esri.featureLayer. However, when it comes time to bind the popup to each one of these variables, I want to avoid duplication and group each variable so I can just .bindPopup once because I want the popup to be the same in each layer. Is this possible with ESRI Leaflet?

- using **esri-leaflet 2.0.3** and **leaflet 1.0.3**
- browser shouldn't be the issue but contributing guidelines say to include so, I'm using Chrome primarily for development
- not using any bundling tools, testing locally using node.js (connect & serve-static)

See below for my code which may explain a bit better:

    //create separate AUS TxDOT project layers by project status
    var ausConstruct = L.esri.featureLayer({
        url: 'https://services.arcgis.com/KTcxiTD9dsQw4r7Z/arcgis/rest/services/TxDOT_Projects/FeatureServer/0',
        where: "DISTRICT_NAME = 'Austin' AND PRJ_STATUS = 'Construction Scheduled'",
        style: function (feature) {
            return {color: '#d7191c', weight: 4};
        }
    });

    var ausFinalize = L.esri.featureLayer({
        url: 'https://services.arcgis.com/KTcxiTD9dsQw4r7Z/arcgis/rest/services/TxDOT_Projects/FeatureServer/0',
        where: "DISTRICT_NAME = 'Austin' AND PRJ_STATUS = 'Finalizing for Construction'",
        style: function (feature) {
            return {color: '#fdae61', weight: 4};
        }
    });

    var ausDevelop = L.esri.featureLayer({
        url: 'https://services.arcgis.com/KTcxiTD9dsQw4r7Z/arcgis/rest/services/TxDOT_Projects/FeatureServer/0',
        where: "DISTRICT_NAME = 'Austin' AND PRJ_STATUS = 'Under Development'",
        style: function (feature) {
            return {color: '#80cdc1', weight: 4};
        }
    });

    var ausPlan = L.esri.featureLayer({
        url: 'https://services.arcgis.com/KTcxiTD9dsQw4r7Z/arcgis/rest/services/TxDOT_Projects/FeatureServer/0',
        where: "DISTRICT_NAME = 'Austin' AND PRJ_STATUS = 'Long Term Planning'",
        style: function (feature) {
            return {color: '#2c7bb6', weight: 4};
        }
    });

    //create group of project status variables for bindPopup (I think this is the Leaflet way but how in ESRI Leaflet?)
    var txdotProjects = L.layerGroup([ausConstruct, ausFinalize, ausDevelop, ausPlan]);

    //popup for txdot projects
    txdotProjects.bindPopup(function (evt) {
        return L.Util.template('<b>CSJ: </b>{CONTROL_SECT_JOB}<br><b>HWY: </b>{HIGHWAY_NUMBER}<br><b>COUNTY: </b>{COUNTY_NAME}<br><b>LENGTH: </b>{PROJ_LENGTH}<br><b>PROJECT CLASS: </b>{PROJ_CLASS}<br><b>EST. COST: </b>{EST_CONST_COST}<br><b>TYPE OF WORK: </b>{TYPE_OF_WORK}<br><b>LET DATE: </b>{DIST_LET_DATE}<br><b>BEGIN MILE PT: </b>{BEG_MILE_POINT}<br><b>END MILE PT: </b>{END_MILE_POINT}<br><b>FUND CATEGORY: </b>{TPP_CATEGORY_P2}<br><b>WORK PROGRAM: </b>{TPP_WORK_PROGRAM}<br><b>STATUS: </b>{PRJ_STATUS}',
        evt.feature.properties);
    });

**Comment by nickpeihl** [comment]
I think you just need to create a separate named function like so.

```
function createPopup (evt) {
  return L.Util.template('<b>CSJ: </b>{CONTROL_SECT_JOB}<br><b>HWY: </b>{HIGHWAY_NUMBER}<br><b>COUNTY: </b>{COUNTY_NAME}<br><b>LENGTH: </b>{PROJ_LENGTH}<br><b>PROJECT CLASS: </b>{PROJ_CLASS}<br><b>EST. COST: </b>{EST_CONST_COST}<br><b>TYPE OF WORK: </b>{TYPE_OF_WORK}<br><b>LET DATE: </b>{DIST_LET_DATE}<br><b>BEGIN MILE PT: </b>{BEG_MILE_POINT}<br><b>END MILE PT: </b>{END_MILE_POINT}<br><b>FUND CATEGORY: </b>{TPP_CATEGORY_P2}<br><b>WORK PROGRAM: </b>{TPP_WORK_PROGRAM}<br><b>STATUS: </b>{PRJ_STATUS}',
    evt.feature.properties)
})
```
Then you can chain the `bindPopup` method to each featureLayer and pass the name of the function as the argument. 

```
var ausConstruct = L.esri.featureLayer({
  url: 'https://services.arcgis.com/KTcxiTD9dsQw4r7Z/arcgis/rest/services/TxDOT_Projects/FeatureServer/0',
  where: "DISTRICT_NAME = 'Austin' AND PRJ_STATUS = 'Construction Scheduled'",
  style: function (feature) {
    return {color: '#d7191c', weight: 4};
  }
}).bindPopup(createPopup)

var ausFinalize = L.esri.featureLayer({
  url: 'https://services.arcgis.com/KTcxiTD9dsQw4r7Z/arcgis/rest/services/TxDOT_Projects/FeatureServer/0',
  where: "DISTRICT_NAME = 'Austin' AND PRJ_STATUS = 'Finalizing for Construction'",
  style: function (feature) {
    return {color: '#fdae61', weight: 4};
  }
}).bindPopup(createPopup)
// and so on...
```

**Comment by jwhaney** [comment]
That definitely works and makes sense! Thanks for helping a newb.

**Comment by nickpeihl** [comment]
Good to hear. Please close the issue.

Also general support questions are better handled in [GIS Stackexchange](https://gis.stackexchange.com/questions/tagged/esri-leaflet) or [GeoNet](https://geonet.esri.com/discussion/create.jspa?sr=pmenu&containerID=1841&containerType=700&tags=esri-leaflet,leaflet).

Cheers!

**Comment by jwhaney** [comment]
Ya I posted to GIS Stackexchange yesterday but got impatient due to no response, my bad. Thanks again for your help. I'll close this out.
