### ISSUE TITLE
Where Clause Not Holding on "Quicker" Pans

### ISSUE THREAD

**Issue by mpayson** [Esri/esri-leaflet#966]
* Browser and version:

Chrome 58

* Version of Leaflet (`L.version`):

0.7.7, 1.0.0?

* Version of esri Leaflet (`L.esri.VERSION`):

2.0.8

Steps to reproduce the error:

Check out the sample here: https://esri.github.io/esri-leaflet/examples/querying-feature-layers-1.html -- also happening in my current project

When I set a Where clause on the layer, pan the map somewhat quickly, then pan back to the original location, all the features are displayed instead of the ones abiding by the Where clause. Logging the Where shows that the layer has the right attribute, but it doesn't seem to be registering on the pan. That said, if I only move the map a little bit the Where clause holds

**Comment by jgravois** [comment]
thanks for reporting.

i haven't figured out how best to solve the underlying problem (yet), but in the meantime you'll see more appropriate behavior if you set the constructor option below when instantiating your layer.

```js
L.esri.featureLayer({
    url: yourService,
    cacheLayers: false
}).addTo(map);
```

the only drawback to this approach is that features aren't drawn immediately when you pan back to a location where they have already been drawn once. they have to be fetched again.

**Comment by mpayson** [comment]
Sounds good, thanks John!

**Comment by jwasilgeo** [comment]
Closing and continuing investigation over at #1196.
