### ISSUE TITLE
Problems using tiledMapLayer with MapServer

### ISSUE THREAD

**Issue by hhkaos** [Esri/esri-leaflet#968]
* Browser and version: Version 59.0.3071.115 (Official Build) (64-bit)
* Version of Leaflet (`L.version`): 1.1.0
* Version of esri Leaflet (`L.esri.VERSION`): 2.0.8
* I'm using the CDN (not webpack, browserigy,...)

What happens is: tile layer doesn't load and I was expecting tiles to load ^_^.

---

**Detailed explanation**:

I was trying to reproduce [this same example](http://esri.github.io/esri-leaflet/examples/tile-layer-1.html) but with another MapServer, as you can [check it in Plunker](http://plnkr.co/edit/o4OE7T2vm3e17BMxP204?p=preview=). But it doesn't load the tiles:

<img width="1279" alt="2017-07-04_1341" src="https://user-images.githubusercontent.com/826965/27828880-dcd64022-60be-11e7-8112-f6ac087cdfc2.png">

I also tested the service with the ArcGIS Online Web Map Viewer and the services works properly:
http://arcg.is/5mH00

**It seems to be something related with the X & Y in the URL** because [some tiles load](http://www.girona.cat/servergis/rest/services/MapesBase/Topografic_Girona/MapServer/tile/15/6081/8321) and [some doesn't](http://www.girona.cat/servergis/rest/services/MapesBase/Topografic_Girona/MapServer/tile/15/12164/16643).

I also tried using [leaflet.TileLayer.WMTS](https://github.com/mylen/leaflet.TileLayer.WMTS) but [it didn't work either](http://jsfiddle.net/hhkaos/6xqjnsbj/1/)

Any thoughts?

**Comment by jgravois** [comment]
there are a couple things going on with your tiled service

1. the SSL cert isn't trustworthy
![screenshot 2017-07-04 11 59 31](https://user-images.githubusercontent.com/3011734/27840904-c0e67970-60b1-11e7-841a-4d0c5f322959.png)
2. the web server doesn't support CORS
![screenshot 2017-07-04 12 25 56](https://user-images.githubusercontent.com/3011734/27841172-ea9ab7ac-60b3-11e7-91a2-704729c39adc.png)
3. the tiling scheme of the map service includes a single non-standard lod at level 0.

```js
// Google/Bing/OSM/ArcGIS Online tile servers start at 156543/5.9165
{
  "level": 0,
  "resolution": 4.0448008356352134E12,
  "scale": 15287405654300000
},
{
  "level": 1,
  "resolution": 156543.03392800014,
  "scale": 5.91657527591555E8
}
```

this API makes a best faith effort to correct non-standard lods that we recognize, but even after downgrading to http and forcing a JSONP metadata request, i wasn't able to get the layer to display the way it should.

```js
// still no bueno
L.esri.tiledMapLayer({
  url: 'http://www.girona.cat/servergis/rest/services/MapesBase/Topografic_Girona/MapServer',
  useCors: false
}).addTo(map);
```

to resolve the problem you can instead define a custom crs for Leaflet manually.

```js
// JSONP because server doesn't support CORS
L.esri.get.JSONP('http://www.girona.cat/servergis/rest/services/MapesBase/Topografic_Girona/MapServer', {}, function(error, response) {
  // loop through the lods of the esri tile service and pluck individual resolutions
  response.tileInfo.lods.forEach(function (lod) {
    serviceResolutions.push(lod.resolution);
  });

  // define a custom web mercator coordinate system for leaflet (because of the non standard lod)
  var crs = new L.Proj.CRS("EPSG:3857","+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext  +no_defs", {
    origin: [response.tileInfo.origin.x, response.tileInfo.origin.y ],
    resolutions: serviceResolutions
  });

  var map = L.map('map', {
    crs: crs
  }).setView([41.975680, 2.818628], 12);

  // by default you can only zoom in on a tileLayer to level 18
  L.tileLayer('http://www.girona.cat/servergis/rest/services/MapesBase/Topografic_Girona/MapServer/tile/{z}/{y}/{x}', {
    attribution: 'Powered by <a href="https://esri.com">Esri</a> | UMAT. Ajuntament de Girona',
    maxZoom: 23
  }).addTo(map);
}); 
```
[live demo](http://jsbin.com/lugibuq/edit?html,output)

based on logic you can find in our [non-mercator projection sample](http://esri.github.io/esri-leaflet/examples/non-mercator-projection.html).

**Comment by hhkaos** [comment]
Thank you very much @jgravois , you are the best!, Sorry I didn't answer before :-**!

**Comment by jgravois** [comment]
no need to apologize. i saw the emoji reactions 👯 .

i'll go ahead and close the issue now, but if someone else runs into the same problem i can take a deeper look into how to get the library to correct the lods of a service like this automagically.

**Comment by johnsalzbrunn** [comment]
5 years later, it seems I have run into a similar problem. 

`var ottertailcountyImagery = L.esri.tiledMapLayer({
maxZoom: 28,
url: "https://web2.co.ottertail.mn.us/arcgis/rest/services/Photography/2021_Photo/MapServer"
});`

@jgravois any thoughts?

**Comment by johnsalzbrunn** [comment]
With the L.proj.CRS piece of code before the L.map, it throws me this error instead. The error posted before occurs when I have the L.proj.CRS piece of code after the L.map.  

![error 10_19(2)](https://user-images.githubusercontent.com/91380601/196740062-7db9f682-8cc5-43a2-ae01-cbde7b09c0d9.PNG)

**Comment by jgravois** [comment]
> when I try to merge this code with my application, it is throwing me an error:

see https://github.com/Esri/esri-leaflet/issues/1342

**Comment by jgravois** [comment]
> Have you seen map rotation function correctly using a tiledmaplayer?

I havent tried.
