### ISSUE TITLE
FYI: Esri Leaflet and IE Compatibility Mode

### ISSUE THREAD

**Issue by pauldzy** [Esri/esri-leaflet#972]
* Browser and version: IE 11

* Version of Leaflet (`L.version`): 1.1.0

* Version of esri Leaflet (`L.esri.VERSION`): 2.0.8

Steps to reproduce the error:

1. Using IE11, open http://esri.github.io/esri-leaflet/examples/
2. Select settings and then Compatibility View Settings
3. Add esri.github.io to the site list
4. Inspect the resulting errors

This is not a bug report but perhaps a request to clarify or add documentation (perhaps this issue is enough).  

Esri-Leaflet currently is non-functional with Internet Explorer Compatibility Mode.  This **usually** can be worked around using X-UA-Compatible meta directives and/or request headers.  However there appear to be some IE scenarios (such as expressly listing a site or certain policy settings) whereby a given domain will **always** be rendered in compatibility mode.  And if your Esri-Leaflet app is in that domain you are out of luck.

Anyhow not sure if there is anything actionable here other than perhaps documentation of the problem to help others more quickly sort out their errors.  

Thanks,

Paul

**Comment by jgravois** [comment]
thanks Paul!

i've added this information to our FAQ and tagged this issue to help others find it in the future.

https://github.com/Esri/esri-leaflet/wiki/FAQ#compatibility-mode
