### ISSUE TITLE
Extra Request details (QueryString / Body)

### ISSUE THREAD

**Issue by steveway1982** [Esri/esri-leaflet#979]
* Browser and version:

ie: Chrome 51, IE11

* Version of Leaflet (`L.version`):

1.0.0?

* Version of esri Leaflet (`L.esri.VERSION`):

 2.0.8, `master`?

Steps to reproduce the error:

I currently have my ArcGIS Server in a secured environment behind a firewall, and behind an API Gateway.

My API Gateway requires that I pass a token (myToken) to access resources.  The layer allows me to set an ESRI token - that is not the issue here

The ESRI-Leaflet does not allow to add the API Gateway (myToken) token to the query string or body, or to set any kind of layer properties to add to the query string or body.

Normal convention would be to set in query string of URL parameter, therefore if i have the following URL property of the layer:

https://abc.apigateway.com/server/rest/services/mapservice?mytoken=abc

The request fails, as the request being sent is:

https://abc.apigateway.com/server/rest/services/mapservice?mytoken=abc/export?<all props required to make request>

The ESRI leaflet plugin should either:
1) Resolved URLs, so that if a querystring parameter has been set, they are merged, 
or (preferably)
2) have requestParam Object to the layer objects (feature, dynamic, tile etc) where the user can set such custom parameters, and the layer will either add as a querystring parameter (GET) or as body (POST).

I'm loading/bundling the library using:
[webpack](https://webpack.github.io/)

**Comment by jgravois** [comment]
you're right. [`dynamicMapLayer._buildExportParams()`](https://github.com/Esri/esri-leaflet/blob/4d588fe95e752149f5c87e264a1cd0665658fe54/src/Layers/DynamicMapLayer.js#L117-L164) currently doesn't expose an opportunity to pass through custom request parameters.

for the time being, you can obviously insert your own logic there, but a pull request for something more generic would also be really cool.

**Comment by jgravois** [comment]
resolved via #1036 and published in `v2.1.2`.

let us know how you get on!
