### ISSUE TITLE
revisit artificially restricting zoom of tiled basemaps

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet#980]
we currently set the maximum zoom level of our gray basemaps at [`16`](https://github.com/Esri/esri-leaflet/blob/4d588fe95e752149f5c87e264a1cd0665658fe54/src/Layers/BasemapLayer.js#L62-L100), but these basemaps were updated with additional zoom levels to match the others a long time ago.

http://services.arcgisonline.com/arcgis/rest/services/Canvas/World_Light_Gray_Base/MapServer

for that matter, even the World Topographic basemap lists zoom levels all the way down to [`23`](http://services.arcgisonline.com/arcgis/rest/services/World_Topo_Map/MapServer) now!

**Comment by jgravois** [comment]
this would be a *really* straightforward fix if anyone is looking for an excuse to make their first foray into open source 😉 😉

**Comment by jgravois** [comment]
steps to reproduce:

1. launch our [Switching basemaps]( http://esri.github.io/esri-leaflet/examples/switching-basemaps.html) sample
2. zoom in 6 times
3. choose 'Gray' from the basemap toggle and notice that its not possible to zoom in farther.

![screenshot 2017-07-24 11 09 59](https://user-images.githubusercontent.com/3011734/28537704-ac60bf2e-7060-11e7-947e-5c3bbb87351b.png)

same rules apply as #647

**Comment by machikoyasuda** [comment]
adding this issue to the next Fullstack meetup for people to dig into :) https://github.com/fullstackla/pairing-meetup/issues/161

**Comment by jgravois** [comment]
turns out the current behavior is *as designed*.

[![sad trombone](http://cdn.hark.com/images/000/003/392/3392/original.jpg)](https://www.youtube.com/watch?v=yJxCdh1Ps48)

for the curious, more info can be found in #981
