### ISSUE TITLE
force POST for featureLayer as GET is too long and fails

### ISSUE THREAD

**Issue by mladenp** [Esri/esri-leaflet#983]
* Version of Leaflet (`L.version`):
1.0.2
* Version of esri Leaflet (`L.esri.VERSION`):
2.0.6

Steps to reproduce the error:
Create large query like: TREEID in ('12313', '3213'.....) 

What happens is that services are returning 404 not found.
It works fine if i use POST in ArcGIS web query builder but fails if i try to use GET.

**Comment by jgravois** [comment]
i can't reproduce the error you describe

```js
var parks = L.esri.featureLayer({
    url: "https://services.arcgis.com/rOo16HdIMeOBI4Mb/arcgis/rest/services/Portland_Parks/FeatureServer/0",
    where: "1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1 AND 1=1"
}).addTo(map);
```
in the app below, the API switches to a POST `/query` automatically
http://jsbin.com/zipifat/edit?html,output

**Comment by mladenp** [comment]
You are right it works in your example in jsbin, BUT if i copy it in jsfiddle it uses GET instead.
https://jsfiddle.net/mladen5/r8zk55cr/4/

**Comment by jgravois** [comment]
in your jsfiddle example you never reference the variable you declared so there's no reason for the API to switch to a POST.

```js
let querystr = "1=1 AND 1=1 AND 1=1..."

// but you never do anything with 'querystr'
```

https://jsfiddle.net/24exbqjp/

**Comment by mladenp** [comment]
Ah sorry, wrong update.
Here it is: https://jsfiddle.net/mladen5/uq8jn416/
The problem is when i try to use it like so:
` parks.query().where('...').run() `
Then it uses GET no matter what.

But if i try to use it like in your example it works fine and uses POST: https://jsfiddle.net/mladen5/24exbqjp/4/

So i can work with that but i am assuming this is still a bug?

**Comment by jgravois** [comment]
ok, now i see what you're reporting.  thank you.

**Comment by jgravois** [comment]
i sat down and took another look at this and there's no bug in the API here.

your 'long string' is only ~1040 characters.  we don't switch to a POST until [`requestLength > 2000`](https://github.com/Esri/esri-leaflet/blob/aedaec8def8dfacbc08cecc19c44d3c6f829487e/src/Request.js#L124)

https://jsfiddle.net/jagravois/zo9v410f/

happy to chat more if you have any other questions.

**Comment by mladenp** [comment]
Ok, so i concluded that error is in fact somewhere on my ArcGIS server, as it shouldn't fail for those GET queries (< 2000 chars). Demo ArcGIS services in that jsfiddle helped me figure that out.
So now i use POST requests and CORS and it works fine.
Thanks.

**Comment by Gurskiy** [comment]
Same issue. Force POST requests works fine.

**Comment by jgravois** [comment]
what is the maximum url length your misbehaving services support?
what browser are you using?
what version of ArcGIS Server?

**Comment by mladenp** [comment]
I was having that issue with ArcGIS verison: 10.22 but i think the problem is in server max url length.
