### ISSUE TITLE
leaflet dependency overrides npm installed leaflet

### ISSUE THREAD

**Issue by GeorgeKnap** [Esri/esri-leaflet#987]
* Browser and version:
Chrome 60

* Version of Leaflet (`L.version`):
1.2.0

* Version of esri Leaflet (`L.esri.VERSION`):
2.1.0

Steps to reproduce the error:
install via npm 
```"leaflet": "1.2.0",
"esri-leaflet": "2.1.0",
"proj4leaflet": "1.0.1",
"typescript": "2.4.2",
    "webpack": "3.4.1",
    "webpack-dev-server": "2.6.1",
```
What happens is:
`esri-leflet` installs it's own `leaflet` dependency which is version 1.0.3. When app is created `esri-leaflet` somehow overrides the global `L` object with the object created from this old version.

I was expecting:
`esri-leaflet` to use the global `L` object created by leaflet 1.2.0.

* Optional: I'm *not* using the [CDN](http://www.jsdelivr.com/projects/leaflet.esri), I'm loading/bundling the library using:

webpack 3.4.1

Why does `esri-leaflet` installs old `1.0.3` version of `leaflet`?
perhaps `esri-leafet` should have `leaflet` as a peer dependency and let user to choose to version?

**Comment by jgravois** [comment]
this is because of #974.

do you see the same thing if you explicitly include the latest Leaflet in your own package.json?

**Comment by GeorgeKnap** [comment]
Aye. That's what happens. The leaftlet global object is then created twice. First the one from explicit 1.2.0 package and after that it's overwritten by 1.0.3 from esri-leaflet package.

**Comment by jgravois** [comment]
yuck. thanks for reporting. i don't see any drawback to making leaflet a `peerDependency`. does anyone else?

**Comment by jgravois** [comment]
just patched and published `v2.1.1`. confirmation that this resolves the problem would be _sincerely_ appreciated.

**Comment by jfolds** [comment]
This fixes it for me (1.0.3 no longer overriding, no duplicate library code). Although there is an Unmet peer dependency warning, which may be expected?

`-- UNMET PEER DEPENDENCY leaflet@1.2.0

**Comment by jgravois** [comment]
> which may be expected?

correct. until I can figure out how to get our tests passing when pointing at 1.1.x, that nag can be safely ignored.

thanks for confirming the new behavior!

**Comment by GeorgeKnap** [comment]
Confirmed. Working great now. Cheers.

**Comment by mush** [comment]
The fix works for me. However, I get the `-- UNMET PEER DEPENDENCY leaflet@1.1.0` as I'm using leaflet 1.1.0.
