### ISSUE TITLE
L.esri undefined with webpack

### ISSUE THREAD

**Issue by GeorgeKnap** [Esri/esri-leaflet#994]
* Browser and version:

ie: Chrome 60

* Version of Leaflet (`L.version`):

1.2.0

* Version of esri Leaflet (`L.esri.VERSION`):

2.1.1

Steps to reproduce the error:

using 
```
"leaflet": "1.2.0",
"esri-leaflet": "2.1.1",
"webpack": "3.5.3"
```
This might be a followup problem after #990 
`esri-leaflet` does not override leaflet's L object now but also does not create the `esri` property in it. 

I've tried to debug the initialization proccess and the `esri-leaflet-debug.js` script runs without producing any error. When the app loads the L.esri is undefined though.

**Comment by jgravois** [comment]
in webpack, you shouldn't be expecting our plugin to reside within Leaflet's namespace.

```js
var L = require('leaflet');
var esri = require('esri-leaflet');

esri.basemapLayer('Topographic').addTo(map);
```

https://github.com/Esri/esri-leaflet-webpack-example/blob/cf53572c1293f3c982a1524482c697284798b857/main.js#L19

**Comment by GeorgeKnap** [comment]
@jgravois  Thanks. the `var esri = require('esri-leaflet');` works.
Anyway I would like to dig a bit deeper: 
I am using ES6 import & typescript. If I import `import * as esri from 'esri-leaflet';` the typings provided by `esri-leaflet` gives me the full `L` object type with `esri` property in it:

![import](https://user-images.githubusercontent.com/11920691/29261219-bf542e4e-80ce-11e7-9feb-a06f7c00d7b5.png)
![esri-type](https://user-images.githubusercontent.com/11920691/29261223-c13c8f1c-80ce-11e7-8799-d027a44245eb.png)

This is in fact wrong because  when compiled to es5 it is just the `esri` plugin object.
![esri_obj](https://user-images.githubusercontent.com/11920691/29261399-886abf32-80cf-11e7-9b74-4ea7fc897824.png)
I believe the typings may be wrong here.

**Comment by jgravois** [comment]
i'm not a TypeScript expert. perhaps @strajuser can chime in.

the crux of the question is whether there is a way to publish typings that allow for both TypeScript use cases simultaneously.

**Comment by strajuser** [comment]
Fxed it. An error was in default export.

In our project we've used global imports, so there was no such problems.

**Comment by jgravois** [comment]
thanks @strajuser!

```js
declare module 'esri-leaflet' {
    export = L;
    export = L.esri;
    // no need to export plain old 'esri'?
}
```
@GeorgeKnap can you test with the typings in @strajuser's pull request above and confirm that they'll do the trick please?

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/18970

**Comment by GeorgeKnap** [comment]
the module declaration above does not seems to be valid
![exports](https://user-images.githubusercontent.com/11920691/29317735-a13a5f50-81cd-11e7-813c-038ab1703262.png)

but this is and works:
```
declare module 'esri-leaflet' {
     export = L.esri;
  }		 
```
![esri-intellisense](https://user-images.githubusercontent.com/11920691/29317881-3a7d139c-81ce-11e7-8348-a574f5419ca8.png)

**Comment by strajuser** [comment]
@GeorgeKnap 
Yes, I've changed format of default export in last pull-request in this case.

Also it should fix some ugly imports in esri-leaflet-geocoder typings...

**Comment by GeorgeKnap** [comment]
Perfect! Thanks.

**Comment by jgravois** [comment]
awesome. thank you both!
