### ISSUE TITLE
dynamicMapLayer not visible

### ISSUE THREAD

**Issue by ajuliano** [Esri/esri-leaflet#996]
* Browser and version:
Chrome 60

* Version of Leaflet (`L.version`):

1.2.0

* Version of esri Leaflet (`L.esri.VERSION`):

2.1.0

Steps to reproduce the error:
When trying to show a dynamic map layer it's not showing at all. 

```
var map = L.map('mapID', {
    renderer: L.canvas()
}).setView([56.0472439, 12.7159026], 20);

L.esri.basemapLayer('Gray').addTo(map);

L.esri.dynamicMapLayer({
	url: 'https://geodata.helsingborg.se/arcgis/rest/services/Bygglov/situationsplan_apptest_3857/MapServer',
	opacity: 1,
	useCors:false,
	maxZoom: 20,
	minZoom: 15
}).addTo(map);
```

Does the problem resides on https://geodata.helsingborg.se/arcgis/rest/services/Bygglov/situationsplan_apptest_3857/MapServer or is it in our code?

* Optional: I'm *not* using the [CDN](http://www.jsdelivr.com/projects/leaflet.esri), I'm loading/bundling the locally.

**Comment by jgravois** [comment]
i'm not able to reproduce the error you describe.

![screenshot 2017-08-14 11 36 07](https://user-images.githubusercontent.com/3011734/29285814-a703689e-80e4-11e7-8fb0-5d22931b5e5f.png)

what happens when you send a raw [/export](https://geodata.helsingborg.se/arcgis/rest/services/Bygglov/situationsplan_apptest_3857/MapServer/export?bbox=1415433.420227854%2C7567861.770187361%2C1415622.124141433%2C7567790.707637627&size=632%2C238&dpi=96&format=png24&transparent=true&bboxSR=3857&imageSR=3857&callback=window._EsriLeafletCallbacks.c3&f=image) request to the server?

**Comment by ajuliano** [comment]
I tried to remove `L.esri.basemapLayer('Gray').addTo(map);` and now it does work. Strange though. Is there a way to show both the base layer and the dynamicmapLayer?

**Comment by jgravois** [comment]
this one took me a bit to figure out.

the gotcha here is that even though you specified level 20 as the initial zoom level for the map, Leaflet dictates that will actually inherit the `maxZoom` of any instance of [TileLayer](http://leafletjs.com/reference-1.2.0.html#tilelayer) added to the map unless it is set explicitly. 

in the case of our 'Gray' basemap, internally our library knows tiles only exist down to level 16 and sets maxZoom accordingly. 

https://github.com/Esri/esri-leaflet/blob/0b38bc5b4486ff876a2cbe277f0e2b59a22e8ef8/src/Layers/BasemapLayer.js#L82-L86

that level is far enough out that the scale dependency set in your map service ([Min Scale: 5000](https://geodata.helsingborg.se/arcgis/rest/services/Bygglov/situationsplan_apptest_3857/MapServer/)) prevents it from displaying entirely. 

to fix the problem you just need to swap in a basemap with more cached tile levels and force the map to actually allow zoom down to 20
http://jsbin.com/rukecuv/edit?html,output

```js
var map = L.map('mapID', {
  // instantiate a map that includes LODs all the way down to 20  
  maxZoom: 20
}).setView([56.0472, 12.716], 19);

// load a basemap with cached tiles at least down to 19
L.esri.basemapLayer('Topographic').addTo(map);

L.esri.dynamicMapLayer({
  url: 'https://geodata.helsingborg.se/arcgis/rest/services/Bygglov/situationsplan_apptest_3857/MapServer'
}).addTo(map);
```

**Comment by ajuliano** [comment]
Hi,

That's so great! Now we've switched the initial zoom level to 12 and are now loading the `Streets` baseMapLayer. Thank you for referencing to https://github.com/Esri/esri-leaflet/blob/0b38bc5b4486ff876a2cbe277f0e2b59a22e8ef8/src/Layers/BasemapLayer.js#L82-L86

```
var map = L.map('mapID', {
			    renderer: L.canvas(),
			    maxZoom: 21,
				minZoom: 12,
			}).setView([56.0472439, 12.7159026], 12);

			L.esri.basemapLayer('Streets', {maxZoom: 18} ).addTo(map);

			L.esri.dynamicMapLayer({
				url: 'https://geodata.helsingborg.se/arcgis/rest/services/Bygglov/situationsplan_apptest_3857/MapServer',
				opacity: 1,
				useCors: false,
				maxZoom: 21,
				minZoom: 17
			}).addTo(map);
```
