### ISSUE TITLE
dynamic map layer order

### ISSUE THREAD

**Issue by cgalvarino** [Esri/esri-leaflet#999]
I must admit that this may be more of an esri dynamic layer REST question than esri-leaflet, but I'm going to give it a shot.

* Browser and version:

ie: Chrome 51, IE11

* Version of Leaflet (`L.version`):

1.0.3

* Version of esri Leaflet (`L.esri.VERSION`):

2.0.8

Steps to reproduce the error:

Is it true that the order that the the layers array does not affect the image stack order?  I.e. it's not like WMS where the order of layers matters?  This seems to be the case.

The layer I want on top.
https://nowcoast.noaa.gov/arcgis/rest/services/nowcoast/wwa_meteoceanhydro_longduration_hazards_time/MapServer/export?bbox=-11187934.95604468%2C2965756.6974648396%2C-10171628.227964977%2C3697106.1840974055&size=831%2C598&dpi=96&format=png32&transparent=true&bboxSR=3857&imageSR=3857&layers=show:15&f=image
![image](https://user-images.githubusercontent.com/180985/29733628-1228b4be-89bc-11e7-8d95-c8e26674bf52.png)

The layer I want on bottom.
https://nowcoast.noaa.gov/arcgis/rest/services/nowcoast/wwa_meteoceanhydro_longduration_hazards_time/MapServer/export?bbox=-11187934.95604468%2C2965756.6974648396%2C-10171628.227964977%2C3697106.1840974055&size=831%2C598&dpi=96&format=png32&transparent=true&bboxSR=3857&imageSR=3857&layers=show:4&f=image
![image](https://user-images.githubusercontent.com/180985/29733669-4bf8f988-89bc-11e7-807f-27960bf3e9bb.png)

Mixing them up.
https://nowcoast.noaa.gov/arcgis/rest/services/nowcoast/wwa_meteoceanhydro_longduration_hazards_time/MapServer/export?bbox=-11187934.95604468%2C2965756.6974648396%2C-10171628.227964977%2C3697106.1840974055&size=831%2C598&dpi=96&format=png32&transparent=true&bboxSR=3857&imageSR=3857&layers=show:4,15&f=image
![image](https://user-images.githubusercontent.com/180985/29733645-28453448-89bc-11e7-8601-de49cc894c41.png)

Which is the same as this request where only the layer order has been switched.
https://nowcoast.noaa.gov/arcgis/rest/services/nowcoast/wwa_meteoceanhydro_longduration_hazards_time/MapServer/export?bbox=-11187934.95604468%2C2965756.6974648396%2C-10171628.227964977%2C3697106.1840974055&size=831%2C598&dpi=96&format=png32&transparent=true&bboxSR=3857&imageSR=3857&layers=show:15,4&f=image

**Comment by jgravois** [comment]
> Is it true that the order that the the layers array does not affect the image stack order?

correct.

besides republishing the service with a more appropriate default stacking order, you _can_ reorder on the fly, but only when the service itself supports [dynamic layers](http://server.arcgis.com/en/server/latest/publish-services/windows/about-dynamic-layers.htm) (yours does not)

```
Supports Dynamic Layers: false
```

https://developers.arcgis.com/javascript/3/jssamples/layers_dynamic_reorder.html

**Comment by cgalvarino** [comment]
Boy am I glad I asked. It's amazing how quickly an expert can cut to the chase. Thx for the help.
